### ISSUE TITLE
timeout in gethistorical feature

### ISSUE THREAD

**Issue by amritsh** [feast-dev/feast#1050]
During batch query - batch_client.get_historical_features, I am getting timeout error. Here are the logs-

---------------------------------------------------------------------------
FutureTimeoutError                        Traceback (most recent call last)
/feast/sdk/python/feast/grpc/grpc.py in create_grpc_channel(url, enable_ssl, enable_auth, ssl_server_cert_path, auth_metadata_plugin, timeout)
     47     try:
---> 48         grpc.channel_ready_future(channel).result(timeout=timeout)
     49         return channel

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in result(self, timeout)
    139     def result(self, timeout=None):
--> 140         self._block(timeout)
    141 

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in _block(self, timeout)
     85                         if remaining < 0:
---> 86                             raise grpc.FutureTimeoutError()
     87                         else:

FutureTimeoutError:

**Comment by woop** [comment]
@amritsh would you mind giving us more details on your stack? Are you using Docker Compose? Are you using Kubernetes? Are you running the provided notebook from within the deployment or outside?

**Comment by amritsh** [comment]
I have set it up using docker-compose. I am running the notebook from outside the deployment.
