### ISSUE TITLE
Getting started example not work - host feast.example.com not known

### ISSUE THREAD

**Issue by noklam** [feast-dev/feast#1104]
## Expected Behavior 
I expected there is an example server that user can try on it?
## Current Behavior
Connection Time out, feast.example.com is not a known host. 
## Steps to reproduce
ping feast.example.com
```python
# https://docs.feast.dev/getting-started/connecting-to-feast-1/python-sdk

from feast import Client

# Connect to an existing Feast Core deployment
client = Client(core_url='feast.example.com:6565')

# Ensure that your client is connected by printing out some feature sets
client.list_feature_sets()
```
### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by woop** [comment]
@noklam the idea is that you would deploy Feast using https://docs.feast.dev/getting-started/deploying-feast and then connect to it.

Do you have a suggestion on how we should rephrase it?

**Comment by noklam** [comment]
@woop  Ah sorry I misunderstood, so if I am running it with the docker on my machine, it should default to `localhost:6565` instead?

**Comment by woop** [comment]
Thats right, but you should be using the bundled Jupyter notebook if you use Docker Compose

**Comment by noklam** [comment]
from feast import Client

# Connect to an existing Feast Core deployment
client = Client(core_url='feast.example.com:6565')

# Ensure that your client is connected by printing out some feature sets
client.list_feature_sets()


list_feature_sets method seems missing from the sdk. ![Uploading 97426294...]

**Comment by woop** [comment]
https://github.com/feast-dev/feast/blob/eb9a0a5b2874f17d2226ddc683c8bdeb187ddd0e/sdk/python/feast/client.py#L418

**Comment by noklam** [comment]
I was searching in the master branch, sorry about that. The doc did mention to clone v0.7.0. Thanks for the help!

https://github.com/feast-dev/feast/blob/v0.7-branch/sdk/python/feast/client.py
