### ISSUE TITLE
How can i online retrieve more than on entity ?

### ISSUE THREAD

**Issue by Andrew32bit** [feast-dev/feast#1119]
Hello! Im trying to return more than two entites in online feature retrieval.Can you give me code example of this?
Before that i add on more entity - user_id.
When i try do this -
online_features = client.get_online_features(
    feature_refs=[
        "customer_transactions_v2:daily_transactions",
        "customer_transactions_v2:total_transactions",
    ],
    entity_rows=[
        {
            "customer_id": 1001,'user_id':1
        }
    ],
)

It is ok,but if i want return all rows for one entity and get info about another enitites?
And second question-why feast return only one row ?in dataset i have mutiple rows with this entities

Thank you!

**Comment by woop** [comment]
Entity rows is a list. You can pass multiple entities as follows
```
online_features = client.get_online_features(
        feature_refs=['customer_transactions_v2:daily_transactions', 'customer_transactions_v2:total_transactions'],
        entity_rows=[{customer_id': 1001, 'user_id': 1}, {customer_id': 1002, 'user_id': 2}]
        )
```

Do note that you can retrieve historical values from the online API. The online API only returns the latest values. Please use `get_historical_features` to return older values?
