### ISSUE TITLE
Spark 3+ support

### ISSUE THREAD

**Issue by mike0sv** [feast-dev/feast#1167]
## Expected Behavior 

Can use spark 3+ clusters to run jobs.

## Current Behavior

If used together with spark 3+, there is an exception 

```Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/StreamWriteSupport```

which is caused by old (2+) spark dependencies for IngestionJob. 

## Steps to reproduce

I guess `pip install pyspark>=3` and start any job will be enough

### Specifications

- Version: 0.8.0
- Platform: linux
- Subsystem: 

## Possible Solution

Bump spark.version in dependencies and update job code accordingly.

**Comment by woop** [comment]
@oavdeev @pyalex I believe there was a specific reason why we couldn't use Spark 3.0 right? Protobuf/grpc dependencies?

**Comment by mike0sv** [comment]
FYI https://github.com/RedisLabs/spark-redis/issues/253

**Comment by pyalex** [comment]
Main reason for spark 2.4 was that [bq connector](https://github.com/GoogleCloudDataproc/spark-bigquery-connector) was not supporting 3.x on that moment and that dataproc stable version is still 2.4.
BQ connector seems not an issue anymore
