### ISSUE TITLE
S3 endpoint configuration

### ISSUE THREAD

**Issue by mike0sv** [feast-dev/feast#1169]
**Is your feature request related to a problem? Please describe.**
I want to use my on-premise installment of s3 (minio in my case). For this I need a way to provide custom `endpoint_url` for `boto3.client` initialization.

**Describe the solution you'd like**
New configuration option like `FEAST_S3_ENDPOINT_URL`. And use it's value in `feast.staging.storage_client.S3Client.__init__` when creating s3 client. Default `None` value will ensure backward compatibility. 
To configure this option for spark jobs,  #1168 can be implemented

**Comment by woop** [comment]
Makes sense. I think @tsotnet actually thought about adding this support, but we decided not to add it in Feast 0.8.

@mike0sv do you want to take a stab at it?

**Comment by mike0sv** [comment]
Yep

**Comment by woop** [comment]
@mike0sv so you have fixed the Python SDK, but how are you going to deal with Spark ingestion jobs that load data from Minio? I think you'll also need to set the endpoint there.

**Comment by mike0sv** [comment]
#1168 is about that. it may be reasonable to automatically add S3 endpoint to those additional options, if it was set
