### ISSUE TITLE
Snowflake Support for Offline Store

### ISSUE THREAD

**Issue by jmeisele** [feast-dev/feast#1171]
**Is your feature request related to a problem? Please describe.**
Feature request not related to a specific problem. 

**Describe the solution you'd like**
Would love to see Snowflake data warehouse as an option for data sink for the offline store. Many companies move beyond postgres and into data warehouse solutions. 

**Describe alternatives you've considered**
I've considered going backwards to have offline store back to postgres, but this wouldn't be viable long term

**Comment by woop** [comment]
@jmeisele thanks for creating this issue. Snowflake support is definitely high on the list. 

As an intermediate step, would adding support for Snowflake as a data source (as opposed to an offline store), cover at least part of your use case? Or do you need to be able to ingest data into the store?

**Comment by jmeisele** [comment]
Yes, that think that would be helpful, I should be able to standup a postgres instance for 'offline' store very easily, as long as I can use feast to ingest from Snowflake and insert to the offline store which would then be postgres

**Comment by jmeisele** [comment]
I am really looking forward to experimenting with feast over Christmas shutdown. Feature store has been high on my priority list for a while now

**Comment by woop** [comment]
Noted, lets keep this open. Snowflake support is important for us. We're hoping to pick it up soon, but it will likely happen only after Feast 0.9 since we first want to make it possible to deploy Feast on Azure and into on-prem environments. That being said, it should be pretty straightforward to add support for Snowflake since Spark connectors already exist https://docs.snowflake.com/en/user-guide/spark-connector-overview.html

**Comment by jmeisele** [comment]
Awesome, appreciate the fast feedback. I completely understand the priorities.

**Comment by sfc-gh-madkins** [comment]
I was able to add initial support for Snowflake as an Offline Store: https://github.com/sfc-gh-madkins/feast

**Comment by sfc-gh-madkins** [comment]
https://github.com/sfc-gh-madkins/feast-snowflake
