### ISSUE TITLE
Add support for open source Spark API

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1178]
We would like to add support for an open source Spark API (Livy, Spark Job Server, Spark on K8s operator, Yarn), which would allow on-prem deployments.

- We already have support for EMR, Dataproc, and local execution. 
- We are looking for a more scalable replacement for local execution that can be used for larger workloads, and that retains jobs state. Using local execution in standalone mode does not provide proper job management.
- We only need an MVP implementation with minimal functionality. Meaning "stream-to-online" ingestion, and "batch-to-online" ingestion. The ingestion jobs that will be executed already exist, so they can be reused.
- Spark on K8s Operator is also in use by Kubeflow and supports Spark 3.0. The downside to using it is the coupling to Kubernetes, but it seems like the only implementation with active development, and it would make Kubeflow integration possible.

**Comment by pyalex** [comment]
I think we should looking for something similar to what we already using successfully: dataproc / emr. They are providing next critical APIs:
1. Create/Cancel Job
2. Retrieve Job Status
3. Add labels / retrieve by Labels
4. List of running / completed jobs

Although (1), (2), and (4) are implemented in all open-source solutions, (3) is a critical requirement for us if we want to rely on this API as stateful source of truth. It seems that `Spark on K8s operator` is the only one who supports everything we need, though it may be a little overkill.

**Comment by woop** [comment]
Yea, given that Kubeflow is using `Spark on K8s operator`, I think we should focus on that as our primary implementation.
