### ISSUE TITLE
Add Azure support to Feast

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1181]
This card tracks the addition of Azure support to Feast.

* Spark Job Runner: The current proposal is to implement support for the [Databricks Jobs API on Azure](https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/jobs)
* File system: We will need to add support for either DBFS or directly accessing Azure Blob Storage. It seems like DBFS using [mount points](https://docs.databricks.com/data/data-sources/azure/azure-storage.html#mount-an-azure-blob-storage-container) is the simplest way to implement the file system.
* Terraform Installation: We will need to add support for deploying Feast using Terraform to Azure Kubernetes Service (AKS).
* End-to-end tests: We will need to set up end-to-end tests that run all critical flows through a full Azure deployment.

cc @Yanson

**Comment by woop** [comment]
[Feast on Azure RFC](https://docs.google.com/document/d/1uzSeVedDtxUYil_qlvmjnhbxbta_PXcWaEYj__Nvd3w/edit#)
Noteworthy changes to the above
* We are adding support for Azure Blob Storage
* We did not pick up adding Databricks support for Spark Jobs
* @jklegar is working on e2e test support

**Comment by gramhagen** [comment]
Hey this looks really awesome. I'm super new to the project but was looking for feature store solutions that could be used in Azure and would love to help out.

Is there anything specific I can help with? Or another place I should use to discuss this?

**Comment by woop** [comment]
Hey @gramhagen, I somehow didn't notice your comment here! If you are still interested, do let us know over in the Kubeflow Slack (linked in our readme).
