### ISSUE TITLE
Add support for feature tables to the apply method

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1183]
We need to deprecate [client.apply_entity()](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/client.py#L443) and [client.apply_feature_table()](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/client.py#L565). Both of these methods were added because `client.apply()` was previously used for applying feature sets.

In Feast 0.9 we should
- Add support for applying feature tables and entities through `client.apply()`. This method doesn't currently exist. Please have a look at [Feast 0.7](https://github.com/feast-dev/feast/blob/v0.7.1/sdk/python/feast/client.py#L359) for a reference implementation. We can follow a similar approach.
- Add deprecation warnings on `apply_feature_table()` and `apply_entity()`
- In Feast 0.10 we will remove `apply_feature_table()` and `apply_entity()`, and `apply()` will only work on feature tables and entities.

**Comment by priyankvex** [comment]
Hi @woop, I would like to help with this one. Since this will be my first contribution in Feat hopefully you'll help me out.
Let me raise an MR for this based on the reference you pointed by this weekend.

**Comment by woop** [comment]
Hi @priyankvex, feel free to go ahead. Please ask if you have any questions!
