### ISSUE TITLE
None values in online feature retrieval

### ISSUE THREAD

**Issue by Andrew32bit** [feast-dev/feast#1192]
I have a dataset with 17607453 rows.Whem im ingesting it -strange things happens.Feast writes-ingestion complete but when i trying online retrieval i get some feature values ok but most of them with None.What can it be? Maybe feast has some restrictions or we need to deploy kafka in cluster mode?

**Comment by woop** [comment]
> I have a dataset with 17607453 rows.Whem im ingesting it -strange things happens.Feast writes-ingestion complete but when i trying online retrieval i get some feature values ok but most of them with None.What can it be? Maybe feast has some restrictions or we need to deploy kafka in cluster mode?

Hi @Andrew32bit, thanks for trying out Feast!

Quick question: Are you using Feast 0.7 or another version? Are you using the `ingest()` to ingest the data?

**Comment by Andrew32bit** [comment]
we are using Feast 0.7 and yes im using ingest() to ingest the data

**Comment by Andrew32bit** [comment]
Sorry. We have Feast version 0.6.2 -do we need update to 0.7?

**Comment by woop** [comment]
@Andrew32bit, the order that you are ingesting data matters. If you ingest a null value into the online store it will replace existing values. In Feast 0.7 we will keep the latest values and not always overwrite. Can you confirm that you have values for all rows you are ingesting?

**Comment by Andrew32bit** [comment]
well as i mentioned before with remark-we are using feast 0.6.2 version.I fill all None values of course because if i will not fill or drop them then feast will raise error when i ingest data

**Comment by woop** [comment]
What is your `max_age` set to? Could it be that the values fall outside the max_age?

**Comment by Andrew32bit** [comment]
I dont max_age set for one ingestion for feast.My average number of records for ingestion os about one million rows.is that ok? Or another words what is the maximum for feast per one ingest ?

**Comment by woop** [comment]
The maximum depends on how much memory your Redis instance has. Feast itself doesn't impose a limit.

**Comment by Andrew32bit** [comment]
Maybe we need just to switch version of feast from 6 to 7?

**Comment by woop** [comment]
> Maybe we need just to switch version of feast from 6 to 7?

You could try that yes.

**Comment by Andrew32bit** [comment]
its related to https://github.com/feast-dev/feast/issues/1199
