### ISSUE TITLE
Very slow occurance in online feature store

### ISSUE THREAD

**Issue by Andrew32bit** [feast-dev/feast#1199]
Hello! We are using Feast 0.7.0 and we notice that feature occures very slowly in client.get_online_features - about 10000 records per 5 minutes. What can cause this behavior?

**Comment by Andrew32bit** [comment]
We notice the jobcontroller consumes a lot of CPU and in yaml configuration of jobcontroller docker we see obs:
    polling_interval_milliseconds: 5000
    job_update_timeout_seconds: 240 .Maybe we need to change to another version or tune jobcontroller yaml?

**Comment by woop** [comment]
> We notice the jobcontroller consumes a lot of CPU and in yaml configuration of jobcontroller docker we see obs:
> polling_interval_milliseconds: 5000
> job_update_timeout_seconds: 240 .Maybe we need to change to another version or tune jobcontroller yaml?

Are you using Dataflow for ingestion?

**Comment by woop** [comment]
> Hello! We are using Feast 0.7.0 and we notice that feature occures very slowly in client.get_online_features - about 10000 records per 5 minutes. What can cause this behavior?

Do you mean the writes to the store or reads from the serving api?

**Comment by Andrew32bit** [comment]
> > We notice the jobcontroller consumes a lot of CPU and in yaml configuration of jobcontroller docker we see obs:
> > polling_interval_milliseconds: 5000
> > job_update_timeout_seconds: 240 .Maybe we need to change to another version or tune jobcontroller yaml?
> 
> Are you using Dataflow for ingestion?

We are using python client.ingest(featureset_name,data) method for ingesting ,client version 0.7.0

**Comment by Andrew32bit** [comment]
> > Hello! We are using Feast 0.7.0 and we notice that feature occures very slowly in client.get_online_features - about 10000 records per 5 minutes. What can cause this behavior?
> 
> Do you mean the writes to the store or reads from the serving api?

When we trying to get features by method calling client.get_online_features(features_list=features_list,entity_rows=entity_rows) - it seems like some features appears after 10,20 or more minutes.

**Comment by Andrew32bit** [comment]
![Снимок экрана 2020-11-27 в 20 18 19](https://user-images.githubusercontent.com/28597674/100472664-beb75380-30ed-11eb-9476-7cf972a71864.png)

Maybe problem is in jobcontroller? its consumes a lot of CPU

**Comment by woop** [comment]
@Andrew32bit The Job Controller uses Apache Beam for streaming data into your stores. Beam supports multiple runners. The default we provide is the DirectRunner. DirectRunner is not meant for production use, it is only meant for getting started. You should use [Dataflow Runner](https://www.google.com/search?q=dataflow+google&oq=dataflow+google&aqs=chrome.0.0i457j0l4j69i60l3.2476j0j7&sourceid=chrome&ie=UTF-8). 

https://github.com/feast-dev/feast/blob/v0.7.1/infra/charts/feast/values-dataflow-runner.yaml#L26

**Comment by Andrew32bit** [comment]
On feast 0.8.2 everything works
