### ISSUE TITLE
Amazon EKS Terraform Error - InvalidParameterCombination 

### ISSUE THREAD

**Issue by sarahwooders** [feast-dev/feast#1203]
I'm trying to setup Feast by following the [AWS EKS/terraform tutorial](https://docs.feast.dev/getting-started/install-feast/kubernetes-amazon-eks-with-terraform). After cloning Feast, I did the following: 
1. Run `aws emr create-default-roles`
2. Configure `my_feast.tfvars` like the examples: 
```
name_prefix = "my-feast"
region      = "us-east-1"
```
3. Ran `terraform init` and `terraform apply -var-file=my_feast.tfvars`

Specs: 
* AWS / us-east-1
* Mac OS Catalina 10.15.7
* Terraform 0.13
* Helm 3.4.1
* Feast 0.8.1
* Python 3.8

Although some part of terraform complete (an S3 bucket is created), I get the following error: 
```
module.rds_cluster.aws_rds_cluster.primary[0]: Creating...

Error: error creating RDS cluster: InvalidParameterCombination: Aurora Serverless DB clusters are always encrypted at rest. Encryption can't be disabled.
	status code: 400, request id: 9b3a86a5-c60d-4fd2-890f-7943fb2c0e3f
```
Would really appreciate any help with getting Feast running on AWS!

**Comment by oavdeev** [comment]
Can you try the fix from #1204? It looks like an issue that was fixed upstream in the terraform module we're using. But I'm now surprised we didn't run into this when we were using Feast terraform config ourselves.
