### ISSUE TITLE
Add documentation on how to use Feast gRPC APIs

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1224]
We should add a short guide on how users can use Feast by only using gRPC clients. This is useful for both developers and for teams not wanting to have Feast dependencies.

Context: https://kubeflow.slack.com/archives/CE0L8T267/p1607671093340700?thread_ts=1607669754.338100&cid=CE0L8T267

**Comment by danielschulz** [comment]
I'd like to get started in documenting Feast. May I start a PR for that?

**Comment by woop** [comment]
Hey @danielschulz. Somehow I/we must have missed your comment completely. Please let us know if you are still interested, otherwise somebody else can pick this up.
