### ISSUE TITLE
How can i kill all remote jobs by client by sdk python?

### ISSUE THREAD

**Issue by Andrew32bit** [feast-dev/feast#1226]
In feast 0.8.2 we have command client.list_jobs(include_terminated=False) which output is like [<feast.remote_job.RemoteStreamIngestionJob at 0x7f21921076d8>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f217ec9e7f0>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f2177284a90>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f217720b438>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f217720b8d0>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f217720bd68>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f2182823198>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f21758881d0>,
 <feast.remote_job.RemoteStreamIngestionJob at 0x7f2175888668>]
How can i kill all this jobs?
So i want cancel them all.

**Comment by woop** [comment]
Hi @Andrew32bit, apologies for the delay in response. Currently you will have to run the cancel method on the jobs by looping over the list.

**Comment by Andrew32bit** [comment]
Can you give me example? Bcs i cant call <feast.remote_job.RemoteStreamIngestionJob at 0x7f21921076d8>.cancel() - it returns error

**Comment by Andrew32bit** [comment]
So how can i get list of job_id and then cancel them in loop?

**Comment by woop** [comment]
> Its ok.Can you give me example? Bcs i cant call <feast.remote_job.RemoteStreamIngestionJob at 0x7f21921076d8>.cancel() - it returns error

Are you running the cancel method on the job object itself, or are you running it on the string?

What happens when you do something like

````
for job in client.list_jobs(include_terminated=False):
    job.cancel()
````

**Comment by Andrew32bit** [comment]
oh-it works-thank you!
