### ISSUE TITLE
Jobs registry tables sees not to be used using FileSource?

### ISSUE THREAD

**Issue by pedrosalgadops** [feast-dev/feast#1228]
## Expected Behavior 

The following tables don't keep track of submitted jobs:

- jobs
- jobs_feature_sets
- jobs_stores

## Current Behavior

Empty tables.

## Steps to reproduce

Follow the minimal example;
Ingest using FileSource;
Submit historical retrieval using previously ingested data;

### Specifications

- Version: 0.8.2
- Platform: Linux
- Subsystem: Docker, local, etc

## Possible Solution

Regarding the documentation, I would expect the jobs info to be persisted in these tables.
Idk if these tables are only used previously for the old job ingest tasks, using BigQuery, or if somehow they are deprecated.  
The only entry found in the documentation for this subject was:
https://docs.feast.dev/reference/metrics-reference#feast-ingestion-job

**Comment by pyalex** [comment]
Those are deprecated tables and they are not used by Feast > 0.6. Instead JobServices relies on Dataproc / EMR as state keeper.
