### ISSUE TITLE
Filters on retrieving historical features 

### ISSUE THREAD

**Issue by pedrosalgadops** [feast-dev/feast#1229]
**Is your feature request related to a problem? Please describe.**
Feast historical retrieval is designed for point-in-time joins, I understand this approach and its use cases. But for use cases that don't require strict point-in-time joins or even matches between multiple features, this functionality has some limitations because we don't have a method to simply get the data based on some filters.

**Describe the solution you'd like**
It will be really helpful if feast also has an interface to get historical data with a set of filters, like time-window ranges, entity filters, and so on. 

**Describe alternatives you've considered**
Currently, I have my own spark jobs to look into the output parquet files and filter the data within a time range and set of entities.

**Additional context**
The retrieval example as show [here](https://docs.feast.dev/user-guide/getting-training-features#retrieving-historical-features) says "_it is necessary to provide an entity dataframe as part of the get_historical_features method_", perhaps we can have another implementation of this method that don't require this dataframe with an explicit event-timestamp set, and just provide a set of filters where our data will be filtered on.

Also, idk how this type of functionality fits in the Feast purpose, ecosystem, and roadmap but it's something that surely will provide more visibility and customization on a more direct historical retrieval for training and batch purposes.

**Comment by pyalex** [comment]
Hi, @pedrosalgadops 

You can checkout another method [get_historical_features_df](https://api.docs.feast.dev/python/#feast.client.Client.get_historical_features_df) which returns spark dataframe. This Dataframe could be used for additional filtering. Although you still need to have list of entities. 
For timestamp part of the question - the workaround would be to use `datetime.now()` or whatever higher boundary you have and change `maxAge` of `FeatureTable` to control lower timestamp boundary.

**Comment by woop** [comment]
@pedrosalgadops the means of retrieval you are describing does make sense, it just isnt something we have picked up. Some other feature stores allow users to provide a SQL query to produce their entity dataframe, which allows for arbitrary filtering. It's just a matter of prioritization right now.
