### ISSUE TITLE
Add Terraform installation and guide for Azure

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1232]
This issue tracks the creation of a Terraform script and a guide that allows users to install Feast into Azure and use it remotely (ideally not requiring an embedded Jupyter with Spark).

We can model our approach here on https://docs.feast.dev/getting-started/install-feast/kubernetes-amazon-eks-with-terraform

**Comment by xiaoyongzhu** [comment]
Hello @woop! Would love to contribute to this effort! I've looked thru the issues & terraform on AWS and wondering what's the best way to collaborate.

**Comment by woop** [comment]
Hey @xiaoyongzhu, just acknowledging this message here. We'll sync up offline and see where there is room to collaborate.

**Comment by jklegar** [comment]
done, see #1274 and #1276
