### ISSUE TITLE
The minimal_ride_hailing notebook from `infra/docker-compose/` doesn't work

### ISSUE THREAD

**Issue by limdauto** [feast-dev/feast#1246]
## Expected Behavior 

I expected to be able to run through the notebook without issue.

## Current Behavior

At the ingestion step, I got the following error, presumably due to the lack of an offline storage scheme:

<img width="1101" alt="Screenshot 2020-12-29 at 21 26 57" src="https://user-images.githubusercontent.com/2032984/103315119-97b9ad80-4a1c-11eb-9387-4d7f5f36feac.png">

## Steps to reproduce

Follow the [Quick Start](https://docs.feast.dev/quickstart) example and try to run the example notebook.

### Specifications

- Version: 0.8.2
- Platform: OSX
- Subsystem: Docker (?)

**Comment by oavdeev** [comment]
Hmm I failed to reproduce this with 0.8.2. 

Can you check what is the file source set to? I'm curious to see the output of this:
```
print(client.get_feature_table("driver_statistics").to_yaml())
print(client.get_feature_table("driver_trips").to_yaml())
```

I wonder if it somehow doesn't have `file://` scheme

**Comment by limdauto** [comment]
@oavdeev ah indeed! For some reason it doesn't have `file://`. Sorry, I was playing with the data path and didn't pay attention to the protocol. It's working now. Thank you for your help.
