### ISSUE TITLE
Python client does not accept config file path argument in **kwargs

### ISSUE THREAD

**Issue by Joostrothweiler** [feast-dev/feast#1248]
## Expected Behavior

When we initialise the client, we also initialise the Config class and set it on the client properties. The Config constructor takes the following arguments:
```python
def __init__(
    self, options: Optional[Dict[str, str]] = None, path: Optional[str] = None,
):
```

I would expect to be able to set the path as part of initialising the client. Otherwise, I'm not sure why we would need the path here. From the client, we do append `**kwargs` to the options, so alternatively I would expect the path to be available on the options and set from there in the config. 

In `Client` init:

```python
self._config = Config(options={**options, **kwargs})
```

## Current Behavior

Currently the only way to set the path seems to be from the environment variable key `FEAST_CONFIG_FILE_ENV_KEY` (`"FEAST_CONFIG"`):
```python
        if not path:
            path = join(
                expanduser("~"),
                os.environ.get(
                    FEAST_CONFIG_FILE_ENV_KEY, CONFIG_FILE_DEFAULT_DIRECTORY,
                ),
                CONFIG_FILE_NAME,
            )
```

## Steps to reproduce

Initialise a client and try to pass the config path as a parameter.

### Specifications

- Version: 0.8.0
- Platform: Mac
- Subsystem: 

## Possible Solution

Either drop `path` from `Config` constructor and always take from environment variables or make it part of the `options` to initialise `Client`.

**Comment by woop** [comment]
@Joostrothweiler thank you for being so patient with a reply. 

This is great feedback. Based on the direction we are going we will try to allow users to set the config path.
