### ISSUE TITLE
Python SDK client config initialisation always writes new file

### ISSUE THREAD

**Issue by Joostrothweiler** [feast-dev/feast#1252]
## Expected Behavior 

The docstring for the [python client config](https://github.com/feast-dev/feast/blob/0ef41eb361b91ccbc6f9198bed428f8ca2b45a8b/sdk/python/feast/config.py#L35) seems to be outdated and incorrect.

Expected behavior is described to create a new file at specified path "If the file does not exist":
```python
def _init_config(path: str):
    """
    Returns a ConfigParser that reads in a feast configuration file. If the
    file does not exist it will be created.

    Args:
        path: Optional path to initialize as Feast configuration

    Returns: ConfigParser of the Feast configuration file, with defaults
    preloaded

    """
```

## Current Behavior

Whereas we are always writing the config to file at the end of the function (and not only "If the file does not exist"):
```python
  # Save the current configuration
  config.write(open(path, "w"))
```

This means that if you provide a path to the `init_config` method, it will always try to write to that path. It seems to me that oftentimes the system that initialised the client does not have write permissions (but only read) to the path. Therefore, it might make more sense to only write to the path if it does not yet exist. 

## Steps to reproduce

1. Create config file
2. Set permissions for file to read only
2. Open python terminal
```python
from feast import Client
import os
os.environ["FEAST_CONFIG"] = "/../some_path_dir/"` # where `config` file is located with read permissions only
client = Client()
```
4. Raises `PermissionError: [Errno 13] Permission denied: "/../some_path_dir/config/"`

### Specifications

- Version: Feast 0.8.0
- Platform: Mac
- Subsystem:

## Possible Solution

Rewrite `_init_config` to something like the following:

```python
def _init_config(path: str):
    """
    Returns a ConfigParser that reads in a feast configuration file. If the
    file does not exist it will be created.

    Args:
        path: Optional path to initialize as Feast configuration

    Returns: ConfigParser of the Feast configuration file, with defaults
    preloaded

    """
    # Create the configuration file itself
    config = ConfigParser(defaults=DEFAULTS)
    # Store all configuration in a single section
    config.add_section(CONFIG_FILE_SECTION)

    if os.path.exists(path):
        config.read(path)
        return config

    # Create the configuration file directory if needed
    config_dir = os.path.dirname(path)
    config_dir = config_dir.rstrip("/") + "/"
    os.makedirs(os.path.dirname(config_dir), exist_ok=True)
    # Save the current configuration
    config.write(open(path, "w"))
    return config
```

**Comment by jklegar** [comment]
Hey @Joostrothweiler thanks for the issue - it's a good note and has been incorporated into Feast 0.9, so a read-only config file should now work (apologies for the delay here)
