### ISSUE TITLE
Got error running minimal_ride_hailing.ipynb

### ISSUE THREAD

**Issue by bonacciog** [feast-dev/feast#1288]
## Current Behavior
job = client.get_historical_features(
feature_refs=[
"driver_statistics:avg_daily_trips",
"driver_statistics:conv_rate",
"driver_statistics:acc_rate",
"driver_trips:trips_today"
],
entity_source=entities_with_timestamp
)

KeyError Traceback (most recent call last)
/opt/conda/lib/python3.8/configparser.py in get(self, section, option, raw, vars, fallback)
788 try:
--> 789 value = d[option]
790 except KeyError:

/opt/conda/lib/python3.8/collections/init.py in getitem(self, key)
897 pass
--> 898 return self.missing(key) # support subclasses that define missing
899

/opt/conda/lib/python3.8/collections/init.py in missing(self, key)
889 def missing(self, key):
--> 890 raise KeyError(key)
891

KeyError: 'historical_feature_output_location'

During handling of the above exception, another exception occurred:

NoOptionError Traceback (most recent call last)
in 
1 # get_historical_features will return immediately once the Spark job has been submitted succesfully.
----> 2 job = client.get_historical_features(
3 feature_refs=[
4 "driver_statistics:avg_daily_trips",
5 "driver_statistics:conv_rate",

/feast/sdk/python/feast/client.py in get_historical_features(self, feature_refs, entity_source, output_location)
1032 if output_location is None:
1033 output_location = os.path.join(
-> 1034 self._config.get(opt.HISTORICAL_FEATURE_OUTPUT_LOCATION),
1035 str(uuid.uuid4()),
1036 )

/feast/sdk/python/feast/config.py in get(self, option, default)
136
137 """
--> 138 return self._get(option, default, self._config.get)
139
140 def getboolean(self, option, default=_UNSET):

/feast/sdk/python/feast/config.py in _get(self, option, default, get_method)
118 def _get(self, option, default, get_method):
119 fallback = {} if default is _UNSET else {"fallback": default}
--> 120 return get_method(
121 CONFIG_FILE_SECTION,
122 option,

/opt/conda/lib/python3.8/configparser.py in get(self, section, option, raw, vars, fallback)
790 except KeyError:
791 if fallback is _UNSET:
--> 792 raise NoOptionError(option, section)
793 else:
794 return fallback

NoOptionError: No option 'historical_feature_output_location' in section: 'general'

Specifications

I've installed Feast on my Kubernetes AWS cluster with Helm and gone to http://localhost:8888/tree? as docs said.
https://docs.feast.dev/getting-started/install-feast/kubernetes-with-helm
I was executing all cells in minimal_ride_hailing and it was all right until I tried to execute that cell.

Version: 0.8
Platform: Kubernetes Helm

<img width="564" alt="Schermata 2021-01-25 alle 15 17 18" src="https://user-images.githubusercontent.com/45511179/105717740-c7c37600-5f20-11eb-8147-42471b8cb3f9.png">

**Comment by Moshood-O** [comment]
Has anyone been able to solve this? I'm having the same issue too

**Comment by woop** [comment]
I'm sweeping through these guides to ensure they are still working. Will try to run this one this coming week. Just to confirm @Moshood-O, you are also experiencing this on Feast 0.9.1?

**Comment by Moshood-O** [comment]
I installed it using Kubernetes with helm...How do I confirm the version?

**Comment by woop** [comment]
@Moshood-O you can run `helm list`

**Comment by Moshood-O** [comment]
The version's 0.9.2

**Comment by woop** [comment]
Thanks this is great. I will try to reproduce it and resolve it asap.

**Comment by paravatha** [comment]
@Moshood-O @woop 
I was able to get past the above error, after creating ~.feast/config file mentioned here : https://github.com/feast-dev/feast/issues/1191#issuecomment-734078189

```
jovyan@feast-release-feast-jupyter-86444477b7-qx7jr:~/.feast$ cat config
[general]
historical_feature_output_location = file:///home/jovyan/test_data/output
spark_staging_location = file:///home/jovyan/test_data/staging
```

**Comment by woop** [comment]
Thanks @paravatha. Let's keep this issue open until the docs are up to date.

**Comment by woop** [comment]
The Helm chart should be providing this configuration going forward. Please let me know if anyone runs into this issue again.
