### ISSUE TITLE
Got ConnectionError while Registering entities and feature tables in Feast Core

### ISSUE THREAD

**Issue by piyushfmax** [feast-dev/feast#1314]
## Expected Behavior 
client.apply(Timestamp) and client.apply(collector_data) should register entity and feature table with Feast Core.

## Current Behavior
Instead of registering entity and feature table with Feast Core a ConnectionError is thrown:
ConnectionError: Connection timed out while attempting to connect to online_serving:6571

<img width="765" alt="error_2" src="https://user-images.githubusercontent.com/77475432/106793218-31303c80-6625-11eb-81be-81e2cd446164.PNG">
<img width="823" alt="error_1" src="https://user-images.githubusercontent.com/77475432/106793221-31c8d300-6625-11eb-97bd-f477040b6dc2.PNG">

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by woop** [comment]
Hi @piyushfmax. Thanks for trying out Feast!

This is a known bug that has been fixed here: https://github.com/feast-dev/feast/pull/1308

We are waiting to cut a release for 0.9.2 which will address the problem.

In the mean time you should ensure that you are able to connect to Feast serving. You may need to confirm that the host and port is correct.

**Comment by piyushfmax** [comment]
Thank you @woop for the prompt reply. Could you please let me know what is the expected release date for Feast 0.9.2?

**Comment by woop** [comment]
Our target is over the next week.
