### ISSUE TITLE
Why is driver_trips:trips_today none for online feature (kafka stream source) in the minimal_ride_hailing example

### ISSUE THREAD

**Issue by Adedolapo-Akin** [feast-dev/feast#1321]
![streaming_tris_today_none](https://user-images.githubusercontent.com/47377835/107215116-8dbf9d00-6a13-11eb-8358-34fe227e5989.PNG)

## Steps to reproduce

features = client.get_online_features(
    feature_refs=["driver_statistics:avg_daily_trips", "driver_trips:trips_today"],
    entity_rows=entities_sample).to_dict()

pd.DataFrame(features)

### Specifications

- Version:
- Platform:
 GCP
 Feast 0.9
- Subsystem:

**Comment by tedhtchang** [comment]
@Adedolapo-Akin It's possible the previous steps were not completed. Re-Run steps from this cell and after. At the same time, observe the `feast-release-feast-jupyter-xxxx` pod logs  for exceptions .
```
job = client.start_stream_to_online_ingestion(
    driver_trips
)
 ```

**Comment by Adedolapo-Akin** [comment]
@tedhtchang 
Thanks.
I did a re-run and it was fine.

**Comment by paravatha** [comment]
@tedhtchang I am seeing a slightly different issue, this code is never being executed
`
### Retrieving joined features from several feature tables
entities_sample = np.random.choice(entities, 10, replace=False)
entities_sample = [{"driver_id": e} for e in entities_sample]
entities_sample
`

**Comment by paravatha** [comment]
@tedhtchang @Adedolapo-Akin I am seeing the same issue but at a different point
Can you please let me know how you fixed this? Should I add some delay before and after spark job?

![image](https://user-images.githubusercontent.com/8755869/112479266-df618400-8d42-11eb-925b-6e9886be8040.png)

**Comment by tedhtchang** [comment]
@paravatha Could you re-run the notebook and verify the spark jobs have completed. You should see `job.get_status()` returns something like this `<SparkJobStatus.COMPLETED: 3>`.

**Comment by paravatha** [comment]
Yes, I added a delay in between and it works now
