### ISSUE TITLE
Update development guide to reflect new repository structure

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1353]
https://docs.feast.dev/contributing/development-guide is out of date now that we have refactored Feast repositories. This issue tracks updating the documentation for new developers.

**Comment by baineng** [comment]
Yeah, please, It confused newbies like me. The core codes are missed in master branch.

**Comment by woop** [comment]
@baineng Please see: [[Public] Feast RFC: Component Refactor](https://docs.google.com/document/d/1CjR3Ph3l65hF5bRuchR9u9WSoirnIuEb7ILY9Ioh1Sk/edit#)

**Comment by baineng** [comment]
Thanks for the update, the plan looks good and reasonable.

One quick question:
`but will also include a fully functional Python based feature store` means this repository will have a Python based feast-core and feast-serving?

**Comment by woop** [comment]
Hey @baineng, I responded similarly in Slack

Feast Core and Feast Serving are important components, but we don't believe that they are required for running a Feast deployment. We see both of these as specific implementations to the registry and serving functionalities. We're planning to make them optional going forward, and will provide even lighter weight implementations.
