### ISSUE TITLE
CSV format support

### ISSUE THREAD

**Issue by michcio1234** [feast-dev/feast#1357]
## Expected Behavior 
I can define a `FileSource` with CSV file format.

## Current Behavior
The is no such thing as `CSVFileFormat` in `feast.data_format` module, although the documentation clearly states that [CSV files are supported](https://docs.feast.dev/v/master/concepts/sources#batch-source).

### Specifications

- Version: 0.9.3
- Platform: Linux
- Subsystem: I don't know.

## Possible Solution
If it's actually possible, make the documentation clearer on how to achieve this.  
If it's not, don't write in the documentation that it is. Or implement it. I don't know enough about Feast to do it myself.

**Comment by woop** [comment]
Hey @michcio1234,

Thanks for trying out Feast and for identifying this inconsistency. The CSV data format was on our roadmap but didn't ship, and was erroneously included in in our docs. I'll fix the documentation.

**Comment by woop** [comment]
Updated.

**Comment by andrijaperovic** [comment]
@woop is csv format still within the roadmap?
