### ISSUE TITLE
Environment variable not changing problem.. (FEAST_S3_ENDPOINT_URL)

### ISSUE THREAD

**Issue by devJackie** [feast-dev/feast#1358]
Hello, I am a developer who wants to configure MLOps' feature store with Feast :)

## Expected Behavior 
Expect environment variables to be changed in k8s like local docker.

## Current Behavior
Setting the local docker environment variable works correctly.
`os.environ["FEAST_S3_ENDPOINT_URL"] = "http://172.22.0.7:9000"`

but, After deploying k8s, environment variable setting does not work properly.
environment variables setting (jupyter - minimal_ride_hailing.ipynb)
`os.environ["FEAST_S3_ENDPOINT_URL"] = "http://minio.xxx-ml-dev.is.xxx-corp.com"`

**It is always set to "https://feast.s3.amazonaws.com", even though I change the setting.**
![스크린샷 2021-02-26 오후 5 24 16](https://user-images.githubusercontent.com/10051032/109275109-a2939180-7857-11eb-9ca6-baa4913e37bf.png)

## Steps to reproduce
install Feast -> Kubernetes (with Helm)
https://docs.feast.dev/getting-started/install-feast/kubernetes-with-helm
helm version: 3.5.2
minio version: minio-8.0.10

### Specifications
- Version: Feast (latest)
- Platform: k8s

Any help would be greatly appreciated.

**Comment by woop** [comment]
@devJackie at what point in the notebook do you set the variable? The notebook has a cell at the start where env vars are printed out, is your S3_ENDPOINT_URL printed out?

**Comment by devJackie** [comment]
@woop Thanks for the quick answer :)

Yes, it is output to the notebook cell. (Refer to the image below)

(Edit with necessary environment variables)
![image](https://user-images.githubusercontent.com/10051032/109325703-96c8bf00-7899-11eb-9541-a0e0b665c2cd.png)


**The environment variable was set automatically, but I just in case set the "FEAST_S3_ENDPOINT_URL" env again.**
![image](https://user-images.githubusercontent.com/10051032/109326474-95e45d00-789a-11eb-8deb-63b1d52a9551.png)


It is always set to "https://feast.s3.amazonaws.com", even though I change the env setting(os.environ["FEAST_S3_ENDPOINT_URL"] = "http://minio.xxx-ml-dev.is.xxx-corp.com"). 😭

**Comment by devJackie** [comment]
@woop I think I solved the problem in an unusual way.

1. Connect with kubectl
`kubectl exec -it -n feast feast-release-feast-jupyter-5b54cf46-r4xl7 -- /bin/bash`

2. env check
`(base) jovyan@feast-release-feast-jupyter-5b54cf46-r4xl7:~$ env`

3. env setting (FEAST_S3_ENDPOINT_URL)
I solved the problem when export to FEAST_S3_ENDPOINT_URL.
`(base) jovyan@feast-release-feast-jupyter-5b54cf46-r4xl7:~$ export FEAST_S3_ENDPOINT_URL=http://minio.xxx-ml-dev.is.xxxcorp.com
`
![image](https://user-images.githubusercontent.com/10051032/109522984-31bbd600-7af2-11eb-8c26-ab3ce18241dc.png)

4. It was uploaded to minio.
![image](https://user-images.githubusercontent.com/10051032/109523107-5152fe80-7af2-11eb-80f4-de940080adc3.png)

Is the correct way to export FEAST_S3_ENDPOINT_URL after connecting to the container(kubectl)? 
Are there any other alternatives?

**Comment by devJackie** [comment]
This seems to be resolved. I installed [spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) with the namespace feast installed on top of k8s. 😊

**Comment by woop** [comment]
Thanks @devJackie!
