### ISSUE TITLE
How to set up spark conf in k8s

### ISSUE THREAD

**Issue by devJackie** [feast-dev/feast#1365]
## Expected Behavior 
I set up spark conf according to the example guide.
![image](https://user-images.githubusercontent.com/10051032/109934895-57262b00-7d10-11eb-9dab-90cef04bddea.png)

I may have made the wrong settings, but the spark conf options(FEAST_SPARK_EXTRA_OPTIONS) don't seem to work right now.

## Current Behavior
FEAST_SPARK_EXTRA_OPTIONS was set, but looking at the k8s log, it seems that the spark conf setting is not working.
![image](https://user-images.githubusercontent.com/10051032/109936709-85f0d100-7d11-11eb-8c96-9e60ea83eb82.png)

I ran the source code below.
![image](https://user-images.githubusercontent.com/10051032/109956229-c444bb00-7d26-11eb-85e2-91a5a9576101.png)

k8s spark-operator log capture
![image](https://user-images.githubusercontent.com/10051032/109933820-2c87a280-7d0f-11eb-8f9e-09aec8f044dd.png)

### Specifications

- Version: feast-0.9.3
- Platform: k8s
- Subsystem: spark-operator-1.0.7, minio-8.0.10

**Comment by jklegar** [comment]
Hey @devJackie, thanks for the detailed issue and for trying out Feast! I took a look into this and you're right - the FEAST_SPARK_EXTRA_OPTIONS configuration isn't implemented and I'll plan on removing the env variable from the example notebook while that remains the case. In order to specify spark conf options you'll actually want to use the FEAST_SPARK_K8S_JOB_TEMPLATE_PATH env variable to pass a path containing the spark conf yaml - see https://github.com/feast-dev/feast/blob/442cd6fb1717c5a79241e2de188c37b4628bfe4b/sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py#L278 for the default template and https://github.com/feast-dev/feast/blob/442cd6fb1717c5a79241e2de188c37b4628bfe4b/infra/scripts/test-end-to-end-local.sh#L14 for an example of a customized one. Let me know if this works for you :)

**Comment by devJackie** [comment]
@jklegar  thank you for the reply. 👍

Solved by adding **FEAST_SPARK_K8S_JOB_TEMPLATE_PATH**.

I have created a function to modify the properties of the yaml manifest and save the file.
The "S3" conf should be configured with your own environment.
(See source code at the bottom)

Then I set the location of the yaml manifest file in env.
`os.environ["FEAST_SPARK_K8S_JOB_TEMPLATE_PATH"] = file_name`

I'm attaching the source code for someone. Please tell me if my code is wrong or my method is wrong. 🤗

After setting env, it was confirmed that the core and executor of spark conf in k8s are processed in parallel.
```
import ruamel.yaml
import os
os.environ["FEAST_S3_ENDPOINT_URL"] = "http://minio.xxx-ml-dev.is.xxx.com"
os.environ["AWS_S3_ENDPOINT_URL"] = "http://minio.xxx-ml-dev.is.xxx.com"


def set_k8s_spark_conf(namespace="default", service_account="default", driver_cores=1, driver_coreLimit="1200m", driver_memory="4g", 
                   executor_cores=1, executor_instances=1, executor_memory="4g",
                  s3a_endpoint="", s3a_access_key="", s3a_secret_key=""):
    yaml_str = """
    apiVersion: "sparkoperator.k8s.io/v1beta2"
    kind: SparkApplication
    metadata:
      namespace: feast
    spec:
      type: Scala
      mode: cluster
      image: "gcr.io/kf-feast/spark-py:v3.0.1"
      imagePullPolicy: Always
      sparkVersion: "3.0.1"
      timeToLiveSeconds: 3600
      pythonVersion: "3"
      sparkConf:
        "spark.hadoop.fs.s3a.endpoint": "http://minio.xxx-ml-dev.is.xxx.com"
        "spark.hadoop.fs.s3a.path.style.access": "true"
        "spark.hadoop.fs.s3a.access.key": "GtcIY3Rsg1MMbAfD"
        "spark.hadoop.fs.s3a.secret.key": "IlQDRnhWY6jEuwDgw6PAtrMgl0Qu9NinaCv8"
      restartPolicy:
        type: Never
      volumes:
        - name: "test-volume"
          hostPath:
            path: "/tmp"
            type: Directory
      driver:
        cores: 1
        coreLimit: "1200m"
        memory: "512m"
        labels:
          version: 3.0.1
        serviceAccount: "default"
        volumeMounts:
          - name: "test-volume"
            mountPath: "/tmp"
      executor:
        cores: 1
        instances: 1
        memory: "512m"
        labels:
          version: 3.0.1
        volumeMounts:
          - name: "test-volume"
            mountPath: "/tmp"
    """
    
    dict_obj = ruamel.yaml.round_trip_load(yaml_str, preserve_quotes=True)
    dict_obj["metadata"]["namespace"] = namespace
    dict_obj["spec"]["driver"]["cores"] = driver_cores
    dict_obj["spec"]["driver"]["coreLimit"] = driver_coreLimit
    dict_obj["spec"]["driver"]["memory"] = driver_memory
    dict_obj["spec"]["executor"]["cores"] = executor_cores
    dict_obj["spec"]["executor"]["instances"] = executor_instances
    dict_obj["spec"]["executor"]["memory"] = executor_memory
    dict_obj["spec"]["sparkConf"]["spark.hadoop.fs.s3a.endpoint"] = s3a_endpoint
    dict_obj["spec"]["sparkConf"]["spark.hadoop.fs.s3a.access.key"] = s3a_access_key
    dict_obj["spec"]["sparkConf"]["spark.hadoop.fs.s3a.secret.key"] = s3a_secret_key
    dict_obj["spec"]["driver"]["serviceAccount"] = service_account
    
    return dict_obj



file_name = "/tmp/spark_conf.yml"
res_dict_obj = set_k8s_spark_conf("feast", "spark", 1, "1200m", "4g", 2, 5, "8g", "http://minio.xxx-ml-dev.is.xxx.com", "GtcIY3Rsg1MMbAfD", "IlQDRnhWY6jEuwDgw6PAtrMgl0Qu9NinaCv8")
print(ruamel.yaml.round_trip_dump(res_dict_obj, explicit_start=True))
ruamel.yaml.round_trip_dump(res_dict_obj, stream=open(file_name, 'w'), explicit_start=True)

os.environ["FEAST_SPARK_K8S_JOB_TEMPLATE_PATH"] = file_name
```
