### ISSUE TITLE
How can we get actutal real names of job(not hash)?

### ISSUE THREAD

**Issue by Andrew32bit** [feast-dev/feast#1384]
How can we get actutal real names of job(not hash)? 
```
Code here 
for job in client.list_jobs(include_terminated=False):
    print(job.get_id())

gets something like 9e5e3fe7-8aae-42c6-aa3b-b5fbc41c6884
8c5f7ea1-e00a-42ba-a649-50642346f6f3
```

But how can we determinate what job we want to kill?

**Comment by woop** [comment]
@Andrew32bit which job manager are you using? (Dataproc, EMR, Spark on K8s operator)?

**Comment by Andrew32bit** [comment]
@woop  im using python client feast for retrieve list of jobs.We are using feast 0.8.1 with docker compose image.Is it possible to know name of job via python client?

**Comment by Andrew32bit** [comment]
It can be clodes-we decided just to write to pid file for each job and monitor if job exists)
