### ISSUE TITLE
Connection refused Error when executing "start_offline_to_online_ingestion(...)"

### ISSUE THREAD

**Issue by devJackie** [feast-dev/feast#1391]
## Current Behavior

- When I run the code below, a Connection refused error occurs.

`client.start_offline_to_online_ingestion(...)`
![image](https://user-images.githubusercontent.com/10051032/111129999-1228b100-85ba-11eb-9120-0efc93db6315.png)

- Error pod log capture
<img width="2230" alt="스크린샷 2021-03-15 오후 6 07 27" src="https://user-images.githubusercontent.com/10051032/111131063-389b1c00-85bb-11eb-9618-ec48330a1d21.png">

- It's not exactly the same error, but I tried referring to it [here](https://github.com/feast-dev/feast/issues/1300), but only the host was changed and the same error occurred.
`client = Client(redis_host=os.environ["FEAST_RELEASE_REDIS_MASTER_SERVICE_HOST"])`
![image](https://user-images.githubusercontent.com/10051032/111138953-e3afd380-85c3-11eb-9e52-99ac1ee82bbb.png)

- Error pod log capture After setting (**FEAST_RELEASE_REDIS_MASTER_SERVICE_HOST**) 
<img width="2233" alt="스크린샷 2021-03-15 오후 6 07 05" src="https://user-images.githubusercontent.com/10051032/111131095-3fc22a00-85bb-11eb-9a94-4fe67774e72f.png">

- Python os environment capture (with REDIS)
![image](https://user-images.githubusercontent.com/10051032/111131557-b52dfa80-85bb-11eb-831b-aafb8a948990.png)

- k8s redis-master service yaml manifest (clusterIP is 10.231.1.50)
![image](https://user-images.githubusercontent.com/10051032/111131917-1786fb00-85bc-11eb-954a-7f33533f1fb8.png)

**Is there anything I missed? Is it impossible to connect to redis with the internal IP? 🥺**
**Or could "Connection refused Error" be some pod or service or etc problem?**

**Any help would be greatly appreciated.**

### Specifications

- Version: feast-0.9.3 (helm install)
- Platform: k8s
- Subsystem: spark-operator-1.0.7, minio-8.0.10

**Comment by devJackie** [comment]
@woop , @jklegar 

I found the answer. 🤗
It wasn't a **REDIS** problem.
External network connection to import spark jar was not possible.
After downloading, I uploaded it to s3a and imported it, and set it in the os environment.

https://github.com/feast-dev/feast-spark/blob/49142c2e8280aaae6f9157906ab1c54965f0bc18/python/feast_spark/constants.py#L53


`os.environ["FEAST_SPARK_INGESTION_JAR"] = "s3a://feast/lib/feast-ingestion-spark-develop.jar"`

Thank you all the time.

**Comment by woop** [comment]
Awesome, thanks for responding @devJackie!
