### ISSUE TITLE
How to customise feast's db to use an existing database

### ISSUE THREAD

**Issue by RaghavaKrishnaU** [feast-dev/feast#1408]
I have an mlflow-centric ecosystem which already has a full fetched postgresql database, when I tried to change the core.yaml's configuration as:
`spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_DATABASE:feast}
    username: ${DB_USERNAME:custom_uname
    password: ${DB_PASSWORD:custom_pw}`
I get connection failed error, the username, password and database were created in my db. Is there a way to spin up a custom db container where feast's core talks to the db and schema of choice?
Thanks in advance!

**Comment by woop** [comment]
Hey @RaghavaKrishnaU 

Can you please provide the full stack trace?

**Comment by RaghavaKrishnaU** [comment]
I changed the ports from 5432 to 5431 in the dockerfile of postgresql-alpine-12.6. Now that I have the entire db's context, will work on further customisations. :)

**Comment by woop** [comment]
Great, thanks for the update :)
