### ISSUE TITLE
`feast apply` seems to have no effect in creating entities etc

### ISSUE THREAD

**Issue by smatzana** [feast-dev/feast#1427]
## Expected Behavior 

I created a new repo using `feast init`
I would expect entity `driver_id` to appear in the list of registered entities but it does not

## Steps to reproduce
Installed the Python Feast SDK.
Fired up the docker-compose containers

Then:

```
% feast init
(example.py appears)
% feast apply 
<OK>
% feast entities list
NAME    DESCRIPTION    TYPE
<empty>
```
### Specifications

- Version: commit 0892cd11bb23db1142b96ba21e2e122451350f6a (HEAD -> master, origin/master, origin/HEAD)
- Platform:
- Subsystem:

**Comment by woop** [comment]
Thanks for raising @smatzana!

It's a known issue that we're working on :)
