### ISSUE TITLE
Error in cloning repo of feast 

### ISSUE THREAD

**Issue by manasjain0699** [feast-dev/feast#1430]
## Current Behavior
when I try to clone
 "git clone --depth 1 --branch v0.7.0a https://github.com/feast-dev/feast.git"
Cloning into 'feast'...
warning: Could not find remote branch v0.7.0a to clone.
fatal: Remote branch v0.7.0a not found in upstream origin

https://docs.feast.dev/v/v0.6-branch/getting-started/deploying-feast/docker-compose

## Possible Solution
I think the issue in --branch v0.7.0a should be --branch v0.7.0

**Comment by woop** [comment]
Nice catch, that `a` shouldn't be there!
