### ISSUE TITLE
Write feature API on Serving service

### ISSUE THREAD

**Issue by RoyTal28** [feast-dev/feast#1461]
Hey guys :),
According to the initial [discussion](https://github.com/feast-dev/feast-java/issues/6) that my colleague created.
I want to elaborate more about the write features API and share the proto file for initial feedback.

We think that the API should basically push feature rows for specific feature tables and projects to the online store in a similar way the ingestion logic works (RedisSinkRelation.scala).

The suggested change to the serving proto file is as follows:

![image](https://user-images.githubusercontent.com/20488412/114527895-26aba800-9c51-11eb-8483-3c818af32cf8.png)

Details explanation:
The PushOnlineFeatureRequest contains a definition of the feature table and the project.
And a key-value map containing the values of each row. 

**We assume that the feature table and the project (if empty we use default)   already exist and validate it.

The PushOnlineFeatureResponse contains a list of RowStatus that represent the pushing status of each row.

I would love to have your feedback so we can move forward and prepare a pull request soon.

Thanks!

**Comment by woop** [comment]
Hi @RoyTal28,

Thanks for the proposal!

One question that immediately comes to mind: Are users able to push a subset of feature values for a feature table? Feast currently requires that all features in a feature table be provided during ingestion, but we _could_ in the future make it possible to provide a subset. We'd probably need to read the existing row, mutate it, and then write it back.

Thanks again :)

**Comment by RoyTal28** [comment]
Hey @woop,
In my current implementation, the user can push several features and not all the defined features. 
Should I enforce that all the defined features on the feature table are part of each row on my input?

I am not sure I understand why we would need to read->mutate->write again the row? can u explain?

**Comment by woop** [comment]
> Hey @woop,
> In my current implementation, the user can push several features and not all the defined features.
> Should I enforce that all the defined features on the feature table are part of each row on my input?
> 
> I am not sure I understand why we would need to read->mutate->write again the row? can u explain?

It depends on the way features are being stored. Some storage engines will store the whole feature row as a single value. Meaning you can only update it by reading it first, otherwise some feature values may be lost if the user doesn't provide the complete row.

Perhaps for a first cut we can just say that the full feature row should be provided, but add support for partial updates in the future?

**Comment by RoyTal28** [comment]
> > Hey @woop,
> > In my current implementation, the user can push several features and not all the defined features.
> > Should I enforce that all the defined features on the feature table are part of each row on my input?
> > I am not sure I understand why we would need to read->mutate->write again the row? can u explain?
> 
> It depends on the way features are being stored. Some storage implementations will store the whole feature row as a single value. Meaning you can only update it by reading it first, otherwise some feature values may be lost if the user doesn't provide the complete row.
> 
> Perhaps for a first cut we can just say that the full feature row should be provided, but add support for partial updates in the future?

OK, that sounds good.
Regarding the proto file - Can I proceed with my suggestion?

**Comment by rmankevich** [comment]
> Hi @RoyTal28,
> 
> Thanks for the proposal!
> 
> One question that immediately comes to mind: Are users able to push a subset of feature values for a feature table? Feast currently requires that all features in a feature table be provided during ingestion, but we _could_ in the future make it possible to provide a subset. We'd probably need to read the existing row, mutate it, and then write it back.
> 
> Thanks again :)

Hi,
I just want to clarify current behaviour. I could see in existing code: 
**feast/ingestion/validation/RowValidator.scala**
 def allChecks: Column =
    allEntitiesPresent && atLeastOneFeatureNotNull && timestampPresent
Do you mean that null is also a value or there is also another place to guarantee all features are provided?

**Comment by woop** [comment]
> > > Hey @woop,
> > > In my current implementation, the user can push several features and not all the defined features.
> > > Should I enforce that all the defined features on the feature table are part of each row on my input?
> > > I am not sure I understand why we would need to read->mutate->write again the row? can u explain?
> > 
> > 
> > It depends on the way features are being stored. Some storage implementations will store the whole feature row as a single value. Meaning you can only update it by reading it first, otherwise some feature values may be lost if the user doesn't provide the complete row.
> > Perhaps for a first cut we can just say that the full feature row should be provided, but add support for partial updates in the future?
> 
> OK, that sounds good.
> Regarding the proto file - Can I proceed with my suggestion?

I think it's necessary to share this proposal more widely. Many folks have asked for a write/push API, so I'd like to make sure that people agree on the design. I think it would be better to create a Google document like [one of these](https://drive.google.com/drive/u/0/folders/1msUsgmDbVBaysmhBlg9lklYLLTMk4bC3) and share it to feast-dev@googlegroups.com. It doesn't have to be very long, but it should just allow people to easily comment on the proposed API and understand the functionality that will be introduced.

**Comment by woop** [comment]
> > Hi @RoyTal28,
> > Thanks for the proposal!
> > One question that immediately comes to mind: Are users able to push a subset of feature values for a feature table? Feast currently requires that all features in a feature table be provided during ingestion, but we _could_ in the future make it possible to provide a subset. We'd probably need to read the existing row, mutate it, and then write it back.
> > Thanks again :)
> 
> Hi,
> I just want to clarify current behaviour. I could see in existing code:
> **feast/ingestion/validation/RowValidator.scala**
> def allChecks: Column =
> allEntitiesPresent && atLeastOneFeatureNotNull && timestampPresent
> Do you mean that null is also a value or there is also another place to guarantee all features are provided?

I believe the current guarantees are simply that nulls will overwrite what exists in the store. So if you don't provide all features then you will reset existing values.

**Comment by RoyTal28** [comment]
Hey @woop ,
I have created a design document that describes the proto changes and a component diagram.
I have shared it with feast-dev@googlegroups.com and I hope to get feedback soon.
Thanks!

**Comment by woop** [comment]
The document has been in circulation now for a few days. If no objection by the end of the week then we can go ahead.

**Comment by woop** [comment]
@RoyTal28 @rmankevich @qiuleiSFDC we've left comments in the document. I think we're close to getting this pushed over the line. Would you mind having a look?

**Comment by RoyTal28** [comment]
@woop sorry for the big delay.
Our team couldn't find the resources to continue the Push API contribution work.
Now we are starting a new version in which we are planning to contribute features push API and delete API.
A pull request of the push will be created in a few days by my college.

**Comment by woop** [comment]
Thanks @RoyTal28
