### ISSUE TITLE
Ingestion from spark api

### ISSUE THREAD

**Issue by Andrew32bit** [feast-dev/feast#1465]
Hello! Is it possible make direct ingestion from spark to feast ? I want to ingest directly spark dataframe to feast

**Comment by chappers** [comment]
Hey, 

This is my attempt at this by extending the custom offline store (I haven't touched the part dealing with the online store) by leveraging the code used in [feast-spark](https://github.com/feast-dev/feast-spark/)

https://github.com/chappers/feast-spark-engine/

I think this approach works, though I would be curious on what is the official way.

**Comment by woop** [comment]
This is great @charliec443!!

We're still in the process of documenting our pluggability efforts, but you should be able to package this code up as a new provider (if you want to use Spark for materialization as well), or an OfflineStore (if you only want to use Spark for exporting data from the offline store).

We do support plugins. You can reference external classes (Providers, Stores) using the full class path https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/offline_stores/helpers.py#L8
