### ISSUE TITLE
Registry(local) in feature_store.yaml is not relative to the specified repo_path folder

### ISSUE THREAD

**Issue by tedhtchang** [feast-dev/feast#1478]
## Expected Behavior 
The `registry: data/registry.db` in the `feature_store.yaml` should be relative the specified repo_path?

## Current Behavior
The `registry: data/registry.db` is relative the current working directory.

Using the Quickstart as an example, purposely running the following code outside of the feature_repo directory and with the specified repo_path:

```
from feast import FeatureStore
store = FeatureStore(repo_path="./feature_repo")
training_df = store.get_historical_features(
    entity_df=entity_df, 
    feature_refs = [
        'driver_hourly_stats:conv_rate',
        'driver_hourly_stats:acc_rate',
        'driver_hourly_stats:avg_daily_trips'
    ],
).to_df()
training_df.head()
...
FileNotFoundError: Registry not found at path "data/registry.db". Have you run "feast apply"?
```

### Specifications

- Version: 0.10.0
- Platform: Mac
- Subsystem: OSX

## Possible Solution
Prepend specified repo_path to the relative registry_path.

```
class Registry:
...
    def __init__(self, repo_path, registry_path: str, cache_ttl: timedelta):
        """
...
        elif uri.scheme == "file" or uri.scheme == "":
            if Path(registry_path).is_absolute() is False:
                registry_path = Path(repo_path).joinpath(registry_path).as_posix()
            self._registry_store = LocalRegistryStore(registry_path)
```

**Comment by woop** [comment]
@tedhtchang this is a bug. It should be relative to the repo base. We've also noticed it. Happy to accept a fix, or we can get to it as part of our bug fixes.

**Comment by woop** [comment]
Actually, I will work on this today.

**Comment by woop** [comment]
#1477 fixes this

**Comment by tedhtchang** [comment]
New PR works. Thanks.
