### ISSUE TITLE
feast apply and Google Datastore dependency

### ISSUE THREAD

**Issue by SaschaHeyer** [feast-dev/feast#1485]
## Expected Behavior 
Running `feast apply` works without errors

## Current Behavior
Running `feast apply` runns into an error if client library is not installed https://cloud.google.com/datastore/docs/reference/libraries#client-libraries-install-python

```
cannot import name 'datastore' from 'google.cloud'
```
We should mention this dependency in the documentation. 

## Steps to reproduce

1. Run `feast apply` in an environment where the datastore client library is not installed

### Specifications

- Version: 0.10.0
- Platform: Mac
- Subsystem:

## Possible Solution
Install it with `pip install --upgrade google-cloud-datastore`

**Comment by woop** [comment]
Good catch. Thanks @SaschaHeyer!

**Comment by diogommartins** [comment]
Relates to #1560
