### ISSUE TITLE
feast deploy is a unknown command

### ISSUE THREAD

**Issue by SaschaHeyer** [feast-dev/feast#1486]
## Expected Behavior 
`feast deploy` creates cloud infrastructure in our GCP account. 

## Current Behavior
Error

````
Error: No such command 'deploy'.
````
## Steps to reproduce

1. Go to https://docs.feast.dev/concepts/apply
2. Follow the instructions until the end where `feast deploy` is described in detail
<img width="775" alt="Screenshot 2021-04-21 at 15 23 47" src="https://user-images.githubusercontent.com/1991664/115561151-935c1d80-a2b5-11eb-831f-57e6ee07bd52.png">

### Specifications

- Version: 0.10
- Platform: GCP
- Subsystem:

## Possible Solution
?

**Comment by woop** [comment]
@SaschaHeyer There is only `feast apply`. This document is inaccurate.

**Comment by SaschaHeyer** [comment]
Got it, happy to contribute such stuff as part of PR. 
Is there a dedicated repository for the documentation?

**Comment by SaschaHeyer** [comment]
I see it's already removed at the master

**Comment by woop** [comment]
This issue has been resolved through documentation updates.
