### ISSUE TITLE
Add support for Redis to new Feast

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1497]
Currently Feast only supports Redis as part of a Kubernetes deployment (Feast 0.9). We'd like to make it possible to use Redis as part of the new Feast 0.10 architecture, which would allow teams to migrate from Feast 0.9 to Feast 0.10. We also want to ensure that Feast Serving is fully decoupled from Feast Core, making it easier to operate Feast on K8s.

![image](https://user-images.githubusercontent.com/6728866/115818838-7bb68f00-a3b2-11eb-96fd-2ec52b918e88.png)

## Proposal

1. Decouple [Feast Serving](https://github.com/feast-dev/feast-java/tree/master/serving) from [Feast Core](https://github.com/feast-dev/feast-java/tree/master/core). Instead, make it possible to read `Feature Views`, `Feature Tables`, and `Entities` directly from the Protobuf [feature registry](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/registry.py) that the Feast SDK uses.
2. Add support for feature ingestion from the Feast SDK directly to Redis.
3. Update our Helm charts to provide a Spark-free and Core-free Helm installation. Basically only Feast Serving and Redis. This should be behind a flag to not disrupt existing users.
4. Add a Feast [k8s provider](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/provider.py) for reading/writing to Redis from the Feast Python SDK. ~Reads will happen through Feast Serving.~ Reads will happen directly from Redis if using the Python SDK. From Go or Java it will go through Feast Serving for the time being.

## Further Extension

**Push Based Ingestion**

As an extension to the above proposal we could also add support for push based ingestion to Redis through Feast Serving (Java), following an approach outlined https://github.com/feast-dev/feast-java/issues/6 and https://github.com/feast-dev/feast/issues/1461

We'd then let the Feast SDK write to Redis through Feast Serving using gRPC. The benefit to this approach is that teams can also use the push API for streaming ingestion.

**Spark**

We'd be able to move our existing Spark users over to this new architecture by moving a launcher ([like the Spark on K8s Feast launcher](https://github.com/feast-dev/feast-spark/tree/master/python/feast_spark/pyspark/launchers/k8s)) into the Feast SDK under a new provider.

**Comment by tedhtchang** [comment]
@woop How does the Feast Serving read the local registry ?

**Comment by woop** [comment]
> @woop How will the Feast Serving read the local registry? Or I guess for k8s deployment, the Feast Serving will only read Protobuf directly from gcs backed registry.

For K8s you will have to use the object store registry. I mean in theory you could use a volume mount, but we won't test for or support that.
