### ISSUE TITLE
Run feast cli command without cd into feature repo directory

### ISSUE THREAD

**Issue by tedhtchang** [feast-dev/feast#1507]
**Is your feature request related to a problem? Please describe.**
Is it possible to run a feast command i.e. feast apply, without cd into the feature repo directory?

**Describe the solution you'd like**
feast -p feature_repo apply
feast -p feature_repo materialize-incremental $CURRENT_TIME

**Possible solution**
PR #1509

**Comment by woop** [comment]
I think this change requires a bit of discussion. We used to have this support and we removed it to be more closely aligned with Terraform.

@tsotnet @jparthasarthy do you have thoughts on this?

**Comment by jparthasarthy** [comment]
Upon further consideration, it looks like [ Terraform does support this](https://www.terraform.io/docs/cli/commands/#switching-working-directory-with-chdir) via the  `--chdir` flag. This does seem like useful functionality to have, so no opposition to adding this. 

However, I think we should generally line up our declarative APIs with theirs, so my vote is to ship their specific API (--chdir and the same behavior.) @tedhtchang would it be possible to amend your PR?

**Comment by tsotnet** [comment]
@jparthasarthy technically Terraform's flag is `-chdir`, but I prefer to follow a more standard approach of one hyphen for short command and two hyphens for long commands. So I agree it should be `--chdir`, but would be nice to have a shorthand too, maybe `-c`?

**Comment by jparthasarthy** [comment]
SGTM @tsotnet
