### ISSUE TITLE
Default SqliteOnlineStoreConfig path value not same as online db created by `feast init`

### ISSUE THREAD

**Issue by nicelgueta** [feast-dev/feast#1522]
## Expected Behavior 
When running feast.repo_operations.teardown from python for it to teardown the repo the same way it does from the cli. 

## Current Behavior
Attempting to teardown this way throws the following error
FileNotFoundError: [Errno 2] No such file or directory: 'my_repo/data/online.db'

I believe this is because the deafult value for the SqliteOnlineStoreConfig.path is "data/online.db", however the default created by `feast init` is "data/online_store.db". Teardown does not support a parameter to specify the name of the db file, nor does it take it from the feature_store.yaml

## Steps to reproduce
Create, apply and materialise a local store and teardown using following:
from feast.repo_operations import teardown
from feast.repo_config import RepoConfig
import pathlib
teardown(RepoConfig(
    project='my_repo',
    provider='local'
), repo_path=pathlib.Path('./my_repo'))

### Specifications

- Version: 0.10.2
- Platform: JupyterHub
- Subsystem:

## Possible Solution
Simplest: change default value of `path` in SqliteOnlineStoreConfig to `online_store.db`.

**Comment by woop** [comment]
Thanks @nicelgueta.

We didn't really expect people to run this command from the SDK, but it's great that you tried it out. I think we could have done a better job at making it easier to use.

I haven't had time to check this out, but shouldn't you be specifying the `SqliteOnlineStoreConfig` as part of `RepoConfig`?

**Comment by nicelgueta** [comment]
I suppose yeah I could have provided a config, but it's an optional parameter, and I was running it locally to try it out I thought that this optionality probably came from the fact the value is sourced from the .yaml, but after encountering this error I discovered it's actually a hardcoded default value in `SqliteOnlineStoreConfig`, which is different from the default value created by `feast init`.
Super minor I know! Forgive the pedantry!
