### ISSUE TITLE
Unable to `pip install feast` (0.10.3) on mac

### ISSUE THREAD

**Issue by mstefferson** [feast-dev/feast#1525]
## Expected Behavior 

Successful pip install

## Current Behavior

On my mac:

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/12516153/116627010-2bcf4f00-a901-11eb-98a0-f9c776e59b32.png">
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/12516153/116627028-325dc680-a901-11eb-80dc-c0aa39e1af5f.png">

## Steps to reproduce

On  a macbook

`pip install feast==0.10.3` 

Note, I was able to do a clean install in an ubuntu image. I was also able to install `pip install pyarrow` worked fine.

### Specifications

- Version: Feast 0.10.3
- Platform: MacBook Pro Mojave 10.14.6 
- Subsystem: (I don't know what that means)

## Possible Solution

Unknown

## Additional comments

Feel free to close if this a random corner case.

**Comment by woop** [comment]
Thanks @mstefferson, will investigate whether pyarrow needs to be relaxed.

**Comment by dmatrix** [comment]
@mstefferson I ran into a similar issue and the workaround is to revert back to the python version 3.8 for which the numpy was built.
I believe @woop fix to have a matrix of compatible python version helps. Also, having a requiretment.txt as an argument to `pip install feast requirements.txt` may help too.
