### ISSUE TITLE
Feast Roadmap for 0.11+

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1527]
Our current proposed roadmap for 0.11 and onward is as follows

### Backlog

- On demand transformations
- Data quality monitoring
- Snowflake offline store support
- Bigtable support for Feast
- Add Push/Ingestion API support

### Scheduled for development (next 3 months)

- Ensure Feast Serving is compatible with new Feast (#1497)
    - Decouple Feast Serving from Feast Core
    - Add FeatureView support
    - Update Helm Charts (remove Core, Postgres, Job Service, Spark)
- ~Redis support for Feast (#1497)~
- Direct deployments to AWS and GCP ([RFC](https://docs.google.com/document/u/1/d/17TDdtd3GhChfEyah6dppFxD6Ce9fOmIpNdV0b6SEr5o/edit#))
- ~Dynamo support (#1409)~
- ~Redshift support (#1492)~
- Improved extensibility and contributor documentation ([RFC](https://docs.google.com/document/d/1MD0aS2_hGzd1tJ7DNjE3NgEtcuekh3O06OeQ9aavylY/edit#))
- ~Add Push/Ingestion API support~

We're open to feedback. Either new roadmap items or reprioritization!

**Comment by YikSanChan** [comment]
@woop 

> Add Push/Ingestion API support

Does "ingestion" == "consuming some streams"?

**Comment by YikSanChan** [comment]
@woop Also I hope there will be Hive support for offline store

**Comment by woop** [comment]
> Is "ingestion" == "consuming some streams"?

No. It's simply allowing teams to push events to the online store. We aren't starting consumption jobs, but in theory you could launch those jobs with a custom provider.

> @woop Also I hope there will be Hive support for offline store

@YikSanChan the current plan does not include developing Hive support. What if we work together to make it easy to add support for Hive? We can add a simply plugin interface and you can extend it to support Hive.

**Comment by YikSanChan** [comment]
@woop 

> We can add a simply plugin interface and you can extend it to support Hive.

That sounds good! Will the Hive support be similar as how Dynamo / Redshift support is added, or not?

**Comment by jianshen92** [comment]
Looking forward for Redshift support!

**Comment by cloudbow** [comment]
Looking forward to redshift, dynamo , feature view support.

**Comment by oleg-savko** [comment]
Looking forward for Clickhouse support!

**Comment by singh-b** [comment]
Is there a plan to add AWS as a provider?

**Comment by woop** [comment]
> Is there a plan to add AWS as a provider?

Yes, development is in progress.

**Comment by baineng** [comment]
@YikSanChan @woop Any progress re the Hive support? I'd like to talk/contribute to it as well.

**Comment by YikSanChan** [comment]
> @YikSanChan @woop Any progress re the Hive support? I'd like to talk/contribute to it as well.

I am not working on Hive support

**Comment by baineng** [comment]
#1686 FYI, I created a new issue for Hive support, will work on this recently.

**Comment by woop** [comment]
Thanks @baineng

**Comment by rakshithvsk** [comment]
Hey, Hi @woop,

I have recently moved from "feast 0.9.3" to "feast 0.11.0" and have few questions after using FeatureViews. Particularly I see few gaps in FeatureView

1. All I see is that FeatureView revolves around the FeatureRepo directory hence with the introduction of FeatureView, are we planning to remove dependency on Feast Core, Serving,Postgres and Feast Spark?

2. Also I don't see start_stream_to_online_ingestion in FeatureView, which was available in Client. So should I still depend on FeaturTable, and hence Feast 0.9 for online ingestion?

3. Feast 0.9.3 had client.ingest() API where data was created with datetime partitions, which was helpful in faster historical retrieval. But with Feast 0.11,  in case of local provider, we need to deal with a single large file, which might not scale up for larger datasets. Particularly if we need on-prem deployment, and if I do not want to entitle to GCP, this would be an issue. 

I believe, Point 2 and 3, should definitely be addressed as part of roadmap, if we are going with FeatureView.


Let me know your thoughts @woop

**Comment by rightx2** [comment]
@rakshithvsk I have interested in Q1, Q2 !!

**Comment by woop** [comment]
> Hey, Hi @woop,
> 
> I have recently moved from "feast 0.9.3" to "feast 0.11.0" and have few questions after using FeatureViews. Particularly I see few gaps in FeatureView
> 
> 1. All I see is that FeatureView revolves around the FeatureRepo directory hence with the introduction of FeatureView, are we planning to remove dependency on Feast Core, Serving,Postgres and Feast Spark?

Yes we are removing those dependencies, but we are not precluding the use of Spark or having an API centric registry. We just think that the base installation of Feast should be lighter weight. We are building extension points for Feast so that teams can plug in their own storage or compute systems.

> 2. Also I don't see start_stream_to_online_ingestion in FeatureView, which was available in Client. So should I still depend on FeaturTable, and hence Feast 0.9 for online ingestion?

You should use `materialize()` in order to load data from a Feature View source to the online store.

> 3. Feast 0.9.3 had client.ingest() API where data was created with datetime partitions, which was helpful in faster historical retrieval. But with Feast 0.11,  in case of local provider, we need to deal with a single large file, which might not scale up for larger datasets. Particularly if we need on-prem deployment, and if I do not want to entitle to GCP, this would be an issue.

Our File sources are meant for convenience today, and won't scale to production loads. It's just using Pandas under the hood, not Spark. I don't think the key value here was `ingest()`, but more the compute layer that did the retrieval, right?

One of our design goals is to double down on storage technologies that offload a lot of the complexity of reading, writing, and transforming data. We can't support all technologies. We'd rather support BigQuery, Redshift, and other data warehouses instead of having to rewrite the same queries as ETL pipelines in Spark. In your case it seems like Hive might be a good idea, but we don't support that today. It should be a pretty straightforward addition though.

> I believe, Point 2 and 3, should definitely be addressed as part of roadmap, if we are going with FeatureView.
> 
> Thanks
> 
> Let me know your thoughts @woop

**Comment by woop** [comment]
> @rakshithvsk, @woop I also have interested in your Q1, Q2. I'd like to add some points on the Q2:
> 
> 1. If we should depend on the `FeatureTable`, how can we materialize from stream source to online store? In new version, `Client` doesn't have `start_stream_to_online_ingestion()` anymore on feast >= v0.10 ....

Streaming jobs can be launched by `apply` if you use a custom provider. Other than that you will need to wait for us to add streaming support.

> 2. If I want to use `Featureview`, is there no way to materialize from online source to online storage?

Materialize()

> Thanks

**Comment by rightx2** [comment]
> Materialize()
Isn't it for loading data from 'offline' source to 'online' storage? I asked from 'online(streaming)' source to 'online' storage... But according to your first answer, I guess I need to wait for you guys to add streaming support

**Comment by woop** [comment]
> > Materialize()
> 
> Isn't it for loading data from 'offline' source to 'online' storage? I asked from 'online(streaming)' source to 'online' storage... But according to your first answer, I guess I need to wait for you guys to add streaming support

Ah I see. I was through off by "online source". Yea, there is not solution right now.
