### ISSUE TITLE
feast cli minor bug

### ISSUE THREAD

**Issue by dmatrix** [feast-dev/feast#1531]
## Expected Behavior 

`feast teardown --help` should list the options to this subcommand like

> (feast) ➜  examples git:(br_jsd_mlflow_feast_example) ✗ feast init --help
> Usage: feast init [OPTIONS] [PROJECT_DIRECTORY]
> 
>   Create a new Feast repository
> 
> Options:
>   -m, --minimal               Create an empty project repository
>   -t, --template [local|gcp]  Specify a template for the created project
>   --help                      Show this message and exit.

## Current Behavior

> (base) ➜  delta-lake git:(master) ✗ feast teardown --help
> Usage: feast teardown [OPTIONS]
> 
>   Tear down deployed feature store infrastructure
> 
> Options:
>   --help  Show this message and exit.

I reckon this is a generic message if the subcommand has not options. For example, `feast apply --help` exhibits similar 
behavior.

## Steps to reproduce

`feast teardown --help`

### Specifications

- Version: 0.10.3
- Platform: MacOS Mojave
- Subsystem:

**Comment by woop** [comment]
Thanks @dmatrix. Definitely a few rough edges around the new CLI. Let's keep this issue open until resolved!

**Comment by tedhtchang** [comment]
@dmatrix I'd like to fix this. What exactly should the `feast teardown --help` and `feast apply --help` print ?

**Comment by dmatrix** [comment]
@tedhtchang Generally speaking, most usage messages would print out options if available. For example, the
`feast init --help` will print out: 

> (base) ➜  delta-lake git:(master) ✗ feast init --help
> Usage: feast init [OPTIONS] [PROJECT_DIRECTORY]
> 
>   Create a new Feast repository
> 
> Options:
>   -m, --minimal               Create an empty project repository
>   -t, --template [local|gcp]  Specify a template for the created project
>   --help                      Show this message and exit.

If no options exist for a subcommand, then it's not unreasonable to indicate none exists, IMHO. For example, one can
envision something such as:

> Usage: feast teardown [OPTIONS]
> 
>   Tear down deployed feature store infrastructure
> 
> Options:(No current command options)
>   --help  Show this message and exit.


cc: @woop can recommend or opine on what should the message be or what should it indicate.

**Comment by woop** [comment]
Currently we don't have options for this command (teardown and apply), so following @dmatrix's second recommendation may make sense.
