### ISSUE TITLE
writing to the registry - shall the provider do the write operation or should it live elsewhere?

### ISSUE THREAD

**Issue by vtao2** [feast-dev/feast#1546]
Currently, `materialize()` writes to the registry as a part of the provider code to apply the feature view. It seems that apply() is necessary to save the `FeatureView` in the registry to keep track to timestamps during `materialize_single_feature_view()`. 

Want to start a discussion on whether or not this **write to the registry** belongs to the provider code? Or does it belong in `feature_store.py`? From our side, our instinct was that the `provider` would not be responsible for saving metadata, and it would be more on the responsibility for the `feature_store`. Would like to hear your thoughts @woop and team.

cc @MattDelac

**Comment by woop** [comment]
Hi @vtao2!

I agree with you. The provider and registry should be independent, so I think this code needs a refactor.

Actually there is another problem in that the state that is captured right now during materialize is **_store_** specific, yet it gets saved in the registry in a store agnostic way. This creates a problem where if you change your online store after materialization, you won't be ingesting the same values again, even if the new store is empty. So we either need
1. An awareness of stores inside the registry
2. Store the materialization intervals within the store itself

The latter option would require the provider to track intervals. Happy to hear your thoughts on this as well!

**Comment by woop** [comment]
Scheduling this for development. Please let me know if you've already taken a stab at this.

**Comment by vtao2** [comment]
@woop thank you !! I haven't gotten around to it yet since we're focusing on a batch end to end pipeline for now . Very happy to hear it's scheduled for development though thank you !!!! :)
