### ISSUE TITLE
Add S3 support to FileSource

### ISSUE THREAD

**Issue by qooba** [feast-dev/feast#1548]
**Is your feature request related to a problem? Please describe.**
It should be possible to use s3 file path directly in ```FileSource```
eg.
``` python
driver_hourly_stats = FileSource(
    path="s3://driver/driver_stats.parquet",
    event_timestamp_column="datetime",
    created_timestamp_column="created",
)
```
additionally it should be possible to use custom S3 endpoints.

**Describe the solution you'd like**
I have added S3 support which is internally handled by pyarrow and pandas. 
It is also possible to use custom S3 endpoints using ```FEAST_S3_ENDPOINT_URL``` environment variable

**Comment by woop** [comment]
Thanks for this @qooba. Also, thank you for being so patient with our delayed reviews. We're hoping to speed things up going forward!
