### ISSUE TITLE
Regarding the immutability of featureTable's entity. 

### ISSUE THREAD

**Issue by qiuleiSFDC** [feast-dev/feast#1566]
## Expected Behavior 
As mentioned in [ApplyFeatureTable](https://github.com/feast-dev/feast/blob/v0.9-branch/protos/feast/core/CoreService.proto#L92), the entity can't be changed after table created. 

## Current Behavior
But I don't see any code which checks and verifies the FeatureTable's entities' immutability in the applyFeatureTable workflow. And interestingly, there is a IT test [shouldUpdateFeatureTableOnEntityChange](https://github.com/feast-dev/feast-java/blob/bea6f21a974d7efcddd7a0e35d34137d3cfe160d/core/src/test/java/feast/core/service/SpecServiceIT.java#L580) which verifies the entities can be changed successfully.

### Specifications

- Version: v0.9
- Platform:
- Subsystem:

## Possible Solution
Add a verification to throw exception if there is a entity change.

**Comment by tedhtchang** [comment]
@qiuleiSFDC Could you provide code to reproduce and the errors messages you saw ?

**Comment by woop** [comment]
> But I don't see any code which checks and verifies the FeatureTable's entities' immutability in the applyFeatureTable workflow. And interestingly, there is a IT test shouldUpdateFeatureTableOnEntityChange which verifies the entities can be changed successfully.

From Feast 0.10 onwards we support changes to entities in FeatureViews, and when we add support for FeatureTables we will also ensure support for these changes. In 0.9 it seems like support was added, but the protos weren't updated.

**Comment by qiuleiSFDC** [comment]
Since entity is updatable, we can close this issue.
