### ISSUE TITLE
Support SQL(PSQL) as a DataSource

### ISSUE THREAD

**Issue by sedflix** [feast-dev/feast#1568]
**Is your feature request related to a problem? Please describe.**
Most of our existing data is either in PSQL, therefore we would like an option to be to ingest data from it.

**Describe the solution you'd like**
Adding PSQL(or a generic SQL) as a DataSource.

**Comment by woop** [comment]
@sedflix do you mean as an offline store?

**Comment by sedflix** [comment]
Oops. I had a conceptual misunderstanding.
