### ISSUE TITLE
Introduce Feature Services

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#1572]
You can view & comment [the following doc](https://docs.google.com/document/d/1jC0RJbyYLilXTOrLVBeR22PYLK5fe2JmQK1mKdZ-eno/edit#)

**Is your feature request related to a problem? Please describe.**
Feature Tables and Views allow for storage level grouping of features based on how they are produced. However, there is no concept of a retrieval-level grouping of features in Feast. Without a retrieval-level grouping of features that maps to models

- There is no way for users to track which features were used in the training of a model, or which features are being used for the serving of a specific model. 
- Retrieving features during training requires a complete list of features to be provided, and this complete list of features needs to be persisted and loaded for online serving. This persistence and loading is a low-level implementation that may be error prone (if not all features are references, or provided in the wrong order).
- There is no way to ensure that consumers won't have breaking changes when feature views and tables change since there is no awareness of features that are in use.

**Describe the solution you'd like**
[See doc #design](https://github.com/feast-dev/feast/issues/1572)

**Describe alternatives you've considered**
[See doc #alternatives](https://github.com/feast-dev/feast/issues/1572)

**Additional context**

**Comment by woop** [comment]
Thanks @MattDelac. I'll also send out this RFC to the mailing list.
