### ISSUE TITLE
Materialization into Datastore leads to contention error

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1575]
This issue was reported directly to us by a user. Documenting the failure here for posterity:

```
Materializing 1 feature views from 2021-04-29 21:19:00-07:00 to 2021-04-29 21:19:05-07:00 into the datastore online store.
my_fv:
  8%|████▋                                                    | 2720/33120 [00:07<01:18, 388.10it/s]

[SNIP]

google.api_core.exceptions.Aborted: 409 too much contention on these datastore entities. please try again. entity groups: 
```

Example of the data used for ingestion https://pastebin.com/raw/GCJ2CLSb (this is just a sample, the actual ingestion contains many more rows)

**Comment by woop** [comment]
This issue seems to only happen in the old Datastore (not Firestore in Datastore mode)

**Comment by judahrand** [comment]
I'm facing this issue still 🤔

**Comment by adchia** [comment]
Consolidating in the linked issue

**Comment by adchia** [comment]
think that my (not very well researched) recommendation here generally probably is to stick with bigtable for larger scale use cases since it's both cheaper, doesn't suffer from these afaict, and now auto scales.
