### ISSUE TITLE
Bump fastavro version

### ISSUE THREAD

**Issue by kevinhu** [feast-dev/feast#1584]
**Is your feature request related to a problem? Please describe.**
The version of Fastavro that we're using is kinda old and may be buggy soon. It's also causing some version conflicts with packages that have already upgraded to the newer (1.xx) versions.

**Describe the solution you'd like**
Bump Fastavro to 1.x.x

**Comment by woop** [comment]
Sounds good to me. @kevinhu do you want to try to take a stab at it?
