### ISSUE TITLE
Getting sequence of the data using time_window?

### ISSUE THREAD

**Issue by rightx2** [feast-dev/feast#1592]
**Is your feature request related to a problem? Please describe.**
I'd like to get the *sequence* of data to train them with the sequential model(e.g. RNN). But It looks like feast only support getting most recent data row like this:
![before](https://user-images.githubusercontent.com/10606994/119911676-b785db00-bf94-11eb-82ad-61893a4081d3.png)

**Describe the solution you'd like**
This is what I want:
![after](https://user-images.githubusercontent.com/10606994/119911694-bf457f80-bf94-11eb-91e9-2526e0af848c.png)

**Describe alternatives you've considered**
Still got no idea of alternatives. It would be nice if you can suggest any way to implement this

**Comment by woop** [comment]
@rightx2, Feast supports what you are looking for. You need to use `get_historical_features()`. The entity dataframe that you pass to Feast should provide multiple rows, each row maps to the "red box" in the diagram. And the time it scans backward is called the TTL.

**Comment by rightx2** [comment]
@woop you mean, If I want to get whole green diamond data of given id, I have to prepare 3 rows, the same id with 3 different datetimes, right?

**Comment by rightx2** [comment]
If that so, that's so inefficient,,,isn't it?

**Comment by woop** [comment]
Inefficient in terms of? You just write a query like `SELECT customer, timestamp from table_with_target_variable WHERE date > A and date < B`, and you can even pass that to Feast and Feast will run it. 

Or did you mean something else in terms of inefficient? Is there a different approach that you would prefer?

**Comment by rightx2** [comment]
@woop Looks like my word somewhat confuse you. Sorry for that. What I'd like to say is that If the query you wrote is just for preparing `entity_df`, that would work in `get_historical_features()` but what about in `get_online_features()`? I even need the sequence of data of the given id in the inference time but I can only pass `id` without date infos in this case?

**Comment by woop** [comment]
> @woop Looks like my word somewhat confuse you. Sorry for that. What I'd like to say is that If the query you wrote is just for preparing `entity_df`, that would work in `get_historical_features()` but what about in `get_online_features()`? I even need the sequence of data of the given id in the inference time which requires only `id` without `date`?

You only need to provide the `id` for online retrieval. In `get_online_features` you only return the latest value.

**Comment by rightx2** [comment]
@woop That's what I have complained about. I need to have a sequence of data in the online phase as well cuz my RNN model needs a sequence. Feast does not support this, doesn't it?

**Comment by woop** [comment]
> @woop That's what I have curious about. I need to have a sequence of data in the online phase as well cuz my RNN model needs a sequence in inference time. The Feast does not support this, doesn't it?

That's why I was confused, because you said `train`. Are you training or predicting? Unless you are doing time-series forecasting, why do you need historical data for prediction? That isn't a use case that I have seen come up before.

**Comment by rightx2** [comment]
@woop  I don't see why you're confused, focusing on the word `train`? `train` phase should be consistent with `inference`, of course. They both are supposed to have the same format of input X.... My model is for time series prediction.. getting N of sequence as an input and have an output of binary(classification). So I need sequence of X data(for a given time window) for both `train` and `prediction` phases and asked whether feast support this or not. Is that clear?

**Comment by woop** [comment]
>  I don't see why you're confused, focusing on the word train? train phase should be consistent with inference, of course.

For the majority of ML use cases this is _not_ true. You only need consistency between feature columns. For prediction you only need the current feature values, not historic ones.

For time series however, it is the case that you need historic values. The reason why I was confused is because I didn't realize that your model is time series.. Now that I know that you are talking about time series, its clear what you are looking for.

Feast does not currently support time series lookups for online serving using the online store. The only way to achieve it today is to

1. Create features for the time differences that you want. So you could do something like

Something like `customer` - > `f1_time_now`, `f1_time_minus_1_second`, `f1_time_minus_2_seconds`

OR

2. You can use time as an entity

Something like `customer`, `time_difference` -> `f1`, but then you would need to have a convention for `time`. It would be some interval of time in the past. So your lookup would be something like

```
get_online_features(
    features=["f1"],
    entity_rows=[{"customer": 1, "time_difference": 0}, {"customer": 1, "time_difference": 1}, {"customer": 1, "time_difference": 2}]
)
```

**Comment by rightx2** [comment]
- Method 1 could be a good way to model like DNN, XGBoost, but not for a Recurrent-based model because it learns sequence itself. These kinds of model doesn't need to flatten sequence info horizontally.
- Method 2 will be very risky because`time_difference` will be changed as the data being collected and time goes.

I need to think about more to make it work or the way to contribute this feature on the feast
