### ISSUE TITLE
Remove hardcoded references to providers and stores

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1605]
As per https://docs.google.com/document/d/1MD0aS2_hGzd1tJ7DNjE3NgEtcuekh3O06OeQ9aavylY/edit#, we need to ensure that there aren't any hardcoded references in our code to Provider or Store implementations.

**Comment by achals** [comment]
@woop just to be clear you mean that we should be hardcoding to any specific instance of a store or a provider, right?

**Comment by woop** [comment]
This card is done.
