### ISSUE TITLE
Provide option to strip feature view names from feature names

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1618]
**Is your feature request related to a problem? Please describe.**
Users often have hardcode logic in model training pipelines based on specific feature names that come from their data sources. When Feast is introduced during productionization, we expect users to rename their feature names to the Feast convention `feature_view__feature`. This creates an unnecessary overhead for teams if they have many features.

**Describe the solution you'd like**
Provide a way to strip the `feature_view__` prefix from feature names during retrieval and reuse feature names directly from sources.

before
```
training_df = store.get_historical_features(
    entity_df=entity_df, 
    feature_refs = [
        'driver_performance:conv_rate',
        'driver_performance:acc_rate',
        'driver_hourly_stats:avg_daily_trips'
    ],
)
for feature_name in training_df.columns:
    print(feature_name)
```
```
driver_performance__conv_rate
driver_performance__acc_rate
driver_hourly_stats__avg_daily_trips
```
after
```
training_df = store.get_historical_features(
    entity_df=entity_df, 
    feature_refs = [
        'driver_performance:conv_rate',
        'driver_performance:acc_rate',
        'driver_hourly_stats:avg_daily_trips'
    ],
    feature_names_only=True
)
for feature_name in training_df.columns:
    print(feature_name)
```
```
conv_rate
acc_rate
avg_daily_trips
```

Any collisions in feature names would result in an exception.

**Comment by Mwad22** [comment]
Working on this currently, supervised by David Liu from Twitter!

**Comment by woop** [comment]
FYI there is another question: Whether the default should be to prefix feature view names, or not. Most users seem to not want them.

**Comment by mavysavydav** [comment]
gotcha, we'll proceed with the default being the simple name and if u guys change your mind, we can change the default value in the code easily. I think for twitter, we'd have a high chance of feature name simple name collisions, so we'd set the param to false, but if it'll be better for feasts' growth and adoption to have it as true, that's ok
