### ISSUE TITLE
Decouple Feature Registry from specific storage solution

### ISSUE THREAD

**Issue by mavysavydav** [feast-dev/feast#1643]
**Is your feature request related to a problem? Please describe.**

We would like to have the feature registry stored in other places like BQ.  In terms of what we're trying to achieve, we want the features and feature views to be in an easy to explore format. We also would like want to be able to access this data performantly in the online context for retrieval of [feature sets (i.e. feature services)](https://docs.google.com/document/d/1jC0RJbyYLilXTOrLVBeR22PYLK5fe2JmQK1mKdZ-eno/edit#). Am open to accomplishing these goals by other means. 

**Describe the solution you'd like**

Create abstract interface for Feature Registry storing that various storage solutions can implement. 

**Describe alternatives you've considered**

Different writers that can read the data from GCS to store in other storage option. 

**Additional context**

**Comment by woop** [comment]
@mavysavydav here is an idea. What about only moving from a proto blob on GCS to a .json file on GCS, and then using https://cloud.google.com/bigquery/external-data-cloud-storage to build a view over the .json file. Seems like that could be pretty easy to do, since its trivial to convert proto objects to JSON and back (although we'll need to add tests to make sure no type issues occur).

**Comment by woop** [comment]
Yea, correct. 
> So if I wanted to have the BQ table always up to date, i'd use something like - https://cloud.google.com/functions/docs/calling/storage 

Is this necessary? I thought the federated query would just read the json file. Is there a reason to use a cloud function?

**Comment by mavysavydav** [comment]
I think this will work. Did not know about big query external tables / federated queries.

**Comment by codyjlin** [comment]
Hi all, based on the current needs of the Twitter team and the RFC [here](https://docs.google.com/document/d/1mGsKKiTR2FlaEav1jzUFeR4Lbt5Q5JfXbsUxiDvwRIE/edit#), I will start working on an MVP for the option to store a separate registry on BigQuery (in addition to existing proto blob at the path specified by the registry field in the `.yaml` config).

### Implementation details
Here's my main thoughts, happy to hear any feedback:
1. Optional field in the yaml config for whether the registry should be duplicated in a BigQuery table.
    1. Before:
        ```
        registry: <path>
        ```
        After:
        ```
        registry:
            path: <path>
            bigquery: <project_id>.<dataset>
        ```
2. If the bq field is set, then a `.json` file of the same name will be created alongside the proto blob in GCS
    1. I'm assuming the path is a GCS path too, but let me know if we should allow the registry to be a local filepath but still create the `JSON` in GCS
    2. Is it good practice to try to reuse the same name or should we provide another field for `gcs_json_path`?
3. Design views in BigQuery on the json file, which will have a view per object type (Entities, FeatureViews, etc.), and a row per actual object in the corresponding views.

**Comment by woop** [comment]
> Hi all, based on the current needs of the Twitter team and the RFC [here](https://docs.google.com/document/d/1mGsKKiTR2FlaEav1jzUFeR4Lbt5Q5JfXbsUxiDvwRIE/edit#), I will start working on an MVP for the option to store a

At first glance it seems like the BigQuery view can be static, right? I like the idea of also writing a `.json` blob next to the proto blob, but I wonder if Feast should be responsible for creating the BigQuery view. It seems like that may be a separate view that is defined outside of Feast.

**Comment by codyjlin** [comment]
Sorry @woop just revised my long comment, you were too quick!

**Comment by woop** [comment]
Can I make a difference suggestion? What about moving from specifying a file name
```
registry: this/is/my/file.db
```
To a folder
```
registry: this/is/my/folder
```
and then Feast treats that folder as the location to store the the registry, but it comes up with the Proto registry name. Then we can add a flag like
```
registry:
  path: this/is/my/folder
  publish_json: true
```
The reason I prefer this approach is because it requires less effort for users to provide a folder path than to come up with a registry.db name. It also simplifies adding a `.json` file.

**Comment by codyjlin** [comment]
> The reason I prefer this approach is because it requires less effort for users to provide a folder path than to come up with a registry.db name.

For sure, I totally agree with you. A few questions:
1. How about the automatic registry name be `<project_name>_registry.json`?
2. Do you know what the common file type suffix is for the proto blob?

**Comment by woop** [comment]
> > The reason I prefer this approach is because it requires less effort for users to provide a folder path than to come up with a registry.db name.
> 
> For sure, I totally agree with you. A few questions:
> 
> 1. How about the automatic registry name be `<project_name>_registry.json`?
> 2. Do you know what the common file type suffix is for the proto blob?

1. What about just `registry`? Do we need to have more than one registry in the same folder?
2. What about `pb`? So `registry.pb`, like [this](https://stackoverflow.com/questions/50632258/how-to-restore-tensorflow-model-from-pb-file-in-python)

**Comment by tsotnet** [comment]
@woop Instead of maintaining both proto and json registries, what do you think about simply switching from proto blobs to json? This will avoid issues with json and proto being out of sync. On the Feast SDK side, we can download the json blob and convert it to proto object as needed.

**Comment by woop** [comment]
> @woop Instead of maintaining both proto and json registries, what do you think about simply switching from proto blobs to json? This will avoid issues with json and proto being out of sync. On the Feast SDK side, we can download the json blob and convert it to proto object as needed.

I advocated for that, but @oavdeev had a concern regarding the fact that proto <> json serialization isn't guaranteed to work. There may be conversion problems. I'm open to the idea, but we'd need to add tests to ensure that the conversion works 100% correctly to and from.

**Comment by oavdeev** [comment]
I think it may work its just some of the nice properties of protobufs are lost in JSON, e.g. renaming fields is no longer possible.

**Comment by codyjlin** [comment]
> I think it may work its just some of the nice properties of protobufs are lost in JSON, e.g. renaming fields is no longer possible.

Plus protobuf is much a more efficient serialization right? My changes in #1653 keep protobuf as the default, but just duplicates it as JSON every time the registry is updated if the `publish_json` field is set.

**Comment by woop** [comment]
> @woop Instead of maintaining both proto and json registries, what do you think about simply switching from proto blobs to json? This will avoid issues with json and proto being out of sync. On the Feast SDK side, we can download the json blob and convert it to proto object as needed.

Also @tsotnet I'm not sure if it's clear, but we're not maintaining two registries. We are simply publishing a json copy of the registry as a read only file. 

Can we stick to this approach for now and change the storage format in the future?

**Comment by tsotnet** [comment]
> Also @tsotnet I'm not sure if it's clear, but we're not maintaining two registries. We are simply publishing a json copy of the registry as a read only file.
> 
> I don't feel too strongly. Can we stick to this approach for now and change/merge the storage format in the future? @tsotnet do you have strong opinions?

As long as the JSON file is a read-only replica, I'm fine with it. @oavdeev's point of not being able to rename fields also makes sense.

**Comment by mavysavydav** [comment]
We had decided to go with implementing the JSON conversion in our custom code, so no changes were made to OSS and have closed this issue.
