### ISSUE TITLE
Clean up inferencing code

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1645]
A few small refactors are necessary for our feature inferencing code.

All inferencing of columns from sources should only happen during `apply` time, not during the construction of objects. Otherwise these objects will execute eagerly during instantiation which prevents Feast from controlling the execution order and may even lead to duplicate executions.

One example is over here: https://github.com/feast-dev/feast/blob/f29cb8cca5d87b2f9a56fd02428e9a9f014a079f/sdk/python/feast/data_source.py#L676

Also, inferencing code should be more cleanly separated. Right now we have a DataSource being subclassed to implementations, which reference the DataSource base class, which contains hardcoded references to the same child classes, which then call methods on this child classes. The interdependencies are overly complex and cyclic. 
https://github.com/feast-dev/feast/commit/f55b51cf25efbf846e65115cfa23fe2c4a8d9edd#diff-fada7a84510bd3d3051cffc414ee51ed92eff4cdd4c2ac53a1b8b7c47286cab4R523

We can maybe just extract `_infer_event_timestamp_column` code into a function on its own.

Finally, we don't need to query tables in order to get schemas. We can simply use the `get_table()` method and inspect the schema instead of pulling data to the client https://github.com/feast-dev/feast/commit/f55b51cf25efbf846e65115cfa23fe2c4a8d9edd#diff-fada7a84510bd3d3051cffc414ee51ed92eff4cdd4c2ac53a1b8b7c47286cab4R756

**Comment by mavysavydav** [comment]
got it, working on it

**Comment by woop** [comment]
Thanks @mavysavydav!
