### ISSUE TITLE
Automatically retry an upload of the registry to GCS

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#1650]
## Expected Behavior 
At the end of a `feast apply`, we should have a retry strategy if the upload failed because of a 5** error
## Current Behavior
When I use `feast apply` in my Continuous Deployment process, I sometimes encounter issues with GCS
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/18557047/122227731-29ab5a80-ce85-11eb-846e-74c386f00447.png">

## Steps to reproduce
`feast apply` during a CI/CD process using GCS to store the registry
If it fails, I simply need to retry the CD job manually

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
Use [tenacity](https://tenacity.readthedocs.io/en/latest/) 😉

**Comment by woop** [comment]
@MattDelac I am wondering if this code should live within Feast or should be outside (Gitlab CI retries or a wrapper), just from a point of view of keeping things as simple as possible.

**Comment by MattDelac** [comment]
> @MattDelac I am wondering if this code should live within Feast or should be outside (Gitlab CI retries or a wrapper), just from a point of view of keeping things as simple as possible.

Yes I thought about it. Unsure about CI retries. Will check toward this direction too

**Comment by woop** [comment]
@MattDelac are you still having this problem? If so, should we perhaps look into figuring out the root cause on the Feast SDK side? I suspect this is related to hitting rate limits on GCS.
