### ISSUE TITLE
Ability to choose the BQ project in Feast

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#1655]
**Is your feature request related to a problem? Please describe.**
After merging the [current commit](https://github.com/feast-dev/feast/commit/a3d7c8661039eb3abc1beb9cb48718a6ad24e3ef), we need to create datasets on the ServiceAccount that is currently using Feast. This cause permissions issues on our side

The issue it that the service account that using Feast might have permissions to write into another BQ account that is not its own.

**Describe the solution you'd like**
Thus we should be able to pass the `project` in which to write tables/datasets in the `BigQueryOfflineStoreConfig()`.
This could be an optional argument and get infer if not passed

**Describe alternatives you've considered**
Give permissions to service accounts that don't need it

**Additional context**

**Comment by woop** [comment]
> The issue it that the service account that using Feast might have permissions to write into another BQ account that is not its own.

I'm a bit confused. How is having permissions a problem. Or are you saying that **do** want to write to a different project?

**Comment by MattDelac** [comment]
> Or are you saying that do want to write to a different project?

Yes ! Having the ability to write to a project that is different from the current Service Account

**Comment by woop** [comment]
I see, feel free to add the `project` field to the config. Sounds good to me.
