### ISSUE TITLE
Remove sys.exit from exception handling

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#1666]
We're currently calling sys.exit on exception handling here https://github.com/feast-dev/feast/blob/master/sdk/python/feast/feature_store.py#L301, which will cause the Feast (and wrapping) process to exit. Instead, we should either reraise or even just let the exception bubble up.

**Comment by charliec443** [comment]
Is the "simple" fix just to reraise everything? Or is it more nuanced than that?
Happy to put a quick PR for it.

**Comment by achals** [comment]
@charliec443 I think it's sufficient to not catch the exception at all if all we're doing it re-raising it - but I was looking at the code and I don't see a `sys.exit` call anywhere in the `feature_store.py`. Maybe it was removed in an intermediate PR?

**Comment by charliec443** [comment]
Yes I think you're right. it was progressively removed in in some of the PRs, I think namely the Redshift one.

**Comment by achals** [comment]
Alright, going to close this out in that case!

**Comment by achals** [comment]
Fixed by #1641
