### ISSUE TITLE
Duplicate rows in entity_df can cause get_historical_features to return more rows than input

### ISSUE THREAD

**Issue by codyjlin** [feast-dev/feast#1693]
## Expected Behavior 
`get_historical_features` works regardless of whether there are duplicate rows or not. (Or clarify that there should not be duplicate rows in the `entity_df` and shift it to the user's responsibility)

## Current Behavior
Working with a pretty large dataset (input_df with 1+ billion total rows and 0.4+ million unique rows), I didn't remove duplicates and noticed that `get_historical_features` returned a table with 170+ billion rows (not sure how). All was well after I removed duplicates from the entity_df and reran `get_historical_features` 

## Steps to reproduce
Couldn't reproduce in a simple example with just one duplicate, but since I was able to fix my issue by deduplicating the entity_df, I suspect this is the problem.

## Possible Solution
- if we want to support entity_df with duplicate rows
    - look deeper into the join and figure out how it can result in extra rows
- if we don't want to support entity_df with duplicate rows
    - validate that the entity_df has no duplicates and warn user or throw an exception

**Comment by woop** [comment]
From your description it seems like more rows are being returned than you expected. You should always be getting back exactly the same amount of rows as you provided in the entity_df. I think it's going to be necessary for us to find a way to reproduce this problem in order to be sure it's related to duplicates.

**Comment by codyjlin** [comment]
> From your description it seems like more rows are being returned than you expected.

Yep, exactly. I'm not really sure how it happened either, but I also don't have much time to dig deeper into the issue at the moment. Happy to just have this closed until it reappears in the future / is a recurring issue.
