### ISSUE TITLE
BigQuery Columns are not escaped in FeatureView point in time query

### ISSUE THREAD

**Issue by hugoleodev** [feast-dev/feast#1695]
## Expected Behavior 
When FeatureView name is a hyphen separated, just like "cool-feature-view" the feature view point in time query should escape columns names.

## Current Behavior
The current query does not escape the column names

## Steps to reproduce
- Create a FeatureView with hyphen separated name
- Retrieve historical features from feature store with hyphen separated features_refs

## Possible Solution

Escape column names in BigQuery feature view point in time query here: https://github.com/feast-dev/feast/blob/cb1e7d76605bbac33974c3c1e1a0fec64d96528c/sdk/python/feast/infra/offline_stores/bigquery.py#L482

**Comment by woop** [comment]
Thanks @hugoleodev, makes sense. Seems like a bug.

**Comment by hugoleodev** [comment]
@woop In fact, I think that the expected behavior should be a FeatureView name validation for BigQuery column name constraints.
