### ISSUE TITLE
Support for BQ Datasets not in US

### ISSUE THREAD

**Issue by eliasecchi-dt** [feast-dev/feast#1728]
## Expected Behavior 
 Currently Feast is assuming the location of my datasets is always in US as this is the current default location for the BQ Client. 
It would be good to have the possibility to specify the location somewhere

## Current Behavior

```
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/feast/infra/offline_stores/bigquery.py", line 239, in to_df
    df = self.client.query(self.query).to_dataframe(create_bqstorage_client=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1340, in to_dataframe
    query_result = wait_for_query(self, progress_bar_type)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/cloud/bigquery/_tqdm_helpers.py", line 65, in wait_for_query
    return query_job.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1172, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 679, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/api_core/future/polling.py", line 134, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset project_id:test_feast was not found in location US
```

**Comment by woop** [comment]
You should be able to set the `dataset` manually as part of your bigquery configuration. Or would you like to **not** set the dataset name but only the region?

**Comment by elia-secchi** [comment]
@eliasecchi-dt thanks for your quick response! I am able to set manually my table reference as part Big query source configuration. When I do feast apply everything works well but when I try to store some data in that table I receive a message saying that the dataset can't be found in US. So yes responding to your question I would like to set the region for a certain table (and the relative dataset)

**Comment by elia-secchi** [comment]
@woop  thanks for your quick response! I am able to set manually my table reference as part Big query source configuration. When I do feast apply everything works well but when I try to store some data in that table I receive a message saying that the dataset can't be found in US. So yes responding to your question I would like to set the region for a certain table (and the relative dataset)

**Comment by woop** [comment]
> @woop thanks for your quick response! I am able to set manually my table reference as part Big query source configuration. When I do `feast apply` everything works well but when I try to store some data in that table I receive a message saying that the dataset can't be found in US. So yes responding to your question I would like to set the location for a certain table (and the relative dataset)

@elia-secchi can you try to delete that dataset, recreate it manually in the right region, and then configure Feast to use your dataset? I am assuming you are still using the automatically generated on (which defaults to the US).

**Comment by woop** [comment]
Separately we can also add a configuration option for this, but I the above is a workaround for the time being.

**Comment by elia-secchi** [comment]
@woop thanks for the help, the workaround you suggested solved the issue I was having!

**Comment by absol4u-byte** [comment]
@woop I set the BQ dataset to "asia-northeast3" region, but it doesn't work.

**Comment by absol4u-byte** [comment]
@woop 
Is there any way to manually set the region?
