### ISSUE TITLE
Support entityless features

### ISSUE THREAD

**Issue by mavysavydav** [feast-dev/feast#1737]
**Is your feature request related to a problem? Please describe.**

We have features that don't have a corresponding entity and should just be joined based on the timestamp column. 

**Describe the solution you'd like**

There are probably more efficient solutions than the one here but this one does a good job of preserving modularity such that it turns the entityless problem into a normal entity so all the existing logic/sql can run without needing to be adjusted to handle a special case. The code to turn the entityless case into a normal entity case can be quite self contained. 

Feast supports an entity named "__entityless" which is internally defined. When an user registers a new featureview that involves entityless features, they pass an empty entity list. Empty list defaults to using the "__entityless" entity. Upon a join, feast looks at the entities involved with the features and if "__entityless" is present, the entity source data is appended with an "__entityless" column (`SELECT *, 0 as __entityless from my_entity_table`) and the feature data tables that use these entityless features are also appended with that constant column. __entityless is added to the join_key set. Everything else can proceed as normal. 

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by woop** [comment]
@mavysavydav just to be clear, each feature column will only have a single value right? (global entity)

**Comment by mavysavydav** [comment]
i think you've already seen it, but we've start developing the design via this rfc - https://docs.google.com/document/d/1mOZ-a6Voq43JcsPu2BIaZEEa3FJ6RhyFxs2CZDbby-U/edit#heading=h.9gaqqtox9jg6

**Comment by woop** [comment]
Only pending item here is still documentation, then we can close the card :)

**Comment by felixwang9817** [comment]
Closing since this has been implemented in #1804 and #1848
