### ISSUE TITLE
materialize throws error: AttributeError: 'NoneType' object has no attribute 'name' when one row has null entity value

### ISSUE THREAD

**Issue by zhiyanshao** [feast-dev/feast#1756]
## Expected Behavior 
`materialize` call succeeds even if one row has a null entity value.

## Current Behavior
throws error: AttributeError: 'NoneType' object has no attribute 'name' 

## Steps to reproduce
1. Insert a row that has null as the entity value in the offline feature store.
2. feast materialize

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/provider.py#L292
https://github.com/feast-dev/feast/blob/master/sdk/python/feast/type_map.py#L303-L308
https://github.com/feast-dev/feast/blob/master/sdk/python/feast/type_map.py#L177

## Possible Solution

1. Filter out rows that have null entity value in the materialize call.
2. The logic in `type_map.py` needs to be changed to check null first instead of checking whether feast_value_type.name is list. [https://github.com/feast-dev/feast/blob/master/sdk/python/feast/type_map.py#L177](Link)

**Comment by adchia** [comment]
Quick question: what is the usecase for having null entity values?
