### ISSUE TITLE
Datastore online request makes a call once for each entity

### ISSUE THREAD

**Issue by jallard-ueat** [feast-dev/feast#1759]
**Is your feature request related to a problem? Please describe.**
There are performance issues with Datastore when fetching features for multiple entities. An individual fetch request is made for each entity 

**Describe the solution you'd like**
I would like to have a more efficient access to the Datastore for multiple entities. The python api for datastore offers a method `get_multi()` which allows to fetch multiple keys in one request.

**Describe alternatives you've considered**
---

**Additional context**

I have done some basic tests using the `get_multi` vs get and it seems that a improvement can be made by using the function `get_multi`

Here is part of code  I used for testing:

```
import numpy as np
import timeit
from google.cloud import datastore

def multi_online_read(num_keys=5):

    client = datastore.Client(
                    project=project_name, namespace=None,
                )
    
    feast_project = "feature_repo"
    key = client.key("Project", feast_project, "Table", table, "Row",  row)
    keys = []
    response = []
    for i in range(num_keys):
        keys.append(key)

    response = client.get_multi(keys)

    return response

def online_read(num_keys=5):
    client = datastore.Client(
                    project=project_name, namespace=None,
                )
    
    feast_project = "feature_repo"
    key = client.key("Project", feast_project, "Table", table, "Row", row)
    
    response = []
    for i in range(num_keys):
        response.append(client.get(key))


    return response

if __name__ == "__main__":

    results = timeit.repeat(online_read, repeat=10, number=1)
    print(results)
    print(np.mean(results))

    results = timeit.repeat(multi_online_read, repeat=10, number=1)
    print(results)
    print(np.mean(results))
```

**Comment by woop** [comment]
We'd love to see a contribution here if you have time :)
