### ISSUE TITLE
Can users share online and offline store in different environments

### ISSUE THREAD

**Issue by liuweibin6566396837** [feast-dev/feast#1763]
I have two questions about newer feast

1. Can uses share an online or offline store  in different development and production environments ?
2. Can FeatureView be applied by feast core just like entity and feature table, so users can find FeatureView in one feast core service ?

**Comment by liuweibin6566396837** [comment]
I just came from feast-spark, so I'm a little confused about these two kinds of stores. Uses can registry their FeatureView in different environments (like production1, production2 env ... ) by the same FileSource or BigQuerySource ect ?

**Comment by tedhtchang** [comment]
May be you are mixing the Feast v0.9 and v.0.10+ terms. Which Feast release are you using ?
The feast-spark, feast core, and feature table are in v0.9 and older releases.
The FeatureView is in v0.10 newer.

**Comment by liuweibin6566396837** [comment]
> May be you are mixing the Feast v0.9 and v.0.10+ terms. Which Feast release are you using ?
> The feast-spark, feast core, and feature table are in v0.9 and older releases.
> The FeatureView is in v0.10 newer.

Thanks for your reminding. I use both v0.9 and v01.10+. The reason why I put forward this question is I wonder share FeatureView in different environment.

**Comment by tedhtchang** [comment]
@liuweibin6566396837 Have you seen this [link](https://docs.feast.dev/v/master/how-to-guides/running-feast-in-production). I think this may answer your question.
