### ISSUE TITLE
Latency in getting online features

### ISSUE THREAD

**Issue by swapkh91** [feast-dev/feast#1764]
I've followed the tutorial and setup my online store in Firestore and I'm able to fetch features using `get_online_features`

What I notice is that there is too much latency in getting the results, ranging from 800ms to 2s and I'm not able to figure out what went wrong.

The dataset has 4 columns - `price{float}`, `mms{string}`, `datetime`, `created`
`mms` is the entity and `price` is the feature to fetch

The Firestore database and my GKE cluster from where I fetch features, both are in `asia-south1` location so I guess that is fine.

This is the code I use to fetch, takes 800ms to 2s at times:
```
feature_vector = self.store.get_online_features(
        feature_refs=feature_ref,
        entity_rows=entity_row).to_dict()
``` 

Code for setting up store object, this runs only once during initialiazation and takes around 300ms
```
self.store = FeatureStore(config=RepoConfig(
            project=feast_proj_name,
            provider="gcp",
            registry="<gs path>/registry.db",
            ))
```

Would appriciate some help on this

**Comment by woop** [comment]
Hey @swapkh91, thanks for creating this issue. 

How are you measuring the latency? Are you running a load test with many requests? Are you measuring only the online retrieval for Feast or other code as well?

**Comment by swapkh91** [comment]
@woop it's for single request only
I noticed that the 1st request took 2s and subsequent ones took around 800ms, sent separately through Postman
These times are for the Feast online fetch only
I put `datetime.now()` before the `get_online_features` and after to get latency and logged the diff in GKE

**Comment by woop** [comment]
Individual requests are not representative. So ideally you would run a few hundred requests and ignore the first 10-20. Can you use a load testing service?

**Comment by swapkh91** [comment]
@woop I ran 150 req using Apache JMeter, still the response times are close to 800ms

![Screenshot from 2021-08-08 14-43-44](https://user-images.githubusercontent.com/5755405/128627123-ac6ff406-bbec-4892-8b0f-39088c518b32.png)

This ss is of the last requests out of 150
