### ISSUE TITLE
Only the Redis online store uses the requested_features param, and other online stores return all feature values from feature view

### ISSUE THREAD

**Issue by mavysavydav** [feast-dev/feast#1781]
## Expected Behavior 
Only requested features of feature view are returned.

## Current Behavior
All features of feature view are returned by all online stores except the Redis one.

## Steps to reproduce
N/A Example of one online store that has this mistake - https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/datastore.py#L222

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
Should just fetch requested features or filter for the requested features.

**Comment by woop** [comment]
Good catch, we need to add a test for this
cc @achals
