### ISSUE TITLE
Support TiKV as online store

### ISSUE THREAD

**Issue by zz-jason** [feast-dev/feast#1782]
**Is your feature request related to a problem? Please describe.**

To support a large number of features in the online store.

**Describe the solution you'd like**

TiKV (GitHub: https://github.com/tikv/tikv, Website: https://tikv.org/) is an open-source, distributed, and transactional key-value database. It provides both raw and ACID-compliant transactional key-value API. Would you like to consider integrating TiKV as alternative storage for the online store:

- It's highly scalable and easy to operate.
- It supports online bulk loading with little impact on the online service for a large amount of data.
- It's cloud-native, users can easily deploy a TiKV cluster in k8s.

**Describe alternatives you've considered**

No

**Additional context**

No

**Comment by woop** [comment]
Hey @zz-jason, this is a great idea. Would you like to take a stab at adding this online store? It should be pretty easy for you to build it as an external package.

**Comment by zz-jason** [comment]
sure!
