### ISSUE TITLE
Pattern based file sources

### ISSUE THREAD

**Issue by vishal-ramesh2** [feast-dev/feast#1805]
**Is your feature request related to a problem? Please describe.**
Sometimes when I have my data split into multiple files, it would make things easier if I could load them all using a filename patter

**Describe the solution you'd like**
Using a regex to define files to load

**Comment by woop** [comment]
@vishal-ramesh2 a few questions
* Are you using FileSource?
* Are you using local or remote files?

**Comment by vishal-ramesh2** [comment]
@woop My expectation was that it would work for both remote and local files. More info can be found on this slack thread
https://tectonfeast.slack.com/archives/C01MSKCMB37/p1624951008173500
