### ISSUE TITLE
feast apply does not remove deleted feature views from Redis

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#1806]
## Expected Behavior 
The Redis online store removes materialized feature views if they are no longer present in the repo

## Current Behavior
Nothing happens on feast apply. This is particularly bad because Redis is in-memory, so deleted feature views that aren't accessed incur a continued hit on resources (as opposed to other stores where this is written to disk)

**Comment by loftiskg** [comment]
@adchia Is this currently being worked on?  I think this would be pretty easy to add now that https://github.com/feast-dev/feast/pull/1965 has been merged.  Happy to give it a shot if not.
