### ISSUE TITLE
Leaving "online_store" key out of "aws" provider in feature_store.yaml produces error

### ISSUE THREAD

**Issue by akuma12** [feast-dev/feast#1809]
**Is your feature request related to a problem? Please describe.**
In `feature_store.yaml`, if your `provider` is set to `aws`, and you leave out the `online_store` key, it will produce the errors:

```
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RepoConfig
__root__ -> online_store -> region
  field required (type=value_error.missing)

feast.repo_config.FeastConfigError: 1 validation error for RepoConfig
__root__ -> online_store -> region
  field required (type=value_error.missing)
at /Users/jimrohrer/Projects/feast-demo/demo/feature_store.yaml
```

**Describe the solution you'd like**
Ideally `online_store` would be an optional key. In our case we don't need an online store currently.

**Describe alternatives you've considered**
For now I've just set the `online_store` to `sqlite`, which let me continue on.

**Comment by fcas** [comment]
I have the same scenario.

**Comment by adchia** [comment]
Thanks for filing this! This should be relatively easy to pick up for someone in the community. The parsing happens roughly in that error and I think it should be as simple as changing the type of the online_store in RepoConfig

**Comment by mirayyuce** [comment]
Looking into this
