### ISSUE TITLE
Bigquery job id is not found in locations outside of US

### ISSUE THREAD

**Issue by LarsKlingen** [feast-dev/feast#1842]
## Expected Behavior 
When querying for offline features with bigquery source, the job id is used to get the status of the bigquery job.
 
## Current Behavior
For a location outside of US (southamerica) the job id to get the status is not found.

## Possible Solution
Pass `bigquery.job.query.QueryJob` object to `client.get_job(job_id).state` instead of job_id as a string. `get_job` will then get the correct location automatically.

**Comment by woop** [comment]
Thanks for raising this @LarsKlingen. Would you be open to submitting a pull request?
