### ISSUE TITLE
Are the integration tests actually running?

### ISSUE THREAD

**Issue by judahrand** [feast-dev/feast#1879]
## Expected Behavior 
The integration tests should run.

## Current Behavior
It looks to me like only the benchmarks are actually running.

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by achals** [comment]
Hi @judahrand , can you point me a workflow where the tests weren't running? We've been making changes here very recently so it's possible something went wrong.

**Comment by judahrand** [comment]
It was my confusion I think. I saw the benchmark step has `--integration` but the integration tests aren't running there - they're running the in the `Test Python` step.
