### ISSUE TITLE
Add PEP-561 compliant stub package

### ISSUE THREAD

**Issue by DvirDukhan** [feast-dev/feast#1884]
**Is your feature request related to a problem? Please describe.**
Adding Feast as a third-party dependency, and proofing code with MyPy yields `error: Skipping analyzing "feast": found module but no type hints or library stubs`

**Describe the solution you'd like**
Call `mypy --install-types` or `pip install feast-types` (or similar) will remove this error message

**Describe alternatives you've considered**
None

**Additional context**
Thanks!

**Comment by achals** [comment]
I think this has been fixed as of #2405
