### ISSUE TITLE
I would like to add Astra as online feature store 

### ISSUE THREAD

**Issue by hamzakpt** [feast-dev/feast#1891]
**Astra**
Astra is an online storage of Cassandra database, If we will add Astra as our online storage plugin, we can capture a lot of audience for features store in who want to use Cassandra
I have a repo for plugin: kindly review my code and also I created pull request here

[github_repo](https://github.com/hamzakpt/feast_astra)
[pull_req](https://github.com/feast-dev/feast/pull/1875)

**Comment by felixwang9817** [comment]
Hi @hamzakpt, thanks for this! I'll try to take a look at your repo soon. On our end, we are currently thinking about how best to allow plugin repos to use our test suite. I'll keep you updated on that.

By the way, are you on our [Slack](https://slack.feast.dev/)? If you are, we can move some communication there, for faster response times.

**Comment by hamzakpt** [comment]
> Hi @hamzakpt, thanks for this! I'll try to take a look at your repo soon. On our end, we are currently thinking about how best to allow plugin repos to use our test suite. I'll keep you updated on that.
> 
> By the way, are you on our [Slack](https://slack.feast.dev/)? If you are, we can move some communication there, for faster response times.

Yes I am already on slack channel

**Comment by adchia** [comment]
This is now partially addressed now with https://github.com/datastaxdevs/feast-cassandra-online-store!
