### ISSUE TITLE
Offline Redshift pulls duplicated columns

### ISSUE THREAD

**Issue by gopalladha** [feast-dev/feast#1917]
## Expected Behavior 
Offline Redshift pulls should get non-duplicated columns

## Current Behavior
Calling https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/feature_store.py#L464 created the redshift query using https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/feature_store.py#L464. This redshift query is being generated as to `select *` at https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/infra/offline_stores/redshift.py#L520, which is causing duplicated columns (except entity columns, entity_timestamp & zipcode_features__entity_row_unique_id) being selected in the query.
Note: zipcode_features__entity_row_unique_id is taken as reference from https://github.com/feast-dev/real-time-credit-scoring-on-aws-tutorial

## Steps to reproduce
Any offline redshift pull using https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/feature_store.py#L464 & on it `.to_df()` should be able to reproduce this issue in the produced pandas dataframe.

### Specifications

- Version: 0.13.0
- Platform: macOS Big Sur 11.5.2
- Subsystem:

## Possible Solution
Update https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/infra/offline_stores/redshift.py#L520 to `SELECT entity_dataframe.*` should solve it.

**Comment by adchia** [comment]
Quick note that this should have been resolved since the use of `final_output_feature_names`
