### ISSUE TITLE
Adopt PEP517

### ISSUE THREAD

**Issue by achals** [feast-dev/feast#1945]
PEP 517 is supposed to be the future of python packaging. More reading available at http://ivory.idyll.org/blog/2021-transition-to-pyproject.toml-example.html, https://snarky.ca/what-the-heck-is-pyproject-toml/ and https://discuss.python.org/t/where-to-get-started-with-pyproject-toml/4906.

## Possible Solution
Include a minimal `pyproject.toml` file

**Comment by woop** [comment]
Does this solve a specific problem for us?

**Comment by achals** [comment]
I think this will help with some of the issues we're seeing in #2627 (specifically with the issue of source builds not working as expected since some required data files aren't being included in the tar.gz.)

**Comment by achals** [comment]
I believe this is done
