### ISSUE TITLE
Distribute Feast with Dask

### ISSUE THREAD

**Issue by qooba** [feast-dev/feast#1953]
**Is your feature request related to a problem? Please describe.**
I would like to add possibility to distribute Feast feature store with Dask library

**Describe the solution you'd like**
I will extend Feast with the Dask library. Thanks to this the users will be able to distribute historical feature handling on the clusters (eg. VMs, k8s, yarn, local machine). This will help to handle huge datasets. 

**Describe alternatives you've considered**
Dask is the best solution because we stay in the python stack others like Spark will need additional setup and maintenance. 

**Additional context**
No

**Comment by judahrand** [comment]
Is there a good reason to reject Modin?

**Comment by qooba** [comment]
> Is there a good reason to reject Modin?

@judahrand  ```Modin``` is great if you want to boost the pandas code with minimal effort. If you want to have full control (partitioning, persistence in memory etc.) and better performance you need to go deeper and use directly eg. Dask or Ray (current Modin backends).
