### ISSUE TITLE
Materializing a large number of keys to Redis is very slow

### ISSUE THREAD

**Issue by loftiskg** [feast-dev/feast#1969]
## Current Behavior
Materializing a large number of keys in Redis is very slow.  When trying to materialize >1,000,000 entities was taking roughly 20 minutes to complete on my machine.  This was just running a locally run Redis server, so I imagine this would be even slower using a remote Redis server.

## Possible Solution
Looking at how writes are handled, it looks like writers are not taking advantage of pipelining.  Pipelining all `HSET` commands could potentially speed up the writes here.

**Comment by felixwang9817** [comment]
Resolved by #1961 @loftiskg
