### ISSUE TITLE
Feast init: ImportError: cannot import name '_message' from 'google.protobuf.pyext'

### ISSUE THREAD

**Issue by duy-effectiv** [feast-dev/feast#1987]
After running the command `feast init feature-repo-name`, I received an error
```
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/opt/homebrew/Caskroom/miniforge/base/envs/intel_py39/lib/python3.9/site-packages/google/protobuf/pyext/__init__.py)
```
Here is what I have tried but none was working as I received the exact same error
1. Reinstall `protobuf` to the latest version using 
```
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
pip3 install --upgrade --force-reinstall protobuf
```
2. Switch to a Mac with an Intel chip and run everything all over again

### Specifications

- Version: **feast 0.14.1**
- **Platform:**
  - macOS Big Sur (version 11.6) (Apple M1 chip)
  - python 3.9.7
- **Dependencies:**
  - protobuf 3.19.1 
  - google-api-core 2.2.1
  - googleapis-common-protos 1.52.0
  - google-auth 2.3.2

**Comment by tsotnet** [comment]
Hi @duy-effectiv, this looks like a protobuf-specific issue. A quick error message search shows a potential solution here: https://github.com/tensorflow/tensorboard/issues/1566#issuecomment-435423631. Can you try this?

**Comment by duy-effectiv** [comment]
> Hi @duy-effectiv, this looks like a protobuf-specific issue. A quick error message search shows a potential solution here: [tensorflow/tensorboard#1566 (comment)](https://github.com/tensorflow/tensorboard/issues/1566#issuecomment-435423631). Can you try this?

Thanks very much for your quick response. Yes, I tried that solution and it did not work for me. I received the same error. 

I understand that this is a protobuf issue. But do you know a specific version of protobuf that would work with feast?

**Comment by duy-effectiv** [comment]
> Hey @duy-effectiv, I've got Python 3.7.11, protobuf==3.17.3, and proto-plus==1.19.0. Could you try with those versions? Also, I'm on Big Sur 11.4 with an Intel chip.

Thanks. I tried it and ran into an issue with installing `grpcio` since it is a dependency to install `feast`. I went through some StackOverflow suggestions and tried a few solutions but none worked. There is one solution that I have not tried since it requires Python 3.9. I could successfully install `feast` on Python 3.9. 

I guess it is a problem with the Apple M1 chip laptop. When I said I tried the intel chip, I was more referring to an Intel chip virtual environment running on the same laptop. It worked on many cases where the libraries can not be installed on the base environment of the M1 chip laptop.

**Comment by felixwang9817** [comment]
Thanks for raising this issue @duy-effectiv and for the thorough investigation!

**Comment by TeoZosa** [comment]
I also ran into the same issue but was able to get it working. My solution (originally posted in https://github.com/protocolbuffers/protobuf/issues/8820#issuecomment-961552604):

> I had the same problem and discovered it was because required shared libraries are missing from the `-py2.py3-none-any.whl` pure python wheel that gets pulled in automatically.
> 
> I was able to solve it by building the protobuf wheel from source:
> 
> ```shell
> brew install protobuf
> export CFLAGS="-I$(brew --prefix protobuf)/include"
> export LDFLAGS="-L$(brew --prefix protobuf)/lib"
> # In my virtual environment: 
> pip install protobuf=="$(brew list --version protobuf | awk '{print $2}')" --force-reinstall --no-deps --install-option="--cpp_implementation"
> ```
> 
> Hope this helps!

**Comment by duy-effectiv** [comment]
> I also ran into the same issue but was able to get it working. My solution (originally posted in [protocolbuffers/protobuf#8820 (comment)](https://github.com/protocolbuffers/protobuf/issues/8820#issuecomment-961552604)):
> 
> > I had the same problem and discovered it was because required shared libraries are missing from the `-py2.py3-none-any.whl` pure python wheel that gets pulled in automatically.
> > I was able to solve it by building the protobuf wheel from source:
> > ```shell
> > brew install protobuf
> > export CFLAGS="-I$(brew --prefix protobuf)/include"
> > export LDFLAGS="-L$(brew --prefix protobuf)/lib"
> > # In my virtual environment: 
> > pip install protobuf=="$(brew list --version protobuf | awk '{print $2}')" --force-reinstall --no-deps --install-option="--cpp_implementation"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps!

Thank you so much @TeoZosa . It works for me now. Finally!!
