### ISSUE TITLE
Need to get objects from FeatureStore without prior knowledge of their IDs and timestamps...

### ISSUE THREAD

**Issue by Felix-neko** [feast-dev/feast#1989]
Hi folks! And thank you for such a great piece of work like `feast`.

Currently I want to use it to store and extract some features for time series analysis tasks. And i'm confused that to get my historical features for ML model training I need to know each object's ID and timestamp. To cope with it I have either to store IDs and timestamps separately, or to select data from raw database with external tools like SqlAlchemy.

I think need the following functionality:
- timestamp of latest object in FeatureStore
- timestamp of earliest object if FeatureStore
- number of rows having timestamps between two given datetimes (maybe by each FeatureView)
- extraction all IDs with timestamps between two given datetimes.

Hope on your answer,
your Felix Neko.

**Comment by achals** [comment]
Hey @Felix-neko , thanks for your interest in feast! Just to make sure - when you say ID of objects, are you referring to entity ids? I.e. the values that you need to provide as `entity_df` in https://rtd.feast.dev/en/latest/#feast.feature_store.FeatureStore.get_historical_features?

If so, does #1611 sufficiently cover the problem you'd like to see addressed?

**Comment by Felix-neko** [comment]
> Hey @Felix-neko , thanks for your interest in feast! Just to make sure - when you say ID of objects, are you referring to entity ids? I.e. the values that you need to provide as `entity_df` in https://rtd.feast.dev/en/latest/#feast.feature_store.FeatureStore.get_historical_features?
> 
> If so, does #1611 sufficiently cover the problem you'd like to see addressed?

Yes, I'm about the entity IDs. And yes, #1611 looks like what I want ^_^

Also, it may be useful to get the number of rows between timestamps too. It may be useful to first inspect the data before transmit large dataframes by slow internet connection.

**Comment by judahrand** [comment]
Perhaps an option to sample the data? Ie. Return 10% of the the entities.

**Comment by Felix-neko** [comment]
> Perhaps an option to sample the data would be useful? Ie. Return 10% of the the entities.

Something about dataframe.head(max_n_rows=10)? Looks useful...

**Comment by adchia** [comment]
Closing to funnel to https://github.com/feast-dev/feast/issues/1611
