### ISSUE TITLE
Feast CLI error - "No module named 'proto'"

### ISSUE THREAD

**Issue by f00stx** [feast-dev/feast#2009]
## Expected Behavior 
Create a feature repo as expected.

## Current Behavior
Feast dies with an error when running the following:

~ ❯ feast init feature_repo                                                                                    
Traceback (most recent call last):
  File "/home/richard/anaconda3/envs/feast/bin/feast", line 5, in <module>
    from feast.cli import cli
  File "/home/richard/anaconda3/envs/feast/lib/python3.7/site-packages/feast/__init__.py", line 12, in <module>
    from .feature_service import FeatureService
  File "/home/richard/anaconda3/envs/feast/lib/python3.7/site-packages/feast/feature_service.py", line 6, in <module>
    from feast.base_feature_view import BaseFeatureView
  File "/home/richard/anaconda3/envs/feast/lib/python3.7/site-packages/feast/base_feature_view.py", line 19, in <module>
    from proto import Message
ModuleNotFoundError: No module named 'proto'

## Environment
Python 3.7.11
Created a brand new conda environment and then ran `pip install feast`, which installed the following:
```
Successfully installed Click-7.1.2 PyYAML-6.0 anyio-3.3.4 asgiref-3.4.1 attrs-21.2.0 cachetools-4.2.4 charset-normalizer-2.0.7 colorama-0.4.4 dill-0.3.4 fastapi-0.70.0 fastavro-1.4.7 feast-0.15.0 google-api-core-2.2.2 google-auth-2.3.3 googleapis-common-protos-1.52.0 grpcio-1.42.0rc1 grpcio-reflection-1.42.0rc1 h11-0.12.0 httptools-0.2.0 idna-3.3 importlib-metadata-4.8.2 importlib-resources-5.4.0 jsonschema-4.2.1 mmh3-3.0.0 numpy-1.21.4 pandas-1.3.4 pandavro-1.5.2 protobuf-3.19.1 pyarrow-6.0.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pydantic-1.8.2 pyrsistent-0.18.0 python-dateutil-2.8.2 python-dotenv-0.19.1 pytz-2021.3 requests-2.26.0 rsa-4.7.2 six-1.16.0 sniffio-1.2.0 starlette-0.16.0 tabulate-0.8.9 tenacity-8.0.1 toml-0.10.2 tqdm-4.62.3 typing-extensions-3.10.0.2 urllib3-1.26.7 uvicorn-0.15.0 uvloop-0.16.0 watchgod-0.7 websockets-10.0 zipp-3.6.0
```

No other packages installed beforehand.

**Comment by f00stx** [comment]
Seems to be fixed after running `pip install proto-plus jinja2`. These were not installed during the initial installation via pip.

**Comment by felixwang9817** [comment]
The main issue here is we have `proto-plus` as a requirement under `CI`, so if a user just does `pip install feast` instead of `pip install feast[ci]`, they'll run into this issue. I'll just move `proto-plus` to be a general requirement.

**Comment by baineng** [comment]
yeah, now pypi feast 0.15.0 having this issue, better to release a version soon

**Comment by AMRITKV88** [comment]
> Seems to be fixed after running `pip install proto-plus jinja2`. These were not installed during the initial installation via pip.

This one worked for me.
