### ISSUE TITLE
Feast Java ODFV logic is inefficient

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2010]
## Expected Behavior

Feast Java sends a request to the Python FTS for each ODFV.

## Current Behavior

Feast Java sends a request to the Python FTS for each ODFV reference, which is extremely inefficient.

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by achals** [comment]
Is this still an issue @felixwang9817?

**Comment by felixwang9817** [comment]
Yes, this is still an issue.
