### ISSUE TITLE
Error in requirement definition 

### ISSUE THREAD

**Issue by hfrechen** [feast-dev/feast#2030]
After installing feast in a conda environment, exporting the environment to a .yml fails. This is probably related to a missing comma at the end of this line:
https://github.com/feast-dev/feast/blob/63680bad344f55e41a281d643bef5972f2ea28da/sdk/python/setup.py#L50

**Comment by achals** [comment]
Thanks for the issue @hfrechen  - we should have a fix out soon .

**Comment by achals** [comment]
Seems like this bug is present in [0.15](https://github.com/feast-dev/feast/blob/v0.15-branch/sdk/python/setup.py) - we probably want to have a bugfix release.

Not sure why `pip` doesn't get tripped up by this but conda does..
