### ISSUE TITLE
[Question] Does Feast still support pulling TFDV-like statistics

### ISSUE THREAD

**Issue by casassg** [feast-dev/feast#2032]
So I came across an example on feast 0.9 that computed TFDV statistics, but I can't seem to find references to generated statistics any more.

Is there a way to pull statistics from the stored data with Feast still or has it been deprecated?

Context: we are building a TFX component to generate datasets from Feast. So we are wondering if we can generate stats as part of that component specifically as Feast may have some cached data already and would speed this up more than running StatisticsGen

**Comment by woop** [comment]
Hey @casassg, it does not support it any more unfortunately. We are looking into integrating with a profiling/validation system. @pyalex and @adchia have been looking into that.

Can you describe the flow that you user workflow that you had in mind?

**Comment by casassg** [comment]
The user flow is to generate statistics at the same time we generate the dataset to later run against the ExampleValidator component on TFX to detect if the dataset has validation issues

Right it would look like:
                                                                   Schema
                                                                       ⬇️ 
ExampleGen ---> StatisticsGen ---> ExampleValidator

It would be interesting to avoid having to run an extra Beam job to extract statistics if instead we can just re-use stats generated by Feast here.

The workflow would do that on a production retraining of model, we would generate stats and dataset at the same time and validate it using TFDV.
