### ISSUE TITLE
Inconsistent column names with universal suite

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#2033]
## Expected Behavior 
Universal tests should upload the right dataframe before performing the tests

## Current Behavior
My dataset in Trino contains a column named `ts_1`
<img width="627" alt="image" src="https://user-images.githubusercontent.com/18557047/141594163-55dfb1e6-0cf8-4229-9d0b-d5d66c0762f6.png">

while the universal test `feast/sdk/python/tests/integration/e2e/test_universal_e2e.py::test_e2e_consistency` is also asking for a column named `ts`
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/18557047/141594873-86e73bb0-9bb3-4bc0-aa45-22f82ff09403.png">

This is what `pull_latest_from_table_or_query()` receives
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/18557047/141594732-41ec69d0-93a6-4277-a50f-db486ea804cb.png">

## Steps to reproduce
- Code is on this branch https://github.com/Shopify/feast-trino/pull/22/files
- make install-feast-submodule
- make start-local-cluster
- make test-python-universal
- make kill-local-cluster

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by MattDelac** [comment]
I also encounter the exact same error with some of the tests part of `feast/sdk/python/tests/integration/registration/test_universal_types.py`
<img width="1762" alt="Screen Shot 2021-11-16 at 10 38 08 AM" src="https://user-images.githubusercontent.com/18557047/142045524-d6c5c0f7-0775-4618-a83c-e539f3fc0db5.png">

**Comment by felixwang9817** [comment]
Resolved offline cc @MattDelac
