### ISSUE TITLE
Feature view created with BigQuerySource when materialize throws AssertionError

### ISSUE THREAD

**Issue by ylokhande82** [feast-dev/feast#2036]
## Expected Behavior 
Expected to consume data and create the feature view

## Current Behavior
Currently when called Feast apply all works well, however when tried to materialize throws AssertionError.

## Steps to reproduce
Below is my feature configuration/ details.
![Screen Shot 2021-11-15 at 1 39 28 PM](https://user-images.githubusercontent.com/6573143/141758412-19f1dc66-cb58-43da-8a47-772a9df03a13.png)

When applied with "feast apply" all works well.
![Screen Shot 2021-11-15 at 1 40 18 PM](https://user-images.githubusercontent.com/6573143/141758530-2f237856-e7d0-4a59-b7a9-18260906f238.png)
Google bigquery can be reached, as seen in above screen shot.

However when called 
feast materialize-incremental '2021-11-15 23:59:59'
Throws AssertionError, screen shot below.
![Screen Shot 2021-11-15 at 1 43 05 PM](https://user-images.githubusercontent.com/6573143/141758929-4205113a-d9a6-46a4-a74a-687322d57b35.png)

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by adchia** [comment]
this looks like feast materialize is trying to pull from your local file. does your `feature_store.yaml` have the provider set to local instead of gcp or the offline store set to file?

**Comment by ylokhande82** [comment]
Yes we have offline store set to file, 

What we are trying to do, consume data sources from 
1. Google - BigQuery 
2. Local parquet file

Is it possible to get data from both sources, when materialized?

Or are we doing something which is not possible?

Here is my `feature_store.yaml
![Screen Shot 2021-11-15 at 6 06 09 PM](https://user-images.githubusercontent.com/6573143/141795402-40925336-6d84-4fda-bcde-569bd50bd324.png)
`

**Comment by adchia** [comment]
Ah yeah this is currently not possible. You can look at https://github.com/feast-dev/feast/blob/2435777d87c19d4eee670a7ccf5e73e88e22ce9d/sdk/python/feast/infra/passthrough_provider.py#L36-L36 which shows in our default provider that only one kind of offline store is provided.

You could make a custom provider though that allows for both. I'd also recommend you make an issue as a feature request. I think it can make a lot of sense especially when debugging. You might be able to query GCS files too via BigQuery as an alternative for using your local parquet file.

**Comment by adchia** [comment]
Closing this to have conversations tracked in other issue

**Comment by unknownusergcp** [comment]
Hi,
 I am trying to configure Feast with PostgreSQLSource. 
 Feast apply is registering the feature views and deploying infrastructure but when I run feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S") it's throwing AssertionError.

What may be the possible solution for this Error.

Thank you
