### ISSUE TITLE
Ensure registry file name indicates that it's a protobuf binary

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#2039]
We currently use `registry.db` as the name for our object store based registry. This leads to people trying to open the file using Sqlite, but the file format is actually a protobuf binary. We should rename this file to `registry.pb` to remove confusion about what file format is being used.

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/repo_config.py#L88

**Comment by nossrannug** [comment]
Changing the default value to `.pb` would be simple. But will we need to check for a `.db` if the `.pb` isn't found, or do we expect people to handle that themselves when they upgrade to a newer version?

**Comment by woop** [comment]
Presumably your registry path is already defined in your `feature_store.yaml` even if you upgrade. So what we are changing here is only the default name that we add to the yaml file. Right now it's not required to define the registry though. One option for folks who did not set their registry explicitly (and rely on the default option) would be to warn users to define the registry explicitly (in 0.16) and make it required to define the file location in (0.17).

**Comment by nossrannug** [comment]
Something like this?
```
Warning: Feast 0.17 and onwards will require 'registry' to be set in the feature_store.yaml file.
```
