### ISSUE TITLE
Flaky test `feast/sdk/python/tests/integration/online_store/test_universal_online.py`

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#2041]
## Expected Behavior 
None flaky test

## Current Behavior
`feast/sdk/python/tests/integration/online_store/test_universal_online.py` can be flaky sometimes where the delta is higher than `0.0001`
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/18557047/141852347-1e10a035-7468-415c-a522-34f3953f533a.png">

### Specifications

- Version: Feast on commit d35fe44807d4362523bed3b561e591043c81c5e4
- Platform: feast-trino
- Subsystem:

**Comment by achals** [comment]
@MattDelac have you observed this with a specific online store? Or does it happen across stores?

**Comment by MattDelac** [comment]
> @MattDelac have you observed this with a specific online store? Or does it happen across stores?

Only when using the universal tests with the feast-trino plugin.

So I think that the online store is always the local one

**Comment by achals** [comment]
Actually looking at the error it seems like there may be a bug, specifically in the on demand feature view code path. That may have specific to the trino plug in, and will probably need a deeper look.

**Comment by MattDelac** [comment]
> Actually looking at the error it seems like there may be a bug, specifically in the on demand feature view code path. That may have specific to the trino plug in, and will probably need a deeper look.

Ok ok, I will have a closer look today then.

**Comment by MattDelac** [comment]
What are the main fucntions used by this test beside `pull_latest_from_table_or_query()` ?

**Comment by MattDelac** [comment]
Ok ok I found the source of the problem
