### ISSUE TITLE
Make direct data ingestion into online store faster

### ISSUE THREAD

**Issue by benny-hal** [feast-dev/feast#2051]
We use the direct data ingestion capability so we can write inference data in a real-time flow and then use it immediately. We need to be able it ingest in milliseconds. Currently, the online ingestion takes a couple of seconds since it does a lookup to refresh the registry for every call to `write_to_online_store`. This blocks the new capability from being used in real-time. 

It would be great to have an `allow_cache` argument added to `write_to_online_store` so that we can do the write without needing to refresh the registry. 

Currently, I moved the registry to Postgres so the refresh is quicker, but it is still not quick enough

**Comment by achals** [comment]
@benny-hal thanks for the issue - this makes a lot of sense.
