### ISSUE TITLE
Universal feature repo has hidden assumptions

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2055]
The universal feature repo has various hidden assumptions that make it challenging to change. For example, `construct_universal_data_sources` constructs data sources using a `DataSourceCreator`, but that `DataSourceCreator` must set `field_mapping = {"ts_1": "ts"}`; if it doesn't, the tests will break. This assumption is not documented at all, and was the root cause of #2033.

As another example, the tests in `test_universal_e2e.py` have the expected result dataframes hardcoded, so the tests will break if we ever change data sources.

**Comment by achals** [comment]
Can we remove any field mappings? Would that be a backwards incompatible change for plugin creators?

**Comment by felixwang9817** [comment]
Yeah that works - it's backward compatible. However, it still leaves the second issue, and means that we're no longer testing `field_mapping`.
