### ISSUE TITLE
On-demand feature view couldn't be renamed

### ISSUE THREAD

**Issue by pyalex** [feast-dev/feast#2064]
## Expected Behavior 
After renaming function that is wrapped into `@on_demand_feature_view` decorator and running `feast apply` changes are being applied.

## Current Behavior
On `feast apply` exception is thrown
```
feast.errors.FeatureViewNotFoundException: Feature view <previous view name> does not exist in project <project name>
```

Traceback
```
  File "/Users/pyalex/projects/feast/sdk/python/feast/repo_operations.py", line 193, in apply_total
    store.apply(
  File "/Users/pyalex/projects/feast/sdk/python/feast/feature_store.py", line 542, in apply
    self._registry.delete_feature_view(
  File "/Users/pyalex/projects/feast/sdk/python/feast/registry.py", line 630, in delete_feature_view
    raise FeatureViewNotFoundException(name, project)
```
## Steps to reproduce
1. create odfv
2. `feast apply`
3. rename odfv
4. `feast apply`
5. 
### Specifications

- Version: master
- Platform:
- Subsystem:

**Comment by pyalex** [comment]
UPD. Couldn't be just deleted either

**Comment by felixwang9817** [comment]
Interesting, I believe #2054 should have fixed this. Were you up to date with #2054 when you saw this issue?
