### ISSUE TITLE
Use memory efficiently in feature materialization

### ISSUE THREAD

**Issue by judahrand** [feast-dev/feast#2071]
**Is your feature request related to a problem? Please describe.**
Currently, the materialization process loads all the data from the Offline Store to an Arrow table, then converts all the data to Protobuf, then writes all the data to the Online Store. This process requires holding the entire dataset in memory which is not practical.

**Describe the solution you'd like**
Instead of returning an Arrow table yield a series of RecordBatches from the OfflineStore and process each batch individually. 

**Describe alternatives you've considered**

**Additional context**

**Comment by adchia** [comment]
Consolidating in the linked issue
