### ISSUE TITLE
On Demand Feature View UDF doesn't get updated with `apply`

### ISSUE THREAD

**Issue by judahrand** [feast-dev/feast#2074]
## Expected Behavior 
When `feast apply` is run the UDF should be updated.

## Current Behavior
I haven't managed to reproduce this which makes this issue a bit tricky but I ran into an issue where in order to update an ODFV I had to teardown the Registry and recreate it.

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by ArrichM** [comment]
I had the same issue, might be closed by #2054
