### ISSUE TITLE
Supporting remote and local data source provider (e.g.: Local parquet and BigQuery)

### ISSUE THREAD

**Issue by ylokhande82** [feast-dev/feast#2079]
**Is your feature request related to a problem? Please describe.**
We are trying to consume two different sources 1 remote e.g.: BigQuery and another one local Parquet file, which is currently not possible?

IMO, there are possible scenarios where multiple data sources needs to be connected to extract the meaningful feature and save it in Feature store. Currently not be able to do that unless we create a custom connector or bring the data to the common data source.

**Describe the solution you'd like**
Supporting multiple data sources (e.g.: BigQuery, Parquest file), making sure it has common attributes to query and connect on will help easy debugging and avoid custom connectg creation.

Here are additional details as a defect: [https://github.com/feast-dev/feast/issues/2036](https://github.com/feast-dev/feast/issues/2036)

**Comment by woop** [comment]
I think this issue requires a bit more discussion. Adding support for any two data sources is certainly an incredible amount of work, but it may be possible to support a single offline store with local file sources. We already need to maintain support for uploading entity dataframes into offline stores, so adding support for also uploading local files should not be a very tall order. So the limitations that I have in mind would be

1. All joins happen in a single offline store (not as part of some external tool like Spark or Dask or locally).
2. The only external sources that are supported are FileSources (you can't join from Redshift to BigQuery).
