### ISSUE TITLE
NUMERIC col_datatype not supported for BigQuery offline store

### ISSUE THREAD

**Issue by benny-hal** [feast-dev/feast#2080]
## Expected Behavior 
NUMERIC columns should be mapped to feast data types correctly

## Current Behavior and Steps to reproduce
Make a big query table with a column that has a BigQuery type of NUMERIC
Use the table as an offline store when applying the store a key error exception is thrown `KeyError: 'NUMERIC'`

### Specifications

- Version: feast 0.15.1
- Platform: GCP

## Possible Solution
Add NUMERIC to `bq_to_feast_value_type` mapping
This seems like the problematic method 
https://github.com/feast-dev/feast/blob/b5d8a531c81fa11297e5c684f898646cb2ee2cd1/sdk/python/feast/type_map.py#L400

**Comment by benny-hal** [comment]
any work around would be much appreciated
thx!

**Comment by judahrand** [comment]
It's my understanding that Feast doesn't currently have a data type which is capable of representing a NUMERIC column correctly. This is another thing which might be able to be addressed by the discussion in #2013
