### ISSUE TITLE
Problems with GCP usage

### ISSUE THREAD

**Issue by jruokola** [feast-dev/feast#2082]
I'm running the https://github.com/feast-dev/feast-fraud-tutorial/blob/main/notebooks/Fraud_Detection_Tutorial.ipynb example on a notebook instance. There is something strange going on with the BQ dataset creation.

So feast creates a feast-oss.fraud_tutorial.transactions table which is not visible in the BQ Editor UI (is this a parquet file in cloud storage or what's going on?). I'm able to query this table with my private GCP account which is BQ admin BUT I'm not able to query that table with a service-account (python bq client is using this account) which is also has BQ admin IAM rights. Dataset viewer and BQ User rights should be more than enough to query tables but it doesn't seem to work with feast.

"Edit": Some gcloud magic revealed the following:
""tableReference": {
    "datasetId": "fraud_tutorial",
    "projectId": "feast-oss",
    "tableId": "transactions"
Isn't it quite illogical that the data is being written in a completely separate project by default? Could you add a step to the guide on how to set the default project and dataset for your featurestore.

## Steps to reproduce
Run the example in f.ex. Vertex AI you need to do somethings manually since all of the colab cellmagic is not available.
### Specifications

- Version: 0.15
- Platform: GCP Vertex AI notebook instance
- Subsystem:

## Possible Solution
Better documentation of the example, some more outputs from feast (what account is it using to create those BQ tables etc).

**Comment by felixwang9817** [comment]
Hi @jruokola, thanks for reporting this issue! We're planning to take a look at our tutorials + how we handle GCP/BigQuery soon, so hopefully that will resolve this issue.
