### ISSUE TITLE
Does BigQuery template query take advantage of Partitions?

### ISSUE THREAD

**Issue by judahrand** [feast-dev/feast#2083]
I'm unclear whether due to the dynamic nature of these `WHERE` clauses this query will take advantage of table partitions on the event timestamp? 

This could be solved by predetermining these min and max values and templating them in directly.

https://cloud.google.com/bigquery/docs/querying-partitioned-tables#pruning_limiting_partitions

https://github.com/feast-dev/feast/blob/b5d8a531c81fa11297e5c684f898646cb2ee2cd1/sdk/python/feast/infra/offline_stores/bigquery.py#L489-L491

**Comment by adchia** [comment]
@MattDelac was looking into taking advantage of partitioning more so my guess would be no?

@mavysavydav might be interested too as an fyi

**Comment by MattDelac** [comment]
> @MattDelac was looking into taking advantage of partitioning more so my guess would be no?

I don't think Feast does a good job with leveraging Partitions everywhere. The problem might not just be here.
We should definitely have a whole RFC about "Handling partitions end-to-end workflow"

**Comment by adchia** [comment]
Closing this to funnel more discussions in https://github.com/feast-dev/feast/issues/2530
