### ISSUE TITLE
requested_features are not passed to online_read() from passthrough_provider

### ISSUE THREAD

**Issue by aurobindoc** [feast-dev/feast#2106]
`OnlineStore.online_read()` has a parameter `requested_features`. Similarly, `PassthroughProvider.online_read()` also has a parameter `requested_features`.
`PassthroughProvider.online_read()`  calls `OnlineStore.online_read()` but doesn't pass on the `requested_features` variable.
I am writing a new OnlineStore where I need the `requested_features` in `OnlineStore.online_read()`.

## Issue Detected 
In [feast/infra/passthrough_provider.py#L90](https://github.com/feast-dev/feast/blob/2d3cea1d1485d0af1a35a7f30abfed475b58973a/sdk/python/feast/infra/passthrough_provider.py#L90)
```
def online_read(
        self,
        config: RepoConfig,
        table: Union[FeatureTable, FeatureView],
        entity_keys: List[EntityKeyProto],
        requested_features: List[str] = None,
    ) -> List[Tuple[Optional[datetime], Optional[Dict[str, ValueProto]]]]:
        set_usage_attribute("provider", self.__class__.__name__)
        result = self.online_store.online_read(config, table, entity_keys) # should also pass requested_features

        return result
```

- Version: 0.15.1
- Platform: all
- Subsystem: all

## Possible Solution

In [feast/infra/passthrough_provider.py#L90](https://github.com/feast-dev/feast/blob/2d3cea1d1485d0af1a35a7f30abfed475b58973a/sdk/python/feast/infra/passthrough_provider.py#L90)
`result = self.online_store.online_read(config, table, entity_keys)` 
change to 
`result = self.online_store.online_read(config, table, entity_keys, requested_features)`

Note: This won't break any of the current tests since none of the Online store implementation uses requested_features in online_read() method.

If it was as per design, can someone explain why the variable `requested_features` was not passed on?

**Comment by achals** [comment]
Good catch @aurobindoc , this is definitely a bug. Would you like to take a stab at fixing it?

**Comment by aurobindoc** [comment]
Sure. I will raise a PR with the fix
