### ISSUE TITLE
date_partition_column is not being used

### ISSUE THREAD

**Issue by baineng** [feast-dev/feast#2114]
**Is your feature request related to a problem? Please describe.**
In DataSource class, there is a `date_partition_column` field defined, but I haven't seen any implementation using it.
This field could be important for OfflineStore like `Hive`, to narrow the queries to specific partitions.

**Describe the solution you'd like**
Pass this field in `offline_store::pull_latest_from_table_or_query` abstract method and also other places like `offline_utils::FeatureViewQueryContext`

**Describe alternatives you've considered**

**Additional context**

**Comment by kevjumba** [comment]
@baineng we have deprecated `date_partition_column`.
