### ISSUE TITLE
Offline stores should support multiple data sources

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2121]
Offline stores currently only support their corresponding data source. For example:

```
class BigQueryOfflineStore(OfflineStore):
    def pull_latest_from_table_or_query(...):
        assert isinstance(data_source, BigQuerySource)
        ...
```

Users have asked about allowing offline stores to support multiple different data sources. This issue tracks that user request.

**Comment by woop** [comment]
@felixwang9817 do you have more details on this request? Specifically what problem is being solved?

**Comment by felixwang9817** [comment]
@woop the specific user request is [here](https://tectonfeast.slack.com/archives/C01MSKCMB37/p1638921410254100?thread_ts=1638862083.246600&cid=C01MSKCMB37).

**Comment by felixwang9817** [comment]
some thoughts from the team after a discussion:

there are two orthogonal issues here:
1. supporting multiple kinds of data sources per offline store (e.g. Athena on S3 + Redshift in a single offline store)
2. supporting multiple kinds of data sources residing in different offline stores (e.g. some data in Snowflake, some data in Postgres)
in this particular case, the user request is of type (2)

both requests are very reasonable, but also not very common, so we won't be prioritizing either of them - however, we do have some general thoughts on implementation, and community members should feel free to take a pass at this

for (2), i.e. supporting multiple kinds of data sources residing in different offline stores, we could extend `feature_store.yaml` to support multiple offline stores. one issue we foresee is joining data across offline stores, so we could limit historical retrieval to only retrieve features from the same offline store. in the future, Trino could be an option to query across offline stores

**Comment by shaibruhis** [comment]
We connect to up to 3 different data sources. Normally it's a `users` table, an `items` table, and an `events` table (containing the interactions between users and items). These 3 tables most of the time live in the same datasource type but sometimes the tables are stored in different places (Postgres, BigQuery, Firebase, etc.)

**Comment by ckarwicki** [comment]
@felixwang9817 @woop Created #3168. We would like to be able to query for features from multiple data sources at scale. We would like to use Spark for that. Since Spark offline store is not really a store but computation engine which can connect to pretty much any source (you just need to provide jdbc driver and connection string) it would fit this ideally. With that Feast would have general purpose engine to get features from multiple different sources at scale. You wouldn't have to maintain growing list of offline stores and data sources. Feast team could focus resources on Spark and add more functionality going forward instead of keep on adding new offline stores and data sources. Let me know your opinions.

**Comment by dbg-raghulkrishna** [comment]
+1

**Comment by sfc-gh-madkins** [comment]
@ckarwicki @dbg-raghulkrishna ultimately you need to get all the data into one place if you want get_historical_features() to work as you need to bring together multiple feature views. For materialize(), this might work abit easier as each feature_view doesnt need to interact with others.

Feast assumes that the features you are registering are quote "ready for modeling" -- why silo those features in different stores and then rely on the feature store to unsilo them? feast really doesnt havent an opinion on your feature pipeline architecture.

**Comment by sfc-gh-madkins** [comment]
bump

**Comment by svenaoki** [comment]
Can we re-open the issue? It is very common to have data across multiple databases especially if the company is not small and have more than just 1 product.

**Comment by MatusChladek** [comment]
Once again can we please reopen this issue?

**Comment by tokoko** [comment]
There was a similar issue opened recently: #4661. To repeat myself from there, I think the issue with this general scope doesn't make much sense, rather you should open issues for specific OfflineStore/DataSource combinations that you require.

**Comment by MatusChladek** [comment]
> There was a similar issue opened recently: #4661. To repeat myself from there, I think the issue with this general scope doesn't make much sense, rather you should open issues for specific OfflineStore/DataSource combinations that you require.

I think majority of the folks that expressed interest in this issue were towards option of supporting multiple kinds of data sources residing in different offline stores (e.g. some data in Snowflake, some data in Postgres).
