### ISSUE TITLE
Any plan to make Feast 0.10+ support docker

### ISSUE THREAD

**Issue by hsz1273327** [feast-dev/feast#2148]
I found there are plan to support k8s, and In the document, the Java based Feature Server can deploy on k8s using  Helm.
But in our production environment we use docker swarm, k8s is too heavy for us. So Is there any plan to support docker?

I found the latest version of feast-serving in dockerhub is 0.26.3 uploaded in  6 months ago, and it seems not support Feast 0.10+

**Comment by adchia** [comment]
Yes! We actually swapped out the docker image names confusingly, but the new ones that support the registry are at https://hub.docker.com/r/feastdev/feature-server-java (you still need to setup the repo tho in python)

**Comment by hsz1273327** [comment]
thanks
