### ISSUE TITLE
Add support for concurrent operations on the registry

### ISSUE THREAD

**Issue by DetourToNirvana** [feast-dev/feast#2176]
**Is your feature request related to a problem? Please describe.**
Current Feast implementation for reading/modifying Registry does not allow for concurrent modifications of the Registry by different processes (or server instances), which will be required in production scenarios to independently scale creation and materialization of feature views. Also, there is no mention of this constraint in the documentation. This severely limits scalability.

**Describe the solution you'd like**

1. Ideally, I would suggest that the data currently stored in the registry be stored in a central relational database (or document storage) instead, so that concurrent modification, reading and locking can happen on individual cells, instead of on the entire repository.
2. If the above is not feasible, please provide a way to lock the registry while a modification is happening so that the other processes are able to wait for it to complete.

**Describe alternatives you've considered**
At the suggestion of a Feast Dev, I have considered implementing a locking mechanism, so that different processes can check for an active lock before modifying the registry. But this would put a severe constraint on the scalability, since no parallel actions requiring registry modifications will be allowed.

**Additional context**
Here is a repo I created to reproduce the concurrency issue when using 2 processes to separate out the materialization from the other create/update requests: https://github.com/DetourToNirvana/mw-feast-samples.
Original Slack post: https://tectonfeast.slack.com/archives/C028V92F1R6/p1640001495050700

**Comment by woop** [comment]
While I think using a database for the registry does make sense, it would add a lot more complexity to Feast in the minimal case. I'd be happy for us to support an RDBMS registry as an external plugin (maybe using SQL Alchemy) if you'd like to contribute it. I think it should be pretty easy to implement. 

However, I **do** think locks on the existing file based registry will get us pretty far and seem like the most reasonable solution that maintains simplicity (doesn't ask users to bring a database).

Solution (2) that you have proposed sounds like _pessimistic locking_. Essentially a single process holds on to the complete registry until an operation completes. This seems like a good first step, but may be restrictive long term. I can imagine a materialization process taking 2-3 hours that holds on to a lock. Is there anything that would prevent us from having more granular locks? I can see us saying something like "You can lock each feature view individually, whether for materialization or update/teardown". So the following workflow could be supported

![image](https://user-images.githubusercontent.com/6728866/147863633-5cb38190-5168-4795-b2bb-d1ebf3c1efe8.png)

**Comment by DetourToNirvana** [comment]
Hi @woop, I will discuss the possibility of contributing to an external plugin to support rdbms registry with my team and get back to you soon.

As for the locking aspect, as long as the registry is a single file, I think there is always a possibility that another process will modify/overwrite it concurrently. Please let us know how you are planning to implement the locking on an individual feature-view-basis, considering that the registry file needs to be deserialized/serialized on modification as well.

**Comment by woop** [comment]
You'd have a lock on the writing as well (which is global). But most of the operations like materialization and apply/teardown don't require a very long amount of time to do writes (a few seconds max), so that isn't a big deal. The key thing is that the writes that are happening won't conflict with one another.

Where the locking happens depends on the object store. For GCS it can be the bucket itself I think, but for S3 it may be better to use Dynamo. We can look at what Terraform does for inspiration.

**Comment by DetourToNirvana** [comment]
Hi @woop, your suggestion sounds like a good approach to me. And yes, for AWS S3, Dynamodb seems like a good option. I haven't yet looked at Terraform codebase, but from the docs, it seems to be what we are looking for: https://www.terraform.io/language/settings/backends/s3. 

Please keep me updated regarding the next steps. Thank you. :)

**Comment by adchia** [comment]
Fixed by https://github.com/feast-dev/feast/pull/2734 and followups! (allowing a SQLAlchemy backed registry)
