### ISSUE TITLE
RegistryStore customization

### ISSUE THREAD

**Issue by sinban04** [feast-dev/feast#2183]
**Is your feature request related to a problem? Please describe.**

Hello, I'm trying to adopt **Feast** as feature store on my team. 
I saw your [documents](docs.feast.dev) and issues here, but i could not find any mention regarding customization of RegistryStore.
You gave 3 options about RegistryStore (Local, AWS, GCP), but we are gonna use the alternative on-premise in my team.
**Is there any way of customizing RegistryStore like GCP or AWS ?**

AFAIK, GCP and AWS is embedded in your code, and "adding custom provider" does not give option to replace RegistryStore. 
```
REGISTRY_STORE_CLASS_FOR_TYPE = {
    "GCSRegistryStore": "feast.infra.gcp.GCSRegistryStore",
    "S3RegistryStore": "feast.infra.aws.S3RegistryStore",
    "LocalRegistryStore": "feast.infra.local.LocalRegistryStore",
}

REGISTRY_STORE_CLASS_FOR_SCHEME = {
    "gs": "GCSRegistryStore",
    "s3": "S3RegistryStore",
    "file": "LocalRegistryStore",
    "": "LocalRegistryStore",
}
```
**Describe the solution you'd like**

As you give a way of customizing provider, it would be great that user can customize RegistryStore somehow (Inheritance)

**Describe alternatives you've considered**

If such solution above is not possible for some reasons, 
**is there any recommendation or the better way you expected to users about using another RegistryStore ?**

Such as, with custom provider(local registry), `Feast Core(Scheduler)` writes to local registry file and upload to custom RegistryStore, and in the case of using Feature, `Feast user` gets registry file from RegistryStore at first, and then use feast.
AFAIK, there could be some sync problem in Registry and following many other issues. 
Thank you 

**Additional context**

**Comment by woop** [comment]
@sinban04 we do support RegistryPlugins after https://github.com/feast-dev/feast/pull/1812 was merged. For example `foo.registry_store.FooRegistryStore`. Would that work for you?

**Comment by sinban04** [comment]
@woop 
Thank you for reply.
It's what i was finding for :) 

based on repo_config.py, i can use 
```
registry:
    registry_store_type: mycustom.RegistryStore
    path: following.registry.path
```
right? 

I didn't see that because i got it wrong that you intended as there's no custom guide only for registry in docs.feast.dev
Anyway, thank you 👍
