### ISSUE TITLE
feast will be broken post numpy 1.7. Post Numpy 1.7, this line should be datetime64 instead of datetime

### ISSUE THREAD

**Issue by fengyu05** [feast-dev/feast#2194]
## Expected Behavior 
:wave: Reporting a small bug. I think feast will be broken post numpy 1.7.
Post Numpy 1.7, this line should be datetime64 instead of datetime
https://github.com/opendoor-labs/feast/blob/master/sdk/python/feast/type_map.py#L67
https://numpy.org/doc/stable/reference/arrays.datetime.html (edited) 
### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by judahrand** [comment]
This looks to be fixed? Please, do reopen this issue if it is not @fengyu05.
