### ISSUE TITLE
Python FeatureServer inefficiently converts entity rows

### ISSUE THREAD

**Issue by judahrand** [feast-dev/feast#2201]
Problem:
It seems silly for the Python FeatureServer to convert EntityValues to Python native types only to then immediately convert them back to Protobuf Values. This can only increase latency by requiring a bunch of memory assignment and copying.

https://github.com/feast-dev/feast/blob/14048fd535f982eed7a3ba3af7d93557335e325a/sdk/python/feast/feature_server.py#L44-L50

Solution:
One option would be to refactor `get_online_features()` to convert `entity_rows` to  a `Dict[str, List[Value]` and then call a new wrapper method, `_get_online_features()`, `entity_rows` as a `Dict[str, List[Value]`. This would allow the FeatureServer to directly call `_get_online_features()` without converting the EntityValues to Python native types. 

This solution would align nicely with the refactoring done in #2186.

**Comment by judahrand** [comment]
A question around this is whether or not the FeatureServer is intended to support FeatureServices? Currently, it doesn't look like it does?

**Comment by adchia** [comment]
It's intended to support Feature Services, but I think the implementation has been patchy.  The feature server does support this though by mapping from feature service to feature refs in `get_online_features`?

**Comment by judahrand** [comment]
> It's intended to support Feature Services, but I think the implementation has been patchy. The feature server does support this though by mapping from feature service to feature refs in `get_online_features`?

I see that now. I'd overlooked that `if...else`.

The way I ended up implementing this it shouldn't matter. 

Do you have any suggestions on the best way to debug these test failures?

**Comment by adchia** [comment]
The easiest way I can think of is locally hardcoding the online feature server endpoint to return a local feature server endpoint (e.g deployed with feast serve) and then running tests locally
