### ISSUE TITLE
`feast apply` is not idempotent

### ISSUE THREAD

**Issue by startakovsky** [feast-dev/feast#2213]
I expect `feast apply` to act the same if I run it twice in a row, but it doesn't.

The behavior I see only matches the expected output from the [quickstart tutorial](https://docs.feast.dev/getting-started/quickstart#step-3-register-feature-definitions-and-deploy-your-feature-store) on the second run of `feast apply`.

Specifically, I do not see `deploying infrastructure` until the second time I run `feast apply`.

**Current Behavior, see image:**

![image](https://user-images.githubusercontent.com/689723/149465334-499c55b3-c456-4945-a0f9-d65499555c48.png)

Specifications:
- Version: 0.17.0
- Platform: Mac OS, Monterey, M1 Chip
- Subsystem: Python 3.10.1, installed with pyenv

**Comment by felixwang9817** [comment]
Hey @startakovsky, thanks for reporting this! The Feast team is in the process of changing the logging info that gets printed on `feast apply`, which is why the two messages you saw don't match. In reality, `feast apply` is idempotent - we expect that the logging will be fixed in a release or two.

**Comment by felixwang9817** [comment]
resolved by #2238
