### ISSUE TITLE
Usage logging slow down the test suite considerably !

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#2216]
## Expected Behavior 
Usage logging ([see doc](https://docs.feast.dev/reference/usage#how-to-disable-usage-logging)), should have a minimum impact of the runtime of the code.

## Current Behavior
It currently slow down the test suite considerably.
In fact running 11 simple tests by doing `pytest -vv -s tests/my_test.py` will result in the tests being passed after 0.05 seconds and the program exit after 5 seconds.
Our whole test suite takes ~2 seconds to run but 21 seconds to exit ...

While running the same tests by doing `FEAST_USAGE=False pytest -vv -s tests/my_test.py` will result in pytest exiting right away once done.

Results of  `pytest -vv -s tests/my_test.py`
![image](https://user-images.githubusercontent.com/18557047/149825140-e6c5a61c-f5ff-4f1d-8a4c-da995275cdcf.jpg)

Results of `FEAST_USAGE=False pytest -vv -s tests/my_test.py`
![image](https://user-images.githubusercontent.com/18557047/149825238-94ecc146-e8bb-4431-be5a-13eca9fa5dcf.jpg)

## Steps to reproduce
Create simple tests
```python
# tests/my_test.py
def test_entity_names1(mock_feature_store):
    entities = mock_pano.list_entities(allow_cache=True)
    assert sorted(entities) == [..., ...]

...

def test_entity_names11(mock_feature_store):
    entities = mock_pano.list_entities(allow_cache=True)
    assert sorted(entities) == [..., ...]
```
Run those 11 tests with and without the flag to desactivate tracking
`pytest -vv -s tests/my_test.py` vs `FEAST_USAGE=False pytest -vv -s tests/my_test.py`

### Specifications

- Version: 0.16.1
- Platform: MacOS / Linux
- Subsystem:

## Possible Solution
Don't emit events if the script is called by `pytest`
or 
Fix how we emit events

**Comment by pyalex** [comment]
Hi @MattDelac, just wondering why you don't consider settings `FEAST_USAGE=False` as a permanent solution? I, for example, don't run pytest directly, there are a lot of various configurations, so we put test command in Makefile including this `FEAST_USAGE` flag.

**Comment by MattDelac** [comment]
> just wondering why you don't consider settings `FEAST_USAGE=False` as a permanent solution?

Yes this is what we do now locally 👍
If this is the permanent solution, then it should be documented clearly to our users as I spent couple of hours to understand why I had this behaviour.

Unsure where is the best place to document that. Thoughts ?
