### ISSUE TITLE
Unable to deploy feast chart in release 0.17.0

### ISSUE THREAD

**Issue by psheorangithub** [feast-dev/feast#2232]
## Expected Behavior 
Should be able to deploy chart seemlessly
## Current Behavior
Looks like some issue in YAML files.I get below error when trying the install the base chart.
history.go:56: [debug] getting history for release feast-feast
upgrade.go:123: [debug] preparing upgrade for feast-feast
Error: UPGRADE FAILED: YAML parse error on feast/charts/feature-server/templates/deployment.yaml: error converting YAML to JSON: yaml: line 70: could not find expected ':'
helm.go:81: [debug] error converting YAML to JSON: yaml: line 70: could not find expected ':'
YAML parse error on feast/charts/feature-server/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Upgrade).prepareUpgrade
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:215
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:124
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:155
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
UPGRADE FAILED
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
## Steps to reproduce
git clone https://github.com/feast-dev/feast.git
cd feast/infra/charts/feast
update registry path in values.yaml of the main chart
perform helm install
### Specifications

- Kube Version: 1.21.5
- Helm version: 3.5.4
- Platform:
- Subsystem:

**Comment by pyalex** [comment]
Hi @psheorangithub, thanks for reporting this. I have already created PR with fix for this issue.

**Comment by psheorangithub** [comment]
Thanks @pyalex . Let me know once PR is approved
