### ISSUE TITLE
FEAST_USAGE should default to "False"

### ISSUE THREAD

**Issue by jbvaningen** [feast-dev/feast#2235]
**Is your feature request related to a problem? Please describe.**
I'm currently upgrading feast for our organization, making quite a big jump from 0.8 to 0.14. During testing I discovered the addition of the Telemetry/Usage class, to send anonymized metrics/error reports the feast devs.

While it is mentioned in the logging and if you read the release log carefully, I'm surprised/annoyed the decision was made to make `FEAST_USAGE="True"` the default. For my organization, metrics reporting like this will result in a big NO from our security team, regardless of anonymization. While other organizations might not be so strict, I'm not so sure they would appreciate it either. 

A feature store is a complex system to deploy, and to make sure we disable usage I have to set up `FEAST_USAGE="True"` everywhere. While not impossible, it is really easy to miss one or two corner cases, and concerns such as these basically block us from using feast directly. 

I understand the need for metrics/feedback to steer future feast development work, but IMHO this cannot be the way to that goal.

For now, I will resort to forking feast inside our organization and changing the default to False myself.

**Describe the solution you'd like**
Make sure the default `FEAST_USAGE="False"` is used

**Describe alternatives you've considered**
Mentioned above

**Comment by woop** [comment]
Hi @jbvaningen!

The tricky thing is that keeping `FEAST_USAGE="False"` will result in virtually nobody enabling telemetry, meaning it's actually more an argument for removing telemetry completely. We've also tried to make it super clear to users that we are tracking metrics (by printing a warning during first startup), and we do provide a way to disable it. Feast is also not very unique in tracking metrics to help us inform our development (other projects like Ray, dbt, dagster, etc, are also tracking anonymized metrics).

What about if we provided a build of Feast with telemetry removed, something like `feast-no-telemetry` on Pypi?
