### ISSUE TITLE
Flaky type tests

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2241]
## Expected Behavior

The tests in `test_universal_types.py` are consistent.

## Current Behavior

The test seem flaky. For example, they are all failing [here](https://github.com/feast-dev/feast/runs/4956304265?check_suite_focus=true) but when I run the tests locally, they pass. I also think that I've noticed these tests being flaky before during PRs.

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by adchia** [comment]
Fixed by https://github.com/feast-dev/feast/pull/2242
