### ISSUE TITLE
Feast java server could not retrieve feature value for entities that have String type

### ISSUE THREAD

**Issue by harmeet-singh-discovery** [feast-dev/feast#2253]
I defined the following entity in a python file
```
from google.protobuf.duration_pb2 import Duration
from feast import Entity, Feature, FeatureView, FileSource, ValueType
from importlib_metadata import csv

profile_view_history = FileSource(
    path="model-data-entity-string.parquet",
    event_timestamp_column="event_timestamp",
    created_timestamp_column="created",
)
profile_user = Entity(name="PROFILE_ID", value_type=ValueType.STRING, description="profile id",)

profile_view_history_view = FeatureView(
    name="sample_profile_2",
    entities=["PROFILE_ID"],
    ttl=Duration(seconds=1 * 1),
    features=[
        Feature(name="CHANNEL_ID", dtype=ValueType.INT32),
    ],
    online=True,
    batch_source=profile_view_history,
    tags={},
)

```
After `feast apply` and `feast materialize`, i checked that values can be retrieved using python code:
```
from pprint import pprint
from feast import FeatureStore
import pandas as pd

store = FeatureStore(repo_path=".")

feature_vector = store.get_online_features(
    features=[
        "sample_profile_2:CHANNEL_ID"
    ],
    entity_rows=[
        {"PROFILE_ID": "a-1"}
    ],
).to_dict()
pprint(feature_vector)
```

I installed java server using helm chart with following command with appropriate values.yaml file. 
```
helm install feast-release feast-charts/feast --values values.yaml
```
I verified that my server is running fine by checking the request-response logs on the running pod. 

The following go client code tries to retrieve the feature values from this entity:
```
package main

import (
	"context"
	"fmt"
	feast "github.com/feast-dev/feast/sdk/go"
	_ "github.com/feast-dev/feast/sdk/go/protos/feast/serving"
	_ "github.com/feast-dev/feast/sdk/go/protos/feast/types"
)

func main() {
	host := "localhost"
	cli, err := feast.NewGrpcClient(host, 6566)
	if err != nil {
		panic(err)
	}

	ctx := context.Background()
	req := feast.OnlineFeaturesRequest{
		Features: []string{"sample_profile_2:CHANNEL_ID"},
		Entities: []feast.Row{
			{"PROFILE_ID": feast.StrVal("a-1")},
		},
		Project: "reco_model",
	}

	resp, err := cli.GetOnlineFeatures(ctx, &req)
	if err != nil {
		panic(err)
	}

	out := resp.Rows()
	for _ , v := range out {
		fmt.Println("value is", v)
	}
}
```

To verify the problem, I repeated all above steps exactly in same manner except by replacing PROFILE_ID entity type from STRING to INT64 and then ran `feast apply` and `feast materialize` commands. I verified that data from new key can be retrieve using python code. The goclient was also able to retrieve values for entity with int keys.

## Expected Behavior 
I expect the java server to return the value for the entites that have STRING type.

## Current Behavior
No value is returned.

## Steps to reproduce
1- Create feature_value.yaml file
2- feast apply
3- feast materialize
4- Verify that online store has values using python code
5- Run java server
6- Run  GoGrpc client to retrieve values

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by woop** [comment]
@harmeet-singh-discovery we are aware of this problem and working on a fix.
