### ISSUE TITLE
Incorrect event timestamps being returned with get_online_features

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#2260]
## Expected Behavior 
Event timestamp in the `OnlineResponse` is the real event timestamp.

## Current Behavior
In https://github.com/feast-dev/feast/blob/master/sdk/python/feast/feature_store.py#L1730, we return the current time for all online features. In reality, we want to read from the online store to find the event timestamps and then populate them here

## Possible Solution
https://github.com/feast-dev/feast/pull/2174/files is a start (slightly outdated though).

**Comment by woop** [comment]
@adchia was this actually fixed?

**Comment by adchia** [comment]
nope. hence why I edited the code pointer just now. It still outputs the now() timestamp
