### ISSUE TITLE
On demand feature views (ODFVs) should use support python dicts

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#2261]
In some test benchmarks, using regular python dicts for inputs for executing the transformations is _much_ faster (up to ~10x) than pandas for the online flow. This tends to be the more latency sensitive flow (offline flows seem to be ~40% slower if using vectorized operations).

Something that looks like:

```python
@on_demand_feature_view(
    sources=[driver_hourly_stats_view, val_to_add_request],
    schema=[
        Field(name="conv_rate_plus_val1", dtype=Float64),
        Field(name="conv_rate_plus_val2", dtype=Float64),
    ],
    mode="python"
)
def transformed_conv_rate(driver_hourly_stats: Dict[str, Any], vals_to_add: Dict[str, Any]) -> Dict[str, Any]:
    features = {}
    features['conv_rate_plus_val1'] = (driver_hourly_stats['conv_rate'] + vals_to_add['val_to_add'])
    features['conv_rate_plus_val2'] = (driver_hourly_stats['conv_rate'] + vals_to_add['val_to_add_2'])
    return features
```

might be similar to what we want

**Comment by judahrand** [comment]
In your example what types would the `driver_hourly_stats['conv_rate']` be? Would it be a `list`? If so this interface will require some additional transformation. Would it be better to pass Numpy Arrays? If so have you factored the instantiation of these into the ~10x speed up?

**Comment by judahrand** [comment]
I was actually thinking a dict of 1d Numpy arrays?

**Comment by franciscojavierarceo** [comment]
tagging @maksstach who has implemented a version of this on our fork

**Comment by franciscojavierarceo** [comment]
I did this one https://github.com/feast-dev/feast/pull/4045 next I'll do writes.

**Comment by franciscojavierarceo** [comment]
I added writes here: https://github.com/feast-dev/feast/issues/4376
