### ISSUE TITLE
`created_timestamp` and `last_updated_timestamp` are never set

### ISSUE THREAD

**Issue by judahrand** [feast-dev/feast#2267]
## Expected Behavior 

`created_timestamp` and `last_updated_timestamp` should be set when things are updated in the Registry.

## Current Behavior

For:

- FeatureViews
- SavedDatasets
- Entites
- FeatureServices
 
this field is not currently set.

For OnDemandFeatureViews the `last_updated_timestamp` field does not even exist and the `created_timestamp` is not set.

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
Set the fields 😉

**Comment by woop** [comment]
Nice catch @judahrand.
