### ISSUE TITLE
Snowflake support does not include list features

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#2280]
## Expected Behavior 
Snowflake offline store works with list features

## Current Behavior
Right now Snowflake produces errors when using list features. This isn't caught by tests because of this skip with the aws provider: https://github.com/feast-dev/feast/blob/master/sdk/python/tests/integration/registration/test_universal_types.py#L39

**Comment by adchia** [comment]
cc @sfc-gh-madkins

**Comment by sfc-gh-madkins** [comment]
@adchia Here @woop  here is the docs related to semi-structured data in Snowflake: https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html#array

Arrays for list feature types are possible in Snowflake, but there is no enforcement of data type within the array, its stored as type VARIANT, where VARIANT, can store values of any other type, including OBJECT and ARRAY, up to a maximum size of 16 MB. Snowflake does not currently support fixed-size arrays or arrays of elements of a specific non-VARIANT type.

Im curious to your initial thoughts on this. We can certainly test an array if it complies with a certain data type that is supported or throw an error. If it does then execellent, if not we throw an error to remove the feature

**Comment by achals** [comment]
I think we can take the approach described by @sfc-gh-madkins

**Comment by sfc-gh-madkins** [comment]
bump

**Comment by sfc-gh-madkins** [comment]
bump

**Comment by JohnLemmonMedely** [comment]
Looks like we'll need this for our implementation so I'll be taking a look at implementing this in our sprint starting tomorrow.

**Comment by sfc-gh-madkins** [comment]
@JohnLemmonMedely I am afraid snowflake does not support structured types on the server side. All semistructured types are currently returns as strings. We are working to support this in the next couple of quarters.

**Comment by JohnLemmonMedely** [comment]
@sfc-gh-madkins I was planning on using the method you suggested earlier and attempt to cast them to what they need to be and throwing errors when we can't. It'll be better to guarantee data types via Snowflake but until that's possible I can enforce those guarantees myself via the data pipeline.

> We can certainly test an array if it complies with a certain data type that is supported or throw an error. If it does then execellent, if not we throw an error to remove the feature

**Comment by sfc-gh-madkins** [comment]
will look forward to the PR :)

**Comment by sfc-gh-madkins** [comment]
let me ping to see where this is at

**Comment by JohnLemmonMedely** [comment]
@sfc-gh-madkins just following up on if Snowflake still plans on supporting structured types soon. I just need to know if work will start on it over the next quarter or not.

**Comment by sfc-gh-madkins** [comment]
negative. this is continuing to be pushed out due to lack of customer
demand. however, we do now have vector support capabilities for both fixed
and floating point 32 bit numbers, however, the client arent ready yet

**Comment by will-e-yams** [comment]
from a related issue:

> @jkruzek sorry for the delay on this. Snowflake currently does not support list data types. Snowflake Arrays, Variants, etc are "Schema-less" types, and so the only thing they can be returned as is VARCHAR. Snowflake is working on this support in 2023

well, it's now 2024 and i can't figure out how to get json out of snowflake into a dict/list pydantic model.

any ideas, y'all?
