### ISSUE TITLE
Online store batch read/write interface

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2281]
**Is your feature request related to a problem? Please describe.**

The current `OnlineStore` read and write interfaces are batched with respect to entity rows, but not with respect to feature views:
```
@abstractmethod
def online_read(
    self,
    config: RepoConfig,
    table: FeatureView,
    entity_keys: List[EntityKeyProto],
    requested_features: Optional[List[str]] = None,
) -> List[Tuple[Optional[datetime], Optional[Dict[str, ValueProto]]]]:

@abstractmethod
def online_write_batch(
    self,
    config: RepoConfig,
    table: FeatureView,
    data: List[
        Tuple[EntityKeyProto, Dict[str, ValueProto], datetime, Optional[datetime]]
    ],
    progress: Optional[Callable[[int], Any]],
) -> None:
```

This makes it difficult to do store-specific optimizations. For example, batching Redis retrievals could lead to a significant speedup.

**Describe the solution you'd like**

Introduce non-breaking (e.g. non-abstract) methods to the `OnlineStore` interface:
```
@abstractmethod
def online_read(
    self,
    config: RepoConfig,
    tables: List[FeatureView],
    entity_keys: List[EntityKeyProto],
    requested_features: Optional[List[str]] = None,
) -> List[Tuple[Optional[datetime], Optional[Dict[str, ValueProto]]]]:

@abstractmethod
def online_write_batch(
    self,
    config: RepoConfig,
    tables: List[FeatureView],
    data: List[
        Tuple[EntityKeyProto, Dict[str, ValueProto], datetime, Optional[datetime]]
    ],
    progress: Optional[Callable[[int], Any]],
) -> None:
```

**Describe alternatives you've considered**
N/A

**Additional context**
This is partially motivated by #2254. In particular, having a batch interface would allow for greater optimizations to the Redis online store implementation.

**Comment by judahrand** [comment]
Slightly tangential but also worth noting that there doesn't seem to be any real reason to pass `entity_keys` as `List[EntityKeyProto]` anymore. Creating these Proto objects is unnecessary overhead when the OnlineStores could just use `Mapping[str, Value]`. It's a less important optimization but if we're thinking of changing the interface anyway 🤷
