### ISSUE TITLE
Snowflake login support private key or web browser authentication

### ISSUE THREAD

**Issue by realLyans** [feast-dev/feast#2292]
The current snowflake support seems only allow password authentication but we are using Azure AD login without password for the account.
Can we add functionality to allow different mechanism of authentication?

**Comment by felixwang9817** [comment]
@realLyans thanks for this feature request! cc @sfc-gh-madkins who's been working on Snowflake - do you think this could be supported easily?

**Comment by realLyans** [comment]
From what I can see backend is not very hard - just need to change https://github.com/feast-dev/feast/blob/f2bc4119b44fd35ea6739118273cfa48aa243cbe/sdk/python/feast/infra/utils/snowflake_utils.py to add public key authentication; main question is design of front end which I am not very familiar with.

**Comment by realLyans** [comment]
@adchia meaning the CLI interface that sets up the repo which doesn't really allow configuration there and I am also not too sure how I should enter a private key if it being a long binary typed variable. I don't think SnowflakeSource need a change (I might be wrong).

**Comment by sfc-gh-madkins** [comment]
@felixwang9817 @adchia @realLyans -- the snowflake integration for feast relies on the snowflake-connector-python ... any authentication method available for that package is available to feast users. The current design is for your project .yaml file to override any values set in a config file that by defaults points at where you config lives if you download the snowflake CLI tool

**Comment by sfc-gh-madkins** [comment]
This PR here should allow of forms of authentication available to the snowflake python connector to work for a feast project: https://github.com/feast-dev/feast/pull/2356
