### ISSUE TITLE
Kubeflow manifest update with latest FEAST

### ISSUE THREAD

**Issue by psheorangithub** [feast-dev/feast#2299]
## Expected Behavior 
Kubeflow manifest (https://github.com/kubeflow/manifests/tree/master/contrib/feast)  should have the latest updated FEAST components with new architecture.
## Current Behavior
The latest Kubeflow release 1.4.1 still contains the old FEAST due to which we are seeing lot of vulnerabilities.
## Steps to reproduce
Compare  https://github.com/kubeflow/manifests/tree/master/contrib/feast and latest FEAST chart.
### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by woop** [comment]
@psheorangithub would you be open to taking a stab at updating the manifest?
