### ISSUE TITLE
Assumption of a datetime object within get_historical_features

### ISSUE THREAD

**Issue by Talador12** [feast-dev/feast#2301]
Should be a quick fix here - just need to choose what should be the intended solution.

## Expected Behavior 
Choose a timestamp or date column for `event_timestamp` and call get_historical_features without issue

## Current Behavior
```
feast/utils.py", line 15, in to_naive_utc

AttributeError: 'datetime.date' object has no attribute 'tzinfo'
```
The `event_timestamp` is assuming the timestamp is a datetime object with the ability to check for `tzinfo`.
However, a `date` object will throw the above error if attempts to access that tzinfo attribute.

## Steps to reproduce
1) Choose a column with dates or a lack of full timestamp information for `event_timestamp`
2) Call `get_historical_features()` with this column set
3) Attribute Error. It is interpreted as a date object and cannot access this attribute.

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution

From the docs:
https://rtd.feast.dev/en/latest/_modules/feast/utils.html
```
def make_tzaware(t: datetime) -> datetime:
    """ We assume tz-naive datetimes are UTC """
    if t.tzinfo is None:
        return t.replace(tzinfo=utc)
    else:
        return t

def to_naive_utc(ts: datetime) -> datetime:
    if ts.tzinfo is None:
        return ts
    else:
        return ts.astimezone(utc).replace(tzinfo=None)
```

This should check the `ts` object before accessing tzinfo. If itzinfo is not a member, here are two possible solutions:

1) convert to a datetime object with utc timezone information (like make_tzaware above)
2) convert to a datetime object without timezone information (if having a default time set on the datetime object is not acceptable)

**Comment by adchia** [comment]
ooc is your system inherently tracking timestamps in date format? (i.e. without hours / seconds, etc)

**Comment by Talador12** [comment]
It may be some combination of versions assuming the `date` format instead of `datetime`, but this should still be checked to not throw an attribute error when called.

If it is the wrong type (date), it could still return a cast from date to timestamp. That would not change a lot of the logic, since the granularity of the data would still be stamped by date
