### ISSUE TITLE
__dummy_id column missing when retrieving from offline store with a FeatureService

### ISSUE THREAD

**Issue by pkovacs19** [feast-dev/feast#2312]
## Expected Behavior 
Retrieve offline store features with an `entity_df` and `FeatureService`, convert the response (`BigQueryRetrievalJob` in my case) to a dataframe with `to_df()`

## Current Behavior
The offline store returns a `BigQueryRetrivalJob` but unable to convert it to a data frame.  Error provided: 
```shell
feast.errors.FeastEntityDFMissingColumnsError: The entity dataframe you have provided must contain columns {'event_timestamp', '__dummy_id'}, but {'__dummy_id'} were missing.
```

## Steps to reproduce

1. Connect to a feature store
2. Get feature service from feature store
3. Retrieve historical features with feature service
4. Convert response with `.to_df()` method -> error occurs

### Specifications

- Version: 0.17.0
- Platform: Ubuntu 20.04

**Comment by felixwang9817** [comment]
@pkovacs19 thanks for reporting this bug! I'm current unable to repro it - I believe I've correctly set up the environment you described (with the exception that I'm on MacOS 11.4, which shouldn't matter), but I can't get your error. Would you mind sharing more details so I can repro this? Specifically (a) the contents of your feature repo, (b) the contents of `feature_store.yaml`, and (c) the script you used to do steps (1) through (4). Thanks!

Also note that it's possible that version 0.18.0 would resolve this bug.
