### ISSUE TITLE
Unable to install on GCP

### ISSUE THREAD

**Issue by anusha-karri11** [feast-dev/feast#2313]
## Expected Behavior 

i am trying to install feast in GCP VM with command "pip install 'feast[gcp]' " 

## Current Behavior

Installation was going in a loop, getting stuck at below step

Running setup.py clean for pyarrow
  Running setup.py bdist_wheel for pandas ... -

## Steps to reproduce

I have tried installing many times but no improvement, installation got stuck at the same step

### Specifications

- Version: 
- Platform: GCP
- Subsystem: GCP VM

## Possible Solution

Please help me troubleshoot the issue

below is the screenshot

<img width="853" alt="feast" src="https://user-images.githubusercontent.com/91670457/154243946-9e49b4bd-e756-47e8-a153-5402f51c90ca.PNG">

**Comment by woop** [comment]
What happens when you just do `pip install pyarrow`?

**Comment by anusha-karri11** [comment]
Hi,

Thanks for the response.

I have manages to install feast on GCP successfully, but i am encountering another error while applying my project configuration.

The error pointing to access failure for big query table. Please find the error content below and screenshot.

{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Login Required.",
        "domain": "global",
        "reason": "required",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.cloud.bigquery.v2.TableService.GetTable",
          "service": "bigquery.googleapis.com"
        }
      }
    ]
  }
}
<img width="958" alt="feast-2" src="https://user-images.githubusercontent.com/91670457/154458856-63f90bd3-7bd9-468d-8e05-433c8720c8e2.PNG">

**Comment by anusha-karri11** [comment]
For the above error, i have enables the bigquery API and that solved the issue, i have encountered another problem while materializing.

I am trying to materialize dataset which has 85000 records and while running test.py, materialize step is going no where, it could progress up to 3% as shown in the attached picture after that it was exiting with below error

File "/usr/local/lib/python3.7/dist-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 The referenced transaction has expired or is no longer valid.

kindly check and suggest me the possible solution.
![materialize](https://user-images.githubusercontent.com/91670457/154539840-48d093d7-b36d-457a-ac81-829d5acb4813.JPG)
![materialize-1](https://user-images.githubusercontent.com/91670457/154539859-70e60a41-b19f-457b-b222-a444dd5bef38.JPG)

**Comment by adchia** [comment]
Closing this since it looks like you made a separate issue tracking the newest issue. Thanks!
