### ISSUE TITLE
Pip install feast pulls in latest external dependencies that drop python 3.7 support

### ISSUE THREAD

**Issue by shihgianlee** [feast-dev/feast#2314]
## Expected Behavior 
`pip install feast[gcp]==0.17.0` should install feast successfully

## Current Behavior
`pip install feast[gcp]==0.17.0` failed to install when the external libraries it depends on don't support python 3.7.

## Steps to reproduce
Reproduce using Conda:
```
> conda create --name feast-test python=3.7
> pip install feast[gcp]==0.17.0
```
I used Conda `4.8.5` on my local MacOS `12.1` 

Reproduce using Dockerfile:
```
FROM debian:10

RUN apt-get update -qq && apt-get upgrade -y
RUN apt-get install python3 python3-venv python3-pip git curl jq libpq-dev -y

RUN pip3 install feast[gcp]==0.17.0
```

**Comment by adchia** [comment]
is this still an issue?

Not sure what the exact issue was here, but I can repro a pyarrow issue that is only specific to if you don't have wheel installed.

**Comment by shihgianlee** [comment]
The issue was feast[gcp]==0.17.0 doesn't support python 3.7 due to unpinned external dependencies. This is not an issue for me anymore after I pinned the numpy version (if I remember correctly) that supports python 3.7.  The Feast test passed with python 3.7 support. @woop suggested me to open an issue.

**Comment by achals** [comment]
Following https://numpy.org/devdocs/release/1.22.0-notes.html, we're planning on dropping support for python 3.7 in Feast as well. #2934
