### ISSUE TITLE
Java 8 version of the datatypes maven artifact

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#2318]
**Is your feature request related to a problem? Please describe.**

@olegharacidi is working with their stack that relies on Java 8 instead of Java 11. Having Java 8 artifacts would help

**Describe the solution you'd like**

The main issue with Maven is that the maven-compile-plugin configures Java 8 vs 11 differently (e.g. with a new <release> tag in Java 11). Haven't dug too deep, but seems like using [toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) is a good solution to work around this to publish separate Java 8 artifacts

**Describe alternatives you've considered**

**Additional context**

**Comment by achals** [comment]
Was this fixed by a7d4cb71af97156905e4567e3ccf484f8255ca88 @adchia ?
