### ISSUE TITLE
Azure blob storage support in Java feature server

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#2319]
## Expected Behavior 
Feast Java feature servers should be able to read from a registry in Azure blob storage.

## Current Behavior
Azure users can use the python feature server through https://github.com/Azure/feast-azure/tree/main/cluster/sdk or use an old Spark centric approach for feature serving. We should enable Java serving support as well

## Possible Solution
https://github.com/feast-dev/feast/blob/master/java/serving/src/main/java/feast/serving/config/RegistryConfig.java#L48 has AWS/GCP equivalents. We should implement the interface for Azure.

**Comment by mdrijwan123** [comment]
Hi, Thanks for creating this issue, our application is very latency critical and python server is not able to meet the requirement. Can I know if there is any update for this. We are using feast 0.19.4

**Comment by adchia** [comment]
Hi!

I would recommend moving forward solving this through using the Go feature server (https://github.com/feast-dev/feast/blob/projectMetadata/go/internal/feast/registry/registry.go#L319)

We're just finishing stabilization of this and it should also be easier to configure

CC @samuel100 . This'll be made easier once we migrate the Azure connector  into the main repo
