### ISSUE TITLE
Automated test setup needed for redis instance testing

### ISSUE THREAD

**Issue by kevjumba** [feast-dev/feast#2320]
**Is your feature request related to a problem? Please describe.**

Essentially currently in order to run integration tests that use redis or redis-cluster, devs need to spin up the redis nodes themselves before they run the local integration tests. 

**Describe the solution you'd like**
Add the logic to spin up redis/redis-cluster instances to the setup of the python test suite so that devs can just run the python test suite without actually needing to do prior setup.

**Describe alternatives you've considered**

**Additional context**

### Current approach to running your own redis cluster for testing

* Install redis on your computer. If you are a mac user, you should be able to `brew install redis`.
    * Running `redis-server --help` and `redis-cli --help` should show corresponding help menus.
* Run `cd scripts/create-cluster` and run `./create-cluster start` then `./create-cluster create` to start the server. You should see output that looks like this:
~~~~
Starting 6001
Starting 6002
Starting 6003
Starting 6004
Starting 6005
Starting 6006
~~~~
* You should be able to run the integration tests and have the redis cluster tests pass.
* If you would like to run your own redis cluster, you can run the above commands with your own specified ports and connect to the newly configured cluster.
* To stop the cluster, run `./create-cluster stop` and then `./create-cluster clean`.

**Comment by adchia** [comment]
Can you describe the current flow btw on how users would run tests? i.e. call the script or run redis-server manually

**Comment by kevjumba** [comment]
> Can you describe the current flow btw on how users would run tests? i.e. call the script or run redis-server manually

The current flow is specified here: https://docs.feast.dev/how-to-guides/adding-or-reusing-tests#running-your-own-redis-cluster-for-testing

**Comment by kevjumba** [comment]
This is fixed with docker containers.
