### ISSUE TITLE
Datastore Error while materializing dataset- The referenced transaction has expired or is no longer valid

### ISSUE THREAD

**Issue by anusha-karri11** [feast-dev/feast#2323]
## Current Behavior

i am running Feast - Feature store on VM and I am trying to materialize dataset which has 85000 records and while running test.py, materialize step is going no where, it could progress up to 3% as shown in the attached picture after that it was exiting with below error. I have Cloud Firestore in Datastore mode for feast online store with Database location: us-west2

File "/usr/local/lib/python3.7/dist-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
six.raise_from(exceptions.from_grpc_error(exc), exc)
File "", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 The referenced transaction has expired or is no longer valid.

kindly check and suggest me the possible solution

- Version: "feast 0.18.1"
- Platform: GCP
- Subsystem: VM, datastore, Bigquery
![materialize-1](https://user-images.githubusercontent.com/91670457/154642618-a92442e1-c7c1-4ac6-81a0-0f515d263ee6.JPG)
![materialize](https://user-images.githubusercontent.com/91670457/154642643-9d58821e-8ac3-447e-80b0-02a6dcbc20d0.JPG)

**Comment by anusha-karri11** [comment]
Hi team,

any update on the same?

**Comment by anusha-karri11** [comment]
Hi Team,

can you please update on the issue?

this error is stopping us from deploying feast which is a roadblock for release.

**Comment by adchia** [comment]
Hm. Looks like this issue does exist elsewhere (https://groups.google.com/g/google-cloud-firestore-discuss/c/XlhfbOU4dZc)

This might be related to some contention issues that we've seen. Is it possible for you to try installing a dev build and making some changes? e.g.

1. Adding a Retry object into the put_multi command that includes this error
https://cloud.google.com/python/docs/reference/storage/latest/retry_timeout#configuring-retries
2. Tweaking parameters in the online store via `feature_store.yaml`. 

e.g. Increasing the batch size of the write (default is 50, but could go up to 500 in some cases) or reducing concurrency (default is 40, but reducing this I've seen helps make materialization succeed)

```yaml
project: driver_ranking
registry: data/registry.db
provider: gcp
online_store:
  type: datastore
  project_id: my_gcp_project
  namespace: my_datastore_namespace
  write_batch_size: 500
  write_concurrency: 20

```

**Comment by anusha-karri11** [comment]
Hello,

Thanks for the response!

I have tried the above options but no luck, the behavior is still the same. Below is the timestamp

Tue Feb 22 16:26:33 UTC 2022

feature_store.yaml

project: feast_feature_store
registry: data/registry.db
provider: gcp
online_store:
  type: datastore
  project_id: us-gcp-ame-con-966-npd-1
  write_batch_size: 500
  write_concurrency: 20

I have checked this at GCP end, please check the below findings

The error message suggests: "The referenced transaction has expired or is no longer valid." 

I only found 9 occurrences of INVALID_ARGUMENT errors from your project over the past 2 days. I picked two examples out of the 9, and in both cases, the commit was attempted over 60 seconds after the transaction was created (and that there were no other activities during the 60 seconds, and so the transaction was "idle"). 

GCP documentation[1] states that a transaction would expire after 60 seconds of being idle, and so this seems to be what is happening here. Do note that it's your own code that creates the transaction as well as to attempt the commit, and so you needs to look into why the commit is happening so late (the two examples here JUST missed the 60-second expiration time). 

and, with the same timestamp provided in previous conversation, below are the findings in GCP RPC logs.

There were only 2 commit failures around the hour of the timestamp posted. Similar to previous observation both of these transactions were created >60 seconds BEFORE the commit was attempted: transaction was created at 08:48:30 EST, commit attempted at 08:49:34 EST 

Because "Feast Feature" is a third-party library the only thing visible is that the commit call came in much later after the transaction was crated (as per RPC log on our end). 

it's most likely that Feast is sending in the commit too late that is causing this issue.

hope above analysis would further help in troubleshooting. Please let me know if you need any information further


regards,

**Comment by adchia** [comment]
Hm seems odd since the commit happens immediately after the transaction is created in the code.

Technically though, we probably don't need to have a transaction here since we don't really have concurrent writes. Could you try removing the client.transaction() line in

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/datastore.py#L218-L218

and trying again? It should also be faster.

**Comment by anusha-karri11** [comment]
Hi,

I am not sure on how to access feast internal code, i am using below installation guide to run feast.

https://docs.feast.dev/how-to-guides/feast-snowflake-gcp-aws

**Comment by anusha-karri11** [comment]
Hi,

I am not sure on how to access feast internal code, i am using below installation guide to run feast.

https://docs.feast.dev/how-to-guides/feast-snowflake-gcp-aws

Also, can you please check if It could be a networking issue?  is there any verbose logging on Feast's side, to show when the transaction was created, and when the commit was attempted?

regards

**Comment by adchia** [comment]
Having a verbose logging mode is not a bad idea actually. 

You could do the same thing, but instead of running `pip install 'feast[gcp]'` you'd clone the GitHub repository (`git clone https://github.com/feast-dev/feast`) and run `make install-python-ci-dependencies PYTHON=3.7`. 

Then you could try making changes to the logic I suggested above.

Unfortunately, it's hard for me to check this since I can't reproduce your specific issue :/

**Comment by anusha-karri11** [comment]
sure, i will try that and get back to you.

**Comment by anusha-karri11** [comment]
Hi,

As you suggested above, i cloned the repo and clone the GitHub repository (git clone https://github.com/feast-dev/feast) and run "make install-python-ci-dependencies PYTHON=3.7" , doing so, i am getting many version dependency errors. seems the requirement file don't have the list of latest versions available. I tried editing /feast/sdk/python/requirements/py3.7-ci-requirements.txt for some package to match the requirement version (absl-py), but, the same didn't work for aiohttp package and so on because of unmatched versions between requirements file and listed versions feast is looking for.

With this i am getting error while running test.py:

Traceback (most recent call last):
  File "movie_test.py", line 4, in <module>
    from movie_repo import movie_test1, movie_stats_fv_test1
  File "/home/usa_karranusha_deloitte_com/feast-feature-store-test/feast/examples/java-demo/feature_repo/movie_repo.py", line 3, in <module>
    from feast import BigQuerySource, Entity, Feature, FeatureView, ValueType
ModuleNotFoundError: No module named 'feast'

The issue is more likely at the package version mis match while installing python-ci . could you please check this at your end.

Please find the attachments of error.
![dependencies_feast](https://user-images.githubusercontent.com/91670457/155507076-3c1e47f3-606e-4cbd-a654-de67288443dc.JPG)
![dependencies_feast_2](https://user-images.githubusercontent.com/91670457/155507087-54ac2627-24b8-4002-bcee-b69eb30c8590.JPG)

**Comment by anusha-karri11** [comment]
hi team,

can you please update on this

**Comment by anusha-karri11** [comment]
I also have python 3.7 , i am running with 3.7 for feast and the same behavior.

**Comment by adchia** [comment]
are you on Slack? might be easier to troubleshoot over a call

**Comment by adchia** [comment]
But it looks like you're using python 2.7 since it says "/usr/local/lib/python2.7" in the trace

**Comment by anusha-karri11** [comment]
that is because i have both python2.7 and python3.7 in my system, i have uninstalled python2.7, the trace was may be config files/data files of python 2.7 as i haven't purge. but, my default python is 3.7 and system only has 3.7 python.

Unfortunately, i dont have access to slack.. is it possible to request permission exception to slack ? or any other channels we can troubleshoot over a call
![python](https://user-images.githubusercontent.com/91670457/156421828-ed761641-a2d2-47cf-8058-62ecd0ce6cd4.JPG)

**Comment by adchia** [comment]
Maybe throw some time on my calendar then and we can have a Zoom or Google Meet call?  https://calendly.com/adchia

**Comment by anusha-karri11** [comment]
Thanks a lot, i have scheduled a call.

**Comment by adchia** [comment]
Consolidating in the linked issue
