### ISSUE TITLE
FileSource.create_filesystem_and_path() has no support for passing ssl and kwargs

### ISSUE THREAD

**Issue by MuhammadZeeshan34** [feast-dev/feast#2335]
## Current Behavior 
When using private S3 as offline file store, while fetching historical features or materializing, `FileSource.create_filesystem_and_path() `has been used to create connection with S3.  This method uses `pyarrow._s3fs.S3FileSystem` class to create this s3 filesystem. 
Which does not accept `use_ssl `parameter as available in actual [s3fs ](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem) implementation. 
If running on secure platform where connection can only be configured with certs, getting table using pyarrow runs into this error

`pyarrow.parquet.read_table(path, filesystem=filesystem)`

> [OSError: When getting information for key '<file-key>' in bucket '<bucket-name>': AWS Error [code 99]: curlCode: 60, SSL peer certificate or SSH remote key was not OK]()

Probably because the way filesystem is being created in `feast.infra.offline_store.file_source.py` using `pyarrow._s3fs`

## Steps to reproduce
```
import os
os.environ["FEAST_S3_ENDPOINT_URL"] = s3_endpoint
from feast.infra.offline_stores.file_source import FileSource
filesystem, path = FileSource.create_filesystem_and_path(f's3://{bucket_name}/{filename}',s3_endpoint)
table = pyarrow.parquet.read_table(path, filesystem=filesystem)
```

### Specifications

- Version: 0.18.0 
- Platform: Linux
- Subsystem: K8s/KF

## Possible Solution

However, if we import latest s3fs and pass use_ssl along with kwargs having s3_endpoint_url to create the filesystem, the same `pyarrow.parquet.read_table(path, filesystem=filesystem)` returns the result successfully.

```
import pyarrow
kwargs={'endpoint_url': s3_endpoint}
filesystem = s3fs.S3FileSystem(use_ssl=True, client_kwargs=dict(endpoint_url=s3_endpoint))
table = pyarrow.parquet.read_table(f's3://{bucket_name}/{filename}', filesystem=filesystem)
isinstance(table, pyarrow.Table)
**True**
```

Is it possible to import stable version of s3fs inside feast.infra.offline_store.file_source.py and provide the option to pass kwags and use_ssl?

**Comment by woop** [comment]
@MuhammadZeeshan34 I think the outlined solution makes sense. Would you be open to submitting a PR to make this change?
