### ISSUE TITLE
Int32 ValueType features using Snowflake as Offline Store cause local feature server to return nan's

### ISSUE THREAD

**Issue by sfc-gh-madkins** [feast-dev/feast#2343]
## Expected Behavior 

I would expect the local feature server to return the same results as fs.get_online_features() with the same input payload

## Current Behavior

local feature server returns status NOT PRESENT for all feature values, INT32 or otherwise

## Steps to reproduce

feast init -t snowflake

then follow steps in: https://docs.feast.dev/reference/feature-servers/local-feature-server

### Specifications

- Version: 0.18
- Platform: Mac
- Subsystem

**Comment by sfc-gh-madkins** [comment]
It appears that there a is a couple of things going on:

1. For a file offline_store, even if a feature is ValueType.INT32, it still gets saved as ValueTypeINT64 
2. In the feature_server.py, the following only returns int64_val,
`
            request_proto = GetOnlineFeaturesRequest()
            Parse(body, request_proto)`
3.) Because of issue 1, issue 2 isnt observed for testing a file store implementation of the feature server

**Comment by kevjumba** [comment]
This issue should be resolved by the int64.
