### ISSUE TITLE
[Docs] Explain DynamoDB online_write_batch uses a batch_writer

### ISSUE THREAD

**Issue by TremaMiguel** [feast-dev/feast#2346]
## Expected Behavior 

`DynamoDBOnlineStore` method `online_write_batch` uses a [BatchWriter](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html#batch-writing) under the hood. 

User documentation should explain the advantages of using it, including 

> automatically handle buffering and sending items in batches. In addition, the batch writer will also automatically handle any unprocessed items and resend them as needed.

**Comment by woop** [comment]
Thanks for raising this issue @TremaMiguel!

Are you suggesting we need to make a change to our docs to explain how BatchWriter is used?

**Comment by TremaMiguel** [comment]
Yes, the idea is that the user is aware that he/she can load a lot of data at a time without worrying about it. It could read something like

```
Write a batch of feature rows to the online DynamoDB store. This method implements a ``BatchWriter`` to handle
loading a lot of data at a time. Including automatically handling any unprocessed items and resending them if necessary.
```

Other public methods [online_read](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/dynamodb.py#L151), [update](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/dynamodb.py#L65) etc could have similar documentation. 

I'm open to write a PR documenting the public methods from [DynamoDBOnlineStore](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/dynamodb.py#L56).

**Comment by woop** [comment]
Sounds good. We'd love a PR. The docs are all in this repo.
