### ISSUE TITLE
[DynamoDB] - Allow passing ddb endpoint_url to enable feast local testing

### ISSUE THREAD

**Issue by vlin-lgtm** [feast-dev/feast#2358]
**Is your feature request related to a problem? Please describe.**
Currently in feature_store.yaml, we can only specify a region for DynamoDB provider. As a result, it requires an actual DynamoDB to be available when we want to do local development/testing or integration testing in a sandbox environment. 

**Describe the solution you'd like**
A way to solve this is to let user pass an endpoint_url. More information can be found [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html). 
This way, users can install and run a [local dynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html), and use it as an online store locally. 
The is especially useful when:

- accessing real DynamoDB requires a tedious and time-consuming steps (e.g.: IAM role set up, permissions, etc.) and these steps can be deferred later,
- integration testing locally, in docker, in Jenkins

**Describe alternatives you've considered**
N/A

**Additional context**
Not much but the initial slack thread can be found [here](https://tectonfeast.slack.com/archives/C01MSKCMB37/p1646166683447239), which was followed by a slack message from our team member
![image](https://user-images.githubusercontent.com/59895578/156633577-aa24f426-a350-4d0d-ba93-e71d5e350df0.png)

**Comment by TremaMiguel** [comment]
@vlin-lgtm I think this one is kind of easy [_initialize_dynamodb_client](https://github.com/feast-dev/feast/blob/ea6a9b2034c35bf36ee5073fad93dde52279ebcd/sdk/python/feast/infra/online_stores/dynamodb.py#L288) and [_initialize_dynamodb_resource](_initialize_dynamodb_resource) would now accept `endpoint_url` 

```python
def _initialize_dynamodb_client(region: str, url: str):
    return boto3.client("dynamodb", endpoint_url=url, region_name=region)
```

which can be passed through the [DynamoDBOnlineStoreConfig](https://github.com/feast-dev/feast/blob/ea6a9b2034c35bf36ee5073fad93dde52279ebcd/sdk/python/feast/infra/online_stores/dynamodb.py#L47). 

But, I'm not sure how will this be for local integration tests, as far as I know just need to change the [DYNAMODB_CONFIG](https://github.com/feast-dev/feast/blob/ea6a9b2034c35bf36ee5073fad93dde52279ebcd/sdk/python/tests/integration/feature_repos/repo_configuration.py#L48) with an additional parameter `endpoint_url` and set an [IntegrationTestConfig](https://github.com/feast-dev/feast/blob/ea6a9b2034c35bf36ee5073fad93dde52279ebcd/sdk/python/tests/integration/feature_repos/repo_configuration.py#L93) with DynamoDB as Online Store.

What are your thoughts?

P.D. I'm happy to contribute with this

**Comment by vlin-lgtm** [comment]
Thanks so much, @TremaMiguel! 

> But, I'm not sure how will this be for local integration tests, ....

My understanding is one can run a [local dynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) on their development machine or in a docker container, and by specifying an endpoint_url to for example `localhost:8080`, all DynamoDB invocations will go to the localhost instance instead of an actual one in AWS.  

This is useful for integration testing as everything is still "local". 

Would love it if you can help contribute to this 🙏

**Comment by TremaMiguel** [comment]
@vlin-lgtm Thanks for replying

I agree with the local integration tests, additionaly I think this development could help with #2400 

I'll start working on this.
