### ISSUE TITLE
No local test that tests feast apply without ci dependencies

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#2374]
We've had several breakages recently where we don't test feast apply thoroughly enough. One such example is running a basic `pip install feast` and running cli commands. This would catch breakages such as accidentally pulling in e.g. AWS/GCP/Redis/Spark dependencies when the user hasn't installed those extras.

**Comment by woop** [comment]
I am also pretty sure our CI pulls in all extras. This could lead to a situation where a library is not available without an extra installed, but we don't realize it because one of the extras pulls it in during our tests.
