### ISSUE TITLE
Local feature server example is out of date

### ISSUE THREAD

**Issue by milesadkins** [feast-dev/feast#2388]
## Expected Behavior 

curl -X POST \
  "http://localhost:6566/get-online-features" \
  -d '{
    "features": [
      "driver_hourly_stats:conv_rate",
      "driver_hourly_stats:acc_rate",
      "driver_hourly_stats:avg_daily_trips"
    ],
    "entities": {
      "driver_id": [1001, 1002, 1003]
    }
  }'

200

## Current Behavior

{"detail":"_get_online_features() missing 1 required positional argument: 'entity_values'"}%

## Steps to reproduce

https://docs.feast.dev/reference/feature-servers/local-feature-server

### Specifications

- Version:
- 0.19
- Platform:
- Mac
- Subsystem:

**Comment by woop** [comment]
which online store are you using?

**Comment by milescadkins** [comment]
local and redis

**Comment by adchia** [comment]
I can't seem to repro this with local + Redis?
