### ISSUE TITLE
Data source conversion from protobuf doesn't use type information

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#2409]
For some reason we are using field names https://github.com/feast-dev/feast/blob/b35e1e84720523cef70cba6d6306af8f193b469f/sdk/python/feast/data_source.py#L217 to infer data source types. We should be using the actual data source types in the protos.

Also, https://github.com/feast-dev/feast/blob/b35e1e84720523cef70cba6d6306af8f193b469f/sdk/python/feast/data_source.py#L213 doesnt exist

**Comment by adchia** [comment]
Yep. I think there is some bug that might have been introduced when we started storing data sources separately since the feature view class adds that, but i don't think we add this class_type with applying data sources to the registry.
