### ISSUE TITLE
Add support for Trino offline store

### ISSUE THREAD

**Issue by olivierlabreche** [feast-dev/feast#2413]
**Is your feature request related to a problem? Please describe.**
Right now there is a Trino offline store plug-in available at https://github.com/Shopify/feast-trino 
To improve visibility, support and maintainability of the plug-in, it should be moved to the main feast repo.

**Describe the solution you'd like**
Move the feast-trino plugin to the contrib folder of the main feast repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by felixwang9817** [comment]
Closing this since #2517 was merged, and #2518, #2519, and #2520 are tracking follow up tasks.
