### ISSUE TITLE
Unable to materialize from external Redshift table

### ISSUE THREAD

**Issue by npow** [feast-dev/feast#2419]
Tried running `feast materialize` on an external Redshift table, and encountered the following error:

```
InternalServerException: An error occurred (InternalServerException) when calling the DescribeTable operation (reached max retries: 4): ERROR: syntax error at or near "CASE"
  Position: 6746
```

I have narrowed this down to the boto3 `redshift-data` client unable to describe external tables, while normal tables work fine.

## Possible Solution
Fetch schema from Glue Catalog instead of `redshift-data` client.

**Comment by woop** [comment]
Thanks for raising this @npow. Have you been able to identify the exact problem? Do you have a stack trace?

**Comment by npow** [comment]
I reached out to AWS support, and they confirmed that there was an ongoing issue with describing external tables, which as now been resolved (also confirmed on my end).
