### ISSUE TITLE
Support parallel writing to online store

### ISSUE THREAD

**Issue by npow** [feast-dev/feast#2421]
**Is your feature request related to a problem? Please describe.**
Writing to online store (DynamoDB) currently uses a [single thread](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/passthrough_provider.py#L161), and takes extremely long when attempting to write billions of records (on the order of 12+ hours).

**Describe the solution you'd like**
Ability to parallelize writes to online store across multiple threads, ideally multiple nodes.

**Describe alternatives you've considered**
Tried using `multiprocessing.Pool` to parallelize writes on a single node with 96 cores but am hitting memory limits.
Historically have used AWS Glue to ingest data from S3->DynamoDB (using DynamoDB as a sink), and it works quite well. 

**Additional context**
N/A

**Comment by woop** [comment]
Thanks for raising this issue @npow! 

> Ability to parallelize writes to online store across multiple threads, ideally multiple nodes.

Would you be open to submitting a pull request to implement this functionality?

**Comment by adchia** [comment]
Moving discussions to the linked issue!
