### ISSUE TITLE
Get_historical_features() Does Not Have Option To Return Distributed Dataframe Like A Spark DF

### ISSUE THREAD

**Issue by adamluba1** [feast-dev/feast#2504]
When doing get_historical_features().to_df on a large training dataset in databricks I am hitting memory full errors. Since to_df is returning the data as a pandas dataframe it is not able to use the full capacity of the databricks cluster and distribute it across the different nodes the way a spark dataframe might.

**Comment by adchia** [comment]
Ah correct. Right now it only allows returning it in arrow batches. Is the intention to be able to materialize through a spark df?   Or to do training e.g. with MLLib.

In either case, might make sense for the SparkOfflineStore (this naming doesn't really make too much sense...) to be able to query from data warehouses (but maybe run the join within the DWH)

**Comment by adamluba1** [comment]
@adchia The intention is to just return snowflake data offline as a training dataset with the results being a distributed spark df. Is it possible to use snowflake as the source with the SparkOfflineStore? I found a way to hack around it by manipulating the to_sql() string and issuing that as a spark query using snowflakes spark connector, but wondering if there is a cleaner way

**Comment by adchia** [comment]
That works as a start and I don't think it's that hacky. Would be happy to check that in. 

An alternative would be to flush the output of Snowflakes query to S3 and read that, but that also seems pretty hacky
