### ISSUE TITLE
Add trino universal test suite in Github workflows

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#2520]
**Is your feature request related to a problem? Please describe.**
Once all the tests are fixed (see https://github.com/feast-dev/feast/issues/2518), we should add Trino universal tests in GH actions

**Describe the solution you'd like**
There are multiple strategies we could choose from
- The tests on Trino always run (and in that case, it might block other PRs)
- The tests on Trino only run if the Trino contrib folder has been modified
- The tests can be triggered manually

**Describe alternatives you've considered**

**Additional context**

**Comment by kevjumba** [comment]
I am going to merge this into the universal tests issue from before.
