### ISSUE TITLE
Feature repo setup for Java integration tests is broken

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2522]
## Expected Behavior

The feature repo that is set up for Java integration tests with docker compose (see `feast/java/serving/src/test/resources/docker-compose/feast10`) should rely on the most recent Feast code (e.g. for a PR, it should pull from the latest commit on the PR).

## Current Behavior

Instead, the feature repo pulls from `main`: `RUN git clone https://github.com/feast-dev/feast.git /root/feast`. This means that breaking changes might not be caught. As an example, #2488 made a breaking change, but the Java integration tests still passed on the PR; once the PR was merged in, the tests began to fail.

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution

Pull code from the latest commit on the PR instead of `main`.

**Comment by pyalex** [comment]
Fixed by #2645
