### ISSUE TITLE
Python feature server integration tests are flaky

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2544]
## Current Behavior

If I comment out all the other integration tests other than the 2 local tests and the 2 Go-based tests, and then run these 4 tests with `FEAST_USAGE=False IS_TEST=True python -m pytest -n 8 --integration sdk/python/tests/integration/online_store/test_universal_online.py::test_online_retrieval`, some of the tests will sometimes fail with errors like the following:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6572): Max retries exceeded with url: /get-online-features (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13184af10>: Failed to establish a new connection: [Errno 61] Connection refused'))
```
Similarly, on PRs, these tests are failing with errors such as:
```
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=6572): Read timed out. (read timeout=30)
```
However, these tests never fail when run individually. This suggests there is somehow some contention when the tests are run with multiprocessing.

Note that the recent test failures on master are all due to this flakiness.

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by kevjumba** [comment]
This is fixed
