### ISSUE TITLE
Switch from `redis-py-cluster` to `redis-py`

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2552]
As [documented](https://github.com/Grokzen/redis-py-cluster#redis-py-cluster-eol), `redis-py-cluster` has reached EOL. It is now being merged into [`redis-py`](https://github.com/redis/redis-py#cluster-mode). We previously tried to switch from `redis-py-cluster` to `redis-py` but ran into various issues; see #2328. The upstream [bug](https://github.com/redis/redis-py/issues/2003) has since been fixed, so we can now switch from `redis-py-cluster` to `redis-py`.

**Comment by achals** [comment]
Related, we should try to get redis-cluster integration tests running using testcontainers somehow.
