### ISSUE TITLE
Create Kustomize installation for Feast 0.3

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#258]
The primary means of deploying Feast right now is [Helm](helm.sh). Helm templates create the Kubernetes manifests that deploy the various components like Feast Core, Serving, and optionally some infrastructural components like Redis, PostgreSQL, and Kafka.

Helm charts for Feast 0.3 installation can be found [here](https://github.com/gojek/feast/tree/0.3-dev/infra/charts). 

Helm is becoming harder and harder to maintain, even though it's the defacto package manager in the Kubernetes ecosystem. We'd like to add support for installing Feast through [Kustomize](https://github.com/kubernetes-sigs/kustomize). This would hopefully allow us to have a simpler and more human readable way to install Feast, and would allow for integration of Feast onto platforms like Kubeflow.

In order to complete this issue, we would like to have a Kustomize installation script that has feature parity with the existing Helm installation. Meaning you can configure and deploy a complete Feast 0.3 installation into a Kubernetes cluster.

**Comment by Jemereny** [comment]
Will work on this

**Comment by nrchakradhar** [comment]
@jemereny one option to start would be to use helm-convert https://github.com/ContainerSolutions/helm-convert

**Comment by woop** [comment]
That's great, thanks @nrchakradhar!

**Comment by woop** [comment]
This issue is still open if anyone is free to pick it up.

**Comment by dr3s** [comment]
I may take it up because despite the issue description, kustomize has become the defacto config mgmt tool for k8s.  we could use the helm charts for the templating still for dependencies if need be as described [here](https://testingclouds.wordpress.com/2018/07/20/844/)

**Comment by woop** [comment]
> I may take it up because despite the issue description, kustomize has become the defacto config mgmt tool for k8s. we could use the helm charts for the templating still for dependencies if need be as described [here](https://testingclouds.wordpress.com/2018/07/20/844/)

Yea, the Kubeflow folks are also strongly in favour of having this before we integrate with them.

**Comment by woop** [comment]
#1016 provides an implementation, but we have decided to not maintain a Kustomize installation as part of Feast. We will use Helm as the primary way to install into Kubernetes.

There is also a Kubeflow installation guide here that derives a Kustomize installation from our Helm charts https://github.com/kubeflow/manifests/pull/1733
