### ISSUE TITLE
Support Hive for warehouse and Hbase for serving

### ISSUE THREAD

**Issue by wuxianxingkong** [feast-dev/feast#259]
Hive and Hbase are all open source project which can be deployed on self-build framework，but using BigQuery and Bigtable means 
enterprises need to put their private data on google services which cannot be accepted.Is there any support plan？

**Comment by woop** [comment]
Hi @wuxianxingkong,

This is one of our most requested features and it is one we definitely intend to add. However, the specific technologies we choose might differ. We currently support Redis as an alternative to Bigtable, so we only need an alternative for historical storage.

Do you have a preference for Hive, or would you be open to other warehouses as long as they are open source?

**Comment by wuxianxingkong** [comment]
@woop Thanks for your reply.

Yes,  Hive can be written using  Hadoop or Spark which widely used in internet company such as  alibaba, baidu, xiaomi and so on. Not only because they have good stability and performance for big data processing but also  ease of use with stack of libraries such as sql, streaming, machine learning.  In a word, widely used and the ability combined with other tools are chief concerns.

**Comment by woop** [comment]
Noted. I think our primary task is on identifying the second warehouse type to support. Ideally that would address the majority of users that don't use BigQuery. 

We are planning to target this in the release after 0.3. 

The likely next steps are a public proposal which folks like yourself can comment on.

**Comment by woop** [comment]
If you arent already in the Feast development mailing list then I'd suggest you join it to receive updates on new proposals and releases.

**Comment by Data-drone** [comment]
I think Hive and HBase would provide the widest audience as additional supported warehouse and serving layers.

**Comment by singh-b** [comment]
I agree, Hive is a core warehouse technology very widely used as a default choice with Hadoop deployment.

**Comment by elukey** [comment]
+1 as well

**Comment by sungjuly** [comment]
+1

**Comment by mabbasi90** [comment]
+1

**Comment by Seanspt** [comment]
+1

**Comment by louisZL** [comment]
When will support hive?

**Comment by woop** [comment]
Have you had a look at https://github.com/baineng/feast-hive?

**Comment by dubeno** [comment]
How about support hbase for online store?

**Comment by adchia** [comment]
Going to mark this issue as closed for Hive as a warehouse and make a separate request for HBase
