### ISSUE TITLE
Snowflake has connection issues

### ISSUE THREAD

**Issue by esadler-hbo** [feast-dev/feast#2595]
## Expected Behavior
I try to connect to snowflake using a private key
## Current Behavior
I get an error from the snowflake python connection object saying that I need to set the warehouse.
## Steps to reproduce
I ran the demo
### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
I removed this double quoting and it worked

```python
# line 61 in snowflake_utils.py
    for k, v in kwargs.items():
        if k in ["role", "warehouse", "database", "schema_"]:
            kwargs[k] = f'"{v}"'
```

Happy to replicate through the testing setup and make a PR

**Comment by sfc-gh-madkins** [comment]
@esadler-hbo are you setting creds in a config file?

**Comment by esadler-hbo** [comment]
@sfc-gh-madkins yeah I am. I posted more details in #2601.
