### ISSUE TITLE
Data quality monitoring

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#2596]
This is tracking work related to [Feast RFC-027: Data Quality Monitoring
](https://docs.google.com/document/d/110F72d4NTv80p35wDSONxhhPBqWRwbZXG4f9mNEMd98/edit#)

**Comment by TremaMiguel** [comment]
@adchia I think you could take as example [LightGBM Feature Request Tracking](https://github.com/microsoft/LightGBM/issues/2302) to keep track of issues related DQM. 

In this way, new contributors could know how he/she can contribute to.

**Comment by franciscojavierarceo** [comment]
are there tickets tracking the work here? i was interested in contributing to this area but wasn't sure which milestone @pyalex was working on

**Comment by adchia** [comment]
I think there's actually not too much active work happening right now. @chhabrakadabra is going to also beginning thinking about this a lot soon, but right now still very much in the phase of figuring out what makes sense to build.

We are working on improving documentation at least of what is already supported! (i.e. validating served features in the Go feature server, validating training datasets against a reference data set, using `feast validate`)

**Comment by franciscojavierarceo** [comment]
what would be the best way to contribute in that case? would love to collaborate @chhabrakadabra 

i spoke with the team earlier and heard there was interest in integrating with great expectations and i think that makes a lot of sense, i think there's also some other ideas i have that i'd like to incorporate
