### ISSUE TITLE
Feast python server registry refresh.

### ISSUE THREAD

**Issue by mdrijwan123** [feast-dev/feast#2599]
I am trying to create a centralized feast registry but when if someone change the feature view or add another feature view, the feature server cache of Feature store keep on reading the old registry.  This is expected because of how feature_server py file have been written. But is there any way I can achieve the same behavior that is refresh any time I want or schedule it for periodic run.

I am expecting to achieve this registry refresh without writing own logic and using inbuild python feast server. Please help if there is any available or alternate solutions.

**Comment by achals** [comment]
Hi @mdrijwan123 , sorry that this isn't well documented but feast already supports this out of the box. In your `feature_store.yaml`, you can configure a `cache_ttl_seconds` after which the registry is reloaded. By default this is 600seconds.

There's some docs here https://rtd.feast.dev/en/master/index.html?highlight=RegistryConfig#feast.repo_config.RegistryConfig

An example of what this would look like in the feature_store.yaml:
```
registry:
  path: s3://path-to-registry
  cache_ttl_seconds: 60
...
```

**Comment by achals** [comment]
Please feel free to reopen if this solution isn't what you were looking for!

**Comment by mdrijwan123** [comment]
Thankyou so much, I was looking exactly this feature only. Much appreciate your response @achals
