### ISSUE TITLE
spark source complain about "table or view not found" error.

### ISSUE THREAD

**Issue by kfiring** [feast-dev/feast#2605]
## Expected Behavior 
spark offline store

## Current Behavior
if set table of SparkSource with pattern "db.table"，feast will complain about "table or view not found" error.

## Steps to reproduce
1. feast init test_repo
2. modify example.py to use SparkSource, and set table of SparkSource with pattern "db.table"
3. configure featue_store.yaml
4. feast apply

### Specifications

- Version: 0.20.1
- Platform: ubuntu 18/04
- Subsystem:

**Comment by woop** [comment]
Thanks for raising this @kfiring!
