### ISSUE TITLE
Python package wheel is not built for Apple M1 (arm64 architecture)

### ISSUE THREAD

**Issue by pyalex** [feast-dev/feast#2627]
## Expected Behavior 
`pip install feast` works on Apple M1.

## Current Behavior
Currently we don't build a wheel since there's no native Github runner on M1 and our build includes building a cgo extension (can't be cross-compiled).

In addition to that build from source is broken.

The only way to install feast right now is from github.

### Specifications

- Version: 0.20.x
- Platform: MacOSX M1 (arm64)
- Subsystem: distribution

## Possible Solution
Setup custom GH runner on M1.

**Comment by kevjumba** [comment]
@achals and @kevjumba confirmed that source is working.
