### ISSUE TITLE
Snowflake type behavior is strange

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2633]
## Current Behavior

In `test_universal_online::test_online_retrieval`, `orders_df` has the following `dtypes`:
```
order_id             int64
driver_id            int64
customer_id          int64
origin_id            int64
destination_id       int64
order_is_success     int32
event_timestamp     object
dtype: object
```

When type inference occurs, `get_table_column_names_and_types` returns `[('order_id', 'int8'), ('driver_id', 'int16'), ('customer_id', 'int16'), ('origin_id', 'int8'), ('destination_id', 'int8'), ('order_is_success', 'int8'), ('event_timestamp', 'datetime64[ns]')]`.

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by sfc-gh-madkins** [comment]
@felixwang9817 what is strange about this?

**Comment by sfc-gh-madkins** [comment]
Check out https://github.com/feast-dev/feast/pull/2948
