### ISSUE TITLE
test_proto_json.py broken by new python/google/protobuf/json_format.py changes

### ISSUE THREAD

**Issue by michaelcui1986** [feast-dev/feast#2634]
## Expected Behavior 
test_proto_json.py passes

## Current Behavior
test_proto_json.py not passes

## Steps to reproduce
make test-python

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution

The cause is a new version of json_format.py from protobuf repo. Broken by https://github.com/protocolbuffers/protobuf/commit/ab4585a6956675ce14a1cba5d321fde980bbf12b, this added addition "path" parameter in the customized function defined in proto_json.py

**Comment by achals** [comment]
cc @tsotnet 

Thanks for the report @michaelcui1986 ! I think we saw this when protobuf was upgraded unintentionally which broke stuff. That's why we decided to pin protobuf in #2480 to `<3.20`.
