### ISSUE TITLE
support minio with credencials for registry storage

### ISSUE THREAD

**Issue by pengyuan** [feast-dev/feast#2641]
**Is your feature request related to a problem? Please describe.**

support minio with credencials for registry storage

can not find any docs for this feature.

**Describe the solution you'd like**

project: feature_store
registry: s3://feast/registries/dev
provider: local

cannot access minio bucket feast.

**Describe alternatives you've considered**

**Additional context**

**Comment by pengyuan** [comment]
> Setting the AWS cli environment variables before running the `feast apply` command should work
> 
> ```
> export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
> export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
> ```
> 
> However I could not find a way to pass the --no-verify option and the apply command might fail if your certificates are self signed.

sad, it does not work. 

helm chart for feast java feature server cannot set credentials in values.yaml,  so it cannot sync the  s3/minio registry file.

personally, i think the overall design of feast seems not good. too many bugs and inconsistency between versions.

1.  registry or feature server does not support s3/minio, everything only designed around google cloud?
2. ambiguous design between source and offline store,  the latter has no usage from tutorials or demo project.
3. get online feature return feature_view__feature_name instead of feature_view:feature_name,  introduce inconsistency again.

**Comment by adchia** [comment]
I think the issues here are solved. The naming of features is consistent.

Users use pod annotations to configure roles to configure access to S3

**Comment by virtualb0x** [comment]
@adchia can u be so kind to show an example of pod annotations  that can configure access to s3 ?

**Comment by wajeehulhassanvii** [comment]
@adchia can you please share an example? Thank you

> I think the issues here are solved. The naming of features is consistent.
> 
> Users use pod annotations to configure roles to configure access to S3

I also couldn't set the minio credentials for feast-java. Can you please share an example?
