### ISSUE TITLE
basicConfig is called at the module level

### ISSUE THREAD

**Issue by elshize** [feast-dev/feast#2664]
## Expected Behavior 

```
import feast
logging.basicConfig(level=level, format=FORMAT)
logging.error("msg")
```

should print logging message according to `FORMAT`

## Current Behavior

It uses the format defined in `feast` at the module level.

## Steps to reproduce

Same as in "Expected Behavior"

### Specifications

- Version: 0.18.1
- Platform: Linux
- Subsystem: -

## Possible Solution

I see that `basicConfig` is called here: https://github.com/feast-dev/feast/blob/c9eda79c7b1169ef05a481a96f07960c014e88b9/sdk/python/feast/cli.py#L84 so it is possible that simply removing this call here is enough: https://github.com/feast-dev/feast/blob/0ca62970dd6bc33c00bd5d8b828752814d480588/sdk/python/feast/__init__.py#L30

If there are any other entry points that need to set up logging, they should call the function, but the call in `__init__.py` must be removed.

**Comment by achals** [comment]
Actually I'm going to quickly fix this so that we can include the fix in the release we're planning on cutting tomorrow.

**Comment by elshize** [comment]
@achals Thanks. Sorry I didn't reply sooner, it was nighttime here :)
