### ISSUE TITLE
Smart Search Bar for Feature documentation

### ISSUE THREAD

**Issue by davideromano** [feast-dev/feast#2693]
Based on my experience, Feast is the point where are stored all the features, KPIs, and metrics used to train models.
It could be the case that many teams work on different ETL pipelines in order to aggregate and transform data, and as a final step Feast fetch all those data and store them as possible features.
An interesting feature, in my opinion, could be to enhance the search bar implemented on the Feast web UI making possible to search not just by the name of the feature or by tags, but describing a KPI logic.
For example: if I have a feature named `avg_ts_per_view` which describe **"the average Time Spent per Video View"** I should be able to search and find it with the string _"average time per video"_ or even better with the formula _"time spent / number video views"_ .
At the beginning it could be implemented just for the on_demand features, since you have the function used to calculate them, while in the future it could check the features description (even if right now it doesn't exist).

The reasons for this request are the following:
- If you have a bunch of people (or teams) working on the data preparation step it could be the case that the same feature will be calculated several times just because it is not easy to find if that feature already exists.
- Web UI is a fundamental part of the feature store. It helps Data Engineers and Data Scientists to respectively understand if the feature already exists and how it has been calculated.
- Web UI (in my mind) should be a shared feature documentation, where everybody can check available Datasets, which model used a specific dataset, the logic behind a feature, etc.

**Comment by achals** [comment]
I think adding a search box does make sense for discoverability in the long run. cc @adchia

**Comment by adchia** [comment]
Tagging #2353 for visibility

Yeah agreed. Right now there is a search bar that allows searching by title + filtering by tags, but it hasn't implemented robust search capabilities.
