### ISSUE TITLE
Unclear how to get the parquet data dump in the Quickstart docs

### ISSUE THREAD

**Issue by ssge** [feast-dev/feast#2694]
## Expected Behavior 

when there is a picture of a data dump I expect to see how to get that dump (like it is done on the Codelab notebook)

## Current Behavior

just a picture in the middle of the explanation

## Steps to reproduce

just open https://docs.feast.dev/getting-started/quickstart

### Specifications

- Version: n/a
- Platform: n/a
- Subsystem: n/a

## Possible Solution

copy code from Codelab notebook

**Comment by kevjumba** [comment]
You can read the data in python using pd.read_parquet and then printing the pandas dataframe.

**Comment by kevjumba** [comment]
Please join the Feast dev slack and post in Feast beginners if you are still struggling with this.
