### ISSUE TITLE
Value-based Query API for the Online Store

### ISSUE THREAD

**Issue by swapkh91** [feast-dev/feast#2698]
Is there a way to fetch features from Online Store with SQL like query for example using `where` clause? 

I have multiple columns where I need to filter the rows (which I currently do through a SQL table using `where` clause). I'm thinking of moving this table to Feast, so I can have history separately in offline store. One way is to combine all columns and form a new column and do fetch but that would greatly increase the number of rows.

Any idea on how to achieve this?

**Comment by swapkh91** [comment]
@achals yes. So instead of getting features for `entity_rows` only, I would like to fetch the entities matching feature values.
Like in a SQL query `select entity_column from table where feature_column=value`. The use case is that I only know the feature values and need to find the entities matching those. 

Not sure if this is the use case for Feast.

**Comment by achals** [comment]
Thanks @swapkh91 - this is not something that is supported in Feast right now, but I can imagine this being useful for specific use cases like recommendations systems for candidate generation. 

The feast time is planning on prioritizing work on transformations and data quality for the coming few months so we are unlikely to get to it, but we'd be happy to review community contributions for it. A good start would be a mini-RFC to describe what the API would like look. 

I'll update the title of the issue with my understanding, but please correct me if I'm wrong.
