### ISSUE TITLE
Support for Firestore in Native Mode

### ISSUE THREAD

**Issue by natsoule** [feast-dev/feast#2712]
**Is your feature request related to a problem? Please describe.**
The current Feast online store for GCP implementation requires Firestore in Datastore mode. Firestore can only be in one mode at a time per GCP account. You cannot use native mode for some applications and Datastore mode for others within the same account. Adding a feature store to an existing GCP account that uses native mode would not allow us to use the online store. 

Secondly, Datastore is deprecated. Presumably Google does not want to support it forever, and there may come a time when Google no longer allows new Datastore implementations.

**Describe the solution you'd like**
Feast should support Firestore in native mode. 

**Describe alternatives you've considered**
Creating a separate GCP account is certainly a possibility, but an inconvenient one. Creating a new account at many companies would require approvals and setup. 

**Additional context**

**Comment by achals** [comment]
Thanks for bringing this up @natsoule - naively seems like we'd need to create a new online store implementation using https://googleapis.dev/python/firestore/latest/index.html. 

Happy to review PRs from the community for this!

**Comment by sapphire008** [comment]
Hi, can we review this issue again given this was asked 2 years ago and Datastore has been deprecated since then? If anyone can point out the necessary online store implementation that is needed, I can take a look and see if I can help contribute.
