### ISSUE TITLE
client.apply : invalid value for feature resource, argument must only contain alphanumeric characters and underscores.

### ISSUE THREAD

**Issue by axlmrlls** [feast-dev/feast#2714]
Hi,
I'm working with branch v0.7 and im getting this error (argument must only contain alphanumeric characters and underscores) on my STRING features when executing client(apply), this is my code

from feast import FeatureSet, Client, Entity
from feast import ValueType
import re
df['id']=df['session-Id'].map(lambda x: re.sub(r'\W+', '', x))
df['datetime']=pd.to_datetime(df['serviceRequestTimeStamp'].astype(str).str[:14],format='%Y%m%d%H%M%S')

client = Client(core_url="172.22.137.202:6565")
cdr_volte_fs = FeatureSet("cdr_volte")
cdr_volte_fs.infer_fields_from_df(
            df,
            entities=[Entity(name='id',dtype=ValueType.STRING)],
            
        )

client.apply(cdr_volte_fs)

Output error:

---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/feast/sdk/python/feast/client.py in _apply_feature_set(self, feature_set)
    395                 timeout=self._config.getint(CONFIG_GRPC_CONNECTION_TIMEOUT_DEFAULT_KEY),
--> 396                 metadata=self._get_grpc_metadata(),
    397             )  # type: ApplyFeatureSetResponse

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    825                                       wait_for_ready, compression)
--> 826         return _end_unary_response_blocking(state, call, False, None)
    827 

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    728     else:
--> 729         raise _InactiveRpcError(state)
    730 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "invalid value for feature resource, sIP-Method: argument must only contain alphanumeric characters and underscores."
	debug_error_string = "{"created":"@1652892981.565692574","description":"Error received from peer ipv4:172.22.137.202:6565","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"invalid value for feature resource, sIP-Method: argument must only contain alphanumeric characters and underscores.","grpc_status":13}"
>

During handling of the above exception, another exception occurred:

RpcError                                  Traceback (most recent call last)
<ipython-input-99-61fef4deebb7> in <module>
     14         )
     15 
---> 16 client.apply(cdr_volte_fs)

/feast/sdk/python/feast/client.py in apply(self, feature_sets)
    369         for feature_set in feature_sets:
    370             if isinstance(feature_set, FeatureSet):
--> 371                 self._apply_feature_set(feature_set)
    372                 continue
    373             raise ValueError(

/feast/sdk/python/feast/client.py in _apply_feature_set(self, feature_set)
    397             )  # type: ApplyFeatureSetResponse
    398         except grpc.RpcError as e:
--> 399             raise grpc.RpcError(e.details())
    400 
    401         # Extract the returned feature set

RpcError: invalid value for feature resource, sIP-Method: argument must only contain alphanumeric characters and underscores.

**Comment by achals** [comment]
hi @axlmrlls , it seems like the project name you're using is `sIP-Method` which is invalid because of the listed error. 

Also, v0.7 is an extremely old version of feast - we're currently on 0.21, and there's no development happening on the older branches.

If you're interested in upgrading,  this [guide](https://docs.feast.dev/project/feast-0.9-vs-feast-0.10+) is a good starting point.
