### ISSUE TITLE
FeatureStore Connection issue

### ISSUE THREAD

**Issue by rajeshdhanda** [feast-dev/feast#2716]
I am trying to **connect feature_store using repo_path and RepoConfig inside the cloud function** 
`fs1 = FeatureStore(config=RepoConfig( project="project_name",registry="gs_path_to_registry,provider="gcp"))`
and 
feature_store.yaml in `/tmp` folder 
`fs2 = FeatureStore(repo_path="/tmp/")`
Offline Store - BigQuery
Online Store - Redis ( Pod inside K8s Cluster with internal load Balancer )
However, Connection is successfully built using `fs1` but got an error using `fs2`. 
**Error** --- `TimeoutError: [Errno 110] Connection timed out` for Redis connection. Redis is in a different network so cloud function is not able to build connection. But the issue is, that I can't understand the connection built by using RepoConfig `fs1` in the same cloud function.

**Comment by achals** [comment]
Hi @rajeshdhanda  - this is difficult to debug because it's very specific to the networking setup you have in your environment, and how you're attempting to communicate with the online store, and isn't specific to feast.

Generally, I would try to make sure that wherever location you are running your commands (such as `feast apply` or `fs.get_online_features`) can connect to redis correctly. Feast uses the redis connection information from `feature_store.yaml`. You can use the same configuration using `redis-cli`.

**Comment by rajeshdhanda** [comment]
Hi @achals, this is the code I'm using in my cloud function.
```
def hello_gcs(event, context):
      # < some code above >
      fs_repo_path = FeatureStore(repo_path="/tmp/")
      fs_repo_path.materialize_incremental(end_date=datetime.utcnow())
      print("Materialization Done using conn built using feature_store.yaml !!!!  ")
      #----------------------------------------------------
      fs_config = FeatureStore(config=RepoConfig(project="cloud_func_test",registry=gs_path,provider="gcp"))
      fs_config.materialize_incremental(end_date=datetime.utcnow())
      print("Materialization Done using conn built using registry !!!!  ")
```
My concern is in the same networking environment, I am able to connect to Feature_store using **RepoConfig** but not using **repo_path**.

**Comment by rajeshdhanda** [comment]
Got it @achals Thanks. 

`fs.config` connection through yaml
```
RepoConfig(registry=gs_path, project='cloud_func_test', provider='gcp', 
online_store=RedisOnlineStoreConfig(type='redis', redis_type=<RedisType.redis: 'redis'>, connection_string=ip,password='password_here', key_ttl_seconds=None),
offline_store=BigQueryOfflineStoreConfig(type='bigquery', dataset='feast_test', project_id=None, location=None), feature_server=None, flags={'alpha_features': True, 'on_demand_transforms': True}, repo_path=PosixPath('.'))
 ```
`fs.config` connection through registry
```
RepoConfig(registry=gs_path, project='cloud_func_test', provider='gcp', 
online_store=DatastoreOnlineStoreConfig(type='datastore', project_id=None, namespace=None, write_concurrency=40,write_batch_size=50), 
offline_store=BigQueryOfflineStoreConfig(type='bigquery', dataset='feast', project_id=None, location=None), feature_server=None, flags=None, repo_path=None)
```

So materialization done through  
  `FeatureStore(config=RepoConfig(project="cloud_func_test",registry=gs_path,provider="gcp"))`
will not update the feature values fetched via  
  `FeatureStore(repo_path="/tmp/").get_online_features()` and vice-versa.
correct me if i am wrong here..

**Comment by achals** [comment]
Yes, that's right.
