### ISSUE TITLE
UI fails to run correctly on project with offline Featureviews

### ISSUE THREAD

**Issue by dvanbrug** [feast-dev/feast#2719]
## Expected Behavior 
When FeatureViews have `online=False`, running `feast ui` should start the UI and load the project.
 
## Current Behavior
The UI fails to load with the following error:
```
Error Loading Project Configs
There was an error loading the Project Configurations. Please check that feature_store.yaml file is available and well-formed.
```

This looks like it is caused by the registry dump not containing the `online` key for the feature views.

## Steps to reproduce
1. Create a default repo using `feast init`
2. In `example.py` change `online=True` to `online=False`.
3. Run `feast ui`

### Specifications

- Version: 0.21.2
- Platform: macOS
- Subsystem:

## Possible Solution
To fix this, the registry should always contain the `online` key for FeatureViews even if they are set to False.

Perhaps this is related to this quirk of protobufs: https://github.com/protocolbuffers/protobuf/issues/1772 which would mean that the `online` key doesn't come through in the call to `to_proto` here:

https://github.com/feast-dev/feast/blob/f4eed30c7a01b8e68cb6b5ed4f8ed70cdef86462/sdk/python/feast/registry.py#L914

**Comment by adchia** [comment]
Thanks for catching!

Would you mind opening a PR for this? Think that it's also addressable with changing

https://github.com/feast-dev/feast/blob/master/ui/src/parsers/feastFeatureViews.ts#L42

to have `online` as optional. We probably should throw a better error message too..
