### ISSUE TITLE
Change type of argument value_type in Entity.

### ISSUE THREAD

**Issue by denesbartha** [feast-dev/feast#2721]
https://github.com/feast-dev/feast/blob/b0e2a8d31f259d4b2ba9f02fd9c9115aade2adee/sdk/python/feast/entity.py#L63

In class `FeatureView` the type of argument `schema` has changed to `List[Field]` and `Field` has the argument of `dtype` with type `FeastType`. Here basically one needs to specify primitive data types `PrimitiveFeastType` using `from feast.types import Int64, String, etc.`. But the constructor of class `Entity` still requires one to specify an argument `value_type` that has the old `ValueType`.

`Entity` should also use the same type `Field` for the argument `value_type`.

## Specifications
Version: 0.21.2
Platform: linux

**Comment by kevjumba** [comment]
Hello! Valuetype is actually about to be deprecated! It will be deprecated in 0.24.0
