### ISSUE TITLE
Add registry route to Python feature server 

### ISSUE THREAD

**Issue by tkch3n** [feast-dev/feast#2724]
**Is your feature request related to a problem? Please describe.**
We would like a way for our users to fetch and explore the registry without having to use the Python SDK. 

**Describe the solution you'd like**
We can add the new route `get-feature-registry` to return the current registry. 

**Describe alternatives you've considered**
We're considering using the web UI, but we don't like how it requires a static registry dump.

Adding a `get-feature-registry` route in the feature server could help with decoupling the UI and registry source, where the UI could make an API call to the server.

**Additional context**
I can start working on this once I get a thumbs up!

**Comment by adchia** [comment]
Does deploying a separate service that runs `feast ui` work for this? It regularly pulls from the registry

**Comment by tkch3n** [comment]
> Does deploying a separate service that runs `feast ui` work for this? It regularly pulls from the registry

Is this a capability that already exists in `feast ui`? Or would this be something we would build ourselves?
