### ISSUE TITLE
Are you really sure the quickstart can work?

### ISSUE THREAD

**Issue by wallyell** [feast-dev/feast#2747]
By following the quickstart step by step accurately, and then encounter the following error information in feast ui:

Error Loading Project Configs
There was an error loading the Project Configurations. Please check that feature_store.yaml file is available and well-formed.

There was an error in loading registry information.

**Comment by adchia** [comment]
I just ran through it and it seemed to work successfully?

**Comment by arumugaguru-mindtree** [comment]
Does it work if feast is installed in a remote instance? I too face the same issue on running 'feast ui'. However the sample project which is in feast/ui works fine on npm start. Please could you help?
