### ISSUE TITLE
Conda Packaging

### ISSUE THREAD

**Issue by marcelatoffernet** [feast-dev/feast#2748]
Will feast be added as a conda package at some stage? Many CI workflows rely on the conda packaging system rather than PIP.

**Comment by bgalvao** [comment]
Hello peeps, I am making an effort of [forging Feast](https://github.com/conda-forge/staged-recipes/pull/19960). The recipe was generated using [grayskull](https://pypi.org/project/grayskull/). Now, while all the dependencies seem to be on conda-forge already, there are a couple of things I need to debug. From the [first CI/CD results](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=547260&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=920), it seems there are things to be fixed.
