### ISSUE TITLE
error during feast materialize data source as parquet and online store as postgres

### ISSUE THREAD

**Issue by coalindiax** [feast-dev/feast#2758]
## Expected Behavior 
while feast materialize  with data source as parquet and online store as postgres should be working 
## Current Behavior
it throws error
## Steps to reproduce
use data source as parquet and online store as postgres. feast apply and feast materialize

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by achals** [comment]
Hi @coalindiax can you provide any stack trace or detailed error information? This is not enough data for a bug report.

**Comment by kevjumba** [comment]
@coalindiax  Please reopen this issue if you are still experiencing this bug and provide more information including the specific version of feast, your system and the stacktrace
