### ISSUE TITLE
Feast materialize showing java.lang.OutOfMemoryError: Java heap space error

### ISSUE THREAD

**Issue by mdrijwan123** [feast-dev/feast#2759]
I was expecting to normally materialize my data from **spark to Redis cache db**, but if I try to materialize my data its showing this error.

I got to know that this issue can only be changed by my side by changing spark conf. But I am eager to know how materialization work specifically for spark and why this much heap memory is required.

I am using below spark configuration in my feature store yaml:

project: Feature_spark
registry:
    registry_store_type: feast_azure.AzBlobRegistryStore
    path: ${REGISTRY_PATH}
    cache_ttl_seconds: 60
provider: local
offline_store:
    type: spark
    spark_conf:
        spark.master: "local[*]"
        spark.ui.enabled: "false"
        spark.driver.memory: "16g"
        spark.sql.session.timeZone: "PST"
online_store:
        type: redis
        redis_type: redis
        connection_string: ${REDIS_CONN}
go_feature_server: True

Please help if I can solve this issue and how use this much of memory.

**Comment by adchia** [comment]
ah in this case, I believe since you're using the local provider to do materialization, all the data is pulled into memory in your driver.

You can likely get around this with a custom provider that uses `to_spark_df` and writes that to the online store instead of using `to_df`

**Comment by mdrijwan123** [comment]
Hwy @adchia This PassthroughProvider looking interesting can you please give any reference where we can use it properly in our project like documentation etc.

**Comment by mdrijwan123** [comment]
I think it's because data is being loaded in memory due to pyarrow conversion and if that exceed above max limit of ram then this issue occurs, only materialization with spark can solve this issue.
