### ISSUE TITLE
Getting access to datasets in parquet format

### ISSUE THREAD

**Issue by vecorro** [feast-dev/feast#2772]
Sometimes is hard to use GCP (budget/contract constraints for example). Would it be possible to get the parquet dataset files used in the tutorials so people can run them locally without the need of using GCP?

Thanks!

**Comment by woop** [comment]
Hi @vecorro, you are free to use Parquet. Just be aware of the fact that you won't get nearly the same performance without a scalable system like a cloud datawarehouse.

**Comment by vecorro** [comment]
Thanks, @woop  I think that running the tutorials on Parquet should be ok as the data volume is small. I just wonder if there is a repo where all the Parquet files used in the tutorials can be pulled from.

**Comment by kevjumba** [comment]
@vecorro Hi vecorro, specifically which tutorials are you interested in? For any `feast init`, the parquet file is generated from pandas dataframes in feast.
