### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message with type 'feast.core.Registry'

### ISSUE THREAD

**Issue by BaljinderSmagh** [feast-dev/feast#2790]
while running feast apply getting this above error

**Comment by felixwang9817** [comment]
hey @BaljinderSmagh thanks for filing this issue - could you provide a more detailed stack trace so that we can reproduce this issue?

**Comment by BaljinderSmagh** [comment]
Hey Felix,
it turns out if i am running the feast apply command again and registry.db is already there,,,I always gets this error...

**Comment by kevjumba** [comment]
Hi @BaljinderSmagh, Could you please provide your stack trace and also the version of feast, and your operating system(i.e all of the details in the comments that outline an issue? This would help us debug your problem.

**Comment by kevjumba** [comment]
@BaljinderSmagh I will close this for now. Please reopen with more information if you are still experiencing this issue.
