### ISSUE TITLE
event_timestamp_column showing as deprecated in documentation

### ISSUE THREAD

**Issue by tkch3n** [feast-dev/feast#2809]
## Expected Behavior

`created_timestamp_column` should be shown as deprecated in docs

## Current Behavior

Docs currently show that `event_timestamp_column` is deprecated. I'm assuming `created_timestamp_column` is the one that is supposed to be deprecated.

## Steps to reproduce

https://rtd.feast.dev/en/master/#feast.data_source.DataSource

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by achals** [comment]
Great catch @tkch3n , you're right.

**Comment by achals** [comment]
There's more clarification for this deprecation warning in #2804 which should be landed soon.
