### ISSUE TITLE
Feast Helm Chart Deployment

### ISSUE THREAD

**Issue by jyotsana700** [feast-dev/feast#2818]
Need to deploy helm chart where registry.db file should be in PV with  online store (redis) and offline store (postgres).

**Comment by kevjumba** [comment]
Can you clarify this comment some more? What is the exact issue you are encountering?

**Comment by jyotsana700** [comment]
like i made changes locally in the notebook , so can i deploy in PV , by changing registry.db

**Comment by achals** [comment]
@jyotsana700 we don't have any out of the box mechanism for shipping the regsitry file to k8s. I'd recommend using something like S3 or GCS as the registry location instead, which will allow you to make changes to the registry and have the changes picked up.

https://docs.feast.dev/getting-started/architecture-and-components/registry

**Comment by jyotsana700** [comment]
If i am not using S3 and GCS , can it worked with minio object ?
