### ISSUE TITLE
Handle PII data

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#2821]
**Is your feature request related to a problem? Please describe.**
Feast does not have any functionality to handle PII / sensitive data.

**Describe the solution you'd like**
One possible solution is to build various methods (or allow users to provide these methods) to clean PII data before materialization into the online store. Feast would also support some first-class label that can be applied to specific feature columns. Upon materialization, the cleaner methods would be triggered for the labeled columns.

**Describe alternatives you've considered**
N/A

**Additional context**
Came up in the biweekly feast-ops meeting (see notes [here](https://docs.google.com/document/d/1zUbIWFWjaBEVlToOdupnmKQwgAtFYx41sPoEEEdd2io/edit#))

**Comment by tim5go** [comment]
@felixwang9817 
I would like to give a try on this feature.
Do I needa join the Feat Ops Bi-Weekly meeting for discussion?

**Comment by felixwang9817** [comment]
hey @tim5go no need to join the feast ops bi-weekly meeting - feel free to work on this feature and submit a PR whenever you're ready

we typically use the #feast-development channel in the [slack](http://slack.feast.dev/) for discussing development of new features, so feel free to post in there if you have any questions / want to discuss anything!
