### ISSUE TITLE
Support passing in feature_store.yaml explicitly to FeatureStore

### ISSUE THREAD

**Issue by achals** [feast-dev/feast#2848]
**Is your feature request related to a problem? Please describe.**
Right now, feast assumes that the `feature_store.yaml` is always located at the root of the feature repo. This is a reasonable assumption, but introduces some issues for users - when using multiple environments (e.g. staging vs production) users need to duplicate their feature definitions into multiple directories. 

**Describe the solution you'd like**
The feast CLI should support a new flag on all commands, the explicit location of the feature_store.yaml file. Something like:
```
feast --config-yaml-location production/feature_store.yaml apply
```

Similarly, the `FeatureStore` class should have an additional parameter, `config_yaml_location` (or something like it):

```
class FeatureStore:
    def __init__(
        self, repo_path = None, config_yaml_location = None
    ):

        config_path = config_yaml_location or Path(repo_path) / 'feature_store.yaml'
```

**Describe alternatives you've considered**
?

**Comment by kevjumba** [comment]
This is a duplicate issue @achals from https://github.com/feast-dev/feast/issues/2563
