### ISSUE TITLE
: Access Denied: Table <PROJECT_NAME>: Permission bigquery.tables.get denied on table <Project-name> (or it may not exist).

### ISSUE THREAD

**Issue by vaibhavguptaDel** [feast-dev/feast#2854]
## Expected Behavior 
Not Able to connect feast with my GCP BigQuery , no place to find where to provide service account details.
## Current Behavior
: Access Denied: Table <PROJECT_NAME>: Permission bigquery.tables.get denied on table <Project-name> (or it may not exist).
## Steps to reproduce
Need Support

### Specifications

- Version: Feast SDK Version: "feast 0.21.3"
- Platform: GCP
- Subsystem:

**Comment by nikitabarskov** [comment]
There is no need to provide service account details. You can use Application Default Credentials if you are running the application locally, and in GCP Credentials are obtained from the metadata server.

Feast is using Google Cloud libraries for BigQuery and Google Cloud Storage, and they in its turn are using `google-auth`. So, when you are running `feast apply`, feast will try to obtain application default credentials.

https://googleapis.dev/python/google-auth/latest/user-guide.html#application-default-credentials

You can rn `gcloud auth application-default login` before you run `feast apply`, if you locally. In GCP credentials will be obtained from the environment.
