### ISSUE TITLE
Go feature server does not compile on python 3.10 on Mac OS X

### ISSUE THREAD

**Issue by kevjumba** [feast-dev/feast#2881]
## Expected Behavior 
`gopy build` compilation succeeds without errors.

## Current Behavior
https://github.com/feast-dev/feast/runs/7034219412?check_suite_focus=true
Specifically an issue with python 3.10 where wheels are built as `universal2` wheels when they do not support arm64. Causes cross-compilations errors like attached screenshot.
<img width="1018" alt="Screen Shot 2022-06-28 at 3 49 33 PM" src="https://user-images.githubusercontent.com/7833572/176317155-34a9b3c6-6469-47cf-9bce-8f732c2e8b0c.png">

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by felixwang9817** [comment]
See https://github.com/actions/python-versions/pull/114.
