### ISSUE TITLE
Feast 0.21.3 wheels do not build with Python 3.10 on MacOS M1X

### ISSUE THREAD

**Issue by kevjumba** [feast-dev/feast#2882]
<img width="1186" alt="Screen Shot 2022-06-29 at 10 27 22 AM" src="https://user-images.githubusercontent.com/7833572/176498907-b066c4a8-f664-422d-a992-f0dee4d8b1b5.png">
## Current Behavior
The wheels do not build because grpc are built with universal wheels when they are not suitable for m1. The problem is most likely due to this bug: https://github.com/grpc/grpc/issues/28387

## Steps to reproduce
Create a new virtual environment with python 3.10.3 and install feast on MacOS M1.

### Specifications

- Version: 0.21.3
- Platform: Mac M1X OSX 12.2.1
- Subsystem: Python 3.10.3

## Possible Solution

The solution should be to update the grpc versions to latest to force m1's to build from source.

**Comment by achals** [comment]
Can you add a stack trace for this error, or a link to the failure?

**Comment by kevjumba** [comment]
This is fixed, and will be out in patch release 0.22.1
