### ISSUE TITLE
Remove `google-cloud-core` from dependencies

### ISSUE THREAD

**Issue by chhabrakadabra** [feast-dev/feast#2897]
**Is your feature request related to a problem? Please describe.**

Feast is often hard to install alongside other python packages that use `google-cloud-core`. Specifically, Feast sets an upper-bound on this library (`2.0.0`), but the latest version is `2.3.1` and many python packages have a lower-bound of 2.0.0 and above.

**Describe the solution you'd like**

Remove `google-cloud-core` from the `setup.py` file (https://github.com/feast-dev/feast/blob/master/setup.py#L87). It's already a sub-dependency of some of the `[gcp]` packages.

**Describe alternatives you've considered**

In some cases, we can restrict ourselves to older versions of other packages, but this is not always feasible or recommended.

**Additional context**

N/A

**Comment by achals** [comment]
@chhabrakadabra Was this accomplished by #2906?

**Comment by chhabrakadabra** [comment]
Yes it was. Thanks for checking.
