### ISSUE TITLE
Checking Go code generated from protos into Git

### ISSUE THREAD

**Issue by yongheng** [feast-dev/feast#2910]
**Is your feature request related to a problem? Please describe.**
Currently the repo doesn't include Go code generated from protos. As a result, when Go developers want to use structs defined in the protos, they have to generate the structs by running the Makefile target [`compile-protos-go`](https://github.com/feast-dev/feast/blob/master/Makefile#L185). What's worse, the protos assume the generated code to be saved to the location `github.com/feast-dev/feast/go/protos/feast/...`. Therefore, the users have to change the import package paths in the generated Go code.

I ran the following bash script to execute the procedure described above.
```
# Fetch and compile protos.
rm -rf feast protos
git clone https://github.com/feast-dev/feast.git
cd feast
git checkout tags/v0.21.2
make compile-protos-go
mv go/protos ..
cd ..
rm -rf feast

# Replace imports.
for FILEPATH in $(find protos -type f); do
    sed -i "" -e "s/github\.com\/feast-dev\/feast\/go/my\/company\/featurestore\/feastclient/g" "${FILEPATH}"
done
```

**Describe the solution you'd like**
Check Go code generated from protos into Git. This will create a go-gettable package and a big convenience for users. It’s also recommended in the official Go documentation — see [*Section Limitations of About the go command*](https://go.dev/doc/articles/go_command#tmp_4).

**Describe alternatives you've considered**
The bash script above. It works. But it's better to remove the burden for the users.

**Comment by judahrand** [comment]
I think there are other solutions here too. One them is to use a something like `buf` which is able to fix the import paths itself as well as compile the protos remotely which removes the need for the developer to have the correct dependencies installed.
