### ISSUE TITLE
Document how to design a schema for online stores

### ISSUE THREAD

**Issue by achals** [feast-dev/feast#2931]
**Is your feature request related to a problem? Please describe.**
The ideal data model for is very store and implementation specific, and depends on the what teams are prioritizing for (constraints on storage vs read latency). This nuance is not really made explicit in our docs anywhere but has come up in conversations a lot.

We should document the different choices involved (entity-key based vs feature view + entity key based), potentially offer an API in feast or some configuration so that implementors can implement both models to support users. We'd also need documentation and test infra to help implementors test and benchmark different schemas.

**Comment by bbakersmith** [comment]
"Completed" LOL
