### ISSUE TITLE
could not compare FeatureViewProjection objects

### ISSUE THREAD

**Issue by weitian** [feast-dev/feast#2933]
The comparison of FeatureView objects fails before there is no override of method ``__eq__(self, other)`` in FeatureViewProjection

- Version: 0.22.0
- Platform:
- Subsystem:

**Comment by woop** [comment]
Thanks for raising this @weitian!

Would you mind providing a way for us to reproduce the problem? What led to this comparison being needed?

**Comment by weitian** [comment]
https://github.com/feast-dev/feast/blob/bdeb4aeaf2a5cfa144a65cc84f7bfb26e3077e7a/sdk/python/feast/base_feature_view.py#L139

**Comment by kevjumba** [comment]
@weitian Why are you comparing base feature view?
