### ISSUE TITLE
Add metadata when retrieving feature from PostgreSQLSource

### ISSUE THREAD

**Issue by mshka** [feast-dev/feast#2937]
## Expected Behavior 
Can `create_saved_dataset` with `PostgreSQLRetrievalJob`

## Current Behavior
Trying to `create_saved_dataset` with `PostgreSQLRetrievalJob` fails with `ValueError: RetrievalJob must contains metadata. Use RetrievalJob produced by get_historical_features` 

the retrieval does not contain metadata

## Steps to reproduce
```
store = FeatureStore(repo_path=".")

job = store.get_historical_features(
    entity_df=
    features=store.get_feature_service("FEATURE WITH PostgreSQLSource")
)

store.create_saved_dataset(
    from_=job,
    name='name',
    storage=SavedDatasetFileStorage(
        path="data.parquet"
        )
)
```
### Specifications

- Version: 0.22
- Platform: mac os
- Subsystem:

**Comment by mshka** [comment]
if we manually set the metadata on the job it fails on different error:

```
retrieval_job._metadata = RetrievalMetadata(
    features=["all:all"],
    keys=["all:all"],
    min_event_timestamp=datetime.now() - timedelta(days=365),
    max_event_timestamp=datetime.now()
)
```

```bash
 File "feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py", line 202, in pull_all_from_table_or_query
    assert isinstance(data_source, PostgreSQLSource)
AssertionError
```

**Comment by achals** [comment]
@mshka correct, I think this will require a change to implement the `metadata()` method in `PostgreSQLRetrievalJob` for this to work as expected. Happy to review PRs!

For the second error, we'd need more context (stack trace, code snippet, etc) to help debug.

**Comment by TaherehFarrokhi** [comment]
This error also happened for  MsSqlServerSource too
