### ISSUE TITLE
Build feast wheel for ppc64le: This does not look like a platform wheel

### ISSUE THREAD

**Issue by mgiessing** [feast-dev/feast#2973]
I'm trying to compile a feast wheel for ppc64le but got stuck when I try to run `auditwheel`

## Expected Behavior 
It should work without issue as many other wheels do :)

## Current Behavior
Everything works until I want to package the wheel (use auditwheel)

## Steps to reproduce (manually)

I did this on ppc64le, but I also checked on x86 and the same error occurs (just replace power arch with x86 arch)

```bash
docker run -ti quay.io/pypa/manylinux_2_28_ppc64le

##prereqs to build feast
dnf install golang -y
dnf install python3-devel -y

##feast and python version
rel=v0.22.1
ver=cp38-cp38

export PATH=/opt/python/${ver}/bin/:$PATH 
git clone -b ${rel} https://github.com/feast-dev/feast.git && cd feast
make install-protoc-dependencies
make install-go-proto-dependencies
make install-go-ci-dependencies

/opt/python/${ver}/bin/python3 setup.py bdist_wheel
[...]

[root@7dfb95af30eb feast]# auditwheel repair --plat manylinux2014_ppc64le dist/feast-0.22.1-cp38-cp38-linux_ppc64le.whl 
INFO:auditwheel.main_repair:Repairing feast-0.22.1-cp38-cp38-linux_ppc64le.whl
INFO:auditwheel.main_repair:This does not look like a platform wheel
```

### Specifications

- Version: Feast v0.22.1
- Platform: manylinux_2_28_ppc64le (Almalinux 8.6)
- Subsystem: docker

I also tried manylinux2014, but the same error occurs.

**Comment by kevjumba** [comment]
Hello! I suggest you take a look at how we build our wheels in our release workflow here https://github.com/feast-dev/feast/blob/master/.github/workflows/build_wheels.yml

**Comment by mgiessing** [comment]
Thanks Kevin, I forgot to export `COMPILE_GO=True` which then enabled the go build and the "full" wheel. Thanks!
