### ISSUE TITLE
Getting the latest X records

### ISSUE THREAD

**Issue by lethrez** [feast-dev/feast#2978]
**Is your feature request related to a problem? Please describe.**
I'm often finding with feature stores I'm looking to get the last 10 rows. 
A simple example (following some feast dev samples 😁) if we wanted to the driver weight for the last 20 races in both an online/offline setting.

Is this possible for feast?
It's possible to get the records via timestamp etc but often not clear via recency.

**Describe the solution you'd like**
Ability to get latest X records for a particular entity

**Describe alternatives you've considered**
- structuring data as each row containing the data of the last 10 rows (data duplication)
- structuring as a feature view that queries to get the latest 20. Means we end up having different feature views for training and online. (most viable approach I can see using feast)

**Comment by adchia** [comment]
I think with Feast:
- for offline features, you can probably structure a SQL query (for the entity dataframe) to generate that. See the "How to: retrieve offline features for batch scoring" section in https://docs.feast.dev/getting-started/concepts/feature-retrieval
- for online features, a normal practice is probably to create an aggregation and push that to the online store. Feast doesn't really support this today though and would need you to do a transformation (e.g. aggregating across the last X records) to produce a record that then gets ingested via the **push api** or **materialization**

**Comment by lethrez** [comment]
Thanks @adchia, more of less the approach I ended up using.
- offline stores just store the full history via timestamp
- online store either aggregates and materialisation or has a model refreshed at an interval

Could be an interesting feature to look into at some point.
