### ISSUE TITLE
Request for more information about spark offline store

### ISSUE THREAD

**Issue by niklasvm** [feast-dev/feast#2979]
Good day

I am currently exploring using the spark offline store. In the [docs](https://docs.feast.dev/reference/offline-stores/spark) it mentions:

> This Spark offline store still does not achieve full test coverage and continues to fail some integration tests when integrating with the feast universal test suite. Please do NOT assume complete stability of the API.

Where can I get more detail around the test coverage and failing integration tests?

I am interested in leveraging spark mainly due to:
1. its ability to handle data sets with large numbers of columns (> 1500). Redshift unfortunately limits tables.
1. being able to run on scalable infrastructure like EMR on EKS.

I am also eager to contribute to the project.

Regards
Niklas

**Comment by kevjumba** [comment]
Hey @niklasvm, I recommend you join our slack channel to ask these questions but take al ook at this issue https://github.com/feast-dev/feast/issues/2387. We currently have around 10 integration tests that center around protobuf failing. If you have any other questions please refer to the Slack and ask in the #feast-development channel.

**Comment by niklasvm** [comment]
Thank you @kevjumba
