### ISSUE TITLE
Snowflake source warehouse field is unused

### ISSUE THREAD

**Issue by sfc-gh-madkins** [feast-dev/feast#2981]
## Expected Behavior

Id expect if I defined a warehouse source that warehouse would be used for inference functions attached to the source. 

## Current Behavior

Source uses offline store credentials

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution

I think we remove warehouse from snowflake source as source and offline store are currently intertwined

you can either define a query or a database.schema.table path

**Comment by achals** [comment]
Yeah this is strange behaviour. If we keep the warehouse field in the source it should take precedence, otherwise we can remove the field altogether. I'm fine either way.

**Comment by sfc-gh-madkins** [comment]
Until Feast supports a framework where any source can be fed into any offlinestore, it makes sense to remove it. If we wanted this to take precedence, in theory warehouse wouldnt be enough, we would need to add another entire set of snowflake credentials. (makes no sense)

**Comment by sfc-gh-madkins** [comment]
bump

**Comment by sfc-gh-madkins** [comment]
@katyhaynie-snowflake can you knock this out?
