### ISSUE TITLE
Feast UI breaks with savedDatasets

### ISSUE THREAD

**Issue by eso-exs** [feast-dev/feast#2996]
I'm encountering an issue with Feast UI which stops working after I create a Dataset in Snowflake. This is the console error that I am seeing:
```
query.js:356 ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "savedDatasets",
      0,
      "spec",
      "storage",
      "fileStorage"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "savedDatasets",
      0,
      "spec",
      "featureService"
    ],
    "message": "Required"
  }
]
    at yk (index.mjs:449:23)
    at n.value (index.mjs:561:16)
    at n.value (index.mjs:541:29)
    at useLoadRegistry.ts:35:47
```

**Comment by AlexEijssen** [comment]
Hi, I'm experiencing the same issue when testing my implementation of Postgres. If you look at the zod parser it expects the values you're missing here: https://github.com/feast-dev/feast/blob/master/ui/src/parsers/feastSavedDataset.ts
I tested it locally making those values optional and it works, but it will take me some time to submit my PR for this issue.
