### ISSUE TITLE
get_historical_features(features = feature_service, entity_df = entity_df     ).to_df() ; dtypes

### ISSUE THREAD

**Issue by Christoph-Wu** [feast-dev/feast#2997]
## Expected Behavior 
returns a pd df with requested data 
## Current Behavior
returns empty df or throws errors referring to .to_df() and conflicting dtypes at merge 
- entity_df contains datetime[64], string and int64 (tried also datetime[64], int64 and int64) 

### Specifications

- Version: feast 0.22.1
- Platform: Windows 10
- Subsystem: Python 3.10

## Possible Solution
- fix "get_historical_features().to_df()"  or providing a bit more documentation on its use would be much appreciated  ! 
 Thank you :-)

**Comment by felixwang9817** [comment]
@Christoph-Wu thanks for reporting this! could you share more details (e.g. full stack trace, and ideally the feature repo + data that caused this error) so we can try to reproduce this error?

**Comment by kevjumba** [comment]
@Christoph-Wu Refer to this [ issue](https://github.com/feast-dev/feast/issues/2476). We don't officially support windows and don't plan on supporting windows in the near future!

**Comment by keer139206** [comment]
I am getting below error while loading features to Pandas df

ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Parse error at line: 14, column: 33: Incorrect syntax near 'ID'. (103010) (SQLExecDirectW)")

[SQL: 
/*
 Compute a deterministic hash for the `left_table_query_string` that will be used throughout
 all the logic as the field to GROUP BY the data
*/

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
Cell In [24], line 13
      1 sql_job = fs.get_historical_features(
      2     entity_df="SELECT * FROM op",
      3     features=[
   (...)
     10     ],
     11 )
---> 13 training_df = sql_job.to_df()
     14 training_df.head()


But i dont see any syntax error
