### ISSUE TITLE
Error: 'ui' command not found

### ISSUE THREAD

**Issue by Joshwlks** [feast-dev/feast#3010]
Have followed the first few steps of the feast installation process, after using `feast ui` I get an error stating that the 'ui' command is not found.

`feast --help` returns a list of commands without the ui command too.

**Comment by adchia** [comment]
what version are you on? Still works when I run it at least

**Comment by Joshwlks** [comment]
Was using latest version (0.23.0) when I first had the problem, then I tried to downgrade as my colleague was not getting the issue on version 0.18.1 but now the issue remain follows me no matter which version I am using lol. Got my colleague to test version 0.23.0 and the exact same thing happened in her case too.

**Comment by adchia** [comment]
o.O I am not sure why this would happen and can't really repro

Does it work if you pip install directly from the master GitHub repo? 

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/cli.py#L141 has shown the ui command there and i can also locally see the help showing up in `feast --help`

**Comment by Joshwlks** [comment]
Hmm very strange, the version of cli.py I have on my local machine is missing some lines from the one you linked in the github... no idea how that may have happened as all I did was pip install feast. Also interesting that my colleague reproduced the same problem after upgrading to the latest version.

Hopefully using the cli.py file from the github should solve the issue, else I will reinstall from directly as you suggested. Many thanks!

**Comment by kevjumba** [comment]
can you try installing feast 0.22.2 instead?
