### ISSUE TITLE
feast ui not working behind proxy

### ISSUE THREAD

**Issue by bskbgood** [feast-dev/feast#3011]
## Expected Behavior 
Feast UI should be able to load up behind proxy

## Current Behavior
Feast UI not loaded behind proxy

### Specifications

- Version: 0.23.0
- Platform: Linux
- Subsystem:

## Possible Solution
Allow user to pass root_path when initialize FastAPI. 

E.g.
```
from fastapi import FastAPI, Request

app = FastAPI(root_path="/api/v1")


@app.get("/app")
def read_main(request: Request):
    return {"message": "Hello World", "root_path": request.scope.get("root_path")}
```

**Comment by adchia** [comment]
would you mind contributing a fix for this? Thanks!
