### ISSUE TITLE
`feast serve --go` command broken

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#3038]
## Steps to reproduce

See more details at this Slack [thread](https://tectonfeast.slack.com/archives/C01MSKCMB37/p1659697557773299).

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by phil-park** [comment]
I am also having the same issue. 

Version: 0.23.1
Platform: Mac OS (M1, ARM) 
Subsystem: Python 3.9.13


'feast go server' doesn't support m1 architecture?
