### ISSUE TITLE
feast materialize-incremental throws a syntax error 

### ISSUE THREAD

**Issue by bhnaman** [feast-dev/feast#3043]
## Expected Behavior 
I am unable to load the features incrementally into Dynamodb online store. Offline store in Redshift - and it seems to throw a redshift query syntax error when I do a feast materialize-incremental $CURRENT_TIME

## Current Behavior
'Error': 'ERROR: syntax error at or near ","\n  Position: 207',

### Specifications

- Version: AWS
- Platform: Feast SDK Version: "feast 0.23.0"

**Comment by achals** [comment]
@bhnaman Can you attach your feature repo and feature_store.yaml?
