### ISSUE TITLE
can't retrieve specific field from feature service 

### ISSUE THREAD

**Issue by jungyuneum** [feast-dev/feast#3075]
## Expected Behavior 

```
from driver_ratings_feature_view import driver_ratings_fv
from driver_trips_feature_view import driver_stats_fv

driver_stats_fs = FeatureService(
    name="driver_activity",
    features=[driver_stats_fv, driver_ratings_fv[["lifetime_rating"]]]
)
```
If I define my feature service as above, 
it should return **all** fields of driver_stats_fv and **lifetime_rating** field from driver_ratings_fv. 

## Current Behavior
I get **all** fields defined in feature views even though I specify a certain field. 
Could you please check if this is the right behavior of feature service? 

### Specifications

- Version: feast 0.23.1
- Platform: Python3.8
- Subsystem:

**Comment by felixwang9817** [comment]
hey @jungyuneum thanks for reporting this bug! could you share your full feature repo (specifically, the definitions of `driver_ratings_fv` and `driver_stats_fv`) so we can repro this issue?

**Comment by felixwang9817** [comment]
quick update here: managed to repro this issue and should be able to get a fix out soon!

**Comment by jungyuneum** [comment]
Hi @felixwang9817 I just checked this comment. Really need to get this fixed 👍  Thank you so much!
