### ISSUE TITLE
Add Snowflake as a registry

### ISSUE THREAD

**Issue by sfc-gh-madkins** [feast-dev/feast#3086]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by achals** [comment]
It should be doable to use https://pypi.org/project/snowflake-sqlalchemy/ along with https://docs.feast.dev/tutorials/using-scalable-registry

**Comment by sfc-gh-madkins** [comment]
bump
