### ISSUE TITLE
[Java]: Registry storage postgresql isn't unsupported in Java Kubernetes

### ISSUE THREAD

**Issue by vicolby** [feast-dev/feast#3100]
## Expected Behavior 
postgresql registry should be supported when deploying feast on k8s
## Current Behavior
postgresql registry is not supported when deploying feast on k8s
## Steps to reproduce
Deploy feast on kubernetes with application-override.yaml:
`
feast:
  registry: postgresql://....
  registryRefreshInterval: 0
  transformationServiceEndpoint: transformation-service:6566
  activeStore: online
  stores:
    name: online
    type: REDIS 
    config:
      host: redis-master
      port: 6379

grpc:
  server:
    port: 6566
`
### Specifications
apiVersion: v1
dependencies:
- alias: feature-server
  condition: feature-server.enabled
  name: feature-server
  repository: https://feast-helm-charts.storage.googleapis.com
  version: 0.23.2
- alias: transformation-service
  condition: transformation-service.enabled
  name: transformation-service
  repository: https://feast-helm-charts.storage.googleapis.com
  version: 0.23.2
- condition: redis.enabled
  name: redis
  repository: https://charts.helm.sh/stable
  version: 10.5.6
description: Feature store for machine learning
home: https://feast.dev/
keywords:
- machine learning
- big data
- mlops
name: feast
sources:
- https://github.com/feast-dev/feast
version: 0.23.2

## Possible Solution
Here is the error
![image](https://user-images.githubusercontent.com/110413232/185379735-009d8f26-b318-4228-9efd-9c7495292fd8.png)

Add postgresql here https://github.com/feast-dev/feast/blob/master/java/serving/src/main/java/feast/serving/service/config/RegistryConfigModule.java

**Comment by kevjumba** [comment]
Hey @vicolby currently postgresql is not supported in the Java sdk.

**Comment by pengyuan** [comment]
i get the same error
