### ISSUE TITLE
Python server is only creating 1 worker, how can we create multiple workers for efficiently utilising all cpu

### ISSUE THREAD

**Issue by Akashh17** [feast-dev/feast#3111]
## Expected Behavior 

Python server is only creating 1 worker, how can we create multiple workers for efficiently utilising all cpu

## Current Behavior

Currently python server creates only 1 worker, so it affects the latency numbers for retrieving feature values from online store.

### Specifications

- Version : feast 0.23.0
- Platform : Python 3.9.2 
- Subsystem:

**Comment by kevjumba** [comment]
per @adchia => docker containers recommend only 1 worker per container, but contributions in this area are welcome!
