### ISSUE TITLE
abilty to query stores without copying feature_store.yaml around

### ISSUE THREAD

**Issue by cburroughs** [feast-dev/feast#3134]
**Is your feature request related to a problem? Please describe.**

Right now to use feast as a client (that is a data scientist who wants to call `get_historical_features`, not someone running `feast apply`) you still need to copy of `feature_store.yaml`.  Since it is a single small file, distributing it as a package seems excessive, but copies, symlinks, and submodules all have obvious awkward downsides.  For registries hosted on shared infrastructure (such as an S3 bucket), I'd like to be able to just point the clients at the same bucket.

**Describe the solution you'd like**
Something like
```
store = feast.FeatureStore(config=s3://my-bucket/feature_store.yaml') # feast apply uploads this
```

or
```
store = feast.FeatureStore(registry= 's3://my-bucket/registry.pb')
```

**Describe alternatives you've considered**
I don't have an opinion between a convention of uploading `feature_store.yaml` as an object, versus extracting equivalent data from the registry protobuf (which I assume already has most everything).

**Comment by sfc-gh-madkins** [comment]
You can do something like this:

```
  repo_config = RepoConfig(
    registry=RegistryConfig(path="s3://[YOUR BUCKET]/registry.pb"),
    project="feast_demo_aws",
    provider="aws",
    offline_store="file",
    online_store=DynamoDBOnlineStoreConfig(region="us-west-2")
  )
  store = FeatureStore(config=repo_config)
  store.materialize_incremental(datetime.datetime.now())
```

A data scientist for example just need to put in their own credentials

**Comment by seb2704** [comment]
Is there anywhere a documentation how to use RepoConfig? How do I use RepoConfig withe a Postgresql database for the registry, offline stor and online store?

**Comment by cburroughs** [comment]
Which commit 'completed' this issue?

[This example](https://github.com/feast-dev/feast/issues/3134#issuecomment-1227833744) demonstrates that one can instantiate a `RepoConfig` as python code but that still leaves the use cases -- how to share the contents of said config -- unaddressed.

 (In other words in the example `project`, `provider`,  `offline_store`, and `online_store` do *not* get their configuration from declaring `registry=RegistryConfig(path="s3://[YOUR BUCKET]/registry.pb")`.

**Comment by cburroughs** [comment]
Similar request at #3454

**Comment by franciscojavierarceo** [comment]
@ntkathole @jyejare

**Comment by jyejare** [comment]
@franciscojavierarceo Yes, I think we need to document this, the Repoconfig is the way to go here
