### ISSUE TITLE
Support 64-bit hash

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#3142]
The Redis online store implementation currently uses the murmur3 32-bit hash. As noted in this [discussion](https://contributors.scala-lang.org/t/murmur-hash-conflicts-when-hashing-many-items/1506), there is a reasonably high chance of collisions when using 32-bit hashes (this has nothing to do with the murmur3 implementation). Feast should support 64-bit hashes.

**Comment by achals** [comment]
This would probably require a bump in the entity_key_serialization_version since the hash change would be non-backwards-compatible.

**Comment by flyingclouds1985** [comment]
I think the fix may not need to be backwards-compatible. 
the keys in redis will be different anyway (the old entity in cache will expire naturally), the fix just need both offline-writing&online-fetching being consistent.
