### ISSUE TITLE
error: "Snowflake Data Type is not supported" on "NUMBER" with non-zero scale

### ISSUE THREAD

**Issue by cburroughs** [feast-dev/feast#3146]
## Expected Behavior 

feast plan/apply completed without error in version `0.23.0` and I was able to query with `get_historical_features`.

## Current Behavior
With the snowflake datatype ` NUMBER(38,6)` I get:
```
NotImplementedError: The following Snowflake Data Type is not supported: DECIMAL -- Convert to DOUBLE
```

## Steps to reproduce

 * `$ feast init -t snowflake`
 * Alter the table like so:
 ```
alter table SNOWY_FEAST.PUBLIC."amazed_dane_feast_driver_hourly_stats" add column temp_conv_rate NUMBER(38,6);
update SNOWY_FEAST.PUBLIC."amazed_dane_feast_driver_hourly_stats" set temp_conv_rate = "conv_rate";
alter table SNOWY_FEAST.PUBLIC."amazed_dane_feast_driver_hourly_stats" drop column "conv_rate";
alter table SNOWY_FEAST.PUBLIC."amazed_dane_feast_driver_hourly_stats" rename column temp_conv_rate to "conv_rate";
 ```
 * `$ feast apply`
 ```
Traceback (most recent call last):
...
    raise NotImplementedError(
NotImplementedError: The following Snowflake Data Type is not supported: DECIMAL -- Convert to DOUBLE
```
 

### Specifications

- Version: `Feast SDK Version: "feast 0.24.0"`
- Platform: x86_64 on Python 3.10.5
- Subsystem: Linux 5.4.203-

**Comment by achals** [comment]
I think this is intentional cc @sfc-gh-madkins

**Comment by sfc-gh-madkins** [comment]
@cburroughs my advice for right now would be to cast this to type double/float, as the error recommends. Let me see if I can get NUMBER with scale to work.

**Comment by cburroughs** [comment]
I installed from `master` to test it out.  Looks good; thank you!
