### ISSUE TITLE
FeatureStore repo_path to a Object Store, for exmaple S3

### ISSUE THREAD

**Issue by seb2704** [feast-dev/feast#3158]
According to "Running Feast in production" in the docs, it's commen to provide a local copy of the feature_store.yaml file to a pipeline. 
I think it would be nice if there is an option to pass a URI of an object store, like S3, to access this file.

**Comment by cburroughs** [comment]
Similar to -- I think -- #3134

**Comment by seb2704** [comment]
Thank you, in my case the Registry, Online Store and Offline Store are saved in Postgresql. How do i use RepoConfig with Postgresql?

**Comment by sfc-gh-madkins** [comment]
Look at this:

```
  repo_config = RepoConfig(
    registry=RegistryConfig(path="s3://[YOUR BUCKET]/registry.pb"),
    project="feast_demo_aws",
    provider="aws",
    offline_store="file",
    online_store=DynamoDBOnlineStoreConfig(region="us-west-2")
  )
  store = FeatureStore(config=repo_config)
  store.materialize_incremental(datetime.datetime.now())
```

**Comment by mvoitko** [comment]
@sfc-gh-madkins what about Helm chart deployment?
