### ISSUE TITLE
Improper namespacing when retrieving features with conflicting dependent ODFV feature vs a requested feature

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#3165]
## Current Behavior

If a user erroneously specifies a FeatureService like below (note in particular the ODFV source with a `fv_with_feature_X` and the `fv_2_with_feature_X`)

```python
@on_demand_feature_view(
    sources=[fv_with_feature_X, input_request],  
    schema=[
        Field(name="conv_rate_plus_val1", dtype=Float64),
        Field(name="conv_rate_plus_val2", dtype=Float64),
    ],
)
def transformed_conv_rate_fresh(inputs: pd.DataFrame) -> pd.DataFrame:
    df = pd.DataFrame()
    df["conv_rate_plus_val1"] = inputs["conv_rate"] + inputs["val_to_add"]
    df["conv_rate_plus_val2"] = inputs["conv_rate"] + inputs["val_to_add_2"]
    return df

driver_activity_model = FeatureService(
    name="driver_activity_model",
    features=[fv_2_with_feature_X, transformed_conv_rate_fresh],
)
```

and calls `get_online_features(...)` (defaulting to `full_feature_names=False'), then retrieval can result in incorrect features because Feast cannot distinguish between which FV table to retrieve from for the same feature name `feature_X`

## Expected Behavior

Either:
- Feast under the hood uses `full_feature_names=True` and intelligently removes the unnecessary prefix
- Feast throws validation errors when there are conflicts like this (between the source feature view of an on demand feature view and another feature view)

**Comment by adchia** [comment]
Following up here, while there is a conflict in name that we should flag, what's happening here is actually that the feature view the ODFV depends on is actually not the one with the push source. By having two different FV, you have two different online tables, and in that query you actually are fetching from two different SQLite tables

Will update the bug to be more about throwing an error at get_online_features time if there are duplicate feature refs across a FV + an ODFV.
