### ISSUE TITLE
Add Spark materialization engine for parallel, distributed materialization of large datasets.

### ISSUE THREAD

**Issue by ckarwicki** [feast-dev/feast#3167]
**Is your feature request related to a problem? Please describe.**

Current implementation of Spark offline store doesn't have Spark based materialization engine. This makes materialization slow, inefficient and makes Spark offline store not very useful since materialization is still happening in driver node and will be limited by its resources.

**Describe the solution you'd like**
Spark based materialization engine.

**Describe alternatives you've considered**
BytewaxMaterializationEngine  - it relies on `offline_job.to_remote_storage()` but `SparkRetrievalJob` doesn't support `to_remote_storage()`. Also, would rather use one stack for job execution (preferably Spark) instead of two. 

**Additional context**
`spark_materialization_engine` would make Feast highly scalable and leverage full Spark potential. Right now it it very limited.

**Comment by adchia** [comment]
Hey! Thanks for the FR. Are you in the Slack? There have been recent discussions in the #feast-development Slack about this topic

**Comment by niklasvm** [comment]
Hi @ckarwicki

I'm taking a look at potential designs for a `SparkBatchMaterializationEngine`. I've got an open PR that implements the `to_remote_storage` method for a `SparkRetrievalJob` in the mean time. I currently see 3 solutions:

(1) The default `LocalMaterializationEngine` writes the data to the local file system on the driver node and then loops over each parquet file in series. One possible solution is to parallelise this process however the success of this will still be limited by the size of the driver node.

(2) Alternatively, data can be written to remote storage (like S3) and the `LambdaMaterializationEngine` can be used however this requires the use of AWS Lambda.

(3) I don't know if it's possible to parallelise the code from the `LocalMaterializationEngine` to run over the executor nodes.

Any thoughts or ideas?

**Comment by niklasvm** [comment]
Thanks @ckarwicki for the explanation. I have actually gone ahead and implemeted something quite similar in https://github.com/feast-dev/feast/pull/3184 but instead of using `foreachPartition` I've used `applyInPandas`. I'm not sure which is superior.

**Comment by ckarwicki** [comment]
@niklasvm Not sure if we should use `applyInPandas` It is memory intensive and requires full shuffle: https://spark.apache.org/docs/3.2.0/api/python/reference/api/pyspark.sql.GroupedData.applyInPandas.html
```
This function requires a full shuffle. All the data of a group will be loaded into memory, so the user should be aware of the potential OOM risk if data is skewed and certain groups are too large to fit in memory.
```
It works in three steps: Split-apply-combine consists, check this: https://docs.databricks.com/spark/latest/spark-sql/pandas-function-apis.html#grouped-map
```
All data for a group is loaded into memory before the function is applied. This can lead to out of memory exceptions, especially if the group sizes are skewed. The configuration for [maxRecordsPerBatch](https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html#setting-arrow-batch-size) is not applied on groups and it is up to you to ensure that the grouped data fits into the available memory.
```
We should use `foreachPartition()`

**Comment by niklasvm** [comment]
> @niklasvm Not sure if we should use `applyInPandas` It is memory intensive and requires full shuffle: https://spark.apache.org/docs/3.2.0/api/python/reference/api/pyspark.sql.GroupedData.applyInPandas.html
> 
> ```
> This function requires a full shuffle. All the data of a group will be loaded into memory, so the user should be aware of the potential OOM risk if data is skewed and certain groups are too large to fit in memory.
> ```
> 
> It works in three steps: Split-apply-combine, check this: https://docs.databricks.com/spark/latest/spark-sql/pandas-function-apis.html#grouped-map
> 
> We should use `foreachPartition()`

That is very useful, thank you.  I'll update the PR.

**Comment by ckarwicki** [comment]
@niklasvm You should also use [repartition()](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.repartition.html#pyspark.sql.DataFrame.repartition) on df where number of partitions should be number of simultaneous connections (writes) to online store. We can call it without arguments - it will create 200 partitions (number taken from should `spark.sql.shuffle.partitions`). It will be that many simultaneous connections (parallel writes) to Redis. Redis default is 10K connections. You can change it on Redis side if you need more.

**Comment by niklasvm** [comment]
I believe `repartition` will cause a shuffle operation. Here's the DAG that uses `repartition`:

![image](https://user-images.githubusercontent.com/18314300/188547429-f7d904d6-e614-4b86-9dc3-b751db696aba.png)

And without `repartition`:

![image](https://user-images.githubusercontent.com/18314300/188547522-26bb5ee1-6c87-440f-bff9-b831893c67d8.png)

Is the intention to only repartition to a number that redis can handle? Unfortunately `numPartitions` is a required parameter of `repartition`.

Could we use [coalesce()](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.coalesce)?

**Comment by ckarwicki** [comment]
@niklasvm [coalesce()](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.coalesce) should be used when partitioning down. It would be useful to call [repartition()](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.repartition.html#pyspark.sql.DataFrame.repartition) since it would allow have control on the parallelism of materialization and simultaneous writes. They are saying it should be possible to call it without arguments:
```
numPartitions : int
can be an int to specify the target number of partitions or a Column. If it is a Column, it will be used as the first partitioning column. If not specified, the default number of partitions is used.
```

**Comment by niklasvm** [comment]
Thanks @ckarwicki. I have tested running this without a parameter and it fails.
