### ISSUE TITLE
Support for multiple, scalable data sources - Spark based data sources.

### ISSUE THREAD

**Issue by ckarwicki** [feast-dev/feast#3168]
**Is your feature request related to a problem? Please describe.**

Would like to have support for multiple, configurable Spark based data sources. That would allow sourcing features from multiple data stores. We would like to source features from S3, Snowflake, Postgres and have consistent feature repository. 

**Describe the solution you'd like**

Spark source support for configuring things line jdbc driver, database connection string, query.  Each source could then point to different data store and get data efficiently and asynchronously.

**Describe alternatives you've considered**
No solution yet to be able to source from multiple data stores.

**Additional context**

**Comment by cburroughs** [comment]
See also #2121.
