### ISSUE TITLE
Error while deploying a feature store in python

### ISSUE THREAD

**Issue by dsenapaty** [feast-dev/feast#3177]
## Current Behavior
[ERROR] FeastModuleImportError: Could not import module 'feast.infra.online_stores.snowflake' while attempting to load class 'SnowflakeOnlineStoreConfig'

**Comment by felixwang9817** [comment]
@dsenapaty could you share a more complete stack trace?

**Comment by sfc-gh-madkins** [comment]
@dsenapaty did you get this working?
