### ISSUE TITLE
Asynchronous online data retrieval from Redis.

### ISSUE THREAD

**Issue by mdrijwan123** [feast-dev/feast#3185]
**Is your feature request related to a problem? Please describe.**
We wanted to use feast for our project for online data retrieval in a Rest API, but feast API server gives the json output and we need to parse it first and then make final data to be feed into model this json parsing was increasing the latency. We also tried with feast direct sdk but there the internal code is total synchronous and inferencing for concurrent request was taking much time and again latency issue creates a problem.

**Describe the solution you'd like**
To minimize the code and fast data retrieval we have use direct Redis because latency was critical for us. Also we used **aioredis** rather than **redis** library in python to server concurrent request, these are not present in latest code in feast, there should be some option to use asynchronous way for all the function in feast to read the data so if we have to read multiple time in some web API from Redis via feast then concurrent request can work seamlessly. 

**Describe alternatives you've considered**
For now we written plain code to read directly from Redis without feast layer but feast can add to other application in any ML project. Having this feature can greatly help.

**Comment by adchia** [comment]
cc @DvirDukhan

**Comment by DvirDukhan** [comment]
@adchia 
maybe we need to discuss async retrieval/ingest APIs. We have async cluster support in redis-py since 4.3.0 https://github.com/redis/redis-py/releases/tag/v4.3.0
