### ISSUE TITLE
Materializing subsets of features to the online store

### ISSUE THREAD

**Issue by niklasvm** [feast-dev/feast#3196]
**Is your feature request related to a problem? Please describe.**
Hosting an online store for a large number of entities and features can be very expensive.
Materializing large data sets to the online store can also be expensive and time consuming.

My specific use case involves storing large data sets in parquet with feature views consisting of 1000s of features.

Currently all features in a feature view are materialized to the online store.  Standard modelling practices usually involve training a model on the full set of features. A deployed model usually only relies on a subset of the original features. This means thats the online store ends up only serving subsets of features during inference.

**Describe the solution you'd like**
Functionality to
1. represent a subset of features either directly or through the use of feature services
2. Only materialize this subset to the online store when calling `feast materialize`
3. Default behaviour could be to still materialize all features ensuring backward compatibility

**Describe alternatives you've considered**
None

**Additional context**

**Comment by adchia** [comment]
We've discussed this partially in the Feast Development Biweekly (https://docs.google.com/document/d/1zUbIWFWjaBEVlToOdupnmKQwgAtFYx41sPoEEEdd2io/edit#)
