### ISSUE TITLE
FR: Use Snowpipe Streaming for streaming ingest when using Snowflake

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#3212]
Is your feature request related to a problem? Please describe.

I haven't tested this, but right now using the push API to push features into Snowflake stages into a file. When using this from a stream, I can imagine this would run into throughput issues.

Describe the solution you'd like

A better solution is probably to detect if the row count is small, then using Snowpipe Streaming makes more sense (for both writing to offline and writing to online)

Describe alternatives you've considered

Additional context

**Comment by sfc-gh-madkins** [comment]
bump

**Comment by sfc-gh-madkins** [comment]
bump
