### ISSUE TITLE
Import error while running the lambda server

### ISSUE THREAD

**Issue by gourav1298** [feast-dev/feast#3215]
## Expected Behavior 
It should return the online features stored in my DynamoDB.
## Current Behavior
Currently when I am giving a post request to the lambda server endpoint, its giving the error as follows:
[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'feast.protos'
Traceback (most recent call last):
## Steps to reproduce
I am using the '[feast-aws-credit-scoring-tutorial](https://github.com/feast-dev/feast-aws-credit-scoring-tutorial)' code sample 
here I am just deploying it on lambda server

## Possible Solution
I think there may be a issue with the image that is pulling from the hub, and the dependencies are missing there.

**Comment by adchia** [comment]
What image does it say you're using? (and what version of Feast are you on?)

You did follow https://docs.feast.dev/reference/feature-servers/alpha-aws-lambda-feature-server#deployment right?
