### ISSUE TITLE
Feast cannot be installed in Python 3.10

### ISSUE THREAD

**Issue by jkruzek** [feast-dev/feast#3248]
## Expected Behavior 
A user should be able to install Feast in a Python 3.10 environment. In setup.py it shows that `REQUIRES_PYTHON = ">=3.7.0"` which means it should work for Python 3.10

## Current Behavior
Pip install fails when it hits the `mmh3` package since it does not support Python 3.10. This package hasn't been updated in over a year so it doesn't look like they will support Python 3.10 any time soon.

## Steps to reproduce
Create a virtual environment with Python 3.10 and run `pip install feast`

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
Use a different hashing library than `mmh3`

**Comment by achals** [comment]
@jkruzek what error do you get when you try to install feast or mmh3 on python 310? I just tried and was able to install using the sdist.

```
[26/09/22 9:32:55] (python-3.10.6) ~/tecton/feast   achal/owners 
$ pip install mmh3
Collecting mmh3
  Downloading mmh3-3.0.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for mmh3, since package 'wheel' is not installed.
Installing collected packages: mmh3
  Running setup.py install for mmh3 ... done
Successfully installed mmh3-3.0.0

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
[26/09/22 9:33:46] (python-3.10.6) ~/tecton/feast   achal/owners 
$ python -c "import mmh3; print(mmh3.hash('abc'))"
-1277324294
[26/09/22 9:33:54] (python-3.10.6) ~/tecton/feast   achal/owners 
$
```

**Comment by jkruzek** [comment]
@achals Here's my error
```
  Building wheel for mmh3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'mmh3' extension
      creating build
      creating build/temp.macosx-12-x86_64-cpython-310
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/jared/Data-Utilities/venvFeast/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c MurmurHash3.cpp -o build/temp.macosx-12-x86_64-cpython-310/MurmurHash3.o
      clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmh3
  Running setup.py clean for mmh3
Failed to build mmh3
Installing collected packages: mmh3, feast
  Running setup.py install for mmh3 ... error
  error: subprocess-exited-with-error
```

There's also this open PR on that repo: https://github.com/hajimes/mmh3/pull/35

Maybe its due to running it on my specific Mac?

**Comment by achals** [comment]
@jkruzek Hmmm, can you run this command to see what version of xcode you have installed?
```
/usr/bin/xcodebuild -version
```

Could you update it to the latest version? The error implies that clang isn't able to install on your mac (which seems to be an M1) and an outdated/missing xcode is prob the reason why.

**Comment by jkruzek** [comment]
I'm running on the old Macbooks with Intel chip. When i ran that command I got

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by jkruzek** [comment]
I tried running this in a Docker image with Python 3.10 as the base image and it was successful. So it appears that this is just an issue with my local Mac setup. Thanks for helping! I think we can close this issue

**Comment by seunggabi** [comment]
I front same issue.
