### ISSUE TITLE
feast-feature-server ModuleNotFoundError: No module named 'feast.embedded_go'

### ISSUE THREAD

**Issue by jaeoheeail** [feast-dev/feast#3265]
## Expected Behavior 
Install [feature-server helm-chart](https://github.com/feast-dev/feast/tree/master/infra/charts/feast-feature-server), I expect to see the pod running and not have any module import errors

## Current Behavior
feature-server is unhealthy.
```
Traceback (most recent call last):
  File "/usr/local/bin/feast", line 5, in <module>
    from feast.cli import cli
  File "/usr/local/lib/python3.8/site-packages/feast/__init__.py", line 7, in <module>
    from feast.infra.offline_stores.bigquery_source import BigQuerySource
  File "/usr/local/lib/python3.8/site-packages/feast/infra/offline_stores/bigquery_source.py", line 8, in <module>
    from feast.feature_logging import LoggingDestination
  File "/usr/local/lib/python3.8/site-packages/feast/feature_logging.py", line 8, in <module>
    from feast.embedded_go.type_map import FEAST_TYPE_TO_ARROW_TYPE, PA_TIMESTAMP_TYPE
ModuleNotFoundError: No module named 'feast.embedded_go'
```

## Steps to reproduce
Use the instructions to deploy feature-server using helm: https://github.com/feast-dev/feast/tree/master/infra/charts/feast-feature-server

Create a file called feature_store.yaml with the content below:

```
project: test_feast
provider: aws
online_store:
  type: dynamodb
  region: xxx
registry:
  registry_type: sql
  path: postgresql://user:[password@x.x.x.x](mailto:password@x.x.x.x):5432/registry
offline_store: null
entity_key_serialization_version: 2
```

Run: `helm install feast-feature-server feast-charts/feast-feature-server --set feature_store_yaml_base64=$(base64 feature_store.yaml)`

### Specifications

- Version: Chart version 0.25.1
- Platform: Kubernetes version 1.22.11
- Subsystem:

## Possible Solution
Add `__init__.py` file at https://github.com/feast-dev/feast/tree/master/sdk/python/feast/embedded_go

**Comment by adchia** [comment]
@kevjumba Probably best to revert Felix's change (since otherwise the docker image becomes unnecessarily large with the go toolchain) and instead ensure we push the docker images after the sdk is released
