### ISSUE TITLE
`Feature.proto` should have a description field

### ISSUE THREAD

**Issue by chhabrakadabra** [feast-dev/feast#3277]
**Is your feature request related to a problem? Please describe.**

I would like to attach a human-readable description to each field in a feature view. Since data scientists shop for individual features and not feature-views, it's useful to have documentation associated with each feature individually (rather than for the entire feature view). Persisting it here will allow us to surface them in various UIs.

**Describe the solution you'd like**

Similar to `Entity.proto`, we should add a description field to features and store them in the registry.

**Describe alternatives you've considered**

For now, we're just using a `description` tag on each feature. This works, but it's clunky. It also means that in our UI, we have to remove certain tags before showing the raw tags to the users.

**Additional context**

**Comment by achals** [comment]
Yep, this seems like it would be pretty helpful
