### ISSUE TITLE
Does Feast support HTTPS for all communication?

### ISSUE THREAD

**Issue by adamwrobel-ext-gd** [feast-dev/feast#3281]
Does this depend on the DB connector? How to enforce it?

**Comment by achals** [comment]
@adamwrobel-ext-gd what communication are you referring to? Online store? Offline store? Metadata registry?

**Comment by adamwrobel-ext-gd** [comment]
@achals  requesting another look, thanks :)

**Comment by sfc-gh-madkins** [comment]
@adamwrobel-ext-gd this is an interesting question -- HTTPS in general doesnt apply here.

I believe your main concern is, is data encrypted when in transport, ie if I send a dataframe to snowflake or vice versa, is my data exposed? The answer is no, the snowflake python client and snowflake server side encrypts data in transport bebtween the two
