### ISSUE TITLE
Syntax Error for Entity_df SQL Query with Postgres Offline Store

### ISSUE THREAD

**Issue by benaurelschill** [feast-dev/feast#3284]
## Expected Behavior 
SQL statements should be executed without throwing errors. When using pgAdmin with the same query it returns the correct data without throwing any errors. 
## Current Behavior
Throws syntax error 
```python-traceback
SyntaxError: syntax error at or near "SELECT"
LINE 19: SELECT "account_id", "event_timestamp"
         ^
```
## Steps to reproduce
1. Create FeatureStore with Postgres Source 
2. Use historical feature function
``` python

entity_sql = f"""
    
    WITH DATA AS {fs.get_data_source("user_data_source").get_table_query_string()}
    SELECT
        account_id,
        transaction_time as event_timestamp
    FROM DATA
"""
```
``` python

training_df = fs.get_historical_features(
    entity_df= entity_sql,
    features=[
        "transformed_auth_type:used_chip"
    ]
).to_df()
```
### Specifications

- Version: 0.26
- Platform: MAC OSX 
- Subsystem:

**Comment by adchia** [comment]
hm, I'm not sure, but this is the line that generates the query: 

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py#L400

**Comment by benaurelschill** [comment]
@adchia thanks for pointing me to the code.
I adapted the query string to the following. 
```
entity_sql = f"""
    SELECT
        account_id,
        transaction_time as event_timestamp
    FROM (
        {fs.get_data_source("user_data_source").get_table_query_string()} 
    ) AS DATA
"""
```
and it now seems to work 👍

**Comment by adchia** [comment]
glad to hear it! I'm assuming then that the source itself was a reference to a table so it ended up being an invalid CTE.
