### ISSUE TITLE
Clear data from online store

### ISSUE THREAD

**Issue by swapkh91** [feast-dev/feast#3285]
I want to know how can I clear the online store.

The usecase is such that the data in both online and offline store has to be removed and fresh data needs to be loaded. There is no change in the schema, so feature view will remain the same.

Offline store: BigQuery 
Online store: Redis.

I can delete the data from BQ, but how do I clear what is already materialized on Redis?

**Comment by achals** [comment]
Hey @swapkh91 , you can set an entity-level TTL for redis in the feature_store.yaml. https://docs.feast.dev/reference/online-stores/redis

This should look something like this:
```
...
online_store:
  type: redis
  key_ttl_seconds: 604800
...

```

I'll make a PR to add this to the reference docs.

**Comment by swapkh91** [comment]
great, thanks @achals
