### ISSUE TITLE
materialize_incremental pushes entire table when postgres registry is used

### ISSUE THREAD

**Issue by jiewpeng** [feast-dev/feast#3296]
## Expected Behavior 
When calling `store.materialize_incremental()`, only features updated since the previous update should be pushed.

## Current Behavior

It appears that when using a postgres on AWS RDS as the registry, calling `store.materialize_incremental()` always pushes the entire table, despite no changes to the feature view definition, nor the underlying data source. This does not happen when a local file-based registry is used, where calling `store.materialize_incremental()` the first time will push the entire table, but subsequent calls do not appear to do so.

Relevant Slack thread: https://tectonfeast.slack.com/archives/C01MSKCMB37/p1665564214415769

## Steps to reproduce

```python
from feast import Entity, FeatureStore, FeatureView, Field, RepoConfig
from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource


feature_store_config = {
    "project": "test_feast",
    "registry": {
        "registry_type": "sql",
        "path": [REDACTED],
    },
    "provider": "aws",
    "offline_store": {
        "type": "spark",
        "spark_conf": {
            "spark.master": "local[*]",
            "spark.app.name": "feast",
            "spark.ui.enabled": "false",
            "spark.eventLog.enabled": "false",
            "spark.sql.catalogImplementation": "hive",
            "spark.sql.parser.quotedRegexColumnNames": "true",
            "spark.sql.session.timeZone": "UTC",
        }
    },
    "online_store": {
        "type": "dynamodb",
        "region": "ap-southeast-1",
    },
    "entity_key_serialization_version": 2,
}

store = FeatureStore(config=RepoConfig(**feature_store_config))

source = SparkSource(...)  # never tried with other sources, but it should not matter
fv = FeatureView(...)

store.apply([source, fv])

# first materialize should push all the data
store.materialize_incremental(datetime.datetime.now(), feature_views=[fv])

# second materialize should do nothing
store.materialize_incremental(datetime.datetime.now(), feature_views=[fv])
```

The environment where I update the feature store is Databricks, and it is very difficult to use the CLI, so everything is done via the Python SDK. 

If it matters, this is what the setup looks like:

- Platform where we run these commands: Azure Databricks
- Registry: Postgres on AWS RDS
- Offline store: Spark on Azure Databricks
- Online store: AWS DynamoDB

### Specifications

- Version: 0.26.0
- Platform: Azure Databricks, Runtime 10.4 LTS ML (Ubuntu 20.04.4 LTS)

**Comment by adchia** [comment]
Ah I see. What's the rationale for running `apply` here? That means this would not be version controlled. Probably better practice would be to generate a table, and then define in a versioned repo that data source. 

If you _really_ wanted to do this, then I'd check in e.g. `store.list_data_sources()` and `store.list_feature_views()` to see if this data source and feature view exist before applying.

More technical details:
- running `apply` programmatically is not recommended. 
  - It requires an exact equality with a file registry for it to not blow away materialization intervals. 
  - In the SQL registry, @achals can confirm, but I think we will always blow away materialization intervals.
  - The CLI uses a different code path for this (https://github.com/feast-dev/feast/blob/master/sdk/python/feast/cli.py#L509). I could see an argument for making those behaviors consistent.

**Comment by jiewpeng** [comment]
Ah ok I see, it was indeed the `store.apply()` causing issues. I thought it wouldn't actually remove the materialization intervals, but it appears it does. After modifying the code to only call `apply()` if the source/feature view does not exist, `materialize_incremental()` does work as I expect it to.
