### ISSUE TITLE
feast apply command should be able to ignore certain files

### ISSUE THREAD

**Issue by george-kuanli-peng** [feast-dev/feast#3316]
**Is your feature request related to a problem? Please describe.**
I'm using feast in JupyterLab. Running `feast apply` fails with the following message:

```
Traceback (most recent call last):
  File "/usr/local/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)

... skip lines between ...

  File "/usr/lib/python3.8/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.ipynb_checkpoints.example_repo-checkpoint'
```
JupyterLab saves temporary files and feast exists on importing them. I believe the same problem might happen for people using other editors that save temporary files and preserve the `.py` file extension.

**Describe the solution you'd like**
Methods to have feast ignore certain files or directories will help, such as:

- add a commandline option to ignore files
- add ignore section in `feature_store.yaml`
- a separate `.feastignore` file

**Comment by achals** [comment]
A `.feastignore` is already supported - https://docs.feast.dev/reference/feature-repository/feast-ignore#feast-ignore-patterns. Is this what you're looking for?

**Comment by george-kuanli-peng** [comment]
> A `.feastignore` is already supported - https://docs.feast.dev/reference/feature-repository/feast-ignore#feast-ignore-patterns. Is this what you're looking for?

Thank you for pointing that. This is exactly waht I'm looking for.
