### ISSUE TITLE
Cache non file-based registries for python feature server

### ISSUE THREAD

**Issue by sfc-gh-madkins** [feast-dev/feast#3328]
**Is your feature request related to a problem? Please describe.**

A considerable amount of latency occurs when retrieving data from registry when calling ```get_online_features()```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jfli-thu** [comment]
Or  support customize registry in feature_store.yaml firstly ?

**Comment by jfli-thu** [comment]
BTW,  I found that the amount of latency using sql registry may also relate to unnecessary registry update func when [get metadata object](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/registry/sql.py#L799) or [list metadata objects](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/registry/sql.py#L822)  .   @adchia

**Comment by jfli-thu** [comment]
it seems the amount of latency using sql registry may also relate to the unnecessary  feast_metadata update when [get](https://github.com/feast-dev/feast/blob/80712a7cbbc761f2c9874690c6e539660303c9b5/sdk/python/feast/infra/registry/sql.py#L799) or [list](https://github.com/feast-dev/feast/blob/80712a7cbbc761f2c9874690c6e539660303c9b5/sdk/python/feast/infra/registry/sql.py#L822) metadata .

Should that  init func only used by apply_objects?  @adchia
