### ISSUE TITLE
Online store schema documentation inacurate

### ISSUE THREAD

**Issue by bbakersmith** [feast-dev/feast#3330]
## Expected Behavior 
Online store documentation describes the online schema compared to the offline schema. For example, the online store schemas are structured with a row per feature per entity, where in the offline store they are structured with a row per entity.

## Current Behavior
The online store documentation inaccurately describes the online schema as

> The storage schema of features within the online store mirrors that of the original data source.

## Steps to reproduce
Read the documentation: https://github.com/feast-dev/feast/blob/master/docs/getting-started/architecture-and-components/online-store.md#online-store

### Specifications

- Version: v0.26.0, master
- Platform:
- Subsystem:

## Possible Solution
Update the documentation to accurately describe the generated online store schema.

Related issue: https://github.com/feast-dev/feast/issues/2931

**Comment by kevjumba** [comment]
@bbakersmith thanks for raising this issue, Would you be able to add a pr to fix it?

**Comment by bbakersmith** [comment]
We're likely going to use a different tool than Feast because of the issues with materialization scaling. I was looking at writing a custom materialization engine to solve the scaling problems (the Bytewax engine is just not documented or developed enough to use) but issues like this one indicate that it would take a significant effort in reverse engineering to do so.

**Comment by adchia** [comment]
What online store are you looking for? We have some documentation on this in https://github.com/feast-dev/feast/blob/master/docs/specs/online_store_format.md for certain online stores
