### ISSUE TITLE
Add explanation more about feast ui with react, especially in project list part

### ISSUE THREAD

**Issue by dfd19** [feast-dev/feast#3332]
I need more explanation about how to run feast ui with customize with react.

I have read feast/ui/README.md and found out the explanation of "registryPath" in project-list.json is too low. When i try it, i always get error 

```
Error

Error: Unable to properly parse Project List JSON. Check that your project list is formatted properly.
    at new ProjectListError (http://localhost:3000/static/js/bundle.js:34704:24)
    at anticipatedProjectListErrors (http://localhost:3000/static/js/bundle.js:34717:12)
    at http://localhost:3000/static/js/bundle.js:34738:30
```

1. even i try to change registry path to nonexistent file, it still has same error. why does it happened? and where should i save the registry file? is it in react public? or is it in root project react? i kinda confused how to save the location of file and what relative path of registryPath refer to?

2. i have tried `feast registrydump`, i assume this is the file that wants to be read by react feast UI right? and its result is basically registry in JSON. andin Readme.md in feast ui, it's also state that registry in project-list.json has type file json. but, in https://github.com/feast-dev/feast/blob/master/ui/public/projects-list.json the type file of "registryPath" is ".db", it kinda make me more confused. so which one is the correct one? json or .db?

3. I have registry offline saved as file in S3. based on tutorial, the type file is .pb. I know i can fetch the file and add it on react, but can it be read by Feast React? I already try but the error is still same as i stated before.

it'd be great if the README.md in feast/ui updated to be clear about how to run it. all my question stated basically i just want to know how to run feast ui with customize react.
 
P.S. Thank you for help me out, This is my first time to write issue in github. im sorry if this is not proper way to ask.

**Comment by rushabh31** [comment]
@dfd19 Were you able to find out where to place `project-list.json`?

**Comment by priyathamv** [comment]
@rushabh31 I was facing the same issue. Then I found that there is a typo in the documentation. The file name has to be _projects-list.json_ and not _project-list.json_

**Comment by jeremyary** [comment]
referenced typo in last comment seems to need correction to me as well, easy fix [here ](https://github.com/feast-dev/feast/blob/master/ui/README.md?plain=1#L49 )w/a quick README update
