### ISSUE TITLE
PostgreSQL source offline_write_batch support

### ISSUE THREAD

**Issue by memaskal** [feast-dev/feast#3347]
We would like to use PostgreSQL as our offline store, and it lacks the offline_write_batch support

I would suggest, initially, that the solution could be as simple as the following:
```python
# using SQL alchemy and pandas
df.to_sql("table_name", connection, if_exists='append', method='multi')
````

**Comment by ZAn-next** [comment]
try to reopen this issue.
the PostgreSQL template won't work if offline_write_batch does not implement.
