### ISSUE TITLE
Forward-port Cassandra storage support for v0.4+

### ISSUE THREAD

**Issue by ches** [feast-dev/feast#335]
#360 implemented ingestion and serving support for Cassandra, for the v0.3 series of Feast. It is considered experimental: we the implementers have not run it in production and are in the process of stress testing.

Project Namespacing (#359 and others) and async job management (#361), coming along near the same time, brought significant changes to Feast internals for v0.4. Consequently, forward-porting the Cassandra support is not trivial.

As contributors of the functionality, we are evaluating our timeline for whether we can change course for Feast v0.4+, or will need to go to production on v0.3 and update on a later schedule. In the former case, we will take on this porting task in the next 1-2 months (Jan-Feb), but in the latter case, we would welcome anyone else interested in Cassandra for v0.4+ to run with implementing it—tag @smadarasmi and @ches and we'll be happy to review, or answer questions about the existing implementation; I'm also in the public Feast Slack channel.

We will also most likely wait for dust to settle on decisions like Feature Set Versioning (#386) before we revisit the implementation.

I will update this issue accordingly when our timeline is clear.

**Comment by woop** [comment]
@ches Super excited about this!

I think you are right. We can merge this in and simply mark this as experimental at the start.

I would love to be able to review this as well. Specifically want to see which changes you have made to interfaces for writing/reading, if any.

**Comment by ches** [comment]
> Specifically want to see which changes you have made to interfaces for writing/reading, if any.

We've mostly tried to avoid it so as not to stretch the scope of review with extra refactoring, but it is something I'm playing with as a separate follow-up.

I have the other matters discussed in chat still in my hopper to file as issues, I'll include that as well.

**Comment by ches** [comment]
Support was merged for the v0.3 series in #360. The work was done before major changes for Project Namespacing (#359 and others that followed) landed on master, so it will be a fairly substantial task to forward-port it for v0.4+. I'm going to re-title this issue to repurpose it as a task for that port.

**Comment by woop** [comment]
Closing due to issue being stale.
