### ISSUE TITLE
Project structure looks messy

### ISSUE THREAD

**Issue by sudohainguyen** [feast-dev/feast#3361]
## Expected Behavior 
Each modules should look well-organized into sub-modules

## Current Behavior
There are too many files under the main folder sdk/python/feast.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/22145541/203808273-5f841ed1-12de-47ef-9950-45da40177a9b.png">

### Specifications

- Version: 0.26.0
- Platform: MacOS
- Subsystem:

## Possible Solution
Refactoring needed, so the repository will be more maintainable and easier to extend in the future

**Comment by ketangangal** [comment]
Yes +1
