### ISSUE TITLE
Problem when running feast on Kubernetes

### ISSUE THREAD

**Issue by future-xy** [feast-dev/feast#3366]
Hi! I'm trying to run the [python-helm-demo](https://github.com/feast-dev/feast/tree/master/examples/python-helm-demo) but got a few problems.

I can setup local feast repo but failed to [setup the Feast Server](https://github.com/feast-dev/feast/tree/master/examples/python-helm-demo#now-lets-setup-the-feast-server).

## Current Behavior
In step 3 of [Now let's setup the Feast Server](https://github.com/feast-dev/feast/tree/master/examples/python-helm-demo#now-lets-setup-the-feast-server), when I try to run this command,
```bash
sed -i '' 's/localhost:6379/my-redis-master:6379/g' feature_store.yaml
```
I got an error,
```
sed: can't read s/localhost:6379/my-redis-master:6379/g: No such file or directory
```
I tried to skip this command and continue to run the next one but got another error,
```bash
helm install feast-release feast-charts/feast-feature-server --set feature_store_yaml_base64=$(base64 feature_store.yaml)
Error: INSTALLATION FAILED: expected at most two arguments, unexpected arguments: dDogZmVhc3RfcHl0aG9uX2RlbW8KcHJvdmlkZXI6IGxvY2FsCm9ubGluZV9zdG9yZToKICB0eXBl, OiByZWRpcwogICMgTm90ZTogdGhpcyB3b3VsZCBub3JtYWxseSBiZSB1c2luZyBpbnN0YW5jZSBV, UkwncyB0byBhY2Nlc3MgUmVkaXMKICBjb25uZWN0aW9uX3N0cmluZzogbG9jYWxob3N0OjYzNzks, cGFzc3dvcmQ9SG12Qnp4eGZ2YwpvZmZsaW5lX3N0b3JlOgogIHR5cGU6IGZpbGUKZW50aXR5X2tl, eV9zZXJpYWxpemF0aW9uX3ZlcnNpb246IDI=
```
## Steps to reproduce
Follow the [documentation](https://github.com/feast-dev/feast/tree/master/examples/python-helm-demo).

### Specifications

- Version: Feast SDK Version: "feast 0.26.0"
- Platform: Ubuntu 20.04
- Sed: sed (GNU sed) 4.7
- Helm: version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

Is that because my sed and helm version is not supported? Thank you!

**Comment by adchia** [comment]
Did you try running that sed command where the feature_store.yaml file exists?

And with the base64 thing, not quite sure why your base64 command is giving a list of output? There should only be one feature_store.yaml file, and running base64 should give one string

**Comment by dillonmabry** [comment]
> Did you try running that sed command where the feature_store.yaml file exists?
> 
> And with the base64 thing, not quite sure why your base64 command is giving a list of output? There should only be one feature_store.yaml file, and running base64 should give one string

I had a similar issue following the guide on Ubuntu 22.04 with basic bash commands. I had to do the following to get it to work as a single argument, seems the chart is interpreting the multiple lines in the base64 output as multiple arguments.

```
helm install feast-release feast-charts/feast-feature-server --set feature_store_yaml_base64=$(echo "$(cat feature_store.yaml)" | base64 -w 0)
```
