### ISSUE TITLE
`pyspark` dependency breaks Snowflake offline store

### ISSUE THREAD

**Issue by beauchbum** [feast-dev/feast#3383]
[This commit](https://github.com/feast-dev/feast/pull/3358/commits/14c082ef5c039f2b7fa261a485b66e820c56568f) introduced a `pyspark` dependency for the Snowflake offline store that is not reflected in [setup.py](https://github.com/feast-dev/feast/blob/1d3c111c4adb28b7063f45e92af0ad3aef296ee3/setup.py#L98-L104). This causes feast actions to fail due to:

```
File "/usr/local/lib/python3.9/site-packages/feast/infra/offline_stores/snowflake.py", line 26, in <module>
  from pyspark.sql import DataFrame, SparkSession
ModuleNotFoundError: No module named 'pyspark'`.
```

## Steps to reproduce
- Install `feast = {extras = ["snowflake"], version = "^0.27.0"}`
- Set up a Feature Repository with a Snowflake offline store
- Run `feast plan`

### Specifications

- Version: 0.27.0
- Platform:
- Subsystem:

## Possible Solution
Not sure - would prefer not needing `pyspark` for Snowflake offline store to work, but if that's the case then add to `setup.py`?

**Comment by achals** [comment]
cc @adchia @sfc-gh-madkins  - should this dep on pyspark be optional (by moving the import inside the `to_spark_df` method, or should it be added as a proper dep to the `snowflake` extra?

**Comment by adchia** [comment]
yeah should be a try import probably

**Comment by beauchbum** [comment]
Thanks for weighing in on this. Any ideas on when this might be worked on (and eventually released)?
