### ISSUE TITLE
RuntimeError: registry path postgresql://postgres:postgres@localhost:30072/feast has unsupported scheme postgresql. Supported schemes are file, s3 and gs

### ISSUE THREAD

**Issue by pengyuan** [feast-dev/feast#3407]
RuntimeError: registry path postgresql://postgres:postgres@localhost:30072/feast has unsupported scheme postgresql. Supported schemes are file, s3 and gs

**Comment by pengyuan** [comment]
feast feature server not support postgres registry?

**Comment by sudohainguyen** [comment]
have you install `postgres` extra?
