### ISSUE TITLE
028.0 Python SDK:  Assertion failure on Boolean types in type_map.py

### ISSUE THREAD

**Issue by cbarcroft** [feast-dev/feast#3443]
https://github.com/feast-dev/feast/blob/30f3d34b90a9b8fe39a87cef804cfff5e36209ad/sdk/python/feast/type_map.py#L405

A bug was introduced in 0.28.0 at the referenced check above.  For boolean types, if sample = False, then False DOES equal 0 and then triggers a failure on the following assertion.

**Comment by beauchbum** [comment]
I also just ran into this.
