### ISSUE TITLE
materialize_incremental function fails when Snowflake is specified as a batch_engine and not specified as the online_store

### ISSUE THREAD

**Issue by sfc-gh-rsaxena** [feast-dev/feast#3446]
## Expected Behavior 
we should be able to define any supported database as an online store with Snowflake as the batch engine, run materialize_incremental and we should be able to materialise the online store.

## Current Behavior
If you setup Feast Snowflake but update the feasture_store.yaml file to have any online_store other than Snowflake, materialize_incremental command fails with an error of missing functions. The functions don't get created in Snowflake to populate online store. i.e. following does not come as an output after feast apply
`Deploying materialization functions for customer_repo`

## Steps to reproduce
1. `pip install 'feast[snowflake]'`
2. `feast init -t snowflake customer_repo` (provide your Snowflake details)
3. Navigate to ./customer_repo/feature_repo and update feature_store.yaml file to below entry (use sql lite instead of Snowflake for online store):
```
    online_store:
    type: sqlite
    path: data/online_store.db
```
4. `feast apply`
5. create offline store using similar commands as follows:
```
fs = FeatureStore(repo_path=".")  # Initialize the feature store

feature_service = fs.get_feature_service("customer_info")
fs.get_historical_features(features=feature_service, entity_df=customers).to_snowflake(table_name='historical_features')
```

6. Materialise for online store - ERROR appears here
```
fs.materialize_incremental(end_date=datetime.now())

online_features = fs.get_online_features(
    features=feature_service, entity_rows=[{"CUSTOMERID": '7090-ZyCMx'}, {"CUSTOMERID": '1364-wJXMS'}, {"CUSTOMERID": '6564-sLgIC'}],
).to_dict()
```

### Specifications

- Version: 0.28.0
- Platform: MacOS 13.0.1
- Subsystem:

## Possible Solution
Function creation should be based on **batch_engine:** instead of **online_store:** 
I have tested using sqllite as online_store after creation of functions in Snowflake and it works fine.

**Comment by sfc-gh-madkins** [comment]
Duplicate
