### ISSUE TITLE
[Help] How do you share your feast repository between projects?

### ISSUE THREAD

**Issue by ianliu** [feast-dev/feast#3454]
I'm a data engineer at my company, and I'm having a hard time wrapping my head around Feast.

From what I've read, one is supposed to have a "feast repository" that will store the yaml and feature definition files.

But this yaml file must be accessible to other projects to create a `FeatureStore(repo_path, ...)`. How do you _share_ your yaml file? Do you `git submodule add ...` into your other projects that depends on it?

When I was playing with feast, I had the impression that after a `feast apply`, one could create a `FeastStore` by passing the path to the DB file, which turned out to be false. Why isn't this the case? Do I need the feature definition files to consume them?

**Comment by breno-costa** [comment]
@ianliu you can store these files in blob storage (s3, gcs) to share accross projects. You can create some ci pipeline to apply feast modifications and copy the files to blob path. It's also recommended separate files in different environments (stg, prod).

You can also migrate this registey to a sql database as long as you have more people using this feature registry.
