### ISSUE TITLE
schema has duplicate fields

### ISSUE THREAD

**Issue by hao-affirm** [feast-dev/feast#3459]
## Expected Behavior 
feature_view.schema has no duplicate fields

## Current Behavior
feature_view.schema has no duplicate fields

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution

in feature_view:
```
    def schema(self) -> List[Field]:
        return list(set(self.entity_columns + self.features))
```

**Comment by felixwang9817** [comment]
@hao-affirm would you mind sharing the feature view definition that led to duplicate fields shared between `self.entity_columns` and `self.features`?

**Comment by hao-affirm** [comment]
https://github.com/feast-dev/feast/blob/2f7c4ede8f9e66703714261f1152f78526d4bf43/sdk/python/feast/feature_view.py#L261
and https://github.com/feast-dev/feast/blob/2f7c4ede8f9e66703714261f1152f78526d4bf43/sdk/python/feast/feature_view.py#L171 i think both `entity_column` and `features` will append the `field`, if the field is defined in both `entities` and `schema`
