### ISSUE TITLE
Bigtable client issues

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#3493]
## Expected Behavior 
Note: this issue is not present with the Datastore client.
Minimal error rates and no memory leak

## Current Behavior
Given enough load, Feast when using the Bigtable connector can have longer than expected response times / error rates / memory leaks. 

From testing, this appears to be tied to the Bigtable client being created for each request for features

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
Reuse the Bigtable client across requests. Perhaps more ideally even creating a connection pool that users can configure (as per https://cloud.google.com/bigtable/docs/configure-connection-pools)

**Comment by adchia** [comment]
cc @chhabrakadabra @cburroughs

**Comment by chhabrakadabra** [comment]
Thank you for creating this issue.
