### ISSUE TITLE
How to setup and run Feast on local as a developer - to support

### ISSUE THREAD

**Issue by PrasannaKumar1115** [feast-dev/feast#3506]
## Expected Behavior 
setup Feast from github code to contribute 

## Current Behavior
ModuleNotFoundError: feast.protos
### Specifications

- Version: from master 
- Platform: mac
- Subsystem:

**Comment by PrasannaKumar1115** [comment]
the bug occurs when install in edit mode as -  pip install -e git+https://github.com/feast-dev/feast.git#egg=feast

**Comment by sudohainguyen** [comment]
you need to run compile first to generate proto objects in local machine, try:
`make compile-protos-docs`
