### ISSUE TITLE
Unable to install feast via pip

### ISSUE THREAD

**Issue by com9009** [feast-dev/feast#3507]
## Expected Behavior 
`pip install feast` works fine.

## Current Behavior
Installation fails with error:
`
Collecting feast==0.26.0
  Downloading feast-0.26.0.tar.gz (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 17.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in feast setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: pip install --upgrade pip

`

## Steps to reproduce
1. Install Python 3.11 on OSX.
2. create virtualenv with python3.11
3. try `pip install feast`

### Specifications

- Version: 0.26.0
- Platform: OSX
- Subsystem:

**Comment by SR023** [comment]
you can use anaconda to install, 
1, install anaconda(python>3.8)
2. try pip install feast,if fail,then 3
3.go to https://anaconda.org/  search feast,and download .conda file
4. conda install --use-local feast-*-pyh71feb2d_0.conda


it's work for me, you can try it.

**Comment by com9009** [comment]
@SR023 Thank you for reply.

It work fine with conda env using python>3.8. 
Thanks.
