### ISSUE TITLE
pyarrow version restricted

### ISSUE THREAD

**Issue by hsheth2** [feast-dev/feast#3510]
I was looking to install feast with python 3.11 on an M1 machine. Feast requires pyarrow<9. The latest pyarrow is 11.0.0 and has a prebuilt wheel file for macOS, whereas pyarrow<9 requires building from source. Additionally, I think older versions of pyarrow aren't compatible with python 3.11, but not 100% sure of that. I was hoping that we could loosen the requirement to make installing on M1 machines with 3.11 easier.

### Specifications

- Version: feast 0.29.0
- Platform: macOS M1 w/ python 3.11

**Comment by achals** [comment]
We had some cross language integrations that required specific versions of arrow but i believe I'm in process of removing those and that should make out pyarrow requirements looser.

**Comment by hsheth2** [comment]
Thanks. Please keep me posted on that
