### ISSUE TITLE
Rust extensions

### ISSUE THREAD

**Issue by judahrand** [feast-dev/feast#3522]
The Golang Python extension eco-system seems pretty limited whereas the Rust ecosystem is alive and kicking. It seems like it might make sense to write extensions for Feast in Rust rather than Go? I'm thinking of the embedding Go Feature Server which never seems to have worked very well.

Do people have any thoughts on this?

**Comment by achals** [comment]
I like the idea in general. I would also like to investigate mypyc to see if we can speed up python code without any FFI (for reference https://ichard26.github.io/blog/2022/05/compiling-black-with-mypyc-part-1/)

The main challenge i think is how to structure the code to allow for individual extensions cleanly without much x-language duplication and easy debuggability.

All open for proposals on clean interfaces and extension points!
