### ISSUE TITLE
Error while installing `feast` on GCP ( Vertex AI Workbench i.e Notebooks)

### ISSUE THREAD

**Issue by gomrinal** [feast-dev/feast#3530]
## Expected Behavior 
- It should ideally install the library on GCP. However, when I try to install in in a vertex ai workbench. It throws error.
## Current Behavior
- It fails to install the library
## Steps to reproduce
- Go to GCP -> Create a notebook on Vertex AI workbench -> Open terminal -> Try installing feast on the workbench
- ```bash
pip3 install `feast[gcp]`
```
### Specifications

- Version: 
- Platform: Ubuntu
- Subsystem:

Error:
```bash
Collecting feast
  Using cached feast-0.26.0.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in feast setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by jeremyary** [comment]
Revisiting issues in the name of new maintainership & finding that with current version, I'm able to install feast via workbench terminal & successfully `feast init` a new repo. Closing issue as this seems resolved, thanks!
