### ISSUE TITLE
docker pull feastdev/feature-server:0.30.0 not available in docker hub

### ISSUE THREAD

**Issue by kabilan6** [feast-dev/feast#3543]
## Expected Behavior 

docker pull feastdev/feature-server:0.30.0  in docker hub

## Current Behavior

docker pull feastdev/feature-server:0.30.0 not available in docker hub 

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by davidschuler-8451** [comment]
i'm assuming this would also affect the python package? only seeing up to version 0.29.0 in pypi

**Comment by kabilan6** [comment]
Any alternate solution for this ?
