### ISSUE TITLE
Could not import module 'feast.infra.offline_stores.snowflake' while attempting to load class 'SnowflakeOfflineStoreConfig'

### ISSUE THREAD

**Issue by seekerofsai** [feast-dev/feast#3567]
## Expected Behavior 
feast apply with snowflake as offline store failing

## Current Behavior
feast apply fails with exception Could not import module 'feast.infra.offline_stores.snowflake' while attempting to load class 'SnowflakeOfflineStoreConfig'

## Steps to reproduce

Config:
offline_store:
    type: snowflake.offline
    account: ${ACCOUNT}
    user: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    role: ${SNOWFLAKE_ROLE}
    warehouse: ${SNOWFLAKE_WAREHOUSE}
    database: ${SNOWFLAKE_DATABASE}
    schema: ${SNOWFLAKE_SCHEMA}

batch_engine:
  type: snowflake.engine
    account: ${ACCOUNT}
    user: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    role: ${SNOWFLAKE_ROLE}
    warehouse: ${SNOWFLAKE_WAREHOUSE}
    database: ${SNOWFLAKE_DATABASE}
    schema: ${SNOWFLAKE_SCHEMA}

### Specifications

- Version:  
   Feast SDK Version: "feast 0.30.2"
   Python 3.10.10

- Platform:  
   Mac os 13.2.1
- Subsystem:

**Comment by sfc-gh-madkins** [comment]
I think #3587 should solve this
