### ISSUE TITLE
Is it possible run feast[spark] and put offline store on s3 ?

### ISSUE THREAD

**Issue by MinfangTao** [feast-dev/feast#3571]
**Is your feature request related to a problem? Please describe.**
I simple tried 
created a Aws emr, and install feast[spark] and try to point the datasource to a s3 location
path=f"s3://my-bucket/spark_emr_test_data/driver_hourly_stats.parque

and get error  org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"

We already have data in s3, and moving them into redshift will get extra cost ，so want to ask is it possible run feast[spark] and keep offline on S3 ?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shuchu** [comment]
I meet the same error on a different application before. It's about the extra Java . Jars you need to allow spark to read/write to S3.

**Comment by MinfangTao** [comment]
@shuchu Thank you very much. I found other solution: 

The problem is after using "pip3 install feast[spark]",  it installed a pyspark, which can not identify "s3:". However, the emr has its own pyspark already, and it supported "s3:"

So my solution is let feast using the original pyspark .

1. install python3.9 (The latest Emr carry python3.7, which is support the latest feast), https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/using-python.html

2. Find the original pyspark path : running pyspark and print its' path,
echo "export PYTHONPATH=$PYTHONPATH:/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip:/usr/lib/spark/python/" >> /home/hadoop/.bash_profile
4. install feast[spary]
5. done

**Comment by MinfangTao** [comment]
After configure properly, feast support this function.
