### ISSUE TITLE
FeastClassImportError: Could not import class 'SqlRegistryConfig' from module 'feast.infra.registry.sql'

### ISSUE THREAD

**Issue by seekerofsai** [feast-dev/feast#3590]
## Expected Behavior 
 load sql registry type

## Current Behavior
fails to load 
## Steps to reproduce
registry:
  registry_type: sql
  cache_ttl_seconds: 60
  path: <path>

### Specifications

- Version: feast 0.30.2 
- Platform: Python Python 3.8.13
- Subsystem:

## Possible Solution
Add SqlRegistryConfig in feast.infra.registry.sql

**Comment by sudohainguyen** [comment]
please follow this PR #3586 , it resolves this bug but awaiting approval 😞
