### ISSUE TITLE
redis-py Race Condition vulnerability

### ISSUE THREAD

**Issue by catalinm-am** [feast-dev/feast#3603]
redis-py before 4.5.3, leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a pipeline operation), and can send response data to the client of an unrelated request in an off-by-one manner.

The fixed versions for this CVE Record are 4.3.6, 4.4.3, and 4.5.3, but https://github.com/redis/redis-py/issues/2665. https://github.com/advisories/GHSA-8fww-64cx-x8p5 has been assigned the issues caused by the incomplete fixes.

## Possible Solution
Update version of redis from 4.2.2 to 4.3.6, 4.4.3, or 4.5.3.

**Comment by felixwang9817** [comment]
closing this as we have upgraded to 4.4.4 in #3604
