### ISSUE TITLE
how to make ONLY offline feature store in feast ?

### ISSUE THREAD

**Issue by nehal3731** [feast-dev/feast#3615]
**Is your feature request related to a problem? Please describe.**
I am trying to make an offline feature store in Azure ML but whenever I do feature_store.apply automatically an online database is also added to my feature repo which in my case is not required and will be a waste of resource . I have even made all my feature views offline but the issue still persists

**Describe the solution you'd like**
I know it won't be tough job to just add online:bool argument in feature_store.apply function and we will have a solution to make offline feature store 

**Describe alternatives you've considered**
I am trying a work-around in which I made an object for registry and will apply feature views and entities to registry and later retrieve them with get historical features method

**Additional context**
also while using feast azure provider I got the error of version mismatch as azure is only supporting feast version less that 3.20.x and latest is 3.31

**Comment by sudohainguyen** [comment]
my workaround is define a dummy sqlite online store 🤔

**Comment by sfc-gh-madkins** [comment]
This ^

**Comment by nehal3731** [comment]
I have figured out the correct way to implement this 
we don't need to make a dummy sqlite online store 
just in feast config yaml file 
you have to define online store as none.

sample yaml file 

project: pro_feast
registry: registry/registry.db
provider: local
offline_store:
  type: file
online_store: ~
