### ISSUE TITLE
Feast chart 0.30.2 throws  No module named 'feast.protos'

### ISSUE THREAD

**Issue by psheorangithub** [feast-dev/feast#3627]
While deploying the 0.30.2 chart, I'm getting below error when running "feast version". Seems like the feast version installed there is broken. 

While trying to test feast, getting following error.

Traceback (most recent call last):
 File "/usr/local/bin/feast", line 5, in <module>
   from feast.cli import cli
 File "/sdk/python/feast/__init__.py", line 7, in <module>
   from feast.infra.offline_stores.bigquery_source import BigQuerySource
 File "/sdk/python/feast/infra/offline_stores/bigquery_source.py", line 5, in <module>
   from feast import type_map
 File "/sdk/python/feast/type_map.py", line 37, in <module>
   from feast.protos.feast.types.Value_pb2 import (
ModuleNotFoundError: No module named 'feast.protos'

How to fix it:
 Rollback to 0.30.2 version
$ pip uninstall feast
$ pip install feast==0.30.2

**Comment by adchia** [comment]
Not quite sure what you mean. When you deploy the helm chart, that goes into k8s right? are you running `feast version` on the feature server pod?

I also just ran `pip install feast==0.30.2` and ran `feast version` and it seemed to work fine.

**Comment by npsables** [comment]
Ran into the same issue. The way feast is installed in chart docker image is different, it didn't use `pip install`.

**Comment by fsalazarh** [comment]
Same issue here with chart version 0.34.1, the transformation-service pod throws the following once installed the chart with helm:

```
Traceback (most recent call last):
  File "//app.py", line 9, in <module>
    from feast import FeatureStore
  File "/sdk/python/feast/__init__.py", line 7, in <module>
    from feast.infra.offline_stores.bigquery_source import BigQuerySource
  File "/sdk/python/feast/infra/offline_stores/bigquery_source.py", line 5, in <module>
    from feast import type_map
  File "/sdk/python/feast/type_map.py", line 37, in <module>
    from feast.protos.feast.types.Value_pb2 import (
ModuleNotFoundError: No module named 'feast.protos'
```

**Comment by andrewshrout** [comment]
Getting the same thing as @fsalazarh with chart version 0.34.1 when attempting to deploy to k8s.

**Comment by fsalazarh** [comment]
In case it helps anyone, I realized that the error is in the Helm Chart of the [Java version](https://github.com/feast-dev/feast/blob/master/infra/charts/feast/README.md) (which is in Alpha for now). Then I deployed the Python/Go chart following [this tutorial](https://github.com/feast-dev/feast/tree/master/infra/charts/feast-feature-server) and it does not present the issue.
