### ISSUE TITLE
Vulnerability Finding Through SAST

### ISSUE THREAD

**Issue by iomy-gumaro-angi** [feast-dev/feast#3659]
Hello,
I recently found a vulnerability in the Feast library after scanning it in a SAST tool. FastAPI's CSRF protection is turned off (see screenshot below). Can you please explain why the CSRF protection is disabled? Is this intentional?

![Screenshot 2023-06-22 at 2 12 19 PM](https://github.com/feast-dev/feast/assets/113539322/e9d75229-7bf5-4f23-b70f-ef78d2e587b9)

**Comment by shuchu** [comment]
This is the CVE I dig out from the FastAPI website.
https://github.com/tiangolo/fastapi/security/advisories/GHSA-8h2j-cgx8-6xv7

the PR of FastAPI: https://github.com/tiangolo/fastapi/pull/2118/files

A security blog talks about CSRF of FastAPI: https://www.stackhawk.com/blog/csrf-protection-in-fastapi/

//claim: post links here to save some time for future developers who is going to work on this.
