### ISSUE TITLE
get_online_features method is not returning multiple rows per entity

### ISSUE THREAD

**Issue by carolinajimenez** [feast-dev/feast#3663]
I'm experiencing an issue with Feast where the get_online_features method is not returning all the data I expect. Has anyone encountered a similar problem or have any suggestions for troubleshooting? Or could there be any specific configuration requirements in Feast when dealing with multiple rows per entity in the data source? I'm trying to obtain all the features related to each entity value, but I'm only getting a single record per feature.

**Comment by shuchu** [comment]
hi @carolinajimenez, do you mind providing more info about the issue you met? like what's the specific version of Feast you are using? and also the online/offline storage

**Comment by carolinajimenez** [comment]
FEAST VERSION:
I'm using the Feast version: 0.31.1

ISSUE INFO:
For example, I have this Dataframe:

UserId,FriendUserId,NotSuggestedUserId,event_timestamp
66EE971C,CB0FF6DD,,2023-06-30 10:21:02.950086
21C2B531,907AFE4A,,2023-06-30 10:21:02.950086
98548B41,A69F2C76,,2023-06-30 10:21:02.950086
98548B41,907AFE4A,,2023-06-30 10:21:02.950086
98548B41,CA528F46,,2023-06-30 10:21:02.950086

I defined "UserId" as an Entity, and "FriendUserId" and "NotSuggestedUserId" as FeatureViews related to that entity and that dataframe.

user_entity = Entity(
    name="user_entity",
    join_keys=["UserId"]
)

user_source = FileSource(
    name="user_source",
    path="df_users.parquet",
    timestamp_field="event_timestamp",
)

user_fv = FeatureView(
    name="user_feature_view",
    entities=[user_entity],
    ttl=timedelta(days=1),
    schema=[
        Field(name="FriendUserId", dtype=String),
        Field(name="NotSuggestedUserId", dtype=Float32),
    ],
    online=True,
    source=user_source,
    tags={"user_features": "friendship"},
)

As you can see in the Dataframe, there's one more register per UserId, and I hope to get all the records of the same id

feast_features = [
        "user_feature_view:FriendUserId",
        "user_feature_view:NotSuggestedUserId",
    ]
user_features = store.get_online_features(
    features=feast_features,    
    entity_rows=[ { "UserId": "98548B41" } ]
)
user_features = user_features.to_df()
    
But I only get one registry: 
UserId,NotSuggestedUserId,FriendUserId
98548B41,,CA528F46

**Comment by shuchu** [comment]
Based on the online store documentation, it seems only the latest feature of Entity will be stored in the online storage.  Check this doc: https://docs.feast.dev/getting-started/architecture-and-components/online-store

I guess that's the reason why we only see one feature row from the get_online_features() call.
