### ISSUE TITLE
How load defualt value when environ variable is not set

### ISSUE THREAD

**Issue by GyuminJack** [feast-dev/feast#3669]
## Expected Behavior 
`${REDIS_CONNECTION_STRING:"0.0.0.0:6379"}`
-> when "REDIS_CONNECTION_STRING" is not set, i expect return value is "0.0.0.0:6379"
but not properly working

## Current Behavior
only returns "${REDIS_CONNECTION_STRING:"0.0.0.0:6379"}" 
- maybe that function developed via (https://github.com/feast-dev/feast/pull/1909/commits/04334594dceb5d2d7fd867d8646159018280065b)

- could you tell me the code how can get default value with parsing?

## Steps to reproduce
type that string is feature_store.yaml
### Specifications

- Version: python3.9, feast 0.31.1
- Platform:
- Subsystem:

**Comment by tmihalac** [comment]
> ## Current Behavior
> only returns "${REDIS_CONNECTION_STRING:"0.0.0.0:6379"}"

Hello @GyuminJack , can you please clarify what exactly did you mean?
What are the steps to reproduce the returned string you mentioned, I want to write a test that reproduces the issue to resolve it.
