### ISSUE TITLE
`get_table_query_string()` does not return a str but None

### ISSUE THREAD

**Issue by pmayd** [feast-dev/feast#3672]
## Expected Behavior 

Following the tutorial [feature-retrieval](https://docs.feast.dev/getting-started/concepts/feature-retrieval) the table name should be returned by the function `store.get_data_source("driver_hourly_stats_source").get_table_query_string()`.

## Current Behavior

However, instead of a str, the function seems to return `None`. The following error occurs:

```
Traceback (most recent call last):
  File "/Users/michael.aydinbas/git/source.xing.com/michael-aydinbas/quickstart/feature_repo/test_workflow.py", line 146, in <module>
    run_demo()
  File "/Users/michael.aydinbas/git/source.xing.com/michael-aydinbas/quickstart/feature_repo/test_workflow.py", line 19, in run_demo
    fetch_historical_features_entity_df(store, for_batch_scoring=True)
  File "/Users/michael.aydinbas/git/source.xing.com/michael-aydinbas/quickstart/feature_repo/test_workflow.py", line 86, in fetch_historical_features_entity_df
    FROM {store.get_data_source("driver_hourly_stats_source").get_table_query_string()}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/feast/lib/python3.11/site-packages/typeguard/__init__.py", line 1037, in wrapper
    raise TypeError(*exc.args) from None
TypeError: type of the return value must be str; got NoneType instead
```

## Steps to reproduce
Just follow the quickstart tutorial and replace the batch fetching code with

```python
entity_sql = f"""
    SELECT
        driver_id,
        event_timestamp
    FROM {store.get_data_source("driver_hourly_stats_source").get_table_query_string()}
    WHERE event_timestamp BETWEEN '2021-01-01' and '2021-12-31'
"""
training_df = store.get_historical_features(
    entity_df=entity_sql,
    features=[
        "driver_hourly_stats:conv_rate",
        "driver_hourly_stats:acc_rate",
        "driver_daily_features:daily_miles_driven"
    ],
).to_df()
```

### Specifications

- Version: 0.31.1
- Platform: MacOS 13.4.1 (22F82)
- Subsystem:

**Comment by shuchu** [comment]
hi @pmayd  I assume you follow the tutorial and use FileSource  (offline storage) as the DataSource.  The "get_table_query_string()" function is not implemented as shown by the source code: https://rtd.feast.dev/en/latest/_modules/feast/infra/offline_stores/file_source.html#FileSource.get_table_query_string

If we want to test this function, probably we need to use a SQL database as offline storage, like PostgreSQL:
https://rtd.feast.dev/en/master/_modules/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.html#PostgreSQLSource.get_table_query_string

**Comment by redhatHameed** [comment]
@pmayd can you confirm if that issue resolved based on comments by @shuchu

**Comment by jeremyary** [comment]
Hi @pmayd, given the original timeline for this issue & suggestions made previously, I'm moving to close the issue. That said, should your issue persist, please reach out here and let us know & we'd be happy to discuss. Thanks!
