### ISSUE TITLE
Security Vulnerability Disclosure

### ISSUE THREAD

**Issue by AdnaneKhan** [feast-dev/feast#3684]
I've found a security issue with this repository, how can I privately disclose this?

**Comment by shuchu** [comment]
there is a slack channel: 
http://slack.feast.dev/
And you can msg Danny (@adchia)

**Comment by AdnaneKhan** [comment]
Hey! sorry this got away from me - I re-checked and the vuln is still here. Got an email address I can send it to? Kind of a pain to join lots of Slack channels. Thankfully fix is really simple.

**Comment by jeremyary** [comment]
@AdnaneKhan if you'd still like to disclose with us, we can be reached collectively at `feast-dev@googlegroups.com`, but should you prefer further discretion, please feel free to reach out to me directly at `jary@redhat.com` & I'd be happy to serve as conduit in raising the issue with our other maintainers. Thanks!

**Comment by AdnaneKhan** [comment]
> @AdnaneKhan if you'd still like to disclose with us, we can be reached collectively at `feast-dev@googlegroups.com`, but should you prefer further discretion, please feel free to reach out to me directly at `jary@redhat.com` & I'd be happy to serve as conduit in raising the issue with our other maintainers. Thanks!

I sent an email to your Redhat address. The group mail didn't work for some reason (I got a delivery failure notification).

**Comment by jeremyary** [comment]
@AdnaneKhan received! I appreciate you taking the time to share this with me, I'm putting it on my own list to tackle.
