### ISSUE TITLE
Add Supported Schemes in `REGISTRY_STORE_CLASS_FOR_SCHEME` for Window (C:\)

### ISSUE THREAD

**Issue by acn-thanapat-sontayasara** [feast-dev/feast#3686]
## Introduction
I'm attempting to perform a unit test on my personal laptop running Windows 11.
Additionally, I'm trying to implement an approach that enables a `FeatureStore` on a local provider.
Like this example: [test_local_feature_store.py](https://github.com/feast-dev/feast/blob/master/sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py)

## Expected Behavior 
Can use the `registry_path` in this format `C:\Users\<user_name>\AppData\Local\Temp\`

## Current Behavior
When attempting to execute a unit test on my local Windows system using the [test_local_feature_store.py](https://github.com/feast-dev/feast/blob/master/sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py).
The `mkstemp()` function is utilized within the pytest fixtures.
```
@pytest.fixture
def feature_store_with_local_registry():
    fd, registry_path = mkstemp()
    fd, online_store_path = mkstemp()
    return FeatureStore(
        config=RepoConfig(
            registry=registry_path,
            project="default",
            provider="local",
            online_store=SqliteOnlineStoreConfig(path=online_store_path),
            entity_key_serialization_version=2,
        )
    )
```
It creates a temporary file and stores in the path `C:\Users\<user_name>\AppData\Local\Temp\` on my Windows system.
After that, when the `registry_store_type` is not found in the `registry_config`.
It will call the `get_registry_store_class_from_scheme(registry_path)`

```
if registry_config:
    registry_store_type = registry_config.registry_store_type
    registry_path = registry_config.path
    if registry_store_type is None:
        cls = get_registry_store_class_from_scheme(registry_path)
    else:
        cls = get_registry_store_class_from_type(str(registry_store_type))
```

```
def get_registry_store_class_from_scheme(registry_path: str):
    uri = urlparse(registry_path)
    if uri.scheme not in REGISTRY_STORE_CLASS_FOR_SCHEME:
        raise Exception(
            f"Registry path {registry_path} has unsupported scheme {uri.scheme}. "
            f"Supported schemes are file, s3 and gs."
        )
    else:
        registry_store_type = REGISTRY_STORE_CLASS_FOR_SCHEME[uri.scheme]
        return get_registry_store_class_from_type(registry_store_type)
```
As a result, an exception is raised because the `uri.scheme` is not present in the `REGISTRY_STORE_CLASS_FOR_SCHEME` mapping.
In [registry.py#L63-L68](https://github.com/feast-dev/feast/blob/ef4ef32f7466b5d874d537abe8def4731b15dc85/sdk/python/feast/infra/registry/registry.py#L63-L68),
```
REGISTRY_STORE_CLASS_FOR_SCHEME = {
    "gs": "GCSRegistryStore",
    "s3": "S3RegistryStore",
    "file": "FileRegistryStore",
    "": "FileRegistryStore",
}
```
### Specifications

- Version: 0.29.0 (or 0.31.1)
- Platform: Window 11
- Python: 3.9.12

## Possible Solution
A potential solution could be to consider adding the entry `"c": "FileRegistryStore"` to the `REGISTRY_STORE_CLASS_FOR_SCHEME` dictionary.
I'm not quite sure if this addition might help resolve the issue.

## Additional
![image](https://github.com/feast-dev/feast/assets/113094208/4e8ed181-c71c-4996-9721-36e861364d04)

## Note
If my understanding is incorrect or if there are any misconceptions in this issue,
I kindly request your guidance and clarification.
I'm here to learn. Thanks 👍🏻

**Comment by shuchu** [comment]
It's a little bit challenging to do development on Windows11 OS. Do you mind to run it on WSL or other Linux distros?

**Comment by acn-thanapat-sontayasara** [comment]
@shuchu Hi, thank you for your reply.
So, I understand that this is a limitation for the Windows file system. Thanks!
By the way, would you like me to close this issue or leave it open?

**Comment by shuchu** [comment]
if you don't mind, maybe we can close it.  :)

**Comment by acn-thanapat-sontayasara** [comment]
@shuchu Sure, I'll be waiting for an update for this in maybe later release I guess haha.
Thank you so much.👍🏻
