### ISSUE TITLE
Unstructured Data

### ISSUE THREAD

**Issue by ghost** [feast-dev/feast#3698]
Hi 

Do we have option available to handle un-structure data like text, image, audio, video and etc. Please suggest if anything is available now.

**Comment by shuchu** [comment]
For unstructured data, we can store the **feature vectors** after feature engineering.   You can store those feature vectors (numerical only) in a vector database like Pinecone. Or SQL database if the feature vectors include non-numerical values. 

Once you store them in a database, we can use Feast as a feature store.
