### ISSUE TITLE
Make the `BigQuerySource` environment invarient by allowing the omission of `project_id` from the table parameter

### ISSUE THREAD

**Issue by joseph-isaacs** [feast-dev/feast#3704]
**Is your feature request related to a problem? Please describe.**
I am hoping to follow [this](https://docs.feast.dev/how-to-guides/feast-snowflake-gcp-aws/structuring-repos#shared-feast-object-definitions-with-separate-feature_store.yaml-files) feature store cross-environment structuring system. However this will require `project_id` to be injected into the table string in `BigQuerySource(..,table="<<project_id>>.<<dataset_id>>.<<table_name>>",..)`.

**Describe the solution you'd like**
Could this field also support defaulting to the `feature_store`'s offline_store.project_id? I assume that more changes are needed but one piece would be [here](https://github.com/feast-dev/feast/blob/76270f66b3d98b0119b70927c06908f9834b6120/sdk/python/feast/infra/offline_stores/bigquery_source.py#L141), `client = bigquery.Client(project=config.offline_store.project_id)`

**Describe alternatives you've considered**
There other option would be to allow `feast apply` to set environment variables or wrap the call to feast apply with environment variable exports.

I hope I didn't miss something.

**Comment by joseph-isaacs** [comment]
Bumping this

**Comment by sudohainguyen** [comment]
does `BILLING_PROJECT_ID` setting match your expectation?

**Comment by sudohainguyen** [comment]
see this doc
https://rtd.feast.dev/en/latest/index.html#feast.infra.offline_stores.bigquery.BigQueryOfflineStoreConfig
