### ISSUE TITLE
Pandas 2.0 support

### ISSUE THREAD

**Issue by 0x26res** [feast-dev/feast#3709]
**Is your feature request related to a problem? Please describe.**

I'm trying to install feast with pandas 2.0.3, but feast is pinned to pandas `<2`: https://github.com/feast-dev/feast/blob/c75a01fce2d52cd18479ace748b8eb2e6c81c988/setup.py#L55

**Describe the solution you'd like**

Allow pandas >2. I'm not sure how much effort it will be, my experience upgrading has been simple, and provided there's a good test coverage of the pandas features being used by feast, it should be fine.

**Describe alternatives you've considered**

I could rollback my codebase to an older version of pandas but I'm using some of the new feature and rely on recent bug fixes.

**Additional context**

```
python3.9 -m venv --clear tmp
source tmp/bin/activate/
pip install pandas==2.0.3 feast==0.31.1

ERROR: Cannot install feast==0.31.1 and pandas==2.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pandas==2.0.3
    feast 0.31.1 depends on pandas<2 and >=1.4.3


```

**Comment by sudohainguyen** [comment]
I reopened my PR here

#3664

**Comment by sudohainguyen** [comment]
java_pr failed somehow 😢

**Comment by matthewarmand** [comment]
Is this considered a priority for Feast? We're attempting to use Feast but resolving the dependencies and downgrading Pandas so far to accommodate this library is problematic.

**Comment by ddl-joyce-zhao** [comment]
Hello, 

The issue that blocked the PR https://github.com/feast-dev/feast/pull/3664 to extend Pandas version support has been solved. Could you please reconsider this request? Thanks.

**Comment by sudohainguyen** [comment]
Great to know, thanks @ddl-joyce-zhao 
I'm going to handle this soon
