### ISSUE TITLE
The term 'feast' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by mayank6909** [feast-dev/feast#3710]
## Current Behavior
feast : The term 'feast' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ feast init my_feature_repo
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (feast:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
### Specifications

- Version: Python 3.10.6, pip 23.2.1
- Platform: Windows 10
- Subsystem:

**Comment by jeremyary** [comment]
Hi @mayank6909, given the timeframe of this issue and suspicion this is environment-related, I'm moving to close this issue. That said, should the issue persist, please feel free to reach out here & let us know. Thanks!
