### ISSUE TITLE
helm install feast-release feast-charts/feast Unable to install successfully

### ISSUE THREAD

**Issue by zibuyule** [feast-dev/feast#3711]
## Expected Behavior 
helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com
helm install feast-release feast-charts/feast

Then I can access the feast UI (IP:8888).

## Current Behavior
Couldn't read local registry file: /root/data/registry.db

## Steps to reproduce

$ helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com
$ helm pull feast-charts --version 0.31.1
$ tar xf feast-0.31.1.tgz

$ cd feast 
```
$ vim override.yaml
redis:
  # redis.enabled -- Flag to install Redis
  enabled: true
  # redis.usePassword -- Disable redis password
  usePassword: false


feature-server:
    application-override.yaml:
        enabled: true
        feast:
            active_store: online
            stores:
            - name: online
              #type: REDIS
              type: sqlite
              path: data/online_store.db
              config:
                host: localhost
                port: 6379
            entityKeySerializationVersion: 2

global:
  registry:
    path: /root/data/registry.db
    cache_ttl_seconds: 60
  project: feast_java_demo
  provider: local
```

$ helm install feast .  -f values.yaml -f override.yaml  -n feast --create-namespaces

```
$ kubectl logs -f feast-feature-server-6d44cb7cf-2pt7r -n feast
......
.....
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: RuntimeException: Couldn't read local registry file: /root/data/registry.db. Error: /root/data/registry.db
  at RegistryConfigModule.registryFile(RegistryConfigModule.java:52)
  at RegistryConfigModule.registryRepository(RegistryConfigModule.java:72)
      \_ for 1st parameter
  at RegistryConfigModule.registryRepository(RegistryConfigModule.java:72)
  at ServingServiceV2Module.registryBasedServingServiceV2(ServingServiceV2Module.java:40)
      \_ for 2nd parameter
  at ServingServiceV2Module.registryBasedServingServiceV2(ServingServiceV2Module.java:40)
  at OnlineServingGrpcServiceV2.<init>(OnlineServingGrpcServiceV2.java:33)
      \_ for 1st parameter
  at ServerModule.provideGrpcServer(ServerModule.java:43)
      \_ for 2nd parameter
  at ServerModule.provideGrpcServer(ServerModule.java:43)
  while locating Server

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
```

### Specifications

- Version: feast-0.31.1
- Platform: amd x86_64
- Subsystem: ubuntu20.04 

## Possible Solution

https://github.com/feast-dev/feast/blob/master/examples/python-helm-demo/README.md
Above is the reference I saw.
This reference is so fragmented that I don't know how to integrate it with feast.

## My Confusion
I think the chart itself is problematic or the installation documentation you provided is incomplete.. I installed feast through pip on an ubuntu, then feast init, feast apply, and finally I can access the UI through port 8888.

But there is no feast init or feast apply command in this chart, and port 8888 is not seen in the service.

In addition, if the registry specifies S3://XXX/XXX, where to specify the access key? Please give an example.

If the registry specifies local, why is my report wrong? I just hope to see an example that I can install it successfully in kubernets immediately and access port 8888.

**Comment by redhatHameed** [comment]
just sharing the steps if you tried with this

**Add the Feast Helm repository and update**

  helm repo add feast-charts https://feast-helm-charts.storage.googleapis.com
  helm repo update

**Deploy Feast on Openshift using Helm, by setting feature_store.yaml file as a base64 string from feature_repo directory**:

  helm install feast-release feast-charts/feast-feature-server \
  --set feature_store_yaml_base64=$(base64 < feature_store.yaml)

**Comment by jeremyary** [comment]
Hi @zibuyule, given the original timeframe of this issue and our current ability to work through the same use case, I'm moving to close this issue, however, should the issue persist for you please feel free to reach out here & let us know. Thanks!
