### ISSUE TITLE
Feast not loading any entities in Google Colab

### ISSUE THREAD

**Issue by cristiscu** [feast-dev/feast#3738]
## Expected Behavior 
`!feast apply` should load entities in the store
## Current Behavior
`!feast apply` creates the feature store, but leaves it empty
## Steps to reproduce
1. In Colab, open the [quickstart sample notebook](https://colab.research.google.com/github/feast-dev/feast/blob/master/examples/quickstart/quickstart.ipynb) for Feast on Google Colab. (As alternative, you may also load my similar smaller notebook [from here](https://github.com/cristiscu/ml-experiments/blob/main/feast_from_colab.ipynb))
2. Install feast with pip and restart the runtime, as required.
3. Execute each cell, until after the` !feast apply` step.
4. Append a `!feast entities list` cell and run it --> the list is empty
### Specifications

- Version: Feast SDK Version: "feast 0.33.1"
- Platform: Google Colab (online)
- Subsystem:

**Comment by adchia** [comment]
Not sure if this was fixed, but just tried this and it seemed to work fine o.O
