### ISSUE TITLE
Is this repo inactive?

### ISSUE THREAD

**Issue by sudohainguyen** [feast-dev/feast#3742]
## Current Behavior

Hence, Feast is still being used widely, we encountered bugs and also made contributions, but seems like CI flow got broken for days with no recovery actions.

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution
Open for new maintainers?

**Comment by shuchu** [comment]
The CI flow seems working now. We still have a few maintainers working on this project. Please have faith in us.
