### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by Chetan1600** [feast-dev/feast#3770]
I pip installed feast and tried feast init my_project

got the following error 
anaconda3\envs\feast_env\lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

- Version: 0.34.1
- Platform: windows 10
- Subsystem:

I tried researching on that error it shows 
The fcntl module is not available on Windows. The functionality it exposes does not exist on that platform.

Please help me solve the above issue

**Comment by lidpeng** [comment]
Hello, I have encountered the same issue as you. I have noticed that the reason for this error is due to the use of the Gunicorn library in the new version of Feast, which does not support Windows. Therefore, I resolved this issue by demoting the Feast.
`pip install feast==0.31.0`
