### ISSUE TITLE
No such option: -f for feast CLI

### ISSUE THREAD

**Issue by alexander-pv** [feast-dev/feast#3771]
## Expected Behavior 

According to documentation:
https://docs.feast.dev/how-to-guides/feast-snowflake-gcp-aws/structuring-repos
```
feast -f staging/feature_store.yaml apply
```
should work

## Current Behavior

```
Usage: feast [OPTIONS] COMMAND [ARGS]...
Try 'feast --help' for help.

Error: No such option: -f
```
### Specifications

- Version: 0.34.1
- Platform: Linux
- Subsystem:

**Comment by sudohainguyen** [comment]
try `-c staging` instead

**Comment by majamil16** [comment]
I think this is just a docs error. The [correct flag ](https://github.com/feast-dev/feast/blob/2192e6527fa10f1580e4dd8f350e05e45af981b7/sdk/python/feast/cli.py#L74)is `--feature-store-yaml` if you need this functionality, eg 

```
feast --feature-store-yaml=staging/feature_store.yaml apply
```

**Comment by majamil16** [comment]
> I agree.

I'm happy to open a PR to update these docs.

**Comment by shuchu** [comment]
go for it if you have time. :)
