### ISSUE TITLE
Registry path postgresql://user:pwd@server/dbname has unsupported scheme postgresql. Supported schemes are file, s3 and gs. Getting this error while using postgres as Registry and Redis as Online store.

### ISSUE THREAD

**Issue by KantSagar** [feast-dev/feast#3798]
### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by sudohainguyen** [comment]
have you try installing extra `postgres`?
`pip install feast[postgres]`

**Comment by jeremyary** [comment]
Hi @KantSagar, given the timeframe of this issue and our inability to reproduce with recent code, I'm moving to close this issue. However, should the issue persist, please feel free to reach out here & let us know. Thanks!
