### ISSUE TITLE
Got ConflictingFeatureViewNames error while running feast apply in the streaming features tutorial

### ISSUE THREAD

**Issue by romqn1999** [feast-dev/feast#3805]
## Expected Behavior
Expected to successfully register data sources and features as the first cell in [the streaming features tutorial](https://github.com/feast-dev/streaming-tutorial/blob/main/kafka_spark_demo/feature_repo/streaming_features_tutorial.ipynb)

## Current Behavior
I am running [the streaming features tutorial](https://github.com/feast-dev/streaming-tutorial/blob/main/kafka_spark_demo/feature_repo/streaming_features_tutorial.ipynb) with the Feast version `0.34.1` and got the error `feast.errors.ConflictingFeatureViewNames: The feature view name: driver_hourly_stats_stream refers to feature views of different types` while executing `feast apply`.

## Steps to reproduce
- Clone the tutorial: `git clone https://github.com/feast-dev/streaming-tutorial.git`
- Install Feast (current version is `0.34.1`): `pip install 'feast[redis]'`
- Run the command `feast apply` and get the `ConflictingFeatureViewNames` error

### Specifications

- Version: 0.34.1
- Platform: Linux
- Subsystem: CentOS Linux release 7.9.2009 (Core)

## Possible Solution
We can fix the error by implementing the override for the [`proto_class`](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/base_feature_view.py#L88) property in the [StreamFeatureView](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/stream_feature_view.py) class:
```python
    @property
    def proto_class(self) -> Type[StreamFeatureViewProto]:
        return StreamFeatureViewProto
```

**Comment by shuchu** [comment]
I checked the code and agree with your proposed fix.  The proto_class() function is not overloaded in the current implementation (master branch after v0.34.1). let me fix this.
