### ISSUE TITLE
example_repo.py 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

### ISSUE THREAD

**Issue by resonates7** [feast-dev/feast#3811]
Hi,

I noticed an error in line 28 of example_repo.py that was throwing the below error. I easily fixed it by adding an 'r' in front of the file path. I'd love to fix this issue if someone will tell me how. Do I just open a new feature branch and submit a pull request? Sorry, I'm new to open-source projects.

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

![image](https://github.com/feast-dev/feast/assets/49754697/2d157736-e7eb-457a-ac56-cdaf87561ac7)

**Comment by redhatHameed** [comment]
not reproducible at my side at Mac OS. Possibly specific to window OS.  
@resonates7 
Just checking if this issue still valid with latest version.

**Comment by jeremyary** [comment]
My suspicion is that this is environment-specific & related to this specific pathing (and possibly Windows best practice). Prepending `r` on the path is indicating that the value should be considered almost raw / unescaped, thus allowing it to work around the Windows directory format. 

Closing this issue for now, but should the issue persist or you feel this insufficient, please feel free to let us know here. Thanks!
