### ISSUE TITLE
google-cloud-bigquery 3.13.0 breaking change

### ISSUE THREAD

**Issue by tfusillo** [feast-dev/feast#3823]
## Expected Behavior 
Successfully get the pyarrow datatype from a feast ValueType using the `feast_value_type_to_pa` function

## Current Behavior
Currently receive the error `feast.errors.FeastExtrasDependencyImportError: cannot import name 'ARROW_SCALAR_IDS_TO_BQ' from 'google.cloud.bigquery._pandas_helpers'`

## Steps to reproduce
Install feast with the latest GCP dependencies and try to convert a feast schema to pyarrow through the use of the function `feast_value_type_to_pa` 

### Specifications

- Version: 0.34.1
- Platform: Linux
- Subsystem: Debian 11 (bullseye)

## Possible Solution
Downgrade to google-cloud-bigquery 3.12.0

**Comment by achals** [comment]
@tfusillo mind making a PR for this?

**Comment by qianshi508** [comment]
I got the same error with 

> google-cloud-bigquery==0.32.1
> feast[redis,gcp]==0.33.1

**Comment by sudohainguyen** [comment]
yep we should set the upper bound for bigquery client

**Comment by fsalazarh** [comment]
Same issue here!! With `google-cloud-bigquery==3.13.0`.

Resolved by downgrading to 3.12.0
