### ISSUE TITLE
 two featureviews share the same name between stream feature views and regular feature views

### ISSUE THREAD

**Issue by sutodi** [feast-dev/feast#3836]
I have a stream feature view running fine in 0.29. When upgrading to 0.34, getting error on doing feast apply
“feast.errors.ConflictingFeatureViewNames: The feature view name: job_stream refers to feature views of different types.”
Printing type in registry.py in function _check_conflicting_feature_view_names where error is coming.
“print(“feature view instance”, feature_view.proto_class, type(name_to_fv_protos.get(feature_view.name)))”
getting output:
feature view instance <class ‘feast.core.FeatureView_pb2.FeatureView’> <class ‘feast.core.StreamFeatureView_pb2.StreamFeatureView’>
I feel like this might be because of https://github.com/feast-dev/feast/pull/3582

**Comment by sutodi** [comment]
@loftiskg @achals @adchia

**Comment by shuchu** [comment]
Yes, it was fixed :)

**Comment by redhatHameed** [comment]
Thanks @shuchu for confirming.

@jeremyary @etirelli can you help to close this.
