### ISSUE TITLE
Feast Security?

### ISSUE THREAD

**Issue by jeanphi06** [feast-dev/feast#3842]
Hi ,

Currently studying Feast to see if it can fit our needs.   I'm interesting in Security concept implemented in Feast.  Looking at the documentation i found that page :  https://docs.feast.dev/v/v0.11-branch/feast-on-kubernetes/advanced-1/security

But this page does not exist anymore after branch v0.11  .  Is it implemented in 0.34?  Where can i find up to date documentation on what is currently implemented and how to use it?

thanks and Kind Regards.

**Comment by tokoko** [comment]
The docs linked above is outdated. The work to reintroduce security layer is currently underway and tracked in #4198. I'll go ahead and close this one.
