### ISSUE TITLE
The Future of Feast

### ISSUE THREAD

**Issue by ChuckHend** [feast-dev/feast#3862]
Given https://www.tecton.ai/blog/announcement-doubling-down-on-production-ai/, what are the plans for Feast? My understanding is that Tecton has been the main driver behind this project's resources.

**Comment by shuchu** [comment]
It should not be an issue :p.  Still, many developers want to contribute to this project. Right now, Tecton is working on finding an idea Maintainer. We are waiting for this to be done.

**Comment by woop** [comment]
Hy @ChuckHend, we just had a community call last week where we discussed next steps for Feast. There are still many teams actively using the project and also interested in contributing back!

**Comment by robhowley** [comment]
@woop for those who missed the call, any insight into the time commitment the current tecton maintainers will be able to put in to code reviews and security patches until a handoff is completed?

**Comment by woop** [comment]
Hey @robhowley, we're still chatting to folks. Time towards code reviews is unclear, but a handover to new maintainers should be smooth. We're still fleshing that out but it's taking a bit longer due to the EOY break.

**Comment by robhowley** [comment]
thanks for the update!

**Comment by EXPEbdodla** [comment]
Community call details are missing in  https://docs.feast.dev/community page. Are there any recording or meeting invites information for future community calls? Thank you.

**Comment by woop** [comment]
Hey folks, just a quick update here. We're still in the handover process trying to make sure all project resources are fully migrated and usable by maintainers. We're hoping to unblock PRs/reviews and releases soon. We're also planning to update broken links and make sure that community calls are recorded and visible for folks that can't join them.

Appreciate all your patience!

**Comment by cburroughs** [comment]
Thank you for the update. 

I appreciate the thought and care going into the handover and making Feast a viable long term community project.   Even if it isn't with the desired end-state process, I am compelled to nudge on getting a release out the door as the pyarrow security issue in #3841 is rather high impact.

**Comment by woop** [comment]
Thanks @cburroughs - That's on myself and @franciscojavierarceo to push over the line asap.

**Comment by woop** [comment]
Hey @cburroughs I've just cut a release. So all merged PRs should now be in 0.35.0. We can have a fast follow release for all other PRs that are going to get merged in the next week or two.

**Comment by cburroughs** [comment]
Thank you!

**Comment by shuchu** [comment]
As for Feb 17 2024. The Feast project is in good shape now.

**Comment by cburroughs** [comment]
Should we link to the blog posts(s) for people who stumble upon this issue in the future?

**Comment by franciscojavierarceo** [comment]
i think that would make sense.
