### ISSUE TITLE
Big Query upgraded needed to causing FeastExtrasDependencyImportError

### ISSUE THREAD

**Issue by Vishnu-Rangiah** [feast-dev/feast#3870]
## Expected Behavior 
BQ .get_historical_features() works fine

## Current Behavior
Getting big-query dependency error since [ARROW_SCALAR_IDS_TO_BQ](https://github.com/googleapis/python-bigquery/blob/d225a94e718a85877c495fbd32eca607b8919ac6/google/cloud/bigquery/_pyarrow_helpers.py#L73) has moved to _pyarrow_helpers.py module in google-cloud-bigquery library 

Is it possible to upgrade the bigquery dependency version and [fix this import statement.](https://github.com/feast-dev/feast/blob/052182bcca046e35456674fc7d524825882f4b35/sdk/python/feast/infra/offline_stores/bigquery.py#L62C5-L62C77) I have other modules and functionality which require google-cloud-bigquery 3.14.1 with along with using feast. 

```
feast.errors.FeastExtrasDependencyImportError: cannot import name 'ARROW_SCALAR_IDS_TO_BQ' from 'google.cloud.bigquery._pandas_helpers' (/Users/v0r03c0/.pyenv/versions/3.8.10/lib/python3.8/site-packages/google/cloud/bigquery/_pandas_helpers.py)
You may need run pip install 'feast[gcp]'

```
### Specifications

- Version: Feast 0.34.1
- Platform: Mac OS Ventura 13.6.3
- Subsystem: 

## Possible Solution
Upgrade big-query dependency, fix import statement

**Comment by sudohainguyen** [comment]
hey @Vishnu-Rangiah this should be resolved in the latest release v0.35.0
