### ISSUE TITLE
move dependency and virtual env management to poetry

### ISSUE THREAD

**Issue by robhowley** [feast-dev/feast#3875]
**Is your feature request related to a problem? Please describe.**
Manage python dependencies via poetry for simpler builds and virtual env management.

**Describe the solution you'd like**
Would like to see poetry configs added to the existing `pyproject.toml` and a `poetry.lock` committed to the project. 

**Describe alternatives you've considered**
Stick with current `setup.py`

**Additional context**
The [affirm/feast](https://github.com/Affirm/feast/blob/0.28-affirm/pyproject.toml) fork implemented this and can be used as inspiration. Looks like @franciscojavierarceo and @hao-affirm did so [here](https://github.com/Affirm/feast/commit/a291bdd91375eced34460a33e65622d3321ee4ed).

**Comment by sudohainguyen** [comment]
although a fan of poetry but I don't think if there is a significant impact adopting poetry, would cause unnecessary complexity, especially when connecting between `setup.py` and `poetry.lock` 🤔
