### ISSUE TITLE
usage.feast.dev ssl cert wrong

### ISSUE THREAD

**Issue by babyhuey** [feast-dev/feast#3886]
Looks like ssl cert got updated yesterday, and it's set for *.netlify.app and causing issues in logs: 
![image](https://github.com/feast-dev/feast/assets/7751607/fdb9f25d-b5a3-4d9f-971f-a240339abb18)

```
WARNING   2024-01-16 16:46:30,278 urllib3.connection.connection:547 | Certificate did not match expected hostname: usage.feast.dev. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'California'),), (('localityName', 'San Francisco'),), (('organizationName', 'Netlify, Inc'),), (('commonName', '*.netlify.app'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert Global G2 TLS RSA SHA256 2020 CA1'),)), 'version': 3, 'serialNumber': '03ED167A2659DA278E7B21CDBEB33E32', 'notBefore': 'Jan 15 00:00:00 2024 GMT', 'notAfter': 'Feb 14 23:59:59 2025 GMT', 'subjectAltName': (('DNS', '*.netlify.app'), ('DNS', 'netlify.app')), 'OCSP': ('http://ocsp.digicert.com/',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertGlobalG2TLSRSASHA2562020CA1-1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertGlobalG2TLSRSASHA2562020CA1-1.crl', 'http://crl4.digicert.com/DigiCertGlobalG2TLSRSASHA2562020CA1-1.crl')}
```

**Comment by robhowley** [comment]
ran into the same issue. as a stopgap, i set `FEAST_USAGE` to `false` and it went away. I know I shouldn't really be advocating for people to work around feast telemetry, but it should keep things quiet until a real fix goes in.

**Comment by tokoko** [comment]
This has already been fixed, right?

**Comment by redhatHameed** [comment]
found similar warnings when using Feast in OpenShift/Kubernetes but setting environments  ```FEAST_USAGE=False``` and it get disappeared.

**Comment by SeanWidesense** [comment]
When running "feast serve" the certificate warning still appears as of a pip download on Feb 25, 2024.

**Comment by shuchu** [comment]
let's disable the feature of "usage.feast.dev". It will be more useful for the users who use Feast at Enterprise level.
