### ISSUE TITLE
It is possible to materialize in S3 from multiple data sources?

### ISSUE THREAD

**Issue by andre-yai** [feast-dev/feast#3887]
**Problem Statement:**

The current implementation lacks support for materializing data in S3 from multiple sources, including S3 file source, RDS, Athena, and Redshift. This capability is crucial for scenarios where data needs to be consolidated from diverse sources into a single destination in S3.

**Expected Behavior:**

The Materialize process should be enhanced to seamlessly handle data extraction and consolidation from various sources such as S3 file source, RDS, Athena, and Redshift. The goal is to empower users to efficiently and flexibly manage data flows across these different platforms.

**Comment by tokoko** [comment]
> The current implementation lacks support for materializing data in S3 from multiple sources

Hi, can you clarify what you mean here? In feast, `materialize` refers to ingesting data from offline sources to online stores (redis for example). There's no concept of materialization to S3.
