### ISSUE TITLE
Deprecate PostgreSQLRegistryStore

### ISSUE THREAD

**Issue by tokoko** [feast-dev/feast#4020]
Right now we have 2 ways to use postgres as a registry backend. The first is with scalable `SqlRegistry` that uses `sqlalchemy`, another is an older option of using `PostgreSQLRegistryStore` which keeps the whole proto in a single table. Since we are [recommending](https://docs.feast.dev/tutorials/using-scalable-registry) the scalable registry anyway, we should deprecate `PostgreSQLRegistryStore` and remove it soon after. Or maybe remove it directly? It's under contribs as of now.

**Comment by HaoXuAI** [comment]
I agree it make sense to remove the `PostgreSQLRegistryStore`. but it might cause incompatibility if someone still specify it in `registry_store_type`. probably need to point it to the `sqlregistry` as well.

**Comment by tokoko** [comment]
Do you mean rewiring one registry_store_type to point to other? I think that'll be too hard to figure out as the way they store protos in the database is completely different, plus the way they are configured from `RepoConfig` is also not exactly the same. Better to deprecate it and throw a warning instructing users to move to sql registry themselves.

**Comment by HaoXuAI** [comment]
i mean to update https://github.com/feast-dev/feast/blob/a0f7472f200300f3a45aa404922dd67bb4ad237f/sdk/python/feast/infra/registry/registry.py#L59 to point to sqlregistry directly. not sure if that will work.

**Comment by tokoko** [comment]
That will fail, `SqlRegistry` expects the protos to be stored in a particular way. It won't be able to read the existing registry data written previously by `PostgreSQLRegistryStore`.

**Comment by HaoXuAI** [comment]
> That will fail, `SqlRegistry` expects the protos to be stored in a particular way. It won't be able to read the existing registry data written previously by `PostgreSQLRegistryStore`.

I see. let's deprecate it then.
