### ISSUE TITLE
SqlRegistry _apply_object doesn't take into account match with project_id when updating row

### ISSUE THREAD

**Issue by Nmroth42** [feast-dev/feast#4027]
SqlRegistry _apply_object doesn't take into account match with project_id when updating row.
https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/registry/sql.py#L736

Wrong (as is):
.where(getattr(table.c, id_field_name) == name) 

Correct:
.where(getattr(table.c, id_field_name) == name, table.c.project_id == project)

**Comment by tokoko** [comment]
@Nmroth42 thanks, would you like to open a PR for this?
