### ISSUE TITLE
Remote offline feature server deployment

### ISSUE THREAD

**Issue by tokoko** [feast-dev/feast#4032]
**Is your feature request related to a problem? Please describe.**

Currently Feast has the capability to deploy both online store (feature server) and registry as standalone services that feast library can access remotely. I'd like to see the same capability with offline store deployment. The primary goal of the feature is to enable fully remote deployment of all feast components and in future enable a common enterprise-level security model for all three components.

**Describe the solution you'd like**
There are two possible general solutions I have in mind:

1. Arrow Flight Server Deployment

We can deploy an offline feature server as an Apache Arrow Flight Server that will wrap calls to offline store implementations and expose interface methods as Arrow Flight endpoints. This is also something that Hopsworks seems to have [implemented](https://www.hopsworks.ai/post/python-centric-feature-service-with-arrowflight-and-duckdb) before. They are using duckdb engine behind a flight server.

2. Metadata Sharing Server Deployment (similar to Delta Sharing)

Offline feature server can be deployed as a lightweight rest or grpc server that only handles requests and metadata and utilizes cloud filesystems for data transfer to and from the user. For example in case of s3, feature server would write out the results as a parquet dataset to a folder in an s3 bucket, generate presigned urls for it and return a list of urls to the caller. The idea is to emulate the mechanics of [delta sharing](https://delta.io/sharing/) but avoid it's limitations (in delta-sharing, dataset needs be in `delta` format and metadata responses must be immediate, which is obviously not an option for feast).

In both scenarios, client-side code should be virtually indistinguishable from other offline store implementations. The particulars of the implementations will be hidden behind RemoteOfflineStore class.

**Comment by tokoko** [comment]
Hey, thanks for getting involved here :)

1. Yes, that's exactly what I mean. The user sets store type to `remote` (for example) and `FeatureStore` client forwards the requests to a remote server rather than executing directly. And also agreed on the "generalize" point as well, I think we should have `remote` options for all three components (online store, offline store, registry):
- We obviously already have a feature server and I have a ticket #4121 for a `remote` client as well. (I may be wrong, but I think Lokesh is working on this.)
- We actually already have a grpc registry server (#3924 it's still read-only at this point though) and `remote` client for it (#3941)
- Once we close this ticket we should have some sort of offline server with it's accompanying `remote` client implementation.

2. Yeah, duckdb is just a choice that they made. feast unlike hopsworks tries to cover as many different configurations as possible (for better or worse 😄) and lets the user choose whatever fits their needs. Any performance optimizations should happen separately on engine level. In our case I think the offline server administrator should have an option to set offline store type to any of the engines supported (incl. duckdb) and that will be the one that flight server will be forwarding the requests to.

3. imho that's the result of inherent duality of feature stores in general, the whole point of it is to be a bridge between offline world and an online one after all. Even if ignore technical difficulties, I think the usage pattern is very different between these components. online store is almost always queried by some software application and is usually very critical in terms latency and availability. offline store is sometimes queried by periodical batch production jobs, but is mainly in service of data scientists running their experiments at their own schedule. That's just the conceptual part... From more technical standpoint, The scale is the first obvious difference. Another problem is that we actually already have two feature servers (http and grpc). Which one would we use as a base? We may have to abandon one of them if we take a "single server" route. Also, I've also tried in the past to combine flight server with normal protobuf rpc service definitions (unrelated to feast) and failed miserably. It's probably doable, but at the cost of going against the way 99% of people out there do these things.

**Comment by redhatHameed** [comment]
Just one thought:  for easiness of use can sdk or remote keep the same `feature_store.yaml` file and simply add a flag 
to indicate whether it's a remote server. For example:
```
offline_store:
  is_remote_server: true  # Flag to indicate whether it's a remote server
  type: postgres
  host: localhost
  port: 5432
```
 
`feature_store.yaml `content can be encoded into base64 and stored as an environment for offline store server as done online store.

**Comment by tokoko** [comment]
@redhatHameed I'm not sure flag is necessary. If we replicate the way remote registry works, on server side `feature_store.yaml` will look identical to how it looks now. The only difference being that someone will need to run `feast serve offline` (just an example, something like this) command to start the server. (For a k8s deployment, one would set a `command` field to `["feast", "serve", "offline"]`):
```
offline_store:
  type: postgres
  host: localhost
  port: 5432
```

On the client-side, the user will have to configure it's client to query the server, it should have no knowledge whatsoever about with type of offline store the server's wrapping. So `feature_store.yaml` for client will look something like this:
```
offline_store:
  type: remote-flight
  host: mystore.feast.svc.cluster.local
  port: 8815
```

**Comment by redhatHameed** [comment]
@tokoko Thanks for clarifying and that make sense.

**Comment by tokoko** [comment]
@dmartinol yes, but let me go a bit more into details just to make sure we're on the same page. The first three of those five methods are lazy, in other words they don't return datasets themselves, they return `RetrievalJob` objects that can be used by the user to get the dataset. So while yes, there should be a way to invoke `GetFlightInfo` on the server with all 3 of them (with dedicated proto message types, I guess), that invocation should only happen when the user does something like the following -> (`store.get_historical_featues(...).to_arrow() // or .to_df()`)

if the user instead opts to call `to_remote_storage()` method on the `RetrievalJob` object, then client implementation will probably have to call the server with similar message types, but on `DoAction` endpoint instead of `GetFlightInfo` as there's no data to be returned directly.

**Comment by dmartinol** [comment]
agree, we must respect the lazy behavior. @redhatHameed we need to experiment on this one as a first step

**Comment by redhatHameed** [comment]
@tokoko one more clarification what you think about `Materializing functionality` will this be part of remote Offline store deployment,  as Feast [documentation](https://docs.feast.dev/getting-started/architecture-and-components/offline-store) mentioned this as primary functionality.

**Comment by tokoko** [comment]
@dmartinol I think starting with `pull_latest_from_table_or_query` might be easiest to get the basic functionality, as there's no need to upload anything the the server.

@redhatHameed that's a very good point. I haven't thought much about it, but I think it should depend on which materialization engine the user has configured. 

- If it's the default one, then data will have to be pulled locally and then ingested to the online store.
- We can create `RemoteMaterializationEngine` (similar to this `RemoteOfflineStore`) that will invoke the same flight server to push entire materialization call to the server. So I guess what I'm saying is that the server we will build now will have to (eventually) act as a backend for both remote offline store and remote materialization engine. Does that make sense?

**Comment by redhatHameed** [comment]
Thanks @tokoko in that case we can create a new issue to address the implementation of the `RemoteMaterializationEngine`, while keeping the focus of this ticket on implementing the `RemoteOfflineStore`. cc @dmartinol

**Comment by dmartinol** [comment]
@tokoko, I see that all the implementations of `BatchMaterializationEngine` already fetch the offline data using the `OfflineStore` interface, as in:
```py
        offline_job = self.offline_store.pull_latest_from_table_or_query(...)
```
That said, if the client doing the materialization already has a remote `offline_store`, I assume that the materialize would work through the flight server, correct? What else could a `RemoteMaterializationEngine` add, in this case?

**Comment by tokoko** [comment]
yup, It would work through the flight server, but only in the sense that the source data will be pulled from there. All the rest of the logic (conversion to arrow and `online_write_batch` calls) will happen locally (in case of local materialization engine, for example). With `RemoteMaterializationEngine`, we could offer another implementation that pushes not only `pull_latest_from_table_or_query`, but the whole materialization pipeline to the server.

**Comment by redhatHameed** [comment]
@tokoko me and @dmartinol created a draft [PR](https://github.com/RHEcosystemAppEng/feast/pull/3). To get your initial input on whether we're heading in the right direction. Please take a look when you time. Thanks cc @jeremyary

**Comment by tokoko** [comment]
@redhatHameed thanks, great work. looks good overall, I'll leave the comments in the PR.

**Comment by redhatHameed** [comment]
@tokoko Thanks for the review and comments. 

Before moving further with this approach do you have idea for implementing a security model that aligns with this (arrow flight server )approach and that fits with other components ?

**Comment by dmartinol** [comment]
> I might be delving into "speculation" territory here, but I can try to describe a high-level overview of what I'm expecting from the security model. ...
> P.S Mostly just thinking out loud here, I might be totally overengineering this 😄

@tokoko, do we have a separate issue dedicated to discussing these details? It appears that the topic is more generic than just the remote offline feature server, and your hints have been really valuable. Having a dedicated space for discussion until we reach a conclusion might be beneficial.

**Comment by tokoko** [comment]
No, we don't. I'll go ahead and split the last comment off as a separate issue.

**Comment by franciscojavierarceo** [comment]
@tokoko whats the benefit of a remote server?aren't we then adding additional network overhead?

The recommended model, in my opinion should be:

1. use Feast SDK server side
2. create SDK to operate with this 

(2) can be evaluated using the python server code.

This is how I did it previously and it worked well but curious to understand benefits of the remote approach.

**Comment by tokoko** [comment]
Yes, it would for most actions add an additional network overhead, that's why we're strictly talking about it as an optional add-on. The biggest upside, the only one really, is that a remote deployment allows you to put it behind your own security layer (3A) which is impossible when a client has a direct access to the data with SDK.

> 2\. create SDK to operate with this

I'm not sure what you mean here.
