### ISSUE TITLE
Feast release cycle?

### ISSUE THREAD

**Issue by job-almekinders** [feast-dev/feast#4040]
Does `feast` follow some release cycle pattern? Or how is determined when a new release should be done?

**Comment by jeremyary** [comment]
heya @job-almekinders, thanks for the ask. If you've not seen, we've recently had a new set of maintainers (incl. myself) step in to help shepherd the Feast project. We're still getting our ducks in a row which means talking through impactful issues on our bi-weekly community [calls](https://calendar.google.com/calendar/u/0?cid=ZTFsZHVhdGM3MDU3YTJucTBwMzNqNW5rajBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) / or via [Slack](https://feast.slack.com). We haven't yet tackled a new release cycle as there's more underlying things needing our attention prior to starting up a cadence, so for now we've been touching base on our community call and cutting releases ad hoc based on those discussions. 

I'm adding the topic to today's community call just to ensure it's visible and keep it in back of minds.

**Comment by job-almekinders** [comment]
Hey @jeremyary, thank you for your response. 

That makes a lot of sense, I hope your efforts are going into a good direction :) 
I unfortunately wasn't able to join last week, I'll try to join the next session!

**Comment by jeremyary** [comment]
@job-almekinders apologies, I goofed the URL. Try hitting [this](https://feast.slack.dev) which should act as an open invite to allow you in instead. 

Also wanted to let you know we're discussing a new release cut which will likely occur next week.

**Comment by job-almekinders** [comment]
> Try hitting https://slack.feast.dev/ which should act as an open invite to allow you in instead.
Ah yes that works, thanks a lot! @jeremyary 

> Also wanted to let you know we're discussing a new release cut which will likely occur next week.
Amazing! Looking forward to the next one :)
