### ISSUE TITLE
Next release 0.37 timeline

### ISSUE THREAD

**Issue by ElliotNguyen68** [feast-dev/feast#4070]
Hi maintainer team, as I observe from previous versions, at about 1 month will have new release, but after 0.36 release, I am waiting for new feature in the next release (0.37) but it seem over 1 month and still not have new version to release on Pypi. I wonder if there is any schedule on this ?

**Comment by jeremyary** [comment]
Hey @ElliotNguyen68, we should have a new release cut very soon as this week is our target, but it seems we're still working out some convos regarding some of the new ODFV changes. Once we're in a good place there, Francisco will be cutting next release for us.

**Comment by franciscojavierarceo** [comment]
Thanks @jeremyary, that's right. We're going to cut a release soon! Just have to patch a bug!

**Comment by ElliotNguyen68** [comment]
Thanks @jeremyary , @franciscojavierarceo  very much

**Comment by jeremyary** [comment]
https://github.com/feast-dev/feast/releases/tag/v0.37.1
