### ISSUE TITLE
Remove numpy <1.25 dependency in setup.py

### ISSUE THREAD

**Issue by softwareentrepreneer** [feast-dev/feast#4084]
In setup.py, I can see that the dependency for pandas has already been updated from 
"pandas>=1.4.3,<2" (which is still in the current PyPI version) to "pandas>=1.4.3,<3", but numpy hasn't, which will break the installation if I am using e.g. pandas 2.2.1, that requires numpy (>=1.26.0,<2)

## Problem
"numpy>=1.22,<1.25"

## Solution
"numpy>=1.22,<2"

## Steps to reproduce
poetry add git+https://github.com/feast-dev/feast.git

**Comment by tokoko** [comment]
@softwareentrepreneer thanks, looks like the pin was [added](https://github.com/feast-dev/feast/commit/774ed33a067bf9bf087520325b72f4f4d194106a) simply to get rid of some deprecation warnings, so this shouldn't be an issue. Would you like to open a PR?

**Comment by softwareentrepreneer** [comment]
> @softwareentrepreneer thanks, looks like the pin was [added](https://github.com/feast-dev/feast/commit/774ed33a067bf9bf087520325b72f4f4d194106a) simply to get rid of some deprecation warnings, so this shouldn't be an issue. Would you like to open a PR?

sure, here is the [PR](https://github.com/feast-dev/feast/pull/4085), thanks for the quick response
