### ISSUE TITLE
NameError: name 'driver_hourly_stats_view' is not defined

### ISSUE THREAD

**Issue by david101-hunter** [feast-dev/feast#4104]
Hi I'm new in Feast

I'm following [Quickstart](https://docs.feast.dev/v/v0.35-branch/getting-started/quickstart) section.

I run code step by step, however at **Step 3e: Using a feature service to fetch online features instead.**, I stuck with a issue

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[/tmp/ipykernel_105582/1668967177.py](https://file+.vscode-resource.vscode-cdn.net/tmp/ipykernel_105582/1668967177.py) in <cell line: 0>()
      1 driver_stats_fs = FeatureService(
----> 2    name="driver_activity_v1", features=[driver_hourly_stats_view]
      3 )

NameError: name 'driver_hourly_stats_view' is not defined
```
How can I overcome this?

Thanks a lot!

**Comment by tokoko** [comment]
It's a typo, should be `driver_stats_fv`.

**Comment by lokeshrangineni** [comment]
created [PR](https://github.com/feast-dev/feast/pull/4120) to fix the documentation issue.
