### ISSUE TITLE
feast serve convert number to INT64 

### ISSUE THREAD

**Issue by Akshay-deqode** [feast-dev/feast#4110]
## Expected Behavior 
when we use the get-online-features endpoint the request body numbers converted to Int64 type and while from python file calling get_online_feature function convert number to Int32 which leads to inconsistency between both use 
if the entity value type is Int32 then feature servering with online feast serve command will not work expected behavior is to convert the value to Int32 while it is being converted to Int64
## Current Behavior
when using feast serve number are converted to Int64 type 
## Steps to reproduce
create a entity with a column with type Int32 create a feature view with the entity apply the changes using feast apply materialize the data to online store start feature server using feast serve and call endpoint /get-online-feature to retrive feature ... expected response is the feature retrived  while it show none due to type issue 
### Specifications

- Version: 0.36
- Platform: 
- Subsystem:

## Possible Solution
before converting the type to Int64 get the repo and convert the type to the entity data type defined 
other solution is just write in doc to use Int64 and Float64 type while defining entity

**Comment by tokoko** [comment]
@Akshay-deqode thanks for filing the issue, I was able to reproduce.
