### ISSUE TITLE
Add possibility to choose database name when using DatastoreOnlineStore

### ISSUE THREAD

**Issue by Pawel-Drabczyk** [feast-dev/feast#4113]
**Is your feature request related to a problem? Please describe.**
When introducing `Firestore in Datastore mode` in place of `Datastore`, Google added a possibility to create multiple databases other than `(default)` (in Datastore there was only one database called `(default)`). Class [DatastoreOnlineStore](https://github.com/feast-dev/feast/blob/ad45bb4ac2dd83b530adda6196f85d46decaf98e/sdk/python/feast/infra/online_stores/datastore.py#L351) still doesn't support using a database with another name.

**Describe the solution you'd like**
I would like to have possibility to choose database name when using DatastoreOnlineStore

**Describe alternatives you've considered**
The alternative is using the `(default)` database. However, it has some disadvantages e.g. it doesn't allow fine-grained permissions for each user.

**Additional context**
[Google Datastore client](https://cloud.google.com/python/docs/reference/datastore/latest/client) supports passing `database` when initializing the client.

**Comment by tokoko** [comment]
thanks, would you like to open a PR for this?

**Comment by Pawel-Drabczyk** [comment]
> thanks, would you like to open a PR for this?

Sure, I will try to prepare sth on Monday :)
