### ISSUE TITLE
Nightly CI runs failing on install-python-ci-dependencies / test-python-integration

### ISSUE THREAD

**Issue by jeremyary** [feast-dev/feast#4163]
## Current Behavior
nightly-ci runs are erroring out, first run with failure can be seen [here](https://github.com/feast-dev/feast/actions/runs/8813278172/job/24190831412#step:19:38).

![image](https://github.com/feast-dev/feast/assets/1012188/35b2d955-4d6d-48fd-8803-5759bf386c41)

**Comment by tokoko** [comment]
thanks, apparently I'm only paying attention to PR checks
