### ISSUE TITLE
Evaluate and improve the WRITE performance of On Demand Feature View

### ISSUE THREAD

**Issue by shuchu** [feast-dev/feast#4207]
## Expected Behavior 

The On Demand Feature View has implementations with using Python nativ object and Pandas object as the input/output.
We want to evaluate the performance in terms of Time. Moreover, we want to understand the bottleneck of the performance in code running efficiency level.

### Specifications

- Version:  0.37.1
- Platform: Linux/Ubuntu
- Subsystem:

## Possible Solution

use cProfile and existing unit test functions.

**Comment by shuchu** [comment]
An easy run shows the performance of Pandas is really bad comparing to Python native objects.

![Screenshot 2024-05-18 231742](https://github.com/feast-dev/feast/assets/1526323/f22aee53-4c74-483e-b7e9-6d2ca3d0405d)
![Screenshot 2024-05-18 231751](https://github.com/feast-dev/feast/assets/1526323/9ae4bfad-0cd5-4691-8e06-dc156893426e)

**Comment by franciscojavierarceo** [comment]
Example code of cProfile with [snakeviz](https://gist.github.com/matthewfeickert/dd6e7a5fda1ed1e3498219dafe5f9ea1).

```python
import cProfile

from scipy.optimize import minimize


def main():
    # c.f. https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html
    func = lambda x: (x[0] - 1) ** 2 + (x[1] - 2.5) ** 2
    x0 = (2, 0)

    constraints = (
        {"type": "ineq", "fun": lambda x: x[0] - 2 * x[1] + 2},
        {"type": "ineq", "fun": lambda x: -x[0] - 2 * x[1] + 6},
        {"type": "ineq", "fun": lambda x: -x[0] + 2 * x[1] + 2},
    )

    bounds = ((0, None), (0, None))

    result = minimize(func, x0, method="SLSQP", bounds=bounds, constraints=constraints)
    print(f"result:\n{result}")
    print(f"best fit parameters: {result.x}")


if __name__ == "__main__":
    profiler = cProfile.Profile()
    profiler.enable()
    main()
    profiler.disable()
    profiler.dump_stats("example.prof")
```

**Comment by franciscojavierarceo** [comment]
Done here: https://github.com/franciscojavierarceo/Python/pull/23

## Pandas
![image](https://github.com/feast-dev/feast/assets/4163062/4595b099-7f9a-4978-a1e4-bce20ec2edd6)

## Python
![image](https://github.com/feast-dev/feast/assets/4163062/44485643-1c15-4063-a463-a70da16382b8)

## Comparison
Local performance
Pandas runtime = 8.65ms
Python runtime = 0.907ms

**Comment by HaoXuAI** [comment]
> Done here: [franciscojavierarceo/Python#23](https://github.com/franciscojavierarceo/Python/pull/23)
> 
> ## Pandas
> ![image](https://private-user-images.githubusercontent.com/4163062/337825531-4595b099-7f9a-4978-a1e4-bce20ec2edd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjczNjYsIm5iZiI6MTczMjIyNzA2NiwicGF0aCI6Ii80MTYzMDYyLzMzNzgyNTUzMS00NTk1YjA5OS03ZjlhLTQ5NzgtYTFlNC1iY2UyMGVjMmVkZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMjIxMTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjFiMDg5ZTE0ODgzMGNlZTQ0ZWFmNTY0ODE2MjViOWMzZjEyNmZlZjU2MmYzZmU5MzU4ZDc2MWVkODc3ZjM4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SGHrJvJGPbFnFYyQ38WfbfjNeFHAQY622kVuwXBR6DM)
> 
> ## Python
> ![image](https://private-user-images.githubusercontent.com/4163062/337825537-44485643-1c15-4063-a463-a70da16382b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjczNjYsIm5iZiI6MTczMjIyNzA2NiwicGF0aCI6Ii80MTYzMDYyLzMzNzgyNTUzNy00NDQ4NTY0My0xYzE1LTQwNjMtYTQ2My1hNzBkYTE2MzgyYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMjIxMTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBhZGVkZWI1YmZlM2E3ZmY3OGJhMjU0OWEwY2IxZTAxMDA5MzE5MmJiODYwMWM2N2U5ZTEyNGRlNWZkMjZlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dn3P7l8Awk2mc441QQDCngoRuS3l0QtcaXOgxamcc38)
> 
> ## Comparison
> Local performance Pandas runtime = 8.65ms Python runtime = 0.907ms
> 
> Nearly 10x reduction in processing time.

really cool.
Is the unit right? ~1ms or ~10ms is super fast :)
