### ISSUE TITLE
venv error python3.10

### ISSUE THREAD

**Issue by L0G1C06** [feast-dev/feast#4229]
## Expected Behavior 
Create feature with feast apply

## Current Behavior
ModuleNotFoundError: No module named 'myenv.lib.python3'

## Steps to reproduce
python3 -m venv myenv
source myenv/bin/activate
pip install feast
feast apply

### Specifications

- Version: 0.38.0
- Platform: python3.10
- Subsystem: linux

## Possible Solution
nothing yet, but open to contribute

**Comment by shuchu** [comment]
Do we have a 0.38.0 release now?

**Comment by L0G1C06** [comment]
> Do we have a 0.38.0 release now? 
> @L0G1C06  do you mind to do a double check? 

I have installed using pip. The version from pip freeze is 0.38.0

**Comment by shuchu** [comment]
I see. sorry for my lag. Thank you @L0G1C06! Let me check this.
