### ISSUE TITLE
Update the Snowflake document to mention the SQL query string limitation.

### ISSUE THREAD

**Issue by shuchu** [feast-dev/feast#4242]
Based on the feedback from the Feast community:

====
Hey team! I’m having a problem when running a materialization in Snowflake. [Here](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/materialization/snowflake_engine.py#L271C95-L271C117), this is executed:

```
query = f"""SELECT SYSTEM$LAST_CHANGE_COMMIT_TIME('{feature_view.batch_source.get_table_query_string()}') AS last_commit_change_time"""
```

The problem is that if feature_view.batch_source.get_table_query_string() returns something with ' , that single quotes breaks when running in snowflake.
If I’m using a query like:
```
SELECT
    some_column
FROM
    some_table
WHERE
    other_column = 'value'
That 'value' fails in Snowflake because of the extra quotes.
```
====

That 'value' fails in Snowflake because of the extra quotes.

For snowflake, it’s workable by quoting strings with $$ :
```
SELECT
    some_column
FROM
    some_table
WHERE
    other_column = $$value$$
```
I faced this some times, where I was able to apply a feature definition, but then the materialization failed due to an error on one of the queries used to generate the materialization

As snowflake requires strings to be between $$ or '.  
reference: https://docs.snowflake.com/en/sql-reference/data-types-text#single-quoted-string-constants

- Version: 0.38.0
- Platform:
- Subsystem:

**Comment by sfc-gh-madkins** [comment]
@shuchu can you post the full query from snowflake query history so I can better understand?

**Comment by shuchu** [comment]
@sfc-gh-madkins  Hi Miles, sorry for the late reply. The issue was reported by [Franco Bocci on May 24th ](https://feastopensource.slack.com/archives/C01NTDB88QK/p1716562814534799)in the slack "feast-development" channel. I don't know the failed original query actually.
