### ISSUE TITLE
Ingestion and batch retrieval timestamp column name are inconsistent

### ISSUE THREAD

**Issue by khorshuheng** [feast-dev/feast#429]
## Expected Behavior 
Ingestion and batch retrieval should use either "datetime" or "event_timestamp" and stick to one convention.

## Current Behavior
During ingestion, the function expects the input dataframe to have a column named "datetime". However, this column is later renamed in-place to "event_timestamp" and saved as avro. 

During batch retrieval, "event_timestamp" column is returned instead of "datetime".

## Steps to reproduce
- Batch retrieval does not have any column named "datetime"

## Possible Solution
- Use event timestamp as datetime column instead of "datetime", on the client side.
- Keep the current client behaviour, but the server should expect "datetime" column instead of "event_timestamp".

**Comment by woop** [comment]
I think the solution here is to rename the returned datetime column to `datetime`. We want to separate event and processing timestamps in the backend, but we dont want user to be exposed to them. Although this does make things a bit harder for us.

**Comment by woop** [comment]
This issue is stale. Closing for now.
