### ISSUE TITLE
FeastObject type is missing SavedDataset

### ISSUE THREAD

**Issue by dmartinol** [feast-dev/feast#4312]
## Expected Behavior 
FeastObject should include all types of instances applied to the feature store.

## Current Behavior
It misses SavedDataset type.

### Specifications

- Version: 0.39.0

**Comment by dmartinol** [comment]
@tokoko

**Comment by tokoko** [comment]
Agreed, I'd add that although class `BatchFeatureView` exists in the codebase, it's basically unused at this point and not part of registry CRUD operations. Even if it was, once #4235 gets resolved, do you think it's still a good idea not to treat FeatureViews as a single object type?

**Comment by dmartinol** [comment]
Can I take this one and send a PR?

**Comment by tokoko** [comment]
sure, go ahead

**Comment by dmartinol** [comment]
> Even if it was, once https://github.com/feast-dev/feast/issues/4235 gets resolved, do you think it's still a good idea not to treat FeatureViews as a single object type?

I'm not against having a single type but I cannot estimate the impacts on the registry (endpoints and diff logic).
In the permission model we're using a filter to allow selecting only specific types and exclude sub-classes, which again should be reviewed. 

Pls note that `OnDemandFeatureView` is a `BaseFeatureView` only, this would either need its entry in `FeastObject` or to review its hierarchy.
