### ISSUE TITLE
no image `feastdev/feast-operator:0.37.0` 

### ISSUE THREAD

**Issue by jaffe-fly** [feast-dev/feast#4342]
## Steps to reproduce
`kubectl describe pod feast-operator-controller-manager-b876dfd64-8c8gs -n feast-operator-system`

get error
`Back-off pulling image "feastdev/feast-operator:0.37.0"`
### Specifications

- Version: github master repo
- Platform: centos
- Subsystem:

**Comment by shuchu** [comment]
@jaffe-fly  check this page: https://hub.docker.com/r/feastdev/feast-operator/tags
 v0.37.0 is an old version. try the latest version.
