### ISSUE TITLE
Update CI to have a test for main feast dependency before release/deployment

### ISSUE THREAD

**Issue by franciscojavierarceo** [feast-dev/feast#4344]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As seen in https://github.com/feast-dev/feast/issues/4293, the PyPi package failed because of a dependency in a feast installation that uses an [extra](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-setuptools-extras).

```bash
pip install feast[sqlite_vec]
```

This can be added to the existing [build_wheels ci](https://github.com/feast-dev/feast/blob/master/.github/workflows/build_wheels.yml)  by testing a python import. If the import fails, we should fail the build/release.

**Describe alternatives you've considered**
We should have the CI test building the main feast package before release/deployment as well each extra/add-on.

**Additional context**

**Comment by tokoko** [comment]
Not exactly the same, but this can be mostly covered by #4185 I think.

**Comment by franciscojavierarceo** [comment]
We should have the quickstart run before the release as well: https://docs.feast.dev/getting-started/quickstart

**Comment by dmartinol** [comment]
> This can be added to the existing [build_wheels ci](https://github.com/feast-dev/feast/blob/master/.github/workflows/build_wheels.yml) by testing a python import. If the import fails, we should fail the build/release.

What module would you import, how can we know the modules to validate? I tried with the blamed version 0.39.0:
```console
% pip install -q feast==0.39.0
% feast version
Feast SDK Version: "0.39.0"
% python -c "import feast"
% python -c "import sqlite_vect" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sqlite_vect'
```

**Comment by franciscojavierarceo** [comment]
You have a typo in "vec"

**Comment by franciscojavierarceo** [comment]
But this CI validation would ideally run on all of the extras.

**Comment by dmartinol** [comment]
> You have a typo in "vec"
thanks for noticing, anyway it fails (as expected) for version 0.39.0:
```console
% python -c "import sqlite_vec"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sqlite_vec'
```

> But this CI validation would ideally run on all of the extras.
You mean:
- read all the extras configured in `setup.py`
- for each extra module `m` run `python -c "import <m>" || exit 1`
