### ISSUE TITLE
feast materialize can not load all data  into online store

### ISSUE THREAD

**Issue by jaffe-fly** [feast-dev/feast#4358]
## Expected Behavior 
when materialize START_TS and END_TS timedelta bigger than parquet file timedelta,all parquet data can load online store
## Current Behavior
command is `feast materialize 2017 2024`,only import a few limited pieces of data
the log is
```
07/17/2024 08:58:50 PM root WARNING: _list_feature_views will make breaking changes. Please use _list_batch_feature_views instead. _list_feature_views will behave like _list_all_feature_views in the future.
Materializing 2 feature views from 2017-07-17 08:00:00+08:00 to 2024-07-17 08:00:00+08:00 into the postgres online store.

driver_hourly_stats_fresh:
15it [00:00, 41.94it/s]                                                                             
driver_hourly_stats:
15it [00:00, 105.43it/s]
```
the online store pg is
![image](https://github.com/user-attachments/assets/3e795e35-5d27-4120-b49d-d6a4989d1672)

the parquet data is from `feast init`,and the code is also from it
the parquet file has 1808 records
![image](https://github.com/user-attachments/assets/661df835-3fa1-4c8e-a979-9fb58ee9ca42)

### Specifications

- Version: Feast SDK Version: "0.39.0"
- Platform: centos

**Comment by tokoko** [comment]
@jaffe-fly materialize is supposed to write only a single value (the latest one) per each entity id (in this case `driver_id`), so the number of rows in postgres will definitely be fewer than 1808, it should be the number of unique drivers in the parquet dataset. Can you check whether that is what's happening here?

**Comment by jaffe-fly** [comment]
but from now, no specific  entity id  is used，and any `driver_id` in the parquet file has more data than in pg.

**Comment by jaffe-fly** [comment]
thank you, i am get you said.
