### ISSUE TITLE
Feast s3 support

### ISSUE THREAD

**Issue by absingh-coursera** [feast-dev/feast#4397]
**Is your feature request related to a problem? Please describe.**
Hi Team, I am trying to use feast as an alternative to sagemaker feature store but here are some constraint due t which I am raising this issue

- We right now using redshift + databricks as our dataware house and moving slowly towards databricks as only ground truth
- due to certain reason I can't use redshift and don't want to use rds as we don't really use it and just using and maintaining it for feature store is not what I am looking forward.

**Describe the solution you'd like**
There are two ideal solution I would like to see

- S3 as offline store but not like just using single file but more like standard one where feast is maintain partition of primary data and not like just using a single file.

**Describe alternatives you've considered**
- since there are not many open source feature stores so our best shot is with feast or start using databricks feature store.

**Additional context**
Most of the the context I have cleared above if there are any questions I am happy to answer.

**Comment by tokoko** [comment]
@absingh-coursera Hey, I think you might be somewhat confusing the concepts of `DataSource` and `OfflineStore` here. Offline stores in feast are engines (not storage) by which feast gets the offline datasets, joins them and produces the training set. s3 alone can't be an offline store implementation as you can't do data transformations in s3. There are currently 2 ways you can use s3 to store offline features:
- You can use `FileSource` to point to s3 folders, but `FileSource` data source type can currently be queried by duckdb and dask offline stores only.
- You can use `SparkSource` which is a generic data source for `SparkOfflineStore`. as long as you are able to configure spark session to access s3 locations, you can accomplish the same thing with it. If you're trying to use feast in databricks, this is probably the best way to go for you.

**Comment by tokoko** [comment]
> I built feature view with `SparkOfflineSource` and points it towards a folder containing partioned parquet files.

Yes, today you need to use `SparkSource` for this. We plan to add `FileSource` support to spark offline store as well in the future. It will behave identically, with the only difference being that with `FileSource` you will no longer be bound to spark offline store only. You can have some feast processes running with spark on databricks and some other processes elsewhere with duckdb or dask.



> So how does feast knows new data has been ingested in offline store ? when I call Materialize if goes to same folder and checks for latest update right ?

When you use `materialize`, you are the one who provides lower and upper bound of event_timestamp column to acquire the dataset from offline. In case you use incremental materialization, then feast stores last upper bound in the registry and uses that for the next run. ([docs](https://docs.feast.dev/reference/feast-cli-commands#materialize))

> since I want to maintain individual folders for individual feature views will it affect feast feature gathering ? while building training set during offline feature retrival.

Not sure I get the question. Each table behind a feature view needs to be in a separate "folder" in s3, of course.

**Comment by absingh-coursera** [comment]
thanks @tokoko this makes it much clear.

**Comment by tokoko** [comment]
you're welcome. I'll go ahead and close this then.

**Comment by younghun-jo-levit-com** [comment]
@tokoko Hi I read all above comments and I can use spark as offline store and s3 as data source. But I can't do it by below error. I attached `feature_view.py` for defining feature view and `feature_store.yaml`. 
- feature_view.py
```python
from datetime import timedelta

from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource
from feast import Entity, FeatureView, Field
from feast.types import String, Float32, Array

s3_path = "s3a://my-bucket/test-data"

# Step01) Entity
user = Entity(name="user", join_keys=["user_id"])

# Step02) Offline Store Source
spark_src = SparkSource(
    name="dummy-spark-source",
    path=s3_path,
    file_format="parquet",
    timestamp_field="ts"
)

# Step03) Feature View
user_fv = FeatureView(
    name="user_fv",
    entities=[user],
    source=spark_src,
    ttl=timedelta(minutes=10),
    schema=[
        Field(name="user_sparse_cohort", dtype=String),
        Field(name="user_sparse_gender", dtype=String),
        Field(name="'user_array'", dtype=Array(Float32)),
    ]
)
```
- feature_store.yaml
```yaml
project: sparkFeast
provider: aws
registry:
    path: s3://feast-bucket/registry.db
entity_key_serialization_version: 2
online_store:
    type: redis
    redis_type: redis_cluster
    connection_string: my-redis-host:6379
    # key_ttl_seconds: 86400
offline_store:
    type: spark
    spark_conf:
        spark.master: k8s://xxx.xxx.ap-northeast-2.eks.amazonaws.com  # dev
        spark.kubernetes.container.image: my-ecr-registry:feast-local-v1
        spark.jars.packages: org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.11.1026
        spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
```
- Error log
```
 File "/Users/zedd/.pyenv/versions/3.11.10/envs/feast-spark/lib/python3.11/site-packages/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py", line 187, in get_table_query_string
    raise DataSourceNotFoundException(self.path)
feast.errors.DataSourceNotFoundException: Unable to find table at 's3a://my-bucket/test-data'. Please check that table exists.
24/12/30 16:38:00 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed. 
```

I saw the spark-related source code in feast and I found the below method. 
```python
def get_table_query_string(self) -> str:
    """Returns a string that can directly be used to reference this table in SQL"""
    try:
        from pyspark.sql import SparkSession
    except ImportError as e:
        from feast.errors import FeastExtrasDependencyImportError

        raise FeastExtrasDependencyImportError("spark", str(e))

    if self.table:
        # Backticks make sure that spark sql knows this a table reference.
        table = ".".join([f"`{x}`" for x in self.table.split(".")])
        return table
    if self.query:
        return f"({self.query})"

    # If both the table query string and the actual query are null, we can load from file.
    spark_session = SparkSession.getActiveSession()
    if spark_session is None:
        raise AssertionError("Could not find an active spark session.")
    try:
        df = spark_session.read.format(self.file_format).load(self.path)
```

And I followed `load` function in `spark_session.read.format(self.file_format).load(self.path)`, the `load` function is below.
```python
def load(
    self,
    path: Optional[PathOrPaths] = None,
    format: Optional[str] = None,
    schema: Optional[Union[StructType, str]] = None,
    **options: "OptionalPrimitiveType",
) -> "DataFrame":
    """Loads data from a data source and returns it as a :class:`DataFrame`.

    .. versionadded:: 1.4.0

    .. versionchanged:: 3.4.0
        Supports Spark Connect.

    Parameters
    ----------
    path : str or list, optional
        optional string or a list of string for file-system backed data sources.
    format : str, optional
        optional string for format of the data source. Default to 'parquet'.
    schema : :class:`pyspark.sql.types.StructType` or str, optional
        optional :class:`pyspark.sql.types.StructType` for the input schema
        or a DDL-formatted string (For example ``col0 INT, col1 DOUBLE``).
    **options : dict
        all other string options

    Examples
    --------
    Load a CSV file with format, schema and options specified.

    >>> import tempfile
    >>> with tempfile.TemporaryDirectory() as d:
    ...     # Write a DataFrame into a CSV file with a header
    ...     df = spark.createDataFrame([{"age": 100, "name": "Hyukjin Kwon"}])
    ...     df.write.option("header", True).mode("overwrite").format("csv").save(d)
    ...
    ...     # Read the CSV file as a DataFrame with 'nullValue' option set to 'Hyukjin Kwon',
    ...     # and 'header' option set to `True`.
    ...     df = spark.read.load(
    ...         d, schema=df.schema, format="csv", nullValue="Hyukjin Kwon", header=True)
    ...     df.printSchema()
    ...     df.show()
    root
     |-- age: long (nullable = true)
     |-- name: string (nullable = true)
    +---+----+
    |age|name|
    +---+----+
    |100|NULL|
    +---+----+
    """
    if format is not None:
        self.format(format)
    if schema is not None:
        self.schema(schema)
    self.options(**options)
    if isinstance(path, str):
        return self._df(self._jreader.load(path))
    elif path is not None:
        if type(path) != list:
            path = [path]  # type: ignore[list-item]
        assert self._spark._sc._jvm is not None
        return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    else:
        return self._df(self._jreader.load())
```

The `load()` method is likely for just for file-system based data source. This is not supported for directly reading parquet files in s3? Can you advise to me about this?
