### ISSUE TITLE
Add a close() method to the PostgreSQLOnlineStore

### ISSUE THREAD

**Issue by job-almekinders** [feast-dev/feast#4401]
**Is your feature request related to a problem? Please describe.**
When running the online store as a web app, I want to make sure that the connections made to the Postgres database using the PostgreSQLOnlineStore class are terminated gracefully.

**Describe the solution you'd like**
A close() method on the PostgreSQLOnlineStore which closes all open connections and connection pools.

**Describe alternatives you've considered**

**Additional context**

**Comment by tokoko** [comment]
What's the point of adding this to `PostgreSQLOnlineStore` if it's not part of `OnlineStore`? How are you thinking of calling it?

**Comment by job-almekinders** [comment]
> What's the point of adding this to `PostgreSQLOnlineStore` if it's not part of `OnlineStore`? How are you thinking of calling it?

That is a valid point. It is possible as follows: `feature_store._provider.online_store.close()`. Where `feature_store` is an instance of the `FeatureStore` class. However, this is not ideal, given the fact that the `provider` object is private.

Do you think it would be an option to add a `close()` method on the `OnlineStore` class? This would also open the possibility for other online stores to implement a similar method. 
We could do a similar approach as for the `retrieve_online_documents` function [here](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/online_stores/online_store.py#L341-L375). By not making it a mandatory function, but an optional one. 

Let me know what you think! @tokoko

**Comment by tokoko** [comment]
public/private issue can be remedied in some way, I suppose. I think my main concern here is that I don't fully understand what a `close` method on an abstract `OnlineStore` class should mean and how/when it could be used. The implementation details would naturally be left up to individual online stores, but what should be the result of closing an online store? Would it make online store unusable from that point on in that process so that subsequent calls may throw an exception? Or would it simply clean up resources held to save on utilization?

Also just an aside, what's the actual practical use case here? I couldn't really come up with an actual use case where I would need to clean up connections but for some reason keep the process running.

**Comment by job-almekinders** [comment]
> Would it make online store unusable from that point on in that process so that subsequent calls may throw an exception? Or would it simply clean up resources held to save on utilization?

This is IMO up for debate. I think the second option would be the best here. Such that all connections are closed, but if the same object is used again, it would re-create them and work again.

I think the current implementation would honor the second approach, but I would have to test/double check that to be sure.

> Also just an aside, what's the actual practical use case here?

For us it is the following: We are running different web-apps that expose an ML model, and require features during inference. For the features we use feast. 
These web-apps have all sorts of 'contexts' running, which are connections to different systems. Again, one of them being a connection to the feast feature store. 

For us, it can happen that the web-app keeps running but the 'app' object and thus all connections of the systems are re-created. At the moment, without this close method, it could happen that the connections are being kept alive, which can result in a lot of connections being made to the online feature store, which is undesired.

**Comment by tokoko** [comment]
> In our case, the web app might keep running, but the "app" object, and therefore all system connections, could be re-created. Without this close method, the connections to the feature store remain open, potentially resulting in an excessive number of connections and reaching the maximum connection limit, which is undesirable.

Isn't connection pool configuration a better solution here? With `min_size` set to 0 and a small enough `max_idle`, you should accomplish essentially the same outcome w/o changes to the API.

> This is debatable, but I believe the second option is preferable. In that case, all connections would be closed, but if the same object is used again, it would re-create the connections and continue to function.

We should probably come up with a better name then if we go forward with this.

**Comment by job-almekinders** [comment]
> Isn't connection pool configuration a better solution here? With min_size set to 0 and a small enough max_idle, you should accomplish essentially the same outcome w/o changes to the API.

That is also a good idea, I didn't think of this before. 

> We should probably come up with a better name then if we go forward with this.

Do you have any ideas? ChatGPT came up with these
1. release_resources
2. reset_connections
3. terminate_connections
4. cleanup_connections

**Comment by tokoko** [comment]
`release_resources` is probably the best one, but once again I'd much rather we don't make the change at all unless it's absolutely necessary. So probably best to try solving this with connection pools first. Let me know if I can help.

**Comment by job-almekinders** [comment]
I'll close this issue and PR, since I agree with your train of thought. 

Thanks a lot for your comments and thinking along! This really helps :)
