### ISSUE TITLE
File not found on make install-python-ci-dependencies-uv step in Developer Guide

### ISSUE THREAD

**Issue by dandawg** [feast-dev/feast#4417]
## Expected Behavior 
Follow the developer guide to step 9 in the Feast Python SDK / CLI section. Then do step 9, which is to execute the command:
```make install-python-ci-dependencies-uv```

I expect this to run successfully and install dependencies.

## Current Behavior
I run the command from the feast root directory, and I get the error message:
```uv pip sync --system sdk/python/requirements/py-ci-requirements.txt
error: File not found: `sdk/python/requirements/py-ci-requirements.txt`
make: *** [install-python-ci-dependencies-uv] Error 2
```

On inspection, the file `sdk/python/requirements/py-ci-requirements.txt` doesn't exist, but similar files do:
```ls sdk/python/requirements/
# output
py3.10-ci-requirements.txt	py3.11-ci-requirements.txt	py3.9-ci-requirements.txt
py3.10-requirements.txt		py3.11-requirements.txt		py3.9-requirements.txt
```

My guess is, the requirement files were updated, but the make command was not.

## Steps to reproduce
Verifying this should be as easy as running the command `make install-python-ci-dependencies-uv` from the feast root directory.

To reproduce exactly, follow the [Developer Guide](https://docs.feast.dev/project/development-guide#feast-python-sdk-cli) steps to step 9.

### Specifications

- Version: 0.40.1
- Platform: Mac
- Subsystem: M2

## Possible Solution
A couple of suggestions
1. Update the make command to point to an existing requirements file. We would have to pick which one, or have logic behind make determine the python version that is best--perhaps with input from the user.
2. Update the developer guide to run `pip install -r `sdk/python/requirements/py3.9-ci-requirements.txt`, with instruction to substitute the version if needed. (Possibly `uv pip` instead of just `pip`).

**Comment by tokoko** [comment]
I think what's missing in the guide is that you need to have `PYTHON` env var set to the correct version before running the command, but some sort of auto-detection would be a better option. I'll look into it.
