### ISSUE TITLE
RBAC Enhancement - Getting oidc end points from the discovery URL.

### ISSUE THREAD

**Issue by lokeshrangineni** [feast-dev/feast#4428]
Currently RBAC functionality server side code is getting OIDC endpoints such as token_endpoint, refresh endpoint, jwks endpoints are written as per keycloak. So modifying this logic to get it from the OIDC discovery URLs so that it works with other oidc providers as well.

**Comment by redhatHameed** [comment]
@lokeshrangineni is this closed ?
