### ISSUE TITLE
Update dependencies in sdk/python/feast/ui

### ISSUE THREAD

**Issue by elshize** [feast-dev/feast#4451]
**Is your feature request related to a problem? Please describe.**

The dependencies have vulnerabilities. See #4439 for context.

**Describe the solution you'd like**

I would appreciate it if someone who knows JS stuff could upgrade those dependencies.

**Describe alternatives you've considered**

See #4439

**Comment by elshize** [comment]
I'm willing to open a change for this, but I would need some guidance for how to fix vulnerabilities using yarn.

**Comment by peruukki** [comment]
Most of the vulnerabilities come from [react-scripts](https://www.npmjs.com/package/react-scripts) which hasn't been updated in 2.5 years. We'll need to [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) to basically get rid of that dependency and start managing the setup ourselves, and then update or replace related dependencies. I'd be interested to try it out, I actually quickly tried a while ago but hit some errors.

For the rest, usually these commands go far:
```sh
# Upgrade multiple dependencies selectively at once
yarn upgrade-interactive

# Upgrade direct dependency to latest version
yarn add [--dev] <package> # Use --dev if the dependency is in devDependencies

# Upgrade transitive dependencies of a direct dependency to latest versions
yarn upgrade <package>
``` 

Also `yarn why <package>` is useful for finding out why a package is in the project (which packages depend on it).

These are the direct dependencies we'd need to upgrade based on `yarn audit`:
```sh
% yarn audit | grep 'Dependency of' | sort | uniq
│ Dependency of │ @babel/core                                                  │
│ Dependency of │ @babel/preset-env                                            │
│ Dependency of │ msw                                                          │
│ Dependency of │ protobufjs-cli                                               │
│ Dependency of │ react-code-blocks                                            │
│ Dependency of │ react-scripts                                                │
│ Dependency of │ rollup-plugin-copy                                           │
│ Dependency of │ rollup-plugin-svgo                                           │
```

I'd be happy to try upgrading the others too, and would start from them.
