### ISSUE TITLE
Provide Feature Serving and Model Inference Diagram

### ISSUE THREAD

**Issue by franciscojavierarceo** [feast-dev/feast#4455]
**Is your feature request related to a problem? Please describe.**
We have outlined some options for feature serving and model inference in this documentation: https://docs.feast.dev/v/master/getting-started/architecture/model-inference

In it, we briefly discuss communication patterns and their tradeoffs (elaborated further here: https://docs.feast.dev/v/master/getting-started/architecture/write-patterns).

We don't have an architecture diagram to support these pieces.

**Describe the solution you'd like**
For a Fintech article I'm writing, I ended up drafting this diagram. I think we could potentially adjust this to use in our documentation.

![Screenshot 2024-08-27 at 6 38 42 AM](https://github.com/user-attachments/assets/19a5f091-440d-48d2-b616-d6b0c26de91c)

**Describe alternatives you've considered**
N/A

**Additional context**
Good diagrams provide clarity and what not, so I thought this would be useful.

**Comment by franciscojavierarceo** [comment]
@tokoko any thoughts here? Otherwise I'll cut a PR with this to add to the documentation. I think it's missing the registry, so I could add that as well.

**Comment by tokoko** [comment]
a couple of remarks
- should feast box contain `training datasets`? Once they are generated, they are effectively outside of feast at that point.
- What does a line coming from an online store marked `Logs/CDC/ELT` refer to?

**Comment by franciscojavierarceo** [comment]
That's a good call out! 

The logs/CDC/ELT refers to logs that should be sent from the feature server during transformations. This is the suggestion I would make to most folks to ensure feature and model reproducibility/replay.

**Comment by franciscojavierarceo** [comment]
It could be events to SQS or Kafka/Kinesis or through a sidecar.

**Comment by franciscojavierarceo** [comment]
@tokoko I added the training datasets, lmk what you think.

![feast_model_serving_architecture](https://github.com/user-attachments/assets/76ab07de-7825-447f-b2d1-9062fba2e1e9)
