### ISSUE TITLE
OnDemandFeatureView: Allow `python` transformations for `offline` processing. 

### ISSUE THREAD

**Issue by job-almekinders** [feast-dev/feast#4490]
**Is your feature request related to a problem? Please describe.**
When running a `PythonTransformation` for offline feature retrieval, an exception is raised [here](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/transformation/python_transformation.py#L31-L33). I understand that `python` transformations on very large datasets do not scale well. However, in some cases, a user might still want to apply a `python` transformation to a smaller dataset in the offline store. Due to this error (and the missing implementation of `PythonTransformation().transform_arrow()`), this is currently not possible.

**Describe the solution you'd like**
Instead of raising an exception, we could still run the transformation, and also log a warning indicating that it may not scale well. On top of that we can implement the functionality in `transform_arrow` to make the transformation happen.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by franciscojavierarceo** [comment]
Oh we should definitely discuss this because I agree. Also, for scaling Spark should really call the Transformation as a UDF and then it can scale very well.

**Comment by franciscojavierarceo** [comment]
This has been implemented. 👍

**Comment by job-almekinders** [comment]
Thanks a lot for this! @franciscojavierarceo 

FYI @TomSteenbergen :)
