### ISSUE TITLE
`Install Feast` link broken on home page

### ISSUE THREAD

**Issue by Vandivier** [feast-dev/feast#4496]
1. visit https://feast.dev/
2. click `Install Feast`
3. ERR_NAME_NOT_RESOLVED when forwarded to https://docs.feastsite.wpenginepowered.com/quickstart

**Comment by franciscojavierarceo** [comment]
Thanks for this @Vandivier! I updated it. Can you test?

**Comment by Vandivier** [comment]
@franciscojavierarceo it still looks broken to me ☹️

**Comment by franciscojavierarceo** [comment]
@Vandivier I updated the link on the page. Can you try a hard refresh? I replaced that link (outdated) with the one on our docs which is https://docs.feast.dev/getting-started/quickstart

**Comment by franciscojavierarceo** [comment]
Ah, I fixed it now. Realized I was looking at the FAQs and not the footer.

**Comment by franciscojavierarceo** [comment]
Thank you both!
