### ISSUE TITLE
Error in version 0.40.1: FeastModuleImportError: Could not import module 'feast.infra.offline_stores.contrib.postgres_offline_store.postgres' while attempting to load class 'PostgreSQLOfflineStoreConfig'

### ISSUE THREAD

**Issue by dejavu284** [feast-dev/feast#4507]
The error disappears when I downgrade the version to 0.39.0.

## Steps to reproduce:
- Create new conda env: conda create -n feast-mvp
- Install python: conda install python==3.9.13
- Install feast: pip install feast==0.40.1
- Install other libs: pip install postgres psycopg2-binary==2.9.9

### Specifications

- Version: 0.40.1
- Platform: windows
- Subsystem: wsl ubuntu (for reproduce)

**Comment by franciscojavierarceo** [comment]
Is this issue still happening?

**Comment by dmartinol** [comment]
I think you're installing the wrong version of psql dependencies, according to [setup.py](https://github.com/feast-dev/feast/blob/00be7b0916ec540b48e7ecb70719e1c7ed03bfa1/setup.py#L97).

Try this instead, to ensure that you are installing the validated dependencies:
```
pip install "feast[postgres]==0.40.1"
```
Note: please avoid `pip install postgres psycopg2-binary==2.9.9`

Then validate with:
```
> pip list | grep psyco
psycopg                   3.1.18
psycopg-binary            3.1.18
psycopg-pool              3.2.3
```

**Comment by dmartinol** [comment]
@franciscojavierarceo I think we can close this one, it was definitely an environment issue

**Comment by dmartinol** [comment]
@franciscojavierarceo what about this one?
