### ISSUE TITLE
Running feast version command throw error

### ISSUE THREAD

**Issue by EXPEbdodla** [feast-dev/feast#4532]
## Expected Behavior 
Should return the version without GRPCIO dependencies installed. 

## Current Behavior

Requires GRPCIO dependencies to be installed otherwise throws error 

`python3.11/site-packages/feast/errors.py", line 8, in <module>
    from grpc import StatusCode as GrpcStatusCode
ModuleNotFoundError: No module named 'grpc'`

## Steps to reproduce

Install latest feast and run `feast version` command

### Specifications

- Version: Master branch 
- Platform: Mac
- Subsystem:

## Possible Solution

1. Lazy imports with Try and Except
2. Either make GRPCIO dependencies as required (or)

**Comment by tokoko** [comment]
thanks, I fixed it in #4478, but was unable to merge for unrelated reasons and forgot about it. I'll do a separate PR just for this.
