### ISSUE TITLE
Inaccessible RFC documentation link

### ISSUE THREAD

**Issue by jjasont** [feast-dev/feast#4547]
## Expected Behavior 

Accessible RFC Google Drive/Docs documentation link regarding Kafka/Spark stream processor

[Feast Tutorials - Building Streaming Features](https://github.com/feast-dev/feast/blob/v0.40-branch/docs/tutorials/building-streaming-features.md)

## Current Behavior

Forbidden access to RFC Google Drive/Docs documentation link regarding Kafka/Spark stream processor

## Steps to reproduce

nil

### Specifications

- Version: v0.22+
- Platform: nil
- Subsystem: nil

## Possible Solution
Allow RFC Google Drive/Docs access to public or disable link

**Comment by shuchu** [comment]
v0.22+ is a quite old release version. Try this link for the tutorial: https://github.com/feast-dev/streaming-tutorial

**Comment by jjasont** [comment]
@shuchu I'm aware of the tutorial repo.  I'm raising the matter regarding the hyperlinked `RFC`  text in the document that I linked.
It returned this page which isn't accessible. https://docs.google.com/document/d/1UzEyETHUaGpn0ap4G82DHluiCj7zEbrQLkJJkKSv4e8/edit?usp=sharing

**Comment by shuchu** [comment]
unfortunately,  it seems that document is not sharable...sorry about this.
