### ISSUE TITLE
Make it mandatory to specify value_type for an entity

### ISSUE THREAD

**Issue by tokoko** [feast-dev/feast#4670]
Currently specifying a value_type for an entity is optional. value types are instead inferred during an online call with a this [function](https://github.com/feast-dev/feast/blob/a1ff1290002376b4c9ac8ad14e60df4622bb47a4/sdk/python/feast/utils.py#L578) that basically goes through all the feature views and checks actual data types where a specific entity is used. This is obviously not very performant.

The possible reason for this design is to allow the same entity to have different types in different feature views (although now this is not allowed anyway). I think even that goal is a bit dubious, making joins across values with different data types could lead to many corner cases and bugs. I think we should instead make it mandatory to specify a value type when the user applies an entity and also make sure that data types align when actual feature views reference entities.

This will obviously be a breaking change, but I think the one that can be rectified easily. Maybe we can add DeprecationWarning in the next release saying that entities must have a type and make it mandatory in the release after that.

**Comment by tokoko** [comment]
@franciscojavierarceo @HaoXuAI

**Comment by franciscojavierarceo** [comment]
Yeah I definitely agree with this.

**Comment by tmihalac** [comment]
@franciscojavierarceo @tokoko Can you elaborate a bit more? I want to fix this issue
