### ISSUE TITLE
Documentation missing for the registry server

### ISSUE THREAD

**Issue by dmartinol** [feast-dev/feast#4757]
## Expected Behavior 
Feast user guide is missing details about the registry server that runs with `feast serve_registry`.
The [Feature server](https://docs.feast.dev/reference/feature-servers) page should include details on the registry server.
The [Registries](https://docs.feast.dev/reference/registries) page should include the `remote` registry type.

Note: in addition, the `Feature server` page should also be renamed to something more generic like `Feast server`.

## Current Behavior
The registry server is not documented.

**Comment by tokoko** [comment]
I'd rename the section to `Servers` or `Feast Servers` if servers sound too generic.
