### ISSUE TITLE
Adding e2e integration tests for feast go opertor

### ISSUE THREAD

**Issue by lokeshrangineni** [feast-dev/feast#4792]
Feast go operator is in development and we are creating this issue to track the effort to add e2e integration tests.

The goal of the ticket is to address following scenarios:

1. Kubernetes FeatureStore CR should spin up all the necessary services required  in our case it will be registry, online and offline services.
2. Assert `FeatureStore` CR status should be in ready state.
3. Assert registry, online and offline service pods are in Running state.
4. Assert feast client ConfigMap is existing.
5. Assert registry, online and offline services are having associated Kubernetes service objects defined.
6. Assert registry, online and offline services are having associated Kubernetes service account objects defined.

Related Issues - [4561](https://github.com/feast-dev/feast/issues/4561), [4783](https://github.com/feast-dev/feast/issues/4783)

**Comment by tchughesiv** [comment]
let's get more specific about which e2e test(s)/scenarios are being added w/ this PR.

**Comment by lokeshrangineni** [comment]
> let's get more specific about which e2e test(s)/scenarios are being added w/ this PR.

I have updated the PR and Issue with specific details. Please let me know if I missed any other details.

**Comment by lokeshrangineni** [comment]
We have addressed this ticket as part of the [PR-4791](https://github.com/feast-dev/feast/pull/4791)
