### ISSUE TITLE
No TTL on Redis keys

### ISSUE THREAD

**Issue by idahoakl** [feast-dev/feast#555]
## Expected Behavior 
TTL set on values stored within Redis.

## Current Behavior
No TTL is set on values stored within Redis.  For FeatureSets that have short lived Entity values this leads to Redis filling with old data that is never referenced.  Once Redis is full it either slows down while trying to expire keys or stops ingesting new data.

## Steps to reproduce
1.  Install Feast with an online serving component backed by Redis
1.  Create any FeatureSet
1.  Ingest data into the FeatureSet
1.  Check the TTL on a key within Redis, TTL value of -1 

### Specifications

- Version: 0.4.6
- Platform: 
- Subsystem: ingestion

## Possible Solution
Potentially set the Redis key TTL to be the max_age on the FeatureSet.

**Comment by woop** [comment]
This has come up in the past as well as functionality that we should introduce. I am more included to label this as a feature request though, as opposed to a bug. 

I think setting it to max_age makes sense, but for a lot of folks that parameter is still quite vaguely defined. We might be evicting keys quite aggressively if they max_age is too low, but I guess that is up to the user to configure correct then.

**Comment by idahoakl** [comment]
I debated between a feature request vs a bug.  I decided on a bug given the fact that if the data is older than max_age it can't be retrieved from online serving but there is no easy way to remove it from taking up space within Redis.

I think adding an option to ingest to set a TTL (based on max_age or static) or not would be good to have.  There may be use cases where using on of Redis' maxmemory eviction policies is the desired behavior.  In that case setting no TTL would remain available.

**Comment by ches** [comment]
FWIW we implemented max age as the TTL for the Cassandra serving implementation that is in v0.3 only currently. There is no such general LRU expulsion mode functionality in it and other potential serving store backends, so it’s essential to choose some strategy.

We do expect to have to police that max age cannot be set “unreasonably low”, and may add some constant factor like one day to the TTL from the max age, to mitigate pressure on the storage engine without changing a semantic requirement expected by the user.

**Comment by zhilingc** [comment]
> I debated between a feature request vs a bug. I decided on a bug given the fact that if the data is older than max_age it can't be retrieved from online serving but there is no easy way to remove it from taking up space within Redis.
> 
> I think adding an option to ingest to set a TTL (based on max_age or static) or not would be good to have. There may be use cases where using on of Redis' maxmemory eviction policies is the desired behavior. In that case setting no TTL would remain available.

The latter is exactly what we're doing in production, but when it comes to serving stores that are populated by large batch loads the LRU cache approach is flawed.
