### ISSUE TITLE
Update feast GKE set-up to use latest stable feast release

### ISSUE THREAD

**Issue by imjuanleonard** [feast-dev/feast#572]
## Expected Behavior 
When I run the feast Set-up guide, I should be running on the latest stable version of the feast. 

## Current Behavior
It is running on feast 4.4. It supposes to be 4.5 or 4.6 as feast 4.7 are releasing

## Steps to reproduce
Follow the GKE installation instruction from [here](https://docs.feast.dev/installing-feast/gke)

### Specifications
- Version: Any Version
- Platform: GCP
- Subsystem: Any Version

## Possible Solution
Update the helm charts and feast set-up,

**Comment by woop** [comment]
Resolved https://github.com/feast-dev/feast/blob/master/infra/charts/feast/charts/feast-core/values.yaml#L8
