### ISSUE TITLE
Provide descriptive error messages during constraint violation

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#582]
## Expected Behavior 

When creating feature sets with features that contain names that are already registered in a project, Feast should provide a descriptive error that indicates the violation and how to correct it.

## Current Behavior

Feast raises a cryptic exception due to database constraint violations

```_Rendezvous Traceback (most recent call last) V.pyenv/versions/minicond.-0.3.317/envs/omakase-harvest/lib/pYtho.6,site-Packages,fea 488 ApplyFeaturesetRequestIfeatureset=feature_set_proto), timeout=6RPC_CONNECTION_TIMEOUT_APPLY, 482 ) . type: ApplyFeaturesetResponse 
cliet.PY n_PPlY_feature_set(self, feature_set) 
q.pyenv/versions/mniond.-4.3.30/envs/omakase-harvest/lib/pYtho..6,site-Packages/grPc,_channel.PY in --call--,self, request, meted.,eacl w.it-'°' compression) 56.1 waitforredy, compression) return _end_unary_response_blockingIstate, call, False, None) 
q.pyenv/versions/miniconda3-4.3.30/envs/omakase-harvest/)ib/pytho..6/site-packages/grpc/_channel.py in end_unary_response_blockinglstate, call, with call. deadline) 486 else: raise _RendezvousIstate, None, None, deadline, 488 

_Rendezvous: .fiendezvous of RPC that terminated with: status = Statuscode.INTERNAL details = .could not execute statement; SQL In/al; constraint luk5trpfpcjbjw5✓2dpuugswdxh1;
nested exception is org.hiber ate.exception.ConstraintViolationExcep tion: could not execute statement" dehug_errorstring = "("created":"@1584009073.032857000",“description":"Error received from peer ipv4:117.302.250.99:331917","file":"src/core/lih/surface/call.c c.,"file_line,1052,"grpc_message",
could not execute statement; SQL In/al; constraint luk5trpfpcjbjw5w2dpuugsurdxh1; nested exception is 
org.hihernate.exception.Constra intViolationException: could not execute statement" , "grPc_status'. 
```

## Steps to reproduce

1. Register a feature set with a list of features
2. Register another feature set (with a different name), but with the same feature names in the same project.

## Possible Solution

Simply add improved exception handling to the ApplyFeatureSet method.

**Comment by imjuanleonard** [comment]
Hi @woop can I pick this up and check about the error handling on the ApplyFeatureSet method?

**Comment by woop** [comment]
> Hi @woop can I pick this up and check about the error handling on the ApplyFeatureSet method?

Let's first focus on the other assigned issues for the time being.

**Comment by mrzzy** [comment]
The documentation points in another direction:
> Entities in Feast are defined within Feature Sets and are not treated as standalone concepts.

Suggesting that Features belong to Features should be part of the Feature Set, not standalone. Yet, users have to make sure that features have a globally unique name. Conceptually, this is contradictory.

I suggest that we namespace feature names from the Feature Set's name 
(ie `<feature set>_<feature>`) in the `ApplyFeatureSet()` method
 automatically, so that users don't have to worry about feature name collisions at all.

**Comment by woop** [comment]
@mrzzy Good idea, in fact I've also highlighted it here: https://github.com/gojek/feast/issues/584#issue-589517139

I agree that an feature/entity should be namespaced within a feature set. I would like to make that change in the coming release. Meaning they should only have to be unique within the feature set itself.

I am not sure where `<feature set>_<feature>` would apply though? We already handle that at the database level so this constraint mostly applies at the logical level (core maintains the constraint).

Related #479

**Comment by woop** [comment]
@mrzzy is this issue still relevant?
