### ISSUE TITLE
Feast API pain points

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#584]
These are some personal pain points that I have collected while creating the [Telco Churn Prediction notebook ](https://github.com/gojek/feast/blob/master/examples/feast-xgboost-churn-prediction-tutorial/Telecom%20Customer%20Churn%20Prediction%20(with%20Feast%20and%20XGBoost).ipynb). Ideally we should be spinning these off into their own issues if they warrant development, but for the time being I will capture it in this issue for discussion.

1. Needing to connect to three hosts (Core, Historical Serving, Online Serving) is painful because the user needs to create a new client for adding that third host. Users should ideally just be configuring a single host to connect to Feast, or should be able to add all of their hosts in one go and use only a single client.
2. Having to provide a dataframe of entities and timestamps at historical retrieval time is painful. AirBnB/ZipLine uses a SQL query here to generate the entity set and timestamp combination. I am not convinced that that is a great approach in terms of an API abstraction, but I think we should consider implementing time range based queries as documented in the [Feast 0.3 RFC](https://docs.google.com/document/d/1QnUQWhwJ1fDnMQ4sZdUdLa_4C-x5Hhpw3C8nYLg4nsY/edit#heading=h.vgqdn6a9guyy). This would indirectly allow users to query existing entities and time stamps, eliminating some work on their part. If they still need to ingest a dataframe to provide these entities then we arent really solving the problem. Federation over existing data makes more sense then, whether with a feature set view or a SQL query from the API. Open to ideas here.
3. Not knowing if a dataset has been successfully ingested is painful. Even if your data lands on Kafka you don't know if it has populated a store. Operationally we know how to figure this out at Gojek, but its very hard for the end user without going to a metrics dashboard and looking at ingestion metrics. Our users have repeatedly told us that they want to know a feature is safe and populated in a store before turning it on for production use. This is quite important to have.
4. Having to always provide a `project` isn't a good user experience. `Projects` should be invisible if users don't want to use them. Related #453 
5. Entity row creation is painful in online serving. Have a look at [the telco churn](https://github.com/gojek/feast/blob/master/examples/feast-xgboost-churn-prediction-tutorial/Telecom%20Customer%20Churn%20Prediction%20(with%20Feast%20and%20XGBoost).ipynb) notebook at `_get_online_features()` for an idea of what I mean.
6. I don't think we should force users to bring datetime columns (during retrieval or ingestion). This can be abstracted away.
7. Kafka should throw an error when not accessible. Currently this is just being gobbled up without any details of failure or success.
8. GetOnlineFeatures should be consistent with GetBatchFeatures. Naming and ordering of features are not respected. Ideally we should have identical outputs here, save for the fact that the historical output has many instances per timestamp.
9. GetOnlineFeatures and GetBatchFeatures should trim project names from result sets if only a single project is used, and similarly for feature set names. This should be configurable by the user. 
10. Not having proper return types at `_get_online_features()` means a lot of type casting is needed to create TF Records or a DMatrix. This should be made a lot easier, but perhaps isn't a priority now.
11. Users should be able to see the types of errors in OnlineServing (missing entities, missing keys, stale). Relevant [RFC](https://docs.google.com/document/d/1VQngwBcx-yWgGpAbsFVdth9GnjL8q-ZgUNBGv57R0Fk/edit#).
12. No error messages are being bubbled up at GetBatchFeatures. This makes it very difficult to debug the retrieval of historical features. Examples: Feature name conflicts, missing project, BQ configuration problems.
13. The concepts of projects vs feature sets don't feel intuitive, and [might require attention before 0.5](https://github.com/gojek/feast/issues/479). We are asking users to register and ingest features as part of a feature set, but we don't allow users to retrieve features based on feature sets. The users are also blocked from adding features into feature sets if they violate project level constraints, which feels very counter-intuitive if a feature set is a grouping mechanism.

**Comment by NicholaiStaalung** [comment]
I would like to add that the entity df's for batch retrieval could be optional. First of all you need to know the range of the entity id's of the data you wish to retrieve. Second of all the datetime column is somehow arbitrary since it most likely will be used by adding the time right now. I see that both could make sense if you are dealing with timeseries data, but i think both should be optional.

I think there should be a simple case where you are able to retrieve all of the data in the feature set. Just like loading it into pandas from a csv file.

**Comment by adchia** [comment]
Closing since this predates Feast 0.10
