### ISSUE TITLE
Test Coverage: End to End Tests for Dataflow Runner

### ISSUE THREAD

**Issue by mrzzy** [feast-dev/feast#595]
**Is your feature request related to a problem? Please describe.**

Currently, Feast's end to end tests only verify correctness with Feast Core's [Direct Runner](https://github.com/gojek/feast/blob/2fa30ac1883ad6fdc42168487a0fbafd38020b16/infra/scripts/test-end-to-end.sh#L103), leaving a gap in test coverage for the Dataflow runner. This is an issue a we are unable to verify that new additions to the codebase work well with the Dataflow runner, requiring PR authors to do error prone manual testing.

Case study: PR #575 
- I submitted small PR #575 which updated how `Runner`s are rendered.
- Since the PR is relatively small and all the tests pass, I assumed that the PR did not introduce any bugs and didn't do any independent testing on my own.
- I only discovered that the PR broke the Dataflow runner after it was merged, leaving a known bug on the master branch.

This bug in the PR would have been caught by Feast's test suite, had it tested with the Dataflow runner in addition to the Direct runner.

**Describe the solution you'd like**
Add End to End Tests using the Dataflow Runner, in additional to the Direct Runner.

**Comment by woop** [comment]
I believe this is now resolved: https://github.com/feast-dev/feast/blob/master/.prow/config.yaml#L263
