### ISSUE TITLE
FeatureSet can contain fields with dash which is not allowed in BigQuery

### ISSUE THREAD

**Issue by idahoakl** [feast-dev/feast#606]
## Expected Behavior 
Enforce field names specified for a FeatureSet are acceptable column names according to the BigQuery schema specification.  https://cloud.google.com/bigquery/docs/schemas#column_names

## Current Behavior
An entity or feature can be specified on a FeatureSet containing a dash or starting with a number.  This causes a failure when the ingest job to BigQuery attempts to create the BigQuery table schema.  This prevents the ingestion job from incorporating any new FeatureSets.  The only work around is to manually remove the offending FeatureSet from the database.

## Steps to reproduce
Create any FeatureSet with an entity containing a dash or starting with a number.

### Specifications

- Version: 0.4.7
- Platform: 
- Subsystem:

## Possible Solution
Adjust the regex specified at feast.core.validators.Matchers::VALID_CHARACTERS_REGEX to ^[a-zA-Z_][a-zA-Z0-9_]*$

**Comment by woop** [comment]
Thanks for raising this @idahoakl. Should be an easy fix.
