### ISSUE TITLE
batch_client.get_batch_features throws "Unable to load entity dataset to Bigquery"

### ISSUE THREAD

**Issue by avolution** [feast-dev/feast#629]
Hey guys,

I get the Error below in the basic_example notebook on step 10

All steps before were successful.

The data from the previous steps are existing in the bigquery and there is
an  .avro file created in the bucket on gcs on each run

I already tried tried  a new project ID and also checked that the batch serving api is available 

Here is the exception:

---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
<ipython-input-95-bacf0e7787bc> in <module>
      4                                 f"customer_project/total_transactions",
      5                                ],
----> 6                             entity_rows=entity_rows
      7                          )

/opt/conda/lib/python3.7/site-packages/feast/client.py in get_batch_features(self, feature_refs, entity_rows, default_project)
    617 
    618         # Retrieve Feast Job object to manage life cycle of retrieval
--> 619         response = self._serving_service_stub.GetBatchFeatures(request)
    620         return Job(response.job, self._serving_service_stub)
    621 

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    824         state, call, = self._blocking(request, timeout, metadata, credentials,
    825                                       wait_for_ready, compression)
--> 826         return _end_unary_response_blocking(state, call, False, None)
    827 
    828     def with_call(self,

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    727             return state.response
    728     else:
--> 729         raise _InactiveRpcError(state)
    730 
    731 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Unable to load entity dataset to Bigquery"
	debug_error_string = "{"created":"@1587071800.498003183","description":"Error received from peer ipv4:**.**.**.**:6567","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to load entity dataset to Bigquery","grpc_status":13}"
>

**Comment by woop** [comment]
Hi @avolution, thanks for raising this!

Can you have a look at the BigQuery UI to see if it has an exception in the job that ran?

**Comment by avolution** [comment]
There is:

Load gs://****_feast_bucket/16-04-2020_09-21-18_PM_*******.avro to *****:feast._**************************
21:21
Not found: URI gs://****_feast_bucket/16-04-2020_09-21-18_PM_*******.avro

Which is weird, because that file is available in the bucket.

After a bit of investigation now I found a path problem

I used the root folder of the bucket.
GCS now created a weird "/" folder(you can click on it then you are in kind of a nameless folder) on the root which leads to

https://storage.cloud.google.com/*****_feast_bucket//17-04-2020_10-28-05_AM_******.avro?folder&organizationId 

with a double slash.

(maybe a comment in the Docs/Helm Chart would be nice to prevent people from into running this)

I have changed that to a subfolder and now I can see on the big query side that the job succeed.(Status 
 green)

When I check the BigQuery UI I can see that the new table(with a hash) is created with data in it.

BUT in my notebook I still get the same exception

**Comment by avolution** [comment]
Thats the error message in the batch serving pod:

{
  "thread": "grpc-default-executor-9",
  "level": "ERROR",
  "loggerName": "feast.serving.service.BigQueryServingService",
  "message": "Exception has occurred in loadEntities method: ",
  "thrown": {
    "commonElementCount": 0,
    "localizedMessage": "com.google.api.gax.retrying.PollException: total timeout or maximum number of attempts exceeded; current settings: RetrySettings{totalTimeout=PT0S, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT3S, maxAttempts=0, jittered=true, initialRpcTimeout=PT0S, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT0S}",
    "message": "com.google.api.gax.retrying.PollException: total timeout or maximum number of attempts exceeded; current settings: RetrySettings{totalTimeout=PT0S, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT3S, maxAttempts=0, jittered=true, initialRpcTimeout=PT0S, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT0S}",
    "name": "com.google.cloud.bigquery.BigQueryException",
    "cause": {
      "commonElementCount": 14,
      "localizedMessage": "total timeout or maximum number of attempts exceeded; current settings: RetrySettings{totalTimeout=PT0S, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT3S, maxAttempts=0, jittered=true, initialRpcTimeout=PT0S, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT0S}",
      "message": "total timeout or maximum number of attempts exceeded; current settings: RetrySettings{totalTimeout=PT0S, initialRetryDelay=PT0S, retryDelayMultiplier=1.0, maxRetryDelay=PT3S, maxAttempts=0, jittered=true, initialRpcTimeout=PT0S, rpcTimeoutMultiplier=1.0, maxRpcTimeout=PT0S}",
      "name": "com.google.api.gax.retrying.PollException",
      "extendedStackTrace": [
        {
          "class": "com.google.api.gax.retrying.ExponentialPollAlgorithm",
          "method": "shouldRetry",
          "file": "ExponentialPollAlgorithm.java",
          "line": 70,
          "exact": false,
          "location": "gax-1.48.1.jar!/",
          "version": "1.48.1"
        },
        {
          "class": "com.google.api.gax.retrying.RetryAlgorithm",
          "method": "shouldRetry",
          "file": "RetryAlgorithm.java",
          "line": 116,
          "exact": false,
          "location": "gax-1.48.1.jar!/",
          "version": "1.48.1"
        },

**Comment by avolution** [comment]
Any Ideas?

**Comment by woop** [comment]
Hi @avolution, thanks for being so patient.

This might be related to one of the problems I found in the configuration here

https://github.com/gojek/feast/issues/525#issuecomment-605391084

Can you confirm that those two keys are correctly configured?

Your Feast Serving for batch data should have them configured as follows: https://github.com/gojek/feast/blob/v0.4.7/serving/src/main/resources/application.yml#L38

You can have a look at the configmaps that are deployed for Feast Serving to see if they are set.

**Comment by avolution** [comment]
Yea that works!

Have set

feast-serving-batch -> application.yaml -> feast -> jobs -> bigquery-initial-retry-delay-secs = 1
feast-serving-batch -> application.yaml -> feast -> jobs ->  bigquery-total-timeout-secs = 21600

in the Helm chart

(created also a PR)

Thank you so much! :)
Very curios about testing feast now

**Comment by woop** [comment]
I believe this issue is now resolved. Closing it.

@avolution Please let us know if you want it reopened.
