### ISSUE TITLE
[Feature request] python SDK (CLI) unarchive and/or delete for 

### ISSUE THREAD

**Issue by avolution** [feast-dev/feast#630]
When I archive a project in the python SDK CLI its gone and I am not able to restore it.

A "delete project" function would also be nice. For example when you want to start in a clean env without switching Project IDs

**Comment by woop** [comment]
I think this make sense. It's mostly a matter of prioritization for us right now. Unarchive should be relatively easy to implement. Deletion would be considerably harder.
