### ISSUE TITLE
[Question] Fast ingestion of realtime data

### ISSUE THREAD

**Issue by avolution** [feast-dev/feast#637]
Hey guys,

what is the best practice to ingest data fast into feast?

Example scenario:
A websocket stream which sends 100 to 200 Events per second which have to be saved.

I have tried it via the python sdk but client.ingest("event", event_object) takes one second for every ingestion which is too slow.

Is there a way to send data directly for example via kafka?

Is there an example anywhere?

**Comment by woop** [comment]
@avolution we don't currently have an example for you, but all ingestion happens through Kafka. Meaning if you push to the correct topic then your data will be ingested into Feast.

For each feature set you can find the topic by printing it out. With the Python SDK you can use `get_feature_set()` and then print out the whole feature set to see the source. The source will contain the topic/brokers.

The message you push to Kafka must be in the [FeatureRow](https://github.com/gojek/feast/blob/master/protos/feast/types/FeatureRow.proto) format. You can see an example of the implementation in the Python SDK's `ingest()` method.

**Comment by woop** [comment]
@avolution Please let me know if you have more questions, closing for now.
