### ISSUE TITLE
[Question] How to use same features, but having different statistics, with different models?

### ISSUE THREAD

**Issue by ShantanuKumar** [feast-dev/feast#649]
The case I am talking about is when we are training different models which have some common features, but are trained on different snapshot of data. Is this already possible to do with feast? I would like to avoid creating a new feature.

**Comment by woop** [comment]
Hi @ShantanuKumar,

This is definitely possible with Feast. You would select different features for the models (or reuse the common ones).

**Comment by woop** [comment]
@ShantanuKumar Please let me know if you have more questions, closing this issue for the time being.
