### ISSUE TITLE
Update Python SDK to support labels

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#663]
This issue follows #463 which has a partial implementation in #536. 

One additional PR is needed to get #436 into a consistent and complete state for end users. Currently #536 makes changes to Feast Core by adding support for labels to feature sets and features, but it doesn't add support for labels to feature sets in the Python SDK.

The task here is to add this support and update any end-to-end tests that test both the Python SDK and Feast Core w.r.t label metadata.

**Comment by woop** [comment]
Unless there is any objection then I think we can push this out to 0.6. We'd be introducing new API methods and not taking anything away? I don't see a compelling reason to block 0.5 over this.

**Comment by ches** [comment]
Sounds reasonable, I also think this could be a great community contribution if there's someone wishing to use this functionality from the Python SDK who can prioritize it before the maintainers are able to.

**Comment by Joostrothweiler** [comment]
I would be happy to pick this up somewhere next week. From #463:
> with the Python SDK having a set_label(key, value) method and a remove_label(key) method on the Feature class. list_feature_sets() would print out this information as well, but filtering will be left for a future release.

The idea is still to implement the 2 suggested functions and update `list_feature_sets()` right?

**Comment by woop** [comment]
Hi @Joostrothweiler, that would be great!

Correct, it's about adding those to the `feature set` as opposed to the `feature`. Methods like `list_feature_sets()` should also be tested to see that they expose this information.
