### ISSUE TITLE
Better dev debugging workflow

### ISSUE THREAD

**Issue by dr3s** [feast-dev/feast#691]
**Is your feature request related to a problem? Please describe.**
For newcomers to feast, it can be difficult to set up the necessary dev workflow for multi container projects such as Feast.  Getting all the containers started, making incremental code changes, and debugging the integrated services can be tedious.

**Describe the solution you'd like**
docker compose set up to start feast core with remote debugging.  The main goal is to limit the work necessary when making incremental changes and restarting debugging.  The proposed flow would be:

1. `docker-compose up` would start required services and a shell container that mounts the src code
2. make code changes
3. `docker-compose exec mvn spring-boot:run -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8787"` to start debugging
4. set breakpoints and debug
5. stop debugging and repeat steps 2-4

A reorganization of the docker-compose files into directories, so that they can be more reusable without using the `-f` flag to docker-compose should make for better usability.

**Describe alternatives you've considered**
Certainly, test first development is preferable.  But sometimes debugging is necessary.  Another aspect is integration testing that could be easier to debug if using docker compose with locally mounted source.

**Additional context**
https://github.com/gojek/feast/pull/682 created an initial dev docker compose but falls short making a full round trip dev workflow.

**Comment by dr3s** [comment]
started in PR https://github.com/gojek/feast/pull/682

**Comment by woop** [comment]
Hi @dr3s, thanks for kicking this off. We always want to make it easier for folks to start developing and contribute back to the project.

Have you had a look at the contributing guide? I think it might benefit from some attention, at the very least if you could tell us which parts got in your way or should be expanded upon.

**Comment by dr3s** [comment]
A lot of what I faced was on my end and I'm not yet completely sure if docker compose is even the right choice for a dev workflow but it seemed to help me.  As I actually start going through the workflow more, I hope to bring some specific improvements or at least add documentation.

All of this is on OS X.  As I said, I think I had a few problems:

1. Started https://docs.feast.dev/contributing/development-guide and all the dependent services started but tests failed.
2. I'm having issues with getting the ports excepted in my firewall and I get a lot of pop-ups and have tests fail.  I hope to figure something out.  I thought that this is what caused the tests to fail.
3. I didn't realize that docker on OS X [can't use host networking](https://docs.docker.com/network/host/) .  Docker should at least warn about it.  The dev guide may want to switch to a platform independent port mapping.  But I think docker compose could also be an easier way of dealing with the networking.
4. So I left the dev guide and just tried to get it installed with docker compose.  The docker compose had been updated to require 2 files to start properly but the docs hadn't yet been updated.  Once @woop pointed that out, I was all good.  It might be nice to have different docker compose files for different use cases (maybe even in different directories), so you only have to specify at most 1 file.
3. I wasn't clear on the components that made up feast and how they depended upon each other.  The docker compose helped with this but as I said, I missed the other file and didn't understand job creation.
4. It seems job creation doesn't get created unless a storage is registered but I think that's something @woop said would change.

**Comment by woop** [comment]
Thanks for the detailed write-up @dr3s. I think we should keep this issue open until these points are resolved.

The development guide is definitely out of date right now, given that there have been API changes. Might be easier to simply remove some of the content there than try to keep it up to date.

> It might be nice to have different docker compose files for different use cases (maybe even in different directories), so you only have to specify at most 1 file.

Yea this is a good idea, as long as it doesnt duplicate too much configuration. 

> I wasn't clear on the components that made up feast and how they depended upon each other. The docker compose helped with this but as I said, I missed the other file and didn't understand job creation.

Out of curiosity, where would you expect this to be documented? I've added [Feast Architecture](https://docs.feast.dev/user-guide/architecture). Is this sufficient, or do you need more information on the life cycle of feature sets and jobs?

**Comment by dr3s** [comment]
I think the documentation is fine.  If I read it closer, I may not have had issues with the jobs not starting.  I think the issue here was that I needed to run feast serving even though I was just trying to do ingest because the store wasn't part of the main docker compose.  I expect that will change.

To answer your question though, I think Feast Architecture is the right starting point for understanding the components and their dependencies.
