### ISSUE TITLE
Add Snowflake as a historical store

### ISSUE THREAD

**Issue by dr3s** [feast-dev/feast#705]
**Is your feature request related to a problem? Please describe.**
Currently, it's not feasible to deploy Feast without GCP because BigQuery is the only historical store implemented.  

**Describe the solution you'd like**
Given the storage API https://github.com/gojek/feast/issues/482 it is now possible to implement an historical store based upon Sowflake.

**Describe alternatives you've considered**
Hudi, Athena, Delta, Iceberg could all be options but Snowflake is probably the easiest implementation based upon learning from the existing BigQuery code base.

**Additional context**
Design pending but the flow for batch retrieval would likely be as follows:

1. Client puts entities in s3
2. Snowflake storage loads from s3 to entity temp table 
3. Query for PITC features 
4. Write to s3 stage 
5. Pass client reference to s3 location of results

A key point in the design will also be changes to support S3 staging for client server data transfer.
https://docs.feast.dev/contributing/adding-new-storage-connectors#2-2-1-historical-serving

**Comment by woop** [comment]
Thanks for this @dr3s. I've personally been working on a JDBC storage connector, mostly to allow for Postgres/Sqlite to be used in testing/development.

What I am doing right now to get around the ingest/export step is to add a `TableSource`. Basically the incoming request would reference an existing entity table within the historical store, so there is no import/export step.

I do however think we should be finding a cleaner implementation as per my comment in [482](https://github.com/feast-dev/feast/issues/482#issuecomment-629065139)

Are you using JDBC or a Snowflake specific connector?

**Comment by siniG** [comment]
Shouldn't it be possible to load any 3rd party connector that will upload data to a historical database? That is, given an implementation of a historical DB, we should be able to submit, upload and query data from the store. Creating a generic JDBC based solution will allow Feast to connect to any organization's DWH.

**Comment by dr3s** [comment]
@woop The plan would be to use the snowflake JDBC driver.  Though it is JDBC, snowflake has proprietary DDL and DML to optimize for its implementations.  The key snowflake capabilities I was thinking I would use are around bulk data loading and unloading (like was done with BigQuery) and physical data clustering to optimize querying.

@siniG A generic JDBC solution may work but wouldn't take advantage of these proprietary snowflake features to be able to scale to very large data sets.  I think a generic JDBC storage implementation is still useful but not for the data set sizes we are dealing with unless there were significant design changes to feature storage and retrieval.

**Comment by dr3s** [comment]
requires https://github.com/feast-dev/feast/issues/706

**Comment by dr3s** [comment]
Assuming #706 is done first, the implementation should be fairly straight forward.  Following the [new docs](https://docs.feast.dev/contributing/adding-new-storage-connectors#1-storage-api), there would be 3 aspects to implement:

1.  Store initializaton - proto configuration, properties, loading code
2. Writing - FeatureSink
3. Retrieval - HistoricalRetriever

### Initialization
It may be a better use of our time to make initialization more pluggable.  Since Spring is already a dependency, this should be trivial but I'm not sure about how the protos are used yet.

Otherwise I'll just add configuration and loading code for a new snowflake storage type.

### Writing
`prepareWrite()` will use fairly standard SQL to create tables and update them if the featureset changes.  Data will be clustered by event_timestamp.  

`writer()` will create a PTransform that uses beam jdbc IO to write to snowflake with plain SQL.  An alternative could be to set up a stage and let snowflake pipe it in.

### Retrieval
`getStagingLocation()` will return S3 or whatever is configured

`getHistoricalFeatures()` will take a similar approach to BigQuery.  It will use or create a snowflake stage, import the entity rows into a temp table, select PITC results into the stage under the retrieval id.

**Comment by woop** [comment]
@dr3s I've completed a partial JDBCIO implementation for ingestion, just trying to rebase it on the current master and figure out how to implement retrieval. I hope we arent overlapping here. I am developing this for PG/Sqlite support. I haven't looked at data staging at all.

**Comment by dr3s** [comment]
@woop I don't think we will overlap.  Let me know if you have a branch I can look at.  I'm trying to ramp up the team before we start dev in earnest.  When we do, there is plenty of snowflake specific implementation to do before anything that would be plain JDBCIO.

**Comment by woop** [comment]
> @woop I don't think we will overlap. Let me know if you have a branch I can look at. I'm trying to ramp up the team before we start dev in earnest. When we do, there is plenty of snowflake specific implementation to do before anything that would be plain JDBCIO.

Awesome. I am hoping to have a WIP PR out soon that you can look at.

**Comment by groodt** [comment]
@woop I don't suppose you've got any update on the JDBCIO support? I'm sure there are others that would be interested in using Snowflake. Although I do realise that the priority would be an AWS native option.

**Comment by woop** [comment]
> @woop I don't suppose you've got any update on the JDBCIO support? I'm sure there are others that would be interested in using Snowflake. Although I do realise that the priority would be an AWS native option.

I had the PR pretty far down the line, but we changed the way ingestion jobs work in Feast 0.6. They now allow for dynamically adding sinks, meaning they dont need to restart and can stay online. Unfortunately JDBCIO doesnt support runtime reconfiguration of destinations (like adding new tables), which means we need to do more work to get this out the door.

We have just received a PR from some contributors to add Snowflake support #902, but it hasn't been reviewed yet.

**Comment by groodt** [comment]
Thanks for the background. Good to know.
