### ISSUE TITLE
Online History Querying

### ISSUE THREAD

**Issue by siniG** [feast-dev/feast#713]
**Is your feature request related to a problem? Please describe.**
Currently Feast supports only supports last updates feature values. In RNN we need a time series of features. That is, the last N occurrences of the feature. Taking the data from BigQuery or any other historical engine is not possible as latency is too high for real-time model prediction.

**Describe the solution you'd like**
An online feature set should be configurable to allow a history (with limit) of last feature values calculated.

**Describe alternatives you've considered**
Querying BigQuery or other historical databases was a no go.

**Comment by woop** [comment]
Hi @siniG,

Thanks for raising this point. We used to have time series data for online serving, but we couldn't find a use case in ML for it. It would be interesting to find out more about your usecase.

At the moment you can store historical data in arrays for online serving. So you can have the last 60 minutes of data as individual values in an array for example. This seems to be what most of our users are using, and fits in well with their existing ML frameworks.

Would that work for you?

**Comment by siniG** [comment]
The way we work with time series data today is that we have an online feature computation layer that reads data coming from the stream and pushes it to an output topic where a consumer saves it as a FIFO array.
We can send the entire array with every update to Feast, but I think that would be a bit of a waste as we'll be duplicating data and we won't be able to control our feature metadata in a single place (part time series size will be defined in computation layer while feature definitions in feast)

**Comment by woop** [comment]
> The way we work with time series data today is that we have an online feature computation layer that reads data coming from the stream and pushes it to an output topic where a consumer saves it as a FIFO array.

> We can send the entire array with every update to Feast, but I think that would be a bit of a waste as we'll be duplicating data and we won't be able to control our feature metadata in a single place (part time series size will be defined in computation layer while feature definitions in feast)

Hi @siniG, thanks for being so patient.

You two options with Feast right now.
1. Send an array as mentioned above. Yes, this will duplicate some data, but it will also improve lookup times for both the online and historical cases. It's not clear to me how feature metadata would be duplicated here. It seems like the only metadata you need to capture would be within Feast. Would you mind elaborating?
2. Create multiple features. You can have a feature set that represents the `last n` values. Each feature set contains a single feature. When you look up the features your query would be.

```
features = ['feature_latest', 'feature_n_1', 'feature_n_2']
```

The second option would allow you to update these features independently and still use them in a single retrieval.

**Comment by woop** [comment]
Closing this for now since I don't think there are still open questions. Please let me know if you want to continue the discussion @siniG
