### ISSUE TITLE
Unable to setup feast

### ISSUE THREAD

**Issue by tordsae** [feast-dev/feast#730]
## Summary
Hi, I am trying to set up Feast on a kubernetes cluster by following the instructions on [https://github.com/feast-dev/feast/blob/master/infra/charts/feast/README.md](url). I have added a secret for the postgres pasword, but when I run `helm test test-release` it fails.

I have also tried to test by following the example on [https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb](url). Here it stops at the ingestion part. I stays at 0% for 20 min before I get and error message

```
  File "/home/autilibrain/anaconda3/lib/python3.7/site-packages/feast/client.py", line 790, in ingest
    producer.print_results()
  File "/home/autilibrain/anaconda3/lib/python3.7/site-packages/feast/loaders/abstract_producer.py", line 74, in print_results
    else f"\nLast exception:\n{self.last_exception}"
TypeError: Type cimpl.KafkaError doesn't define __format__`
```

### Serving test pod log:
```
Feature set updated/created: "customer_transactions:0"
Waiting for feature set to be ready for ingestion...
100%|██████████| 5/5 [00:01<00:00,  4.83rows/s]
Ingestion complete!

Ingestion statistics:
Success: 5/5
Removing temporary file(s)...
Ingested dataframe: 
                          datetime  customer_id  daily_transactions  \
0 2020-05-22 08:21:28.029530+00:00            0            0.380651   
1 2020-05-22 08:21:28.029554+00:00            1            0.167942   
2 2020-05-22 08:21:28.029556+00:00            2            0.519692   

   total_transactions  
0                   0  
1                   1  
2                   2  
Traceback (most recent call last):
  File "<stdin>", line 48, in <module>
  File "/usr/local/lib/python3.7/site-packages/feast/client.py", line 658, in get_online_features
    entity_rows=entity_rows,
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Unable to retrieve feature from Redis"
```

**Comment by woop** [comment]
> Hi, I am trying to set up Feast on a kubernetes cluster by following the instructions on https://github.com/feast-dev/feast/blob/master/infra/charts/feast/README.md. I have added a secret for the postgres pasword, but when I run helm test test-release it fails.

Hi @tordsae. Thanks for trying out feast!

After you installed Feast, did all of the pods enter a `running` state in your cluster? Did you see any exceptions on the `feast-core` or `feast-serving` pods when interacting with Feast through the notebooks?

Do you have access to the Kafka cluster that is installed with Feast? You must have direct access to a Kafka port in order to ingest data. Can you confirm that you can access port 9092 (or whatever port your Kafka exposes)? 

An easy way to test it using https://github.com/edenhill/kafkacat.

**Comment by tordsae** [comment]
On the online serving pod I get the error message
```
NOT_FOUND: Unable to retrieve feature from Redis
	at io.grpc.Status.asRuntimeException(Status.java:521)
	at feast.storage.connectors.redis.retriever.RedisOnlineRetriever.sendMultiGet(RedisOnlineRetriever.java:209)
	at feast.storage.connectors.redis.retriever.RedisOnlineRetriever.sendAndProcessMultiGet(RedisOnlineRetriever.java:149)
	at feast.storage.connectors.redis.retriever.RedisOnlineRetriever.getOnlineFeatures(RedisOnlineRetriever.java:84)
	at feast.serving.service.OnlineServingService.getOnlineFeatures(OnlineServingService.java:77)
	at feast.serving.controller.ServingServiceGRpcController.getOnlineFeatures(ServingServiceGRpcController.java:76)
	at feast.proto.serving.ServingServiceGrpc$MethodHandlers.invoke(ServingServiceGrpc.java:495)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required.
```
I am able to get metadata from Kafka, but when I listen to the feast topic nothing comes through during ingestion.

However I get a different error message now, when trying to ingest data. 
```
  0%|          | 0/272 [00:00<?, ?rows/s]Traceback (most recent call last):
  File "/home/autilibrain/Projects/src/Feast/connectiontest.py", line 48, in <module>
    client.ingest(temp_name, temp)
  File "/home/autilibrain/anaconda3/lib/python3.7/site-packages/feast/client.py", line 844, in ingest
    flush(timeout=timeout)
  File "/home/autilibrain/anaconda3/lib/python3.7/site-packages/feast/loaders/abstract_producer.py", line 114, in flush
    raise Exception("Not all Kafka messages are successfully delivered.")
Exception: Not all Kafka messages are successfully delivered.
Removing temporary file(s)...
```

**Comment by woop** [comment]
@tordsae Can you print out the feature set with `client.get_feature_set(your_feature_set)` and see if the broker addresses are correctly defined? Also, can you please make sure that you are using the Feast 0.4 SDK because it looks like you are using Feast 0.4 as the deployment (judging by `customer_transactions:0`).

Alternatively you should upgrade to Feast 0.5 because quite a few quality of life changes have been made.

**Comment by tordsae** [comment]
I already use 0.5. `feast.__version__
Out[5]: '0.5.0'`. 
Seems like the broker is correctly defined. 
```
fs.get_kafka_source_brokers()
Out[22]: 'feast-kafka:9092'
```
The chart I used when installing was `0.5.0-alpha.1`. Also I can mention that all services except from feast-core and online-serving has the ClusterIp type. Core and online-serving are LoadBalancers.

**Comment by woop** [comment]
> Feature set updated/created: "customer_transactions:0"

Feast 0.5 does not have versions. Meaning there should be no `:0` on `customer_transactions`. Can you make sure that you have the latest version of the `basic` notebook and that you are running Feast 0.5 in your cluster? You can just look at the docker images for Feast Core or Feast Serving.

**Comment by woop** [comment]
Thanks for your quick response :)

> metadata from the feature sets I applied

Would you mind printing out the feature set metadata here? 

> `gcr.io/kf-feast/feast-core:dev`

The risk with using a named tag is that you may have an old image cached. I think you should rather use `latest` than `dev`. That will pin your versions to officially released versions. `dev` is the current tip of the master branch.

**Comment by tordsae** [comment]
Like so? 
```
{
  "spec": {
    "name": "Electgricity_meter_HF",
    "entities": [
      {
        "name": "sensor_id",
        "valueType": "STRING"
      }
    ],
    "features": [
      {
        "name": "organization_id",
        "valueType": "STRING"
      },
      {
        "name": "room_id",
        "valueType": "STRING"
      },
      {
        "name": "property_name",
        "valueType": "STRING"
      },
      {
        "name": "floor_name",
        "valueType": "STRING"
      },
      {
        "name": "sensor_key",
        "valueType": "STRING"
      },
      {
        "name": "sensor_name",
        "valueType": "STRING"
      },
      {
        "name": "CurrentL1",
        "valueType": "DOUBLE"
      },
      {
        "name": "EnergyL1L3",
        "valueType": "DOUBLE"
      },
      {
        "name": "building_name",
        "valueType": "STRING"
      },
      {
        "name": "VoltageL1",
        "valueType": "DOUBLE"
      },
      {
        "name": "room_name",
        "valueType": "STRING"
      }
    ],
    "maxAge": "4320s",
    "source": {
      "type": "KAFKA",
      "kafkaSourceConfig": {
        "bootstrapServers": "feast-kafka:9092",
        "topic": "feast"
      }
    },
    "project": "Test2"
  },
  "meta": {
    "createdTimestamp": "2020-05-20T13:00:00Z",
    "status": "STATUS_READY"
  }
}
```

I have used different data, but done everything as in the example(allmost the same code, but different data and )

**Comment by woop** [comment]
Ok, and did you change any configuration on the Redis installation? 

```
NOAUTH Authentication required
```
Normally we dont use auth with Redis. Is it currently enabled?

**Comment by tordsae** [comment]
Did not change anything on the Redis installation. Installed as it was on the the repo I cloned (`git clone https://github.com/feast-dev/feast.git`). Only changed Core and Serving to LoadBalancer so I didn't have to port-forward them.

Not sure how to check if auth is enabled. Found this in the values.yaml file for the redis chart:
```
## Use password authentication
usePassword: true
## Redis password (both master and slave)
## Defaults to a random 10-character alphanumeric string if not set and usePassword is true
## ref: https://github.com/bitnami/bitnami-docker-redis#setting-the-server-password-on-first-run
```

**Comment by woop** [comment]
Hi @tordsae,

Apologies for only coming back to you now. Missed this issue. I think the issue might be related to that Redis deployment. Can you see if you can disable the auth if it is on?

**Comment by woop** [comment]
@tordsae I've just updated the guide to remove Redis authentication. I believe that it was toggled on through one of our dependent charts. Everything should work now.

**Comment by masonlr** [comment]
Thanks for the discussion above, this helped me to get through the same redis auth problem. 
(I know it's not supported but I'm testing via helm v3 using docker-desktop k8s.)

I copied values.yaml locally and changed https://github.com/feast-dev/feast/blob/7f9aa0c161cdcde1f5bcea450beeeb1ab55aa7d6/infra/charts/feast/values.yaml#L25-L27 to

```yaml
redis:
  # redis.enabled -- Flag to install Redis
  enabled: true
  usePassword: false
```

and installed with

```
# assumes feast-postgresql secret has been created
helm install dev feast-charts/feast --set feast-core.postgresql.existingSecret=feast-postgresql --set postgresql.existingSecret=feast-postgresql -f values.yaml
```

> I've just updated the guide to remove Redis authentication

@woop are you referring to https://github.com/feast-dev/feast/blob/7f9aa0c161cdcde1f5bcea450beeeb1ab55aa7d6/infra/charts/feast/values-batch-serving.yaml#L31-L32?

**Comment by woop** [comment]
> Thanks for the discussion above, this helped me to get through the same redis auth problem.
> (I know it's not supported but I'm testing via helm v3 using docker-desktop k8s.)
> 
> I copied values.yaml locally and changed
> 
> https://github.com/feast-dev/feast/blob/7f9aa0c161cdcde1f5bcea450beeeb1ab55aa7d6/infra/charts/feast/values.yaml#L25-L27
> 
> to
> ```yaml
> redis:
>   # redis.enabled -- Flag to install Redis
>   enabled: true
>   usePassword: false
> ```
> 
> and installed with
> 
> ```
> # assumes feast-postgresql secret has been created
> helm install dev feast-charts/feast --set feast-core.postgresql.existingSecret=feast-postgresql --set postgresql.existingSecret=feast-postgresql -f values.yaml
> ```
> 
> > I've just updated the guide to remove Redis authentication
> 
> @woop are you referring to
> 
> https://github.com/feast-dev/feast/blob/7f9aa0c161cdcde1f5bcea450beeeb1ab55aa7d6/infra/charts/feast/values-batch-serving.yaml#L31-L32
> 
> ?

Yes, thats right.
