### ISSUE TITLE
Feast API: BigQuery SQL Sources

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#732]
I've created a proposal for adding BigQuery SQL sources to Feast. The goal is to provide a more scalable way for users to load in data into Feast.

Please leave your comments here: [Feast RFC: BigQuery SQL Source](https://docs.google.com/document/d/1DIBoJIc4scRFLprcyNDb4GF6I8yIE42wVYd2jceumgE/edit#)

To access the file you will need to be a part of our [Google Groups](https://docs.feast.dev/introduction/getting-help#feast-discussion)

Related: #6 

cc @ches @zhilingc @pyalex @Yanson

**Comment by woop** [comment]
We'll be targeting this functionality for Feast 0.8

**Comment by devoftheweb** [comment]
BigQuery as a supported data source would be a huge win for us!

+1

**Comment by woop** [comment]
This functionality has landed.

**Comment by artemlops** [comment]
where can we find the documentation on the BigQuery data source?

**Comment by artemlops** [comment]
Found: https://api.docs.feast.dev/python/feast.html?highlight=bigquerysource#feast.BigQuerySource
