### ISSUE TITLE
Towards lazy consensus

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#733]
I'd like to propose that we officially adopt [Lazy Consensus](http://community.apache.org/committers/lazyConsensus.html).

Currently we are already operating in this model to some degree, however it isn't always clear:
1. If a proposal is needed before starting work.
1. How long a proposal should be left up for discussion and when development can begin.

Moving towards lazy consensus means that contributors can just get to coding if they are certain about what the project needs, instead of requiring proposals and discussions. There is still a risk that their work could be held up in review or in the PR stage, but it is up to them to decide whether to seek feedback first or just start development.

I'll be applying lazy consensus to this issue (in a meta twist). If I don't hear anything back then I will assume nobody disagrees with this approach and add it to our documentation.

**Comment by ches** [comment]
> but it is up to them to dec

You trailed off there.

Otherwise makes sense, though.
