### ISSUE TITLE
Feast API: On-demand features

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#738]
# Updates
_See also: [Feast Slack: #feast-feature-transformations](https://tectonfeast.slack.com/archives/C03A2CH7GAG)_
_See also [RFC-021: On-demand Transformations](https://docs.google.com/document/d/1lgfIw0Drc65LpaxbUu49RCeJgMew547meSJttnUqz7c/edit)_
- below was original issue motivating above RFC + implementation.
- Currently, on demand features are in alpha, with the main outstanding task to make more scalable in the batch use case

-------------
# Archive
## 1. Overview

Feast currently does not apply any transformations on user data. The expectation is that Feast will be the sourcing, ingestion, and serving layer. 

Feature transformations can be grouped according to
1. **Precomputable features**: These are transformations that are applied either on real-time streams or batch data at rest, but they are applied prior to ingestion into Feast and into stores. Thus, they are a pre-computational step.
1. **On-demand features**: These are features that cannot be precomputed. Often the data required to apply these feature transformations are only available at the last moment. Examples of these kinds of features are ones that come from a transaction or order (location data). 

On-demand features are a use case that Feast should support, otherwise teams would need to develop custom logic in both their training and serving systems to apply these transformations. 

## 2. Use Case: **Trip Level Features**

Imagine we need to make a prediction based on a trip with the following data model

```
Trip 
- trip_id
- customer_id
- origin_latitude
- origin_longitude
- dest_latitude
- dest_longitude
```

A trip is created when the user sends a request to start a trip to the `Trip Service`. The `Trip Service` needs to respond within 100 ms to the user to confirm the creation of the trip. The `Trip Service` is always pushing data to a stream, so when a new trip is created it is instantly pushed as an event to the stream, after which the `Trip Service` finishes its logic and responds to the user.

![image](https://user-images.githubusercontent.com/6728866/82725523-0fe62500-9d10-11ea-80ab-4170eaf28189.png)

The `Trip Service` is also powered by an ML model in the `Trip Model Service`. This is one of the steps the `Trip Service` does before responding to the user. It's not important what this ML model does. The `Trip Service` sends a request to the `Trip Model Service`. This model takes in both `customer` features and `trip` level features in order to make a prediction. The entity types are thus `trip` and `customer`. 

One of the features the model wants is the straight line distance between origin and destination. This can easily be calculated with a function like `distance(origin_latitude, origin_longitude, dest_latitude, dest_longitude)`

The `Trip Model Service` then sends a feature request to `Feast Serving` and asks for both features on both the `customer id` and `trip id`, expecting the `distance` feature above to have been precalculated.

The store won't contain the `trip id` features that the model is looking for, only the `customer id` features will be there. In fact the `trip_id` won't even exist in the online store.

This is because the round trip through the stream as well as through stream processing means that `(1)` will always happen faster than `(2)`. Meaning the transactional synchronous systems will reach the feature store for feature lookups faster than the stream processing and ingestion can populate the store with precomputed features.

## 3. Derived features

One solution to the above problem would be to introduce feature transformations that happen just in time in the online serving layer of Feast. These transformations would then take precomputed features, or data provided in the incoming request from the transactional system, and derive new features based on either predefined or user defined functions. The resulting features can then be provided to the model.

## 4. Requirements

**Online to offline consistency:** A key design decision would be to ensure consistency of these transformations between online serving and historical serving. One approach would be to have derived features as a final stage prior to serving (either in historical or online). 

**Client language agnositicism**: The implementation should ideally be agnostic to the execution environment of the client. Meaning the transformations should function for both online and historical serving no matter which environment languages triggers the call (Python, Golang, Java, or any gRPC client). This requirement probably means that the transformation cannot easily happen client side.

**Row vs grouped transformations:** There does not seem to be a strong need for column or dataset (grouped) transformations, only instance level transformations (row level). 

**Development experience**: This is not a strict requirement as the ones above, but more of a design goal. It should ideally be both easy and fast for users to develop these derived feature transformations (if we allow UDFs). So the development experience is one we should optimize for.

## 5. Next Steps

I'm opening this up with a use case / problem statement. There are teams running Feast right now that are looking at implementing this, so it would be great if we can agree on an MVP design.

**Comment by idahoakl** [comment]
Thank you for writing this up.

The current use case that we have is very similar to the distance example above but for us the source data is all within Feast Serving with the complication being a very high cardinality between the parts to be combined into a single feature for a model.  Precomputing all possible combined features is prohibitively expensive in terms of time and compute.  

I believe a key developer experience component is the seamless consumption of a precomputed feature along side of a derived feature, both serving and batch.  For example, if a developer retrieves features `a`, `b`, and `c` with `b` being a derived feature (defined as `a + c`) the request structure should be the same as a request structure where only precomputed features were retrieved.  This would require that the definition of a derived feature be part of the feature definition and not supplied as part of the retrieval request.  Requiring the derived feature definition/expression to be collocated with the FeatureSet also provides a stronger mechanism to ensure online to offline consistency.

Serving performance is a concern when performing transformations in real time vs precomputed.  I think the design should provide some methods and/or patterns to allow for the performance impact to be controlled or expose to users what the latency cost is of retrieving a derived feature vs a precomputed feature.  A few ideas to start the discussion.
- Define a DSL that can be used by create derived features.
  - Pros
    - Performance characteristics are easier to reason about and provide some sort of guarantee.
    - Discourages a derived feature from becoming overly complex and Feast acting as a general purpose data transformation framework.  Data transformations should happen upstream of Feast as much as possible.
  - Cons
    - Maintaining a DSL
    - Potential bottleneck in feature development velocity if required functionality was not present in DSL and needed to be added.
- Performance test a user defined derived feature and expose the results thus allowing users to understand the latency impact of using a given feature.
  - Pros
    - Wider selection of technologies can be considered for supporting development of derived features.
    - Users have more autonomy to define and maintain a derived feature.
    - Understanding the latency of feature allows for a better cost/benefit analysis to use a derived feature vs converting it to a precomputed feature
  - Cons
    - Performance tuning of a derived feature is the responsibility of the user.  Depending on the final implementation of derived features this tuning may take place in a non-natural development environment.
    - Derived features can grow to become arbitrarily complex and increase maintenance costs.
    - A performance testing framework within Feast would need to be built to perform the actual testing.  The complexity of this will depend some on the target deployment infrastructure.

**Comment by woop** [comment]
> I believe a key developer experience component is the seamless consumption of a precomputed feature along side of a derived feature, both serving and batch.
> Requiring the derived feature definition/expression to be collocated with the FeatureSet also provides a stronger mechanism to ensure online to offline consistency

Agreed on these points. 

To me a fundamental question is what the developer experience would be in defining these derived features, how they will be registered in Feast, and how Feast will apply them during the production of data. As much as possible I want to see if we can reuse technologies that exist in this space already instead of implementing something new.

> Define a DSL that can be used by create derived features.

I like this idea, but I think it would be very hard to create a DSL that covers the majority of use cases. My suspicion is that it will very quickly become idiosyncratic and unscalable to maintain, thus leading to the second option which is UDFs or custom transformations.

> Performance test a user defined derived feature and expose the results thus allowing users to understand the latency impact of using a given feature.

It seems like we are combining the requirement/proposal of UDFs with the performance testing requirement. Would it make sense to consider these separately? I believe if we provide a means for profiling UDFs during development, and we provide a means of isolating impact (separate serving deployments), then we should have enough tools to support an MVP of this at scale.

**Comment by idahoakl** [comment]
> As much as possible I want to see if we can reuse technologies that exist in this space already instead of implementing something new.

I agree with trying to re-use existing technologies.

>  like this idea, but I think it would be very hard to create a DSL that covers the majority of use cases. My suspicion is that it will very quickly become idiosyncratic and unscalable to maintain, thus leading to the second option which is UDFs or custom transformations.

We're in agreement with a DSL.  One of the immediate cons is "maintaining a DSL" :)

For performance testing my concern is less about isolation between different serving instances and more about allowing developers to reason about what the impact to the overall latency of evaluating a model when using a derived feature.  For an MVP performance testing isn't strictly necessary as the impact could be evaluated during end to end testing by the developer.

**Comment by idahoakl** [comment]
An example use case that we have internally is the interaction between a customer vector and a product vector.  There are millions of products and millions of customers.  The feature being used within a model is the dot product of these 2 vectors.  

`F1 = C x P`

The components of the respective customer and product vectors are the result of another data job and will change throughout the day, some of them in near real time.

**Comment by futurely** [comment]
Is it possible to use TensorFlow Transform to generate features?

**Comment by liorshk** [comment]
One of the common use cases that we have internally is derived features that are based on the output of other ML models.
In addition, we have 2nd degree of derived features (features that derive of derived features).
I believe that these two use cases should be taken into consideration.

**Comment by woop** [comment]
> Is it possible to use TensorFlow Transform, Apache Beam or other frameworks to generate features?

Yea this is certainly possible. I think the question is just what the developer experience is like. Is this purely a post-processing transform (on demand only), or also used for precomputation? Or both? 

Normally with TFX and TensorFlow transforms you want to own the complete life cycle from raw data to the model.

**Comment by woop** [comment]
> One of the common use cases that we have internally is derived features that are based on the output of other ML models.
> In addition, we have 2nd degree of derived features (features that derive of derived features).
> I believe that these two use cases should be taken into consideration.

That makes sense. Although I would argue that we shouldn't have a distinction between levels of transformations. 

Are these derivations or transformations only for "on-demand" features, or also for precomputed features?

**Comment by liorshk** [comment]
>  I would argue that we shouldn't have a distinction between levels of transformations.
The question is whether the output of the transformation is saved to the feature store or not.
On the precomputed features case - I think it would be valuable to have the ability to create DAGs of transformations on top of existing features and saving the output of those transformations back to the feature store so more transformations could run. This would mean that there would be dependencies between features and transformations.

> Are these derivations or transformations only for "on-demand" features, or also for precomputed features?
Both

**Comment by jcpsantiago** [comment]
> One of the common use cases that we have internally is derived features that are based on the output of other ML models.

Besides "simple" derived features e.g. "average order amount for customer x - current order amount", where "average amount" is _somehow_ pre-calculated and "current amount" is directly ingested, I'm also very much interested in the quoted use-case. Actually, these use-cases are the reason we want some sort of feature store and feature transformation at all. Some questions I still have:

- If the output of a model is supposed to be a feature, is the model server itself publishing the results, or is it part of the _feature transformation layer_?
- How do you deal with the race condition arising when using an aggregate feature like my example? you want to use the current, not yet updated average to calculate the feature, but at the same time you want to update the average because maybe a model downstream cares about that and not the derivative
- For such aggregate features, would Feast "go back" to the original data source (e.g. query orders database), or is it keeping a historical record of all the order amounts, thus potentially duplicating data across systems?

> These transformations would then take precomputed features, or data provided in the incoming request from the transactional system, and derive new features based on either predefined or user defined functions. 

@woop by _transactional system_ do you mean the data being sent to the  `Stream > Stream processing > ...` pathway, or a situation where the model receives a payload with the data it needs?

**Comment by svenharris** [comment]
Is this still somewhere in the Feast roadmap (and if so is there somewhere I can track the progress)? It's a feature I would love to see, and am currently actively looking for in the adoption of a feature store.

**Comment by woop** [comment]
As an update here, we are currently working on an RFC for on-demand transformations.

**Comment by adchia** [comment]
Logging the values of serving features can definitely make sense. This is somewhat relevant to work we're doing with data quality monitoring (which is implementing logging): https://docs.google.com/document/d/110F72d4NTv80p35wDSONxhhPBqWRwbZXG4f9mNEMd98/edit
