### ISSUE TITLE
Fix Telecom Customer Churn Prediction Example Notebook

### ISSUE THREAD

**Issue by bradaallen** [feast-dev/feast#742]
Three small issues with the telco churn walkthrough:
1. The docker container used for loading the example notebooks has all of the packages for the "basic" notebook environment, but not for the "telco" notebook. (eg, `pillow`, `python-slugify`, etc.)
2. The environmental variables do not need to be set, as they are part of the config in the the docker-compose. The environmental variables set to `localhost`, but in the config are `core`. Using the code to set the environmental variables in the notebook results in an error.
3. For making predictions, there is an `entity_df` variable that is referenced in the telco notebook - but that variable is not instantiated anywhere.

**Comment by woop** [comment]
Thanks for this @bradaallen

**Comment by woop** [comment]
Should be fixed in #803
