### ISSUE TITLE
Feast Ingestion not exporting success metrics to statsd

### ISSUE THREAD

**Issue by pmjacinto** [feast-dev/feast#747]
## Expected Behavior 

The dataflow step `WriteSuccessMetrics` should be executed and produce metrics.

## Current Behavior

In the previous step, the "dummy" PTransform always seems to output zero rows.
https://github.com/feast-dev/feast/blob/v0.5.0/storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java#L93-L105

This leads to the metrics transform never getting any inputs.

Is this an expected behaviour?

<img width="825" alt="Screenshot 2020-05-27 at 16 32 13" src="https://user-images.githubusercontent.com/29306657/83040934-c7907500-a037-11ea-9a72-5fd186e9b3c7.png">
---
<img width="825" alt="Screenshot 2020-05-27 at 16 32 34" src="https://user-images.githubusercontent.com/29306657/83040944-cb23fc00-a037-11ea-9beb-f30fb8ba538a.png">

## Steps to reproduce

- Create an ingestion pipeline
- Ingest a row
- Check dataflow metrics

### Specifications

- Version: 0.5.0
- Platform: GKE, Dataflow
- Subsystem: Feast Ingestion

**Comment by woop** [comment]
Hi @pmjacinto 

Thanks for raising this. I believe the comment that you linked to does indicate the problem: BigQueryIO does not emit successful writes, meaning we can't emit metrics. `WriteSuccessMetrics` is an IO agnostic step that is always generated. For the time being we emit total rows processed and failed metrics, the difference of which should give you an estimation of rows written.

**Comment by woop** [comment]
@Yanson @pmjacinto for your information, the latest addition to BQ ingestion will have success metrics again #757
