### ISSUE TITLE
Migrate SDKs to use Native types instead of Protobuf types

### ISSUE THREAD

**Issue by mrzzy** [feast-dev/feast#766]
### Background
One of the stumbling blocks working on PR #658   with the SDKs is that the Python and Golang SDKs directly expose the Serving API to users. This is a problem changes with the Serving protobuf API will propagate to user API changes on the Python and Java client. This makes API compatibility hard to track and maintain. ([see @ches's comment about it here](https://github.com/feast-dev/feast/pull/658#issuecomment-621681310))

### Problem 
Currently the SDKs expose internal Protobuf types directly to users.
For example:
- Python SDK
https://github.com/feast-dev/feast/blob/a33883fbbf0c8d4b27711d85bca313ab11da81b6/sdk/python/feast/client.py#L619
- Golang SDK
https://github.com/feast-dev/feast/blob/a33883fbbf0c8d4b27711d85bca313ab11da81b6/sdk/go/client.go#L84

This poses a problem as:
- This makes the gRPC API exposed by Feast Serving/Core a user facing API, affecting downstream systems if changes are made to it.
- Users prefer to deal with native types instead of Protobuf types. For example, Python users prefer to interact with `datetime.timedelta` instead of Protobuf's `Duration` type.

### Proposed Solution
1. Row API (similar to Java SDK’s Row)  to be introduced to Python and Go SDKs as an higher level API. 
- ie Row would be used to abstract away `GetOnlineFeaturesResponse` etc.
```python
feature_rows = client.get_online_features(....)
```

2. Use native types in User Facing SDK APIs
- ie:
```golang
func (fc *GrpcClient) GetFeastServingInfo(....) map[string]string
```

**Comment by woop** [comment]
Thanks for this @mrzzy. I am assuming that this would also apply to EntityRows

```
    entity_rows=[
        GetOnlineFeaturesRequest.EntityRow(
            fields={
                "customer_id": Value(
                    int64_val=1
                )
            }
        )
    ],
```

Kind of nasty if the user just wants to set that `1`.
