### ISSUE TITLE
Not able to find AutoValue_BigQuery{....}

### ISSUE THREAD

**Issue by zhangchi1** [feast-dev/feast#780]
## Issue
I was trying to understand what the data storage (BigQuery)behind the architecture is. After I compiled the Feast project on my local machine, I was not able to find `AutoValue_BigQueryFeatureSink`, `AutoValue_BigQueryHistoricalRetriever`, and `AutoValue_SubqueryCallable`, under the `builder()` method. Under [feast/storage](https://github.com/feast-dev/feast/blob/4be0eff52e1f74b89971a609921bbbd635c612fe/storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/BigQueryHistoricalRetriever.java#L98)

## Questions
1. I'm wondering if this AutoValue_BigQueryHistoricalRetriever is related to `AutoValue.Builder` for Google BigQuery?
2. Did I miss anything when I was compiling the maven project?

## Steps to reproduce
1. Cloned the feast [repo](https://github.com/feast-dev/feast) 
2. Imported the project as  maven using IntelliJ

## System
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"

Thanks,

**Comment by woop** [comment]
Hi @zhangchi1,

What command did you run to build the project? Can you try `mvn clean compile`?

**Comment by zhangchi1** [comment]
Hi @woop , yes I run`mvn clean compile ` and got build success, here is a snapshot 
```
[INFO] Reactor Summary for Feast 0.6-SNAPSHOT:
[INFO] 
[INFO] Feast .............................................. SUCCESS [  0.698 s]
[INFO] Feast Data Types for Java .......................... SUCCESS [  7.249 s]
[INFO] Feast Storage API .................................. SUCCESS [  0.640 s]
[INFO] Feast Storage Connectors ........................... SUCCESS [  0.223 s]
[INFO] Feast Storage Connector for Redis .................. SUCCESS [  0.617 s]
[INFO] Feast Storage Connector for BigQuery ............... SUCCESS [  0.746 s]
[INFO] Feast Storage Connector for JDBC ................... SUCCESS [  0.470 s]
[INFO] Feast Ingestion .................................... SUCCESS [  2.630 s]
[INFO] Feast Core ......................................... SUCCESS [  1.758 s]
[INFO] Feast Serving ...................................... SUCCESS [  0.645 s]
[INFO] Feast SDK for Java ................................. SUCCESS [  0.155 s]
[INFO] Feast Coverage Java ................................ SUCCESS [  0.103 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.499 s
[INFO] Finished at: 2020-06-
[INFO] ------------------------------------------------------------------------
```
Most of the time, I just let my IDE build the Maven project for me.

**Comment by woop** [comment]
> Hi @woop , yes I run`mvn clean compile ` and got build success, here is a snapshot
> 
> ```
> [INFO] Reactor Summary for Feast 0.6-SNAPSHOT:
> [INFO] 
> [INFO] Feast .............................................. SUCCESS [  0.698 s]
> [INFO] Feast Data Types for Java .......................... SUCCESS [  7.249 s]
> [INFO] Feast Storage API .................................. SUCCESS [  0.640 s]
> [INFO] Feast Storage Connectors ........................... SUCCESS [  0.223 s]
> [INFO] Feast Storage Connector for Redis .................. SUCCESS [  0.617 s]
> [INFO] Feast Storage Connector for BigQuery ............... SUCCESS [  0.746 s]
> [INFO] Feast Storage Connector for JDBC ................... SUCCESS [  0.470 s]
> [INFO] Feast Ingestion .................................... SUCCESS [  2.630 s]
> [INFO] Feast Core ......................................... SUCCESS [  1.758 s]
> [INFO] Feast Serving ...................................... SUCCESS [  0.645 s]
> [INFO] Feast SDK for Java ................................. SUCCESS [  0.155 s]
> [INFO] Feast Coverage Java ................................ SUCCESS [  0.103 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  16.499 s
> [INFO] Finished at: 2020-06-
> [INFO] ------------------------------------------------------------------------
> ```
> 
> Most of the time, I just let my IDE build the Maven project for me.

I think you can find out more about how AutoValue works over here: https://www.baeldung.com/introduction-to-autovalue

If your compilation works, then the classes can be built :)
