### ISSUE TITLE
Deployment on Docker Compose - grpc_cli: command not found

### ISSUE THREAD

**Issue by MatteoFelici** [feast-dev/feast#789]
## Expected Behavior 
Testing Feast Core with `grpc_cli ls ${FEAST_CORE_URL} feast.core.CoreService` as in documentation gives list of results
## Current Behavior
`bash: grpc_cli: command not found`

## Steps to reproduce
I have deployed Feast with docker-compose, following all the steps in the documentation. Then I followed the test connection on "Troubleshooting".
### Specifications

- Version: Latest / Cloned and followed local install / setup instructions
- Platform: Mac OS
- Subsystem:

## Possible Solution
Maybe the installation of the grpc_cli is missing from the docker image?

**Comment by woop** [comment]
Hey @MatteoFelici, I just realized the link to the grpc_cli is already in the installation guide here https://docs.feast.dev/administration/troubleshooting

Please let me know if its not sufficient to get started :)
