### ISSUE TITLE
Please update the official documentation

### ISSUE THREAD

**Issue by LuTang-Terrence** [feast-dev/feast#796]
I was following the official documentation to test run feast using docker compose for online serving only. In the basic experiment jupyter notebook, I was stuck at

> 7. Ingest data into Feast for a feature set
>`client.ingest("customer_transactions", customer_features)`

It always get timeout.

After hours of struggling, a colleague pointed out that the online-serving is not started. It is mentioned in the github main page as:
`docker-compose -f docker-compose.yml -f docker-compose.online.yml up -d`
but missing in the official documentation:
`docker-compose up -d`

I think it's better to add it to the documentation too in case others have the same issue.

**Comment by woop** [comment]
> I was following the official documentation to test run feast using docker compose for online serving only. In the basic experiment jupyter notebook, I was stuck at
> 
> > 1. Ingest data into Feast for a feature set
> >    `client.ingest("customer_transactions", customer_features)`
> 
> It always get timeout.
> 
> After hours of struggling, a colleague pointed out that the online-serving is not started. It is mentioned in the github main page as:
> `docker-compose -f docker-compose.yml -f docker-compose.online.yml up -d`
> but missing in the official documentation:
> `docker-compose up -d`
> 
> I think it's better to add it to the documentation too in case others have the same issue.

Thanks for trying out Feast @LuTang-Terrence, and apologies for the inconsistencies in the documentation. I will walk through the guide today and ensure that it is up to date.

**Comment by woop** [comment]
@LuTang-Terrence I've updated the documentation, testing it out now.

**Comment by LuTang-Terrence** [comment]
> @LuTang-Terrence I've updated the documentation, testing it out now.
Thanks a lot!

**Comment by LuTang-Terrence** [comment]
> @LuTang-Terrence I've updated the documentation, testing it out now.

Thanks a lot!

**Comment by woop** [comment]
> > @LuTang-Terrence I've updated the documentation, testing it out now.
> 
> Thanks a lot!

Still some changes incoming to improve things a bit #803

**Comment by woop** [comment]
All documentation has been updated, closing for now.

Thanks again @LuTang-Terrence
