### ISSUE TITLE
Feature set spec with reserved spec should not be allowed to be registered

### ISSUE THREAD

**Issue by khorshuheng** [feast-dev/feast#818]
## Expected Behavior 
If a feature spec contains reserved column name such as `created_timestamp`, Feast should not allow the feature set to be registered at all.

## Current Behavior
The feature set get registered, and job update fails due to duplicated column in bigquery schema.

## Steps to reproduce
Create a feature spec that contains reserved column name.

## Possible Solution
Feast client should perform verification on feature set spec prior to registering the feature set to Feast core.

**Comment by woop** [comment]
Can we enumerate these?

These come to mind
1. `created_timestamp`
1. `event_timestamp`
1. `ingestion_id`
1. `job_id`
