### ISSUE TITLE
Go SDK: go get by Version Tag Does Not Work

### ISSUE THREAD

**Issue by mrzzy** [feast-dev/feast#824]
## Problem & Expected Behavour
`go get` to install the Feast Go SDK should work by version tag:
```
go get github.com/feast-dev/feast/sdk/go@v0.5.1
```
Returns: 
```
go get github.com/feast-dev/feast/sdk/go@v0.5.1: module github.com/feast-dev/feast@v0.5.1 found, but does not contain package github.com/feast-dev/feast/sdk/go
```
Instead of installing the Go SDK at release version tag v0.5.1.

## Proposed Solution
- Update [setup.py](https://github.com/feast-dev/feast/blob/89883d418b4935d595585689d63d246ad133cabe/sdk/python/setup.py#L86) to support non semver tags. (ie `sdk/go/v0.5.1`)
- Introduce additional tag `sdk/go/v<VERSION>` each release. This tag will allow us to pull the go module by a versioned tag. [Reference](https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories)

**Comment by woop** [comment]
> Introduce additional tag sdk/go/v<VERSION> each release

Does this mean you have 2 tags on one commit?

**Comment by mrzzy** [comment]
>Does this mean you have 2 tags on one commit?
Yes two tags pointing to the tagged release commit.

As a side note, there are `go.mod` and `go.sum` files in project root. They appear to be used to track dependencies of `make compile-protos-go`. Whatever their purpose is, go will treat project root as a go module and the actual go SDK as another module, making it a [multiple module repository as described in this GO FAQ](https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories)

**Comment by woop** [comment]
> > Does this mean you have 2 tags on one commit?
> 
> Yes two tags pointing to the tagged release commit.
> 
> As a side note, there are `go.mod` and `go.sum` files in project root. They appear to be used to track dependencies of `make compile-protos-go`. Whatever their purpose is, go will treat project root as a go module and the actual go SDK as another module, making it a [multiple module repository as described in this GO FAQ](https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories)

Would removing the `go.mod` and `go.sum` in the root be possible and lead to any benefit?

**Comment by mrzzy** [comment]
From my own testing, removing the root `go.mod` and `go.sum` would break `go get` ability of the Go SDK go module entirely. 
So that is not an option.
