### ISSUE TITLE
RpcError: Project name does not exist. Please create a project first: default

### ISSUE THREAD

**Issue by chopradeepanshu** [feast-dev/feast#869]
Hey Team,

While I am executing the code given below as per the example. I am getting an error. Can you pls help me ?
client.apply(customer_fs)

---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/feast/sdk/python/feast/client.py in _apply_feature_set(self, feature_set)
    397                 timeout=self._config.getint(CONFIG_GRPC_CONNECTION_TIMEOUT_DEFAULT_KEY),
--> 398                 metadata=self._get_grpc_metadata(),
    399             )  # type: ApplyFeatureSetResponse

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    825                                       wait_for_ready, compression)
--> 826         return _end_unary_response_blocking(state, call, False, None)
    827 

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    728     else:
--> 729         raise _InactiveRpcError(state)
    730 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Project name does not exist. Please create a project first: default"
	debug_error_string = "{"created":"@1594299986.785817936","description":"Error received from peer ipv4:172.19.0.6:6565","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Project name does not exist. Please create a project first: default","grpc_status":13}"
>

During handling of the above exception, another exception occurred:

RpcError                                  Traceback (most recent call last)
<ipython-input-10-85fc68077ead> in <module>
----> 1 client.apply(customer_fs)

/feast/sdk/python/feast/client.py in apply(self, feature_sets)
    371         for feature_set in feature_sets:
    372             if isinstance(feature_set, FeatureSet):
--> 373                 self._apply_feature_set(feature_set)
    374                 continue
    375             raise ValueError(

/feast/sdk/python/feast/client.py in _apply_feature_set(self, feature_set)
    399             )  # type: ApplyFeatureSetResponse
    400         except grpc.RpcError as e:
--> 401             raise grpc.RpcError(e.details())
    402 
    403         # Extract the returned feature set

RpcError: Project name does not exist. Please create a project first: default

**Comment by chopradeepanshu** [comment]
Can anyone help me on this pls.

**Comment by woop** [comment]
@chopradeepanshu which Feast version are you running? Can you confirm both your client and server versions please?

**Comment by chopradeepanshu** [comment]
We are currently using Master Branch...not sure about the version. I have resolved this issue. I got another issue which is below:

**While Retrieving Online Features and for the below code we are getting an error.
online_features = client.get_online_features(
    feature_refs=[
        f"daily_transactions",
        f"total_transactions",
    ],
    entity_rows=[
        {
            "customer_id": 1001
        }
    ],
)
print(online_features.field_values)

Error:
---------------------------------------------------------------------------
FutureTimeoutError                        Traceback (most recent call last)
/feast/sdk/python/feast/grpc/grpc.py in create_grpc_channel(url, enable_ssl, enable_auth, ssl_server_cert_path, auth_metadata_plugin, timeout)
     47     try:
---> 48         grpc.channel_ready_future(channel).result(timeout=timeout)
     49         return channel

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in result(self, timeout)
    139     def result(self, timeout=None):
--> 140         self._block(timeout)
    141 

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in _block(self, timeout)
     85                         if remaining < 0:
---> 86                             raise grpc.FutureTimeoutError()
     87                         else:

FutureTimeoutError: 

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-14-23f4b9f5430b> in <module>
      6     entity_rows=[
      7         {
----> 8             "customer_id": 1001
      9         }
     10     ],

/feast/sdk/python/feast/client.py in get_online_features(self, feature_refs, entity_rows, project, omit_entities)
    717 
    718         try:
--> 719             response = self._serving_service.GetOnlineFeatures(
    720                 GetOnlineFeaturesRequest(
    721                     omit_entities_in_response=omit_entities,

/feast/sdk/python/feast/client.py in _serving_service(self)
    171                 ),
    172                 auth_metadata_plugin=None,
--> 173                 timeout=self._config.getint(CONFIG_GRPC_CONNECTION_TIMEOUT_DEFAULT_KEY),
    174             )
    175             self._serving_service_stub = ServingServiceStub(channel)

/feast/sdk/python/feast/grpc/grpc.py in create_grpc_channel(url, enable_ssl, enable_auth, ssl_server_cert_path, auth_metadata_plugin, timeout)
     50     except grpc.FutureTimeoutError:
     51         raise ConnectionError(
---> 52             f"Connection timed out while attempting to connect to {url}"
     53         )

ConnectionError: Connection timed out while attempting to connect to online-serving:6566.**

**Comment by woop** [comment]
Are you connecting from within a docker container? Is `online-serving:6566` accessible to you if you use telnet/netcat?

**Comment by woop** [comment]
Also, can you try to use a stable branch instead of the master branch, or are you doing development?

**Comment by chopradeepanshu** [comment]
No, I am not doing any development. I am just using.

Can you please tell which one is the most stable branch, I will fetch code from there.
