### ISSUE TITLE
Feast 0.6.0 | Unable to read store config at /serving/sample_redis_config.yml

### ISSUE THREAD

**Issue by chopradeepanshu** [feast-dev/feast#881]
## Expected Behavior 
After Git clone and docker compose rightly setup, expectation is that the basic example should work correctly without any issue. 
## Current Behavior
However, we can see after executing the code command client.apply(customer_fs) from jupyter notebook, we are getting an below error:
---------------------------------------------------------------------------
FutureTimeoutError                        Traceback (most recent call last)
/feast/sdk/python/feast/grpc/grpc.py in create_grpc_channel(url, enable_ssl, enable_auth, ssl_server_cert_path, auth_metadata_plugin, timeout)
     47     try:
---> 48         grpc.channel_ready_future(channel).result(timeout=timeout)
     49         return channel

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in result(self, timeout)
    139     def result(self, timeout=None):
--> 140         self._block(timeout)
    141 

/opt/conda/lib/python3.7/site-packages/grpc/_utilities.py in _block(self, timeout)
     85                         if remaining < 0:
---> 86                             raise grpc.FutureTimeoutError()
     87                         else:

FutureTimeoutError: 

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-13-85fc68077ead> in <module>
----> 1 client.apply(customer_fs)

/feast/sdk/python/feast/client.py in apply(self, feature_sets)
    371         for feature_set in feature_sets:
    372             if isinstance(feature_set, FeatureSet):
--> 373                 self._apply_feature_set(feature_set)
    374                 continue
    375             raise ValueError(

/feast/sdk/python/feast/client.py in _apply_feature_set(self, feature_set)
    393         # Convert the feature set to a request and send to Feast Core
    394         try:
--> 395             apply_fs_response = self._core_service.ApplyFeatureSet(
    396                 ApplyFeatureSetRequest(feature_set=feature_set_proto),
    397                 timeout=self._config.getint(CONFIG_GRPC_CONNECTION_TIMEOUT_DEFAULT_KEY),

/feast/sdk/python/feast/client.py in _core_service(self)
    150                 ssl_server_cert_path=self._config.get(CONFIG_CORE_SERVER_SSL_CERT_KEY),
    151                 auth_metadata_plugin=self._auth_metadata,
--> 152                 timeout=self._config.getint(CONFIG_GRPC_CONNECTION_TIMEOUT_DEFAULT_KEY),
    153             )
    154             self._core_service_stub = CoreServiceStub(channel)

/feast/sdk/python/feast/grpc/grpc.py in create_grpc_channel(url, enable_ssl, enable_auth, ssl_server_cert_path, auth_metadata_plugin, timeout)
     50     except grpc.FutureTimeoutError:
     51         raise ConnectionError(
---> 52             f"Connection timed out while attempting to connect to {url}"
     53         )

**ConnectionError: Connection timed out while attempting to connect to core:6565**
### Specifications

- Version: 0.6.0
- Platform: Windows
- Subsystem: 10

## Possible Solution
I am not sure about the solution here. But during the docker compose startup feast
**docker-compose** -f docker-compose.yml -f docker-compose.online.yml up 

I can see an error as below:
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servingStoreRedisConf' defined in class path resource [feast/serving/configuration/redis/ServingStoreRedisConfig.class]: Unsatisfied dependency expressed through method 'servingStoreRedisConf' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'specService' defined in class path resource [feast/serving/configuration/SpecServiceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [feast.serving.specs.CachedSpecService]: Factory method 'specService' threw exception; nested exception is java.lang.RuntimeException: Unable to read store config at /serving/sample_redis_config.yml

I am not sure if this is somehow related to this or not. 
Expecting an earliest response from you.

Thanks,
Deepanshu

**Comment by woop** [comment]
@chopradeepanshu Are you perhaps using an old Feast docker image? `/serving/sample_redis_config.yml` should not be in use any more since Feast 0.4. Can you please try to docker pull your images again?

**Comment by chopradeepanshu** [comment]
@woop I mentioned, that I am currently using v0.6.0. 
Just a quick thought, have you guys tested Feast versions  on Windows 10 as well ?
I assume with Mac is running properly but seems much issues while working on windows.

**Comment by woop** [comment]
> @woop I mentioned, that I am currently using v0.6.0.

Can you please run `docker image ls | grep kf-feast/feast-core` and provide the output results? 

> Just a quick thought, have you guys tested Feast versions on Windows 10 as well ?
> I assume with Mac is running properly but seems much issues while working on windows.

We have not tested Feast with Windows. Only Linux and Mac.

**Comment by jakubhava** [comment]
Hitting similar exception, running version 0.6.2, starting as docker-compose up

```
 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servingServiceRestController' defined in URL [jar:file:/opt/feast/feast-serving.jar!/BOOT-INF/classes!/feast/serving/controller/ServingServiceRestController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servingService' defined in class path resource [feast/serving/config/ServingServiceConfig.class]: Unsatisfied dependency expressed through method 'servingService' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'specService' defined in class path resource [feast/serving/config/SpecServiceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [feast.serving.specs.CachedSpecService]: Factory method 'specService' threw exception; nested exception is java.lang.RuntimeException: Unable to update store configuration
historical_serving_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
historical_serving_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227)
historical_serving_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
historical_serving_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
historical_serving_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
historical_serving_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
historical_serving_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
historical_serving_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
historical_serving_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
historical_serving_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
historical_serving_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
historical_serving_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
historical_serving_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
historical_serving_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
historical_serving_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
historical_serving_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
historical_serving_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
historical_serving_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
historical_serving_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
historical_serving_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
historical_serving_1  | 	at feast.serving.ServingApplication.main(ServingApplication.java:36)
historical_serving_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
historical_serving_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
historical_serving_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
historical_serving_1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
historical_serving_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
historical_serving_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
historical_serving_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
historical_serving_1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```
