### ISSUE TITLE
Standalone ingestion in python is leaky due to not closing the MT pool

### ISSUE THREAD

**Issue by diogoncalves** [feast-dev/feast#893]
## Expected Behavior 
Whenever we call client.ingest() it must close the multiprocesing pool after ingestion. 

## Current Behavior
Whenever we call client.ingest(), it calls [get_feature_row_chunks](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/client.py#L886) from [`sdk/python/feast/loaders/ingest.py`](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/loaders/ingest.py#L104) which [opens a pool every time](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/loaders/ingest.py#L142) and does not close it.

This leads to a leaky behavior exploding memory and processor easily if running an ingestion in a loop. 

## Steps to reproduce
run the example of standalone ingestion in a loop.

### Specifications

- Version: v0.5.0
- Platform: any
- Subsystem: Feast Client

## Possible Solution

Change https://github.com/feast-dev/feast/blob/master/sdk/python/feast/loaders/ingest.py#L142:

``` 
pool = Pool(max_workers)
func = partial(_encode_pa_tables, file, feature_set, field_map, ingestion_id)
for chunk in pool.imap(func, row_groups):
    yield chunk
return
```

To:
``` 
with Pool(max_workers) as pool:
    func = partial(_encode_pa_tables, file, feature_set, field_map, ingestion_id)
    for chunk in pool.imap(func, row_groups):
        yield chunk
return
```

**Comment by woop** [comment]
FYI This ingestion method will be replaced completely in the coming versions.
