### ISSUE TITLE
Fixed images versions in Helm charts 

### ISSUE THREAD

**Issue by kkrausert** [feast-dev/feast#924]
## Expected Behavior 
During the deployment of a certain version of Helm charts the images used for the Feast applications should be of the same version.

## Current Behavior
Deploying different versions of Helm charts results in the same Feast images running in Kubernetes. 
Especially deploying the charts from the repo, currently version 0.5.1, as described in https://docs.feast.dev/getting-started/deploying-feast/kubernetes results in e.g. the feast-core version 0.6.1 being deployed.

## Steps to reproduce
Deploy any non current version of Feast Helm charts (e.g. from https://feast-charts.storage.googleapis.com).
 Than compare the chart version via 'helm list' to the deployed application versions (e.g. via the python client: feast_client.version() ).

### Specifications

- Version: 0.5.1 - 0.7.0
- Platform: kubernetes
- Subsystem: helm charts

## Possible Solution
Hard code the image tag in 
infra/charts/feast/charts/feast-core/values.yaml
infra/charts/feast/charts/feast-jupyter/values.yaml
infra/charts/feast/charts/feast-serving/values.yaml
to the version of the chart as given in 
infra/charts/feast/Chart.yaml
and not 'latest'.
The images in the registries need to be tagged accordingly.

**Comment by woop** [comment]
Thanks for raising this @kkrausert!

Will have a look.

**Comment by kkrausert** [comment]
Thank you for the fast fix!
I deployed the charts in the repo:
`helm list` -> feast-0.7-SNAPSHOT
`feast_client.version()` -> 'serving': {... 'version': 'dev'}, 'core': {... 'version': 'dev'}}
In the charts the versions tags are all set to 0.6.2, which is also the version shown in the revisions in GKE.

So it is way better with the fixed version, but there are still come inconsistencies. These probably will be solved automatically in the next non 'dev' version.

**Comment by woop** [comment]
> Thank you for the fast fix!
> I deployed the charts in the repo:
> `helm list` -> feast-0.7-SNAPSHOT
> `feast_client.version()` -> 'serving': {... 'version': 'dev'}, 'core': {... 'version': 'dev'}}
> In the charts the versions tags are all set to 0.6.2, which is also the version shown in the revisions in GKE.
> 
> So it is way better with the fixed version, but there are still come inconsistencies. These probably will be solved automatically in the next non 'dev' version.

This seems like a problem with the build more than the Helm chart right. That version comes from the docker image release itself. So you are saying that when you run `kubectl get pods` you see 0.6.2 running for Core and Serving, but they return `dev` as their versions? That could be due to the build falling back to `dev` if no version is provided.
