### ISSUE TITLE
Add OpenAPI documentation to Core's HTTP Endpoints

### ISSUE THREAD

**Issue by SwampertX** [feast-dev/feast#939]
**Is your feature request related to a problem? Please describe.**
#878 adds HTTP endpoints and documents such endpoints in Javadoc. However, tools such as [OpenAPI](https://github.com/springdoc/springdoc-openapi) does this in a more holistic and visually pleasing manner and is a good to have.

**Describe the solution you'd like**
Add OpenAPI documentation with Swagger UI.

**Describe alternatives you've considered**
[REST Docs](https://spring.io/projects/spring-restdocs) might be a plausible alternative.

**Additional context**
https://github.com/feast-dev/feast/pull/878#discussion_r461770504

**Comment by woop** [comment]
Core is in the process of being replaced with an object store implementation. Closing this card for now.
