### ISSUE TITLE
Missing last chunk when it's less than max_chunk_size in job.get_chunk_data_frame()

### ISSUE THREAD

**Issue by leeway-liu** [feast-dev/feast#948]
## Expected Behavior 
Return all the chunks of data including the last one when its size is less than the max_chunk_size
## Current Behavior
Doesn't return last chunk when its size is less than the max_chunk_size
## Steps to reproduce
Run any data which has a last chunk when its size is less than the max_chunk_size
### Specifications

- Version: 0.5.0
- Platform: Python 3
- Subsystem:

## Possible Solution
In get_chunk_data_frame() function, please update `if not records` to `if records`
```
        # Handle for last chunk that is < max_chunk_size
        if records:
            yield pd.DataFrame.from_records(records)
```

**Comment by woop** [comment]
Thanks for raising this @leeway-liu
