### ISSUE TITLE
Authentication & Authorization Support for Java and Go SDKs

### ISSUE THREAD

**Issue by mrzzy** [feast-dev/feast#950]
### Background
Feast has authentication & authorization support completed for the following components:
-  Core #793 
-  Serving #865 
- Python SDK (#763 & #865)

### Problem
Authentication & Authorization support does not extend to Java and Golang SDK:
- This blocks administrators from having a full authentication and authorization rollout if they have users using Java and Golang SDKs.

### What needs to be done
Extend Authentication & Authorization support to
- Java SDK
- Golang SDK

such that they can access Feast Core and Serving with Authentication & Authorization enabled.

**Comment by woop** [comment]
Thanks for this @mrzzy 

This is probably a good opportunity to finally create integration tests for both of these clients.
