### ISSUE TITLE
Docker Compose is broken on master

### ISSUE THREAD

**Issue by woop** [feast-dev/feast#956]
## Expected Behavior 

Bringing up Feast with docker compose works

## Current Behavior
Problem reported on mailing list
```
 docker-compose % docker-compose up -d

Pulling jobcontroller (gcr.io/kf-feast/feast-jobcontroller:0.6.2)...

ERROR: manifest for gcr.io/kf-feast/feast-jobcontroller:0.6.2 not found: manifest unknown: Failed to fetch "0.6.2" from request "/v2/kf-feast/feast-jobcontroller/manifests/0.6.2".
```

## Possible Solution

* Cut a new release of Feast
* Revert Docker Compose files

**Comment by pyalex** [comment]
We need to update docs to recommend users to checkout stable branch and use docker compose from it.

**Comment by woop** [comment]
The work that needs to be done here.
1. Update our docker compose configuration to always use `dev` images (the latest master build)
1. Update our release process to always update the docker compose images when a release is made. 
1. Update our documentation to ask users to check out a specific tagged version of the Feast repo before running `docker compose up`
1. Add linting to make sure that the version in our docs stays up to date https://github.com/feast-dev/feast/blob/master/infra/scripts/validate-version-consistency.sh#L33

**Comment by sp-davidpichler** [comment]
I've been trying to get feast up and running and haven't been able to do so. I tried the docker compose instructions and was on tag v0.6.2. The cluster spun up but when I went to create a feature it was stuck in a pending state. I also have also noticed that the docker-compose tests badges show as failing on v0.6.2, v0.6.1, v0.6.0. Not sure if that's related to this.

**Comment by woop** [comment]
> I've been trying to get feast up and running and haven't been able to do so. I tried the docker compose instructions and was on tag v0.6.2. The cluster spun up but when I went to create a feature it was stuck in a pending state. I also have also noticed that the docker-compose tests badges show as failing on v0.6.2, v0.6.1, v0.6.0. Not sure if that's related to this.

The old test failures are not related. That is actually a badge that is looking at the wrong test.

I just tried this complete Docker Compose flow.

1. Clone
2. Check out 0.6.2
3. Go to `feast/infra/docker-compose`
4. Create .env
5. Start docker compose
6. Open notebook, step through the Basic example.
7. It took about 10-15 seconds for the feature set to enter ready state.
8. Online retrieval worked

How long did you wait for retrieval David?

**Comment by gbaludev** [comment]
Thanks for taking up this issue reported by in slack channel. 
I tried the above & I am able to run feast UI now. Thanks
