### ISSUE TITLE
client.ingest() from basic.ipynb timing out due to created FeatureSet being stuck in STATUS_PENDING state (feast deployed on GCP).

### ISSUE THREAD

**Issue by pratyush-mishra** [feast-dev/feast#979]
## Context
I was successful in setting up feast on GCP and was trying to test it via reproducing [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb) in an Azure Databricks notebook environment.
## Expected Behavior 
Ideally, once the FeatureSet has been successfully created in the feast deployment via `client.apply()` and verified by observing the successful return of the FeatureSet object by `client.get_feature_set()`, `client.ingest()` should be able to ingest the data supplied as an argument to it.
## Current Behavior
While running through the steps mentioned in [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb), everything works fine until `client.ingest()` is called. On calling `client.ingest()` the function prints out 
> Waiting for feature set to be ready for ingestion...

and then just times out. I tried to increase the timeout limit via the timeout parameter of `client.ingest()` but got the same result. Having looked at the [code](https://api.docs.feast.dev/python/_modules/feast/client.html#Client.ingest) for the ingest function, this must mean that the FeatureSet is never leaving its STATUS_PENDING state and hence not going to STATUS_READY state.
## Steps to reproduce

1. Set up feast on Google Cloud Platform (GCP) via the following instructions: [https://docs.feast.dev/getting-started/deploying-feast/kubernetes](https://docs.feast.dev/getting-started/deploying-feast/kubernetes)
2. Follow the steps mentioned in the [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb). Since the steps from [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb) were being run from an "external" Azure Databricks notebook, of course the correct URL (different from the one mentioned in [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb)) to feast core service were supplied  when initialising the `Client` object.
3. As part of [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb), run `client.ingest("customer_transactions", customer_features)`. This runs into timeout as mentioned under 'Current Behaviour' above.

### Specifications
Here is the pip freeze result from the Azure Databricks environment which is being used to reproduce [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb): [pip_freeze.txt](https://github.com/feast-dev/feast/files/5169149/pip_freeze.txt). The feast version installed there is `feast==0.6.2`.

- Version: 0.6.2 (feast version)
- Platform: Google Cloud Platform (feast deployment) and Azure Databricks (notebook environment)
- Subsystem: Kubernetes Engine

Looking for any leads/insights into why this might be happening and possible solutions if any.
PS: #880 raised this issue, but it was for a local (non GCP) deployment of feast.

**Comment by pratyush-mishra** [comment]
**UPDATE:** We even tried running [basic.ipynb](https://github.com/feast-dev/feast/blob/master/examples/basic/basic.ipynb) from a notebook local to the feast deployment (via GKE on GCP) and still run into the same issue (Earlier we were trying to access the feast deployment via an Azure Databricks notebook). We were observing logs for the `feast-core` service on Google Kubernetes Engine. All different calls like `client.list_feature_sets()`, `client.get_feature_set()`, `client.apply()`, etc. successfully work and thus generate expected logs for the feast-core service. But `client.ingest()` never seems to hit feast-core as it never generates any logs. It seems like the ingestion job is never spinning up in feast core and thus the `status` for the `FeatureSet` is never changing from `STATUS_PENDING` to `STATUS_READY`. 

PS: A pointer to where in the code is the `FeatureSet` status supposed to be updated and where in the code is the ingestion job called would be highly appreciated.

**Comment by woop** [comment]
Hi @pratyush-mishra,

Thanks for giving Feast a try. I'm sorry that you seem to have been struggling so much with this one issue.

Can I ask what runner you are using for starting the jobs? Are you using DirectRunner?

Normally the feature set stays in PENDING state until all jobs go into a READY state. The state change depends on the actual type of runner. So if you are using DirectRunner, then Feast Core will spin up and manage those jobs locally as subprocessed. If you are using DataflowRunner, then Feast Core will start those jobs on Dataflow and wait for them to be ready.

Can you please provide the configuration that you have been using (application.yml for both Core and Serving)?

Also, have you tried to use our Docker Compose setup. Does it work for you?

**Comment by woop** [comment]
Also, I am happy to bug this over chat if you want to join the Kubeflow.org #feast Slack.
